### ISSUE TITLE
Fatal error when clicking into a user

### ISSUE THREAD

**Issue by fredprotein** [snipe/snipe-it#1065]
Symfony \ Component \ Debug \ Exception \ FatalErrorException
Call to a member function fullName() on a non-object

<img width="1283" alt="fatal-error-user" src="https://cloud.githubusercontent.com/assets/10221631/9306502/aae7fda8-44f0-11e5-8eb3-2dcfa381efe3.png">

**Comment by snipe** [comment]
What version are you running? Also, have you manually deleted any data from the system?

**Comment by fredprotein** [comment]
Hey sorry I wasn't the one who install snipe-it, I am trying to find the version number...
And as far as I know no one has touched the database – is that what you mean?

**Comment by snipe** [comment]
Hi @fredprotein - yes, that's what I mean. Typically when that error shows up, it's because there is a record in the asset_log table to a user that no longer exists in the database. It can't find the full name of that user because the user literally doesn't exist anymore. This is why [we strongly recommend against manually editing data](http://docs.snipeitapp.com/installation/manually-editing-data.html), and why we use soft deletes.

If your asset history isn't important, you can empty that table and it will likely clear up that error, but if it is, doing so would lose all of your historical data. (You won't lose your assets or users, but all of the previous checkouts and such will be gone.)

Otherwise the only real option you have is to figure out which of the IDs are missing, and recreate them in the database.

**Comment by fredprotein** [comment]
Hey @snipe thanks for the suggestion, I will try it out!
