### ISSUE TITLE
Feature Request: LDAP Sync - Include option to select field for Location

### ISSUE THREAD

**Issue by grantmoxomZoo** [snipe/snipe-it#1091]
Our "Location" field in LDAP is a non-standard field.
Are we able to get this as an option to select (in the same way mail, firstName and givenName is?)
##

**Comment by snipe** [comment]
Yes, we can add that as an optional field, but we'll also need to make sure we search for and create (if it's not there) the actual location itself, since the user record is looking for a location_id, not a location name.

**Comment by aalaily** [comment]
I guess there are (at least) two ways of looking at this:
1) as described by @grantmoxomZoo 
2) we could have a dropdown list or a form beside the "LDAP Sync" button that fetches all the locations in the installation and let's the importer choose which location to set on import.  This would ensure that a location that is set actually exists.  One of the dropdown fields could be "Use config setting" if the config document has a parameter set for location.  In this last case, we'd use the same logic as point (1) to set the location... and as @snipe said, the location name in LDAP would have to be identical to the one set in the installation so that the location_id can be properly extracted.

**Comment by snipe** [comment]
My plan was to map it as an optional field, and add the location to the database if it didn't exist.

**Comment by aalaily** [comment]
Sounds like a sound plan to me.
