### ISSUE TITLE
(2.0RC) Asset menu collapsed when visiting 'Categories' and 'Asset Maintenance'

### ISSUE THREAD

**Issue by Gehirnfussel** [snipe/snipe-it#1103]
Hi again,

I just noticed that the dropdown menu for assets stays open when visiting the asset-subpages — except for when I visit 'Categories' and 'Asset Maintenance'.
Here the menu is always collapsed and has to be opened manually.

Best regards,
Jan

**Comment by snipe** [comment]
That's not really an accident, more of an information architecture issue. Categories at least are not technically just part of assets, as they're used for consumables and accessories as well (which is why they started off - and still are - in the Admin menu in the top right). We added a shortcut to them in the Assets section to make it easier since most people use Assets more than anything else, but since they are not exclusive to Assets, it seems weird to expand that section by default if you're in the categories section, since you may be in there for consumables or anything else.
