### ISSUE TITLE
getting admin/consumables/message.assoc_users error when deleting consumables

### ISSUE THREAD

**Issue by drahamim** [snipe/snipe-it#1136]
Just upgraded to v2.0 and am getting " Error: admin/consumables/message.assoc_users " when trying to delete consumables. 

the consumable has 1 of 2 checked out. 

I don't really see any errors in logs but may not be looking in the correct place. 

Running on Ubuntu 14.04 
Snipe-IT version	v2.0-RC-1-11-gda6770c
PHP Version	5.5.9-1ubuntu4.11
Laravel Version	4.2.17

**Comment by drahamim** [comment]
Finally figured out that you can't delete a consumable after assignment (which makes sense) but there is no undo method if you accidentally assign a consumable to the wrong user. 
I will close this thread as it is not an actual bug.

**Comment by snipe** [comment]
Reopening, as we should account for that. Thanks.

**Comment by lcalway** [comment]
It would be helpful to be able to hide a consumable from the listing that is no longer used. This would get around the need to delete an item. If you needed to get them again you could use a filter maybe to show hidden items?

Use case for us is a printer that is end-of-life and its toner is no longer stocked, but is clogging up the list.

**Comment by djmbm** [comment]
I don't like that consumables aren't actually consumed. Instead of assigning it to the user, it should instead just be logged that said user consumed it. Then the quantity should be changed to desired quantity, and then the actual on hand quantity should be tracked, and alerts should be available once on hand drops below a specific quantity or percentage of desired quantity. So if we keep a max of 5 spare keyboards on hand, but want to be alerted when we're down to 2 on hand so we can purchase more.

Sorry if that's a bit disjointed, it's been a long day and I just ran into this deleting issue for that very reason.

**Comment by snipe** [comment]
Keyboards aren't consumables though, they are accessories.

**Comment by snipe** [comment]
"I don't like that consumables aren't actually consumed. Instead of assigning it to the user, it should instead just be logged that said user consumed it. Then the quantity should be changed to desired quantity, and then the actual on hand quantity should be tracked" <-- I don't understand what this means. They are marked as assigned to a user, then the amount on-hand is decremented.

**Comment by djmbm** [comment]
At our place, we consider anything under $100 to be a consumable. Just company policy.

As for what it means, when we add more it updates the overall quantity and still just has a bunch checked out. In other words, the overall quantity continues to count things long since thrown away. We're looking for a system that tracks desired quantity, and actual quantity on hand.

**Comment by snipe** [comment]
@djmbm please create a new issue for this, as it's unrelated to the original issue in this ticket

**Comment by Dylan-M** [comment]
Agreed on the idea of how it should work, but I'm also having the exact same issue with being unable to delete existing consumables because they're checked out to a person.

Which is where my comment on that comes in: It shouldn't ever check out a consumable because it's consumed. It should just log who it is consumed by. Then this issue wouldn't happen anyway. I say this, because if an item is consumed it is gone, not checked out to a person.

**Comment by snipe** [comment]
@Dylan-M I'm not sure how a user consuming a thing or being assigned a thing are different, other than semantically.
