### ISSUE TITLE
Change Date/Time Format

### ISSUE THREAD

**Issue by jalynrabey** [snipe/snipe-it#1141]
Dear all

Im kind of newby with snipe so, sorry if i made stupid wuations.

I need to change the time date format to dd/mm/yyyy its possible?

I change the language but that dont change the time and date format.

**Comment by snipe** [comment]
That's not currently an option in Snipe-IT.

**Comment by DonVang** [comment]
Has this changed now - 2 years later?

**Comment by frknozel** [comment]
And updates ? :)
I want to change date format as dd/mm/yyyy too..

**Comment by jaredqpittman** [comment]
Keep coming back to this issue, would love to see this implemented as in the US it's first nature to type MM/DD/YYYY

**Comment by kristiannikolaev** [comment]
Please, think about this feature. As someone from Spain, it's really challenging to read dates in US format 😢

**Comment by csilva-bppw** [comment]
**Please** revisit this issue.

**Comment by snipe** [comment]
@csilva-bppw - this has already been resolved a long time ago, which is why it was closed. Check the Admin Settings > Localization settings. Imported dates will still need to be in YYYY-MM-DD format, but you can pick how you want them to display to you. https://snipe-it.readme.io/docs/localization

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/localization">Localization</a></strong></div><div>Set the language and time/date display of your Snipe-IT installation</div></blockquote>

**Comment by csilva-bppw** [comment]
> @csilva-bppw - this has already been resolved a long time ago, which is why it was closed. Check the Admin Settings > Localization settings. Imported dates will still need to be in YYYY-MM-DD format, but you can pick how you want them to display to you. https://snipe-it.readme.io/docs/localization
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/36f9ad6e91a74ff64cfb482a014804124e880edd3d536aea5c278ef5c68bbaef/68747470733a2f2f66696c65732e726561646d652e696f2f653964383930652d736d616c6c2d7374616e64616c6f6e652d7472616e73706172656e742d3430302e706e67">Snipe-IT Documentation**[Localization](https://snipe-it.readme.io/docs/localization)**Set the language and time/date display of your Snipe-IT installation

Really sorry, my bad.

<blockquote><img src="https://files.readme.io/e9d890e-small-standalone-transparent-400.png" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/localization">Localization</a></strong></div><div>Set the language and time/date display of your Snipe-IT installation</div></blockquote>
