### ISSUE TITLE
Rename Username and Password field on users/edit

### ISSUE THREAD

**Issue by Cylindric** [snipe/snipe-it#1159]
This is probably more of a feature-request than a bug, but it is _really_ annoying that the username and passwords fields on the user-edit pages are actually called "username" and "password" in the HTML. It means the browser and/or LastPass (and I guess any other password management) thinks it's asking for *my* credentials, and auto-fills them. 

If the underlying input names could be something else, then my browser won't keep trying to update my cached credentials with those I'm creating for my users.

Thanks.

**Comment by snipe** [comment]
Can you not just disable autofill on your password manager?

**Comment by Cylindric** [comment]
It's not the biggest problem in the world, sure, but semantically those fields are _not_ the conventional username and password - they are just more random fields on a form. For example, I would still expect autofill, caching, password-managers etc to work when _I_ try and log in to SnipeIT.
It's more about expected behaviour and user-experience really.

**Comment by snipe** [comment]
Sure, but that sounds like an issue with your password manager, not one for Snipe-IT. Semantically, it makes sense for those fields to remain as they are, since that's actually what's being asked for. The expected behavior and user-experience reality is being imposed by your password manager, not by us. I agree that the experience is unfortunate, but they are semantically correct.

At any rate, this is a pretty pedantic conversation. We can consider changing it, but it will be a low priority if we do. The field names map to the validation in our models, so if we change it there, we have to add extra code to make the validation work everywhere across the system.

**Comment by Cylindric** [comment]
Fair enough. Just pointing out an annoyance. You are of course free to ignore it.

**Comment by snipe** [comment]
Quick question - have you tried checking the option "Do not overwrite fields that are already filled" in the preferences? 

<img width="873" alt="screen shot 2015-09-25 at 3 59 30 pm" src="https://cloud.githubusercontent.com/assets/197404/10113988/6a04e436-639f-11e5-90f6-5dcaad02c1e3.png">

**Comment by volephuxuan** [comment]
This is really annoying behavior. When I edit an user, first it shows the correct username then Safari autofills with my Snipe-IT's username instead. This behavior is weird and why should I turn off my AutoFill to use Snipe-IT?

**Comment by snipe** [comment]
I pushed out an update on `develop` that tries to discourage auto-filling more aggressively on the user creation/edit form. Please test when you get a chance and let me know if it helps.
