### ISSUE TITLE
Assign Consumables to Hardware (Printers)

### ISSUE THREAD

**Issue by pachamama40** [snipe/snipe-it#1183]
I need to assign consumables to printers to keep a historical control consumption.
If the user changes printer, consumables history is lost.

Can you help me?
##

**Comment by bailantilles** [comment]
It would be helpful if you could generally assign specific consumables in the asset model interface. That way you could assign cartridges to a printer model since all models use the same cartridge. For people who manage consumables among multiple sites, it would also be helpful if you could assign consumables to a location or sub location so that people would know where they are stored and also to bring up a general inventory listing of consumables by location.

**Comment by bailantilles** [comment]
Additionally, Adding an alert threshold when stock reaches below a specific point per consumable would be helpful.

**Comment by snipe** [comment]
@pachamama40 that's not currently a feature that is available, however can consider adding it.

**Comment by SylentBobNJ** [comment]
+1 this... We have networked printers that aren't assigned to specific users that we'd like to be able to 'Check out' toner to.

**Comment by Weaksid** [comment]
+1 . 

Right now we created a Printer User (The name of our printer) to solve this issue for now. So, when you view the user, it will be in their log of what toner/parts it got.

**Comment by snipe** [comment]
This is in the works for v4
