### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by sig-wim** [snipe/snipe-it#12302]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

After importing a backup from a local server to a hosted server, everything seems to be imported.
The Dashboard shows the right amount of Assets, People and Accessories.
When accessing the assets, there is no problem, however when accessing either People or Accessories, the message: "No matching records found" is displayed.
When then trying to access a person from the Assets screen, the "500 | Server error" is displayed.

In debugging, the console shows this:
![Screenshot 2023-01-04 at 15 23 59](https://user-images.githubusercontent.com/2913010/210576106-385ad8de-453c-4ca1-a6d6-8ffd4abd024a.png)

### Reproduction steps

1. Log in as admin or any other user
2. Navigate to Assets
3. select any Checked out user
4. Navigate to People or Accessories
...
![Screenshot 2023-01-04 at 15 29 01](https://user-images.githubusercontent.com/2913010/210577017-402adef0-e7df-4f15-9291-3c3540c89b36.png)

### Expected behavior

When navigating to either People or Accessories, a list of users/accessories should appear, exactly as it does with navigating to Assets

### Snipe-IT Version

v6.0.14 build 9038 (g163b3f6c0)

### Operating System

hosted

### Web Server

snipe-it.io

### PHP Version

8.0.25

### Operating System

Mac OS 13.1

### Browser

Firefox

### Version

108.0.1 

### Error messages

```shell
Some cookies are misusing the recommended “SameSite“ attribute 3
Cookie “laravel_token” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite admin
Cookie “XSRF-TOKEN” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite admin
Cookie “sig_snipeitv6_session” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite admin
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

None of the errors are reproducible on the demo.
```

### Additional context

The backup used to set up the new hosted server came from a local Ubuntu server with Snipe-it version Version v4.9.4 - build 4437

**Comment by snipe** [comment]
Hi there - sorry to hear you’re having trouble. In order to help, we’ll need the backtraces in the app log: https://snipe-it.readme.io/docs/getting-help

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>

**Comment by fonteijnf** [comment]
@snipe Hi, dear Snipe. Maybe it was not entirely clear from the question, but the problem is occurring on a server hosted by Snipe, not our own server. I am not sure how I would look at the logs now.

A little addition to the cookie error message. That's just an error that occurs on Firefox which isn't really the issue. The issue is that we get an error 500 on specific pages of the database.
We can successfully view assets, licenses, accessories and consumables, but people is empty.
The dashboard shows there are people though, which also show up on the assigned person for any asset, but once a person is selected it goes to an error 500 page.

Can you provide further suggestions?

**Comment by snipe** [comment]
@valdore86 - ah, got it - that usually means a migration on the restore didn't fire for some reason. If you send us an email at support@snipeitapp.com we can take a look at those logs and get you sorted.

**Comment by snipe** [comment]
You should be all set now :)
