### ISSUE TITLE
Feature request: New (cloud) storage options for images (assets & avatars)

### ISSUE THREAD

**Issue by fpalmcrantz** [snipe/snipe-it#1233]
For larger asset/user databases, it would be useful to be able to store the related images in some sort of cloud storage/service and I believe Amazon S3 could be a popular one. A deployed Snipe-it system will often be running on top of a cloud service (with proper storage pricing) but it can still be beneficial to be able to separate the storage concern from the web interface.

Seems Laravel 5 has good support for file storage (http://laravel.com/docs/master/filesystem). Don't know if 4.2 -> 5.x is under consideration. If there's a need to stay on Laravel 4.x for a while longer, then maybe something like https://github.com/aws/aws-sdk-php-laravel can be used for implementation.
##

**Comment by snipe** [comment]
Hi @fpalmcrantz - It's something we've considered, but it's always been pretty low priority, since the vast majority of our users wouldn't use that feature. 

The upgrade path to 5.1 is pretty ugly. We've played with it a bit, and will be doing it eventually, but it's not a few-hours kinda thing, especially because we're using Sentry and not Laravel's native built-in auth. (It's not as bad as a few other apps I have which are using 4.2 and Sentry + Sentry Social - ugh). For those apps, I do use the `aws-sdk-php-laravel` package, and it works fine. 

To truly separate the storage concern, we would also have to include AWS signed requests (so that the files were not publicly available to anyone who knew the URL, such as license files), and will mean additional support tickets as novice users try to implement AWS bucket restrictions, etc. 

We'll try to squeeze it in at some point, but as I said, it's a lower priority than some other stuff that on deck right now.

**Comment by lorenzolewis** [comment]
+1
