### ISSUE TITLE
How acceptance work?

### ISSUE THREAD

**Issue by orygen** [snipe/snipe-it#1272]
Hi guys,
This is not actually an issue but more like question how it supposed to work.
I read through this support forum and it seems like user get an acceptance email?
Is this when we check out asset to user? Is this when the EULA send to them?

When I checked out asset to a user, there's no email sent to them.
Is it because of my email settings?
Thanks.

**Comment by snipe** [comment]
Hi @orygen - the EULA/acceptance has to be enabled on the category level. 

If EULA and acceptance are turned on at the category level, and the user has a valid email address, they should receive an email when you check items within that category out to them.

**Comment by sysnoo** [comment]
Hi,
The problem is that in the email sent there is a choice to accept or decline?
What if the asset when shipped is received and declined in email.

Is there a way to send only a link to accept. (The best to have one time valid URL to accept with no authentication)

Thanks for you nice and well designed Tool

**Comment by snipe** [comment]
@sysnoo the email sends a link that allows the user to accept or decline

**Comment by orygen** [comment]
@snipe Thanks!
