### ISSUE TITLE
Asset Maintenance workflow

### ISSUE THREAD

**Issue by seanism** [snipe/snipe-it#1282]
Would it be possible to have the option to mark an item as ready to deploy when you mark the completion date in asset maintenance?

Currently the workflow is edit asset to Out for Repair, then add an asset maintenance.  When you get the item back you mark the completion date then set it to ready to deploy.  Very tedious.

Alternatively when you set out for repair having the option to setup an asset maintenance would be helpful as well.

**Comment by snipe** [comment]
That's a good idea, @seanism

**Comment by snipe** [comment]
Would it be helpful if we made it so that when you first click on "Add maintenance", it gives you the option to select a "pending" status (like out for repair), and when you add a value for "completed at", it gives you the option to set a RTD status? Thats way you don't have to edit the asset's status first?

**Comment by orygen** [comment]
@snipe That would be great if we can do it in one go.

**Comment by seanism** [comment]
@snipe sounds good.  Thanks!
