### ISSUE TITLE
Upgrading if originally deployed via FTP upload 

### ISSUE THREAD

**Issue by brianjking** [snipe/snipe-it#1287]
I launched a Snipe-IT installation manually by uploading from a zip file instead of doing a git clone of the repo onto my server. Because of this I'm wondering how I should go about upgrading to the release you just updated a few days ago or any future versions.

**Comment by snipe** [comment]
?

**Comment by brianjking** [comment]
@snipe Sorry, I don't know how that got posted without the body text. I've just updated the original message above.

Thanks!

**Comment by ddreier** [comment]
I just drop the new version on top of the existing one (after making a copy) and overwrite on file conflicts. Works well enough so far.

**Comment by brianjking** [comment]
@ddreier And what about all of the files that you have to move around or edit during the installation process? You bring those over manually from your copy?

**Comment by ddreier** [comment]
Well, I make a copy (as a backup) and then overwrite the original folder with the new version. With the exception of (I think) bootstrap/start.php none of my changes get lost because all of the config files are .example.php in the repo.

**Comment by snipe** [comment]
Backup `bootstrap/start.php` (only if you're running this in development mode, otherwise it will default to production on its own), and `app/config/app.php` (which just contains your timezone and language prefs). All of your other config files will not be overwritten, since when you installed the app, you had to copy them over from `blah.example.php`. (That's exactly why we do it that way, to make upgrading easier.)

**Comment by ddreier** [comment]
I knew I was forgetting something! Hopefully I remember to check `app/config/app.php` tomorrow.

**Comment by snipe** [comment]
@ddreier even if you didn't, you'd just need to reset your timezone. Default language is english, so it's no biggie.
