### ISSUE TITLE
Check for existing Accessories during Checkout to User

### ISSUE THREAD

**Issue by jghanlon** [snipe/snipe-it#1288]
When checking out an accessory to a user it would be nice to show if that user already has that accessory. For example if I click on the Checkout button next to the Keyboard accessory, I can choose from a list of users but when I select a user I don't know if that user already has one of those accessories assigned. So I might accidentally give the user 2 keyboards or more.  And I wouldn't know this until I viewed that user's Accessories data.

Not sure how to indicate this in the UI. Maybe once the user is selected the information could populate below the pull-down list noting that the user already has 1 of these accessories and to please confirm that you want them to now have 2.
Or perhaps put a number in parentheses in the pull-down list to show how many of this type of accessory the user already has. ex: "Last, First (first.last) (1)"

**Comment by diekmanu** [comment]
The same goes for checking out licenses. When you manage 100+ seats it's really a matter of time when ComputerA (UserA) gets Seat 1 and Seat ...77 (e. g.). Of course corresponding to same software and not on purpose. So when you manage 250 MS Office 2013 licenses chances are that "Computer032x" will hold MS Office licenses multiple times (bad idea), because you totally lose track of those already assigned ones. So I guess the proposed UI indications would also make perfect sense for checking out license seats to assets.
