### ISSUE TITLE
Clicking ASSET TAG link from All Assets table screwed-up

### ISSUE THREAD

**Issue by itsupportcmsukorg** [snipe/snipe-it#1310]
We're experiencing a really odd issue, on the various View Assets tables, clicking the asset tag, or edit link takes you to either completely the wrong asset, or displays: Error: Asset does not exist.

It looks like the link is borked and picking up the "model_id" field when it should be using the "id" field from the assets table.

Any thoughts as to what's gone wrong?
Many thanks.

Operating Environment:
Snipe-IT version: v2.0-374-g577c193
PHP Version: 5.6.14-0+deb8u1
Laravel Version: 4.2.17

**Comment by itsupportcmsukorg** [comment]
Really weird. My colleague wasn't having the same issues. I flushed my cache in Chrome (v.46) and all has returned to normal again! Clearly some localised storage was causing this, Javascript? V8? Unfortunately I can't now reproduce the issue, but it was something to do with selecting/deslecting columns visibility.

**Comment by mtucker6784** [comment]
I'm on 374 as well. I experienced something similar (or maybe the same thing?) 

The datatable would populate with the right assets, but the link given was the same ID the whole page through. I cleared cache, tried a different browser entirely (Chrome and FF) and yielded the same results. Even cleared `storage/cache` and `storage/views` I found my work around is to show the ID field as a visible column, then hit refresh. Not a big deal, once I hit the refresh, things work as expected. I can't reproduce on the demo for the life of me though.

**Comment by snipe** [comment]
I'm wondering if this is an issue with the cookie plugin for the bootstrap tables library. I have found that when I run into weird behavior, if I rename the cookie-name attribute on the table, it fixes it. It might be because you guys are using the dev branch (which changes frequently) it's causing some wonkiness. I could maybe try adding the hash-abbreviation to the cookie name so that it gets versioned.
