### ISSUE TITLE
Bug While Exporting data

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#1378]
Dear Snipe,

indeed whenever i try to export any data in assets management only first 50 line will be exported , can you please help on this.

Kind regards

**Comment by abdullahalasham** [comment]
the issue has not resolved in the current version   (v2.0.6-54)

**Comment by snipe** [comment]
@abdullahalasham When we have a fix for it, we will update the ticket.

**Comment by balticer** [comment]
It works as intended...at the moment. As far as i can see the problem is, that for the export "tableExport.jquery.plugin" is used. This is a client side java script, which exports the data that you current see in the data table. So maybe it is needed to write an server side exporter which do bulk exports. IMO this is more a feature request, rather then a bug.

@snipe: Any plans for an server side exporter? Maybe something i could do...when you agree with my thoughts.

**Comment by snipe** [comment]
The custom asset repot has been around for a while and will give you a full export. Sorry this ticket didn't get closed when it was implemented.
