### ISSUE TITLE
Make generated labels into a PDF for more consistent printing alignment

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#1389]

**Comment by kieran21** [comment]
@snipe what are your thoughts on implementing a more robust label printing feature-set? 

### Some background
I understand there are multiple ways of printing labels, the one currently in Snipe-IT from my understanding has a page/PDF generated to be sent to an Avery sticker page in a standard A4 printer. At my work we have a number of dedicated network labelling printers (Zebra brand). Of course there are other common label printer brands like DYMO and Epson etc. With the Zebra printers I already have made some customizations in other applications where ZPL code is generated and HTTP POST-ed to the printers IP address directly from client side JS (doesn't have to be client side). Interesting to note is that with ZPL there are commands to generate QR codes (among other barcodes) from a URL.

### The idea
What I'm thinking (Zebra example) is to have printer options in Admin > Settings > Edit. So for example, user could choose print method from a drop-down. Options would be something like Avery sticker A4 page generation (default) or Zebra printer. Then if a Zebra printer specified - enter the printers IP address. There could be an editable code region where a default label code layout could be specified along with {{fields}} or something for data.

### User process
1. Generate Labels is selected
2.  Print job is submitted to print method pre-specified in Settings

### Pros
* Small volume print jobs possible and less wasteful
* Wider range of existing printer devices supported
* Opens options for IT departments with existing label printers
* Can print from a browser without an installed printer (in case of network printing)

### Cons
* Time taken to dev and test Snipe-IT
* Each printer brand generally has differing protocols which could become complex to manage
* Unknown level of complexity and modifiability in existing code that relates to printing.


I'm not asking/pushing you to do this per se, I'm just wanting to understand your thoughts because I was thinking of doing it myself for my Zebra printer and if it works well, submit a pull.

**Comment by snipe** [comment]
I'm definitely not averse to it, and have wanted to implement something like this for a while, it just takes a long time to develop and test. The immediate need for a PDF page will at least resolve the printer label alignment issues we've gotten reports of, but I'm certainly open to more advanced features once the alignment issue has been fixed for people. I don't currently have access to any of those more specialized printers, so your proposed version could be problematic.

**Comment by snipe** [comment]
That said, if you do manage to get it working, I'll happily take a PR for it. :)

**Comment by snipe** [comment]
Upcoming v3 now has customizable page margins, label size, etc. It's not a robust version with pre-defined label sizes, but people can at least customize the output font sizes, margins, etc.
