### ISSUE TITLE
[Multicompany enabled] Admin can edit users not from their company

### ISSUE THREAD

**Issue by swift2512** [snipe/snipe-it#14568]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Admin, not assigned to any company, can edit any user. Worst of all - admin can disable/**delete superadmin** account or change it's password.

### Reproduction steps

1. Enable Multi Company support.
2. Create 1-2 companies. 1 regular user (user1) and 2 admins (admin1, admin2). Leave permissions unchanged (default)
3. Assign user1 and admin1 to a company. Leave admin2 unassigned to a company.
4. Create 1 asset and assign to a company. Checkout asset to user1.
5. Login with admin2. In People section, only admin2 and superadmin will be visible. Open any of visible users and edit URL to [http://ipaddress/users/**{number) of user1}**/edit].
6. Edit any attribute of user1 or just press button SAVE. User1 will be removed from the company and:
- will be become visible for admin2 in People section;
- equipment assigned to user1 will not be visible for user1 and admin2;
- admin1 won't be able to see user1 in People section, but in Assets section he will see that asset is assigned to user1.
7. With admin2 open superadmin account and delete it - account will be deleted and can't be recreated. Also, it's possible to change superadmin password or disable site login.

### Expected behavior

1. Users shouldn't be accessible for admin2 through URL modifications - should throw "403 Forbidden." error like it does for assets.
2. admin2 shouldn't be allowed to edit/delete superadmin user.

### Snipe-IT Version

v6.3.4 - build 13139 (master)

### Operating System

Ubuntu Server 22.04

### Web Server

Apache

### PHP Version

PHP 8.1.27

### Additional context

Fresh install on LAMP server. Installed via git.

**Comment by snipe** [comment]
> Assign user1 and admin1 to a company. Leave admin2 unassigned to a company.
Create 1 asset and assign to a company. Checkout asset to user1.
Login with admin2. In People section, only admin2 and superadmin will be visible. Open any of visible users and edit URL to [http://ipaddress/users/{number) of user1}/edit].

This doesn't make sense tho. admin2 has no company, so it cannot see the user who does have a company. It can only see itself, since it's uncompanied. An admin without a company can only see other things that also do not have a company.)

**Comment by snipe** [comment]
If I am logged into the admin that *is* constrained by a company, I get a forbidden error if I try to access a user outside of my company. 

I think I can see where you're going with this, but it's the reverse of what you detailed. Still investigating.

**Comment by snipe** [comment]
I created a company, "Brand Spankin New", and three users:

- `spankinadmin1` (admin with new spankin company as their company)
- `nospankadmin2` (admin without any company)
- `spankuser1` (regular user with new spankin as their company)
- spankin asset (asset belonging to spankin company)

When I login as `spankinadmin1`, I can see only the spankin users and assets. Fuzzing the url throws a forbidden as expected.

When I login as `nospankadmin2`, I can only see assets *without a company* (which matches the admin I'm logged in as), BUT I can see and edit users in other companies. 

Trying to figure out if we did this on purpose as a way to let people "float", but I don't think so? That makes more sense for assets than it does people, although I have seen the use case for that too (internal contractors, etc).  I also CANNOT edit permissions on the user, since I am not a superadmin and only superadmins can change permissions on people.

**Comment by snipe** [comment]
(Stuff like this should probably have been sent to security@snipeitapp.com instead of posted here, btw, per the docs.)

**Comment by swift2512** [comment]
> (Stuff like this should probably have been sent to [security@snipeitapp.com](mailto:security@snipeitapp.com) instead of posted here, btw, per the docs.)

I've sent an email with an attached video file (~6MB in size)

**Comment by snipe** [comment]
Thanks - I'll delete this thread then.
