### ISSUE TITLE
Fresh installation not working

### ISSUE THREAD

**Issue by asgeralam** [snipe/snipe-it#1512]
Hello Support,

I am installing through snipe it through install.sh on ubuntu 14.04, after installation many database tables and fields are not created and there is no data, after using php artisan db:seed command its created but still users and settings tables are empty.

When I am going to login following error comes -
 ErrorException (E_NOTICE)

Undefined index: notes
Open: /var/www/snipeit/app/controllers/AuthController.php

                        $credentials = $this->createUserFromLdap($userattr);
                        Sentry::authenticate($credentials, Input::get('remember-me', 0));
     
     
                    }
                }
     
                else if ($user && strpos($user["notes"],'LDAP') !== false) {
                    LOG::debug("Authenticating user against LDAP.");
                    if( $this->ldap(Input::get('username'), Input::get('password')) ) {

Please let me know how can we fix it.

Currently I am not using LDAP for user authentication.

Thanks,
Asger

**Comment by uberbrady** [comment]
You need to do the `app:install` command, and **that** will end up running migrations for you. It also asks you if you want to seed your database.

Some tables like the Users table are created only on app:install, and not as part of the Migration process. That's why you have to do it via app:install.
