### ISSUE TITLE
API: Country field isn't validated properly

### ISSUE THREAD

**Issue by StarlessNights** [snipe/snipe-it#15344]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When [`POST`ing a location](https://snipe-it.readme.io/reference/locations-2),[^and_others] the API will accept any string in the `country` field. This arbitrary string will also be returned in subsequent GET requests.

However in the UI `country` is represented as a dropdown. Selecting a country from the UI leads to a 2-letter country code to be returned from the API.

This behavior is inconsistent. The API should enforce the same restriction on the `country field`.

[^and_others]: This likely affects other requests as well. PATCH, PUT and probably `/users` endpoint too. 

### Reproduction steps

`POST /locations` with the following body:

```json
{
  "name": "New loc",
  "country": "Nonsense"
}
``` 

The response will indicate that the operation was a success, and that the `country` field was set to "Nonsense":

```json
{
  "status": "success",
  "messages": "Location created successfully.",
  "payload": {
    "id": 19,
    "name": "New loc",
    "image": null,
    "address": null,
    "address2": null,
    "city": null,
    "state": null,
    "country": "Nonsense",
    "zip": null,
    "phone": null,
    "fax": null,
    "assigned_assets_count": 0,
    "assets_count": 0,
    "rtd_assets_count": 0,
    "users_count": 0,
    "currency": null,
    "ldap_ou": null,
    "created_at": {
      "datetime": "2024-08-20 13:10:39",
      "formatted": "20.08.2024 13:10"
    },
    "updated_at": {
      "datetime": "2024-08-20 13:10:39",
      "formatted": "20.08.2024 13:10"
    },
    "parent": null,
    "manager": null,
    "children": [],
    "available_actions": {
      "update": true,
      "delete": false,
      "bulk_selectable": {
        "delete": false
      },
      "clone": true
    }
  }
}
```

The created location will look like this in the UI:

![Snipe-IT location country](https://github.com/user-attachments/assets/49e336d4-c220-4b19-a095-e75ed1f95d3f)

### Expected behavior

The API should reject nonsense strings, and only accept valid country identifiers.

### Snipe-IT Version

7.0.10

### Operating System

Ubuntu (Container)

### Web Server

Apache

### PHP Version

8.1

### Additional context

Container in Kubernetes.

**Comment by snipe** [comment]
I'm not sure we want to change that - lots of people use the API in unexpected ways, and it could break integrations if we suddenly introduce enforcement there. Really, it's not a special field, just text, and some folks barely use the UI at all.

**Comment by ramanjitsevo** [comment]
I believe it should be fixed because, if random text is added to the Country field, it is unable to detect the country name from the dropdown list.
![image](https://github.com/user-attachments/assets/3463ac0d-2d2f-4969-b710-d6088066cb02)
![image](https://github.com/user-attachments/assets/260e3f6f-be7e-4192-9d8b-608acec299a0)
![image](https://github.com/user-attachments/assets/14ee571d-e6ac-4382-b18c-04f51bfc42c5)

**Comment by snipe** [comment]
I understand that, but breaking existing integrations/imports isn't really an option either.

**Comment by StarlessNights** [comment]
It is an option, and unavoidable in the long run. Deprecation is a normal (and essential) part of software lifecycle.

That said, this particular issue might not be worth it alone. Perhaps queue with other breaking changes in the the future?

**Comment by snipe** [comment]
> It is an option, and unavoidable in the long run.

Please don't tell me what's an option and what isn't in my own software. We have 10+ years of knowledge about our user's workflows and challenges.

**Comment by StarlessNights** [comment]
Thanks for opening up your perspective.

**Comment by snipe** [comment]
The only way I can see this *potentially* working (and even then, it's going to cause a ton of support tickets) is if we do a migration to "best guess" the code based on the word. This wouldn't work for typos (which we see a ton of), and definitely seems like the harm it could cause could be worse than the benefit. Since we use model level validation, making this change would mean if an API endpoint is trying to just update a user's name for example, the save would fail if the bad data was already on the user model, since the model itself would no longer validate.

**Comment by StarlessNights** [comment]
Good points. Another angle would be to change the UI element instead. To display, if not input, freeform strings.

**Comment by snipe** [comment]
That's what I'm looking into (via Select2's tagging option)

**Comment by snipe** [comment]
https://github.com/snipe/snipe-it/pull/15367
