### ISSUE TITLE
Custom Fields - Some Thoughts

### ISSUE THREAD

**Issue by dmeltzer** [snipe/snipe-it#1555]
Hi Friends, 

Playing with custom fieldsets some.. I know It's right before a release and I probably should have checked this a few weeks ago, but here are a few things that I think would be great places for improvements in the long term.. I love the custom fields currently though!
1. Assign Fields to asset models directly, rather than needing a fieldset .  It would be nice if I could pick fields from a list when editing an asset model, and build a fieldset dynamically, rather than needing to create a fieldset from fields for each model.  This kind of ties into 2.
2. Multiple Fieldsets / Asset Model:  Currently, I can only assign one fieldset to each model.  This means that for each combination of fields that might need to be assigned to a model, I need another fieldset.  If I have some assets with weight, some with a mac address, and some that have a custom url, and some that have a specific lamp type, and then some assets with weight and a lamp type, and some with weight and a mac address.. and some with three of the four.. you can see where this is going, right?
3. Default value for fields - It would be nice to assign a default value to fields.  Not sure if it makes more sense on the field level or a default value for a field when you add it to a fieldset... 
4.  Custom fields on an asset-model level.  For something like weight, it would be cool if I could have that value associated with the asset model and not with each individual asset.
5. Edit parameters of a field after it's been created - I'm not sure if this is possible, but changing the validation rules, or the value type, or the field name...  would be cool!

I'll be floating around if any of these are unclear, certainly nothing critical here, but things that would be cool to have!

Thanks

**Comment by snipe** [comment]
![welp-pizza](https://cloud.githubusercontent.com/assets/197404/12060151/1dd7358a-af1e-11e5-9e95-cf693eb2c03f.gif)

**Comment by uberbrady** [comment]
I think, ultimately, I'd really like to hear more of how you're thinking of implementing these things. That might help me better understand what your use cases are here. However, here are my preliminary thoughts on what you're proposing:

1. This sounds like a UI thing. I definitely feel there's some UI refinement that can happen in Custom Fields - and what you propose here sounds like a good way to do it (you should see how it looked before @snipe made it so much better!). However, I imagine there are some 'fieldsets' that you might end up sharing across many different models. For instance, the 'mobile phone' fieldset might have SIM card, IMEI number, Phone number, and perhaps some other ones I can't think of. And so having to keep re-picking that same exact set of fields for iPhone 5, iPhone 5S, iPhone 5C, iPhone 6, iPhone 6Plus, iPhone 6S, iPhone 6SPlus.... - I would imagine that being pretty unpleasant. Whereas just picking 'fieldset: Phone' would be better. That being said, the idea of allowing inline-creating a fieldset on the fly in the model editor would be the best of both worlds.

2. 'requiredness' of a field is an attribute you can define when you are adding fields to a fieldset. So if you have a set of fields where some of them are sometimes empty, you can mark those particular fields as not being required. That should help reduce the count of fieldsets you have. As I mentioned above, I'm curious to hear more about your example in this - you mentioned 'lamp type' and 'weight' and such - I'm curious to know a little more about what you'd be intending to track here.

3. Hrm. No ideas here. Not sure. I *think* I would put the default at the Fieldset level, not the field level - if we were to do this at all. I'll keep pondering.

4. That's a whole other ball of wax - not out of the question, certainly, but probably not something I'd see coming up in the very near future unless there's a lot of demand. I'd probably be more inclined to do the 'default value' thing, and then you could set that when you assign the fieldset (perhaps?) and you'd effectively be setting a model-level value that would also get propagated out to the actual assets.

5. This isn't out of the question. A curious problem could come up though - if you change the validation to make it stricter, what do you do with the pre-existing values that are already assigned to the field? I'd hate to have to spool through the entire collection of all assets to re-validate that the new (stricter) validation will actually pass. Of course one could just punt on this, that'd be easy.

So - definitely tell us more about your use cases here, what you're trying to track, etc. I'd love to hear more about it so that your requests will sound more fully-formed in my head.

**Comment by ddreier** [comment]
A potential use case that would profit from several of @dmeltzer's points: Rack-mounted server height.

Each asset of some particular server model is going to have the same height (2U, for example). So it would be nice if either I could add a custom field to the *Model* to say that "this particular Asset Model is 2U high." Or have new assets of that particular model all have a default height of 2U.

**Comment by mochange** [comment]
What would be useful is being able to "edit" or rearrange and/or remove fields from fieldsets.
Its kind of nuts to need to delete and start a fieldset from scratch if you decide to remove something after the fact, and its already in use by dozens of assets then its a real hassle. 
Secondly the ability to edit custom fields, currently you can create or delete. Even only being able to edit the name would be a good start.

So far in the day or so of tests I am liking it very much, keep up the great work.
Thanks

**Comment by snipe** [comment]
There is already a ticket open for editing and reordering custom fields

**Comment by raj0307** [comment]
Hi, 

Recently i have upgraded to 4.1.3 but after upgrading i am not able to view custom fields in assets. 

Also Is there a way to modify the default columns in assets?

Appreciate your response. 

Regards,
Rajesh

**Comment by snipe** [comment]
@raj0307  -  Hi there - this issue is closed and doesn't seem directly related to your issue. Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)
