### ISSUE TITLE
On installation script tries to authenticate to mysql root with no password

### ISSUE THREAD

**Issue by mileskjeller** [snipe/snipe-it#1561]
Line in snipeit.sh

echo "## Input your MySQL/MariaDB root password: "
sudo mysql -u root < $dbsetup

should read

echo "## Input your MySQL/MariaDB root password: "
sudo mysql -u root -p < $dbsetup

Otherwise installer fails

(see installer log http://pastebin.com/qb770KHG)

**Comment by merid14** [comment]
I know why i took the -p out, it was because if you had a blank mysql/mariadb password as is on a fresh install then it should be blank. and to not confuse anyone trying to figure out what their blank mariadb password was it just passed on. I see now that is a big issue if you already set your mysql password (which is not the case on my test server.) I will add this to my testing methods and re-add the -p to the installer.

**Comment by merid14** [comment]
@mileskjeller Care to test this patch to make sure it works for you?

**Comment by snipe** [comment]
@mileskjeller were you able to test this?

**Comment by mileskjeller** [comment]
Yup, ran it on a blank machine, seems to be all good now!
Brilliant work :)

snipe wrote:
