### ISSUE TITLE
Label Size and Source

### ISSUE THREAD

**Issue by QuantumSchema** [snipe/snipe-it#1570]
Hi Snipe Team!

I must first start by commending you on a job well done! Snipe-IT is gorgeous and well executed!

I was looking at doing a possible implementation of Snipe-IT but the only hold back currently is the label size and source. Is there a way to change the barcode data to be the asset tag and the label to print to a 2"x1" label? We have a quite a bit of money invested in WASP printers and would prefer to keep using these as we move forward.

Thanks!

**Comment by ddreier** [comment]
I don't know that there are any plans to allow customization of the labels. However, you can always just export a CSV and import that into the WASP, or some other, label printing software.

**Comment by snipe** [comment]
Label customization is a planned feature, but it's still a little ways off. It's complicated and even more complicated to test. @ddreier's suggestion is probably the best for now.

**Comment by foxworth42** [comment]
For what it's worth, I've successfully modified my install to do direct printing to a Zebra LP2824 using 2.25"x1.25" labels (https://imgur.com/Ug0bObm).  The ZPL markup used to generate the labels could fairly easily be set up to be customizable in a similar fashion to the label customization in 3.0 that snipe showed on #1850.

That being said, I'm doing the printing directly from the server, with the snipe-it and the printer existing on the same network and printing via direct socket connection which would be more difficult if the Snipe-it installation is hoted remotely.  (I started looking through the open tickets to see if there were others using these kinds of printers, and looking into spending some time refining the modification I did to support ZPL based printers into a possible plugin or something).

Even if the ZPL markup for a label format weren't built into Snipe-it, it might be useful to have an interface where a shop using WASP/Zebra printers can specify a printer's IP/Port and develop their own ZPL(or other markup language) template to output to the printer.  This would put the task of developing/testing the label design/formatting on the shop using the printer, all that Snipe has to be able to do is connect to the ip/port and output the label markup that was given along with some string substitution to populate the asset info.

**Comment by jrodfosheez** [comment]
@foxworth42 by 'modified my install' what exactly do you mean? i have begun to work w/ SnipeIT and we are trying to work out a good solution for printing the barcodes. did you just adjust the Zebra printer settings?

**Comment by foxworth42** [comment]
Sorry for not replying sooner.  I did a quick check in of the WIP I was doing in my local setup (https://github.com/foxworth42/snipe-it/commit/53ce9ca3f23cf6ff95c88857ca24836db71531e7).  I had separated the printing function into a new controller and added some configuration options for defining the target printer to print to, and a field for specifying a ZPL template.  I had established a couple ZPL placeholders that get specified in the template for filling in the necessary content.  I was starting to look into having an option when using ZPL to have the label automatically printed on asset creation rather (since there is no need to batch print labels).

![settings](https://cloud.githubusercontent.com/assets/10375039/15383251/8a2ea664-1d46-11e6-9450-3aca14d02a80.jpg)

This is the ZPL template code I have configured on my setup for printing labels on 2.25x1.25 labels:
^FO10,50^BQN,2,4,Q,7^FN1^FS
^FO5,200^BCN,50,N^FN2^FS
^FO10,10^ATN^FN3^FS
^FO150,60^AQN^FN4^FS
^FO150,90^AQN^FN5^FS
^FO150,120^AQN^FN6^FS
^FO150,150^AQN^FN7^FS

Produces labels like:
![label_example](https://cloud.githubusercontent.com/assets/10375039/15383384/7c8740c4-1d47-11e6-98d3-48d02fbdea47.jpg)

**Comment by snipe** [comment]
Those labels look fantastic! We're just rejiggered the labels for the upcoming v3 (v3 branch). I'll have to see if there's a way to merge in your stuff. Really nice work

**Comment by gertje1978** [comment]
Wow! This is what i am looking for...

But I have this verson of Snipe-It: Version v3.6.2 build 10 (g927a12f)
I can't implement this code... :(
There is a possibility to make this work anyway?
I have a Zebra Stripe 4M with USB...

Thanks for your support!

Gert (Belgium)

**Comment by razmi** [comment]
Hi snipe team
I've changed the url for in the .env but barcode still generate the old url. How can i fix this. Thanks

**Comment by braedenmccann** [comment]
Did this ever get merged in to the new label engine? I have a really roundabout way of printing labels with a zebra printer and it would be so awesome to send ZPL from Snipe directly.

**Comment by snipe** [comment]
Hi there - sorry for the freakishly long time in responding here. This one fell off our radar :( 

Since the time this issue was opened, a ton of changes have been made in Snipe-IT. If you're still seeing this issue in the current version, please open a new issue that includes:

- Version of Snipe-IT you're running
- Specific errors you're seeing in the UI and/or in the browser console and error logs
- Steps to reproduce 
- Whether or not you can reproduce this on the demo (https://demo.snipeitapp.com)

Thanks - and again, sorry for the very late reply. We're doing some cleanup of old issues, so we're rediscovering some older things that didn't get addressed the first time around. 

![BeakerEmbarrased](https://github.com/user-attachments/assets/d37f3fd5-3b1f-4472-9cf6-436c7bd119fc)

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
