### ISSUE TITLE
Suse Enterprise

### ISSUE THREAD

**Issue by xtherebellion** [snipe/snipe-it#1604]
For Suse, the install.sh / snipeit.sh script fails due to inability to detect OS, can it still be installed manually? or are there plans to support Suse in the near future?

**Comment by mtucker6784** [comment]
Hello,

I've never used a suse based box (open or enterprise), but I'm not opposed to integrating it into the install script because it'd be something new for me to learn. Snipe it is all web based, so as long as you have a decent understanding / foundation of Linux, apache (or nginx), it shouldn't be too bad to get going on your box by following the instructions on the snipe it docs.
