### ISSUE TITLE
File Type must be csv

### ISSUE THREAD

**Issue by rvasquez151** [snipe/snipe-it#1614]
I am trying to import assets from a csv file. I keep getting the error 'file type must be csv" when uploading. Any suggestions??

**Comment by snipe** [comment]
Are you sure it's really a CSV file, not just a file whose file extension has been changed?

**Comment by rvasquez151** [comment]
I downloaded the sample csv file and filled in with my data. Asset Notes, Asset Purchase Date and Asset Purchase Cost fields are empty. Documentation states these fields are not required. I re-downloaded the sample csv file and uploaded the blank file and it appears to take it. Not sure what is going on.

**Comment by rvasquez151** [comment]
I figured it out. The "FirstName LastName" data was not formatted correctly.  I used firstname.lastname and it freaked out the csv.  Changed it to proper format and was able to upload it.

**Comment by rvasquez151** [comment]
Think I just created another issue for myself. I accidently clicked on process twice and now I have duplicate entries. Any suggestions on how I can fix this?

**Comment by tmongero** [comment]
In SQL, truncate the table and re-set the auto_increment fields. Then, re-import.

Commands (sql CLI):

TRUNCATE TABLE assets;
ALTER TABLE assets AUTO_INCREMENT=1;

Rinse & Repeat for any other tables affected by the data import that you wish to reset. Also, this is why the Snipe documentation recommends backing up your database prior to running the importer tool. I feel your pain, as I've had to restart within SnipeIT almost 10 times now (mainly because of the horrific inventory database I'm attempting to migrate from).

That being said, the documentation for the importer tool could really use some improvement. It's pretty vague regarding how the importer handles field enclosure, and doesn't precisely describe how the data in the CSV needs to be formatted. Also, the 'Sample CSV with dummy data' contains no dummy data - only field headers. Last point: the field headers in the CSV do not match those in the table columns, which is not only confusing but consumes more time to complete.
