### ISSUE TITLE
If assets are deleted, the user association assumption should be removed

### ISSUE THREAD

**Issue by dudeincali** [snipe/snipe-it#1630]
For example, I deleted 1000 assets, because the csv import is not accurate, even with table column count correct and appropriate csv data in correct column. However, once I delete ALL assets, or even some, then the association of that user should be removed automatically. Then, I can delete the user, but not until the association can be broken. Clicking check in one by one is insanity.

**Comment by snipe** [comment]
Please include the version number with every support ticket. I have no way of remembering from one ticket to another which version you're using, and that matters. http://docs.snipeitapp.com/getting-help.html

Lots of people use the CSV importers and don't have issues with them, so I'm not convinced that the CSV import is not accurate in the first place, but putting that aside...

When an asset is bulk deleted, the currently assigned user is set to null, so that asset is no longer checked out to any user. I'm not sure which user association you're referencing.
