### ISSUE TITLE
Resend user credentials

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#1633]
Hi Snip,

is it possible to add a button or a link to re-send  user credentials from people management , it is now available only while creating the user 
the reason why needed that is when i imported a list of users or created them and after some time i want to send them their credentials .

thanks in advance and kind regards

**Comment by 823Labs** [comment]
+1

**Comment by snipe** [comment]
This is not possible. Passwords are hashed in the database. A hash is one-way and provides no method for decryption. Hashing is a one-way operation, so there is no way to get the user's password from the hash. Simply encrypting passwords on the server is considered less secure, which is why we don't do it. 

The user will have to do a forgotten password request to reset their password.

**Comment by abdullahalasham** [comment]
it is okay for Password , what about other account info such as Username and Email can we use the above requested button to send a notification for this account info with a link to set a password.

thanks
