### ISSUE TITLE
Custom Field Creation Error

### ISSUE THREAD

**Issue by brightonhouseholder** [snipe/snipe-it#1637]
When Trying to create a custom field I receive this error. 
![screen shot 2016-01-14 at 12 39 25 pm](https://cloud.githubusercontent.com/assets/16247685/12335339/e94335a4-babb-11e5-9e83-b4d6fa5f7503.png)

Version: v2.1.0-pre
OS: Centos 6.7
Webserver: Apache (httpd)
Installation method: Manual Installation
Error: I am Receiving a message in my browser-- see image attached 
Error Location: Admin settings --> Custom Fields --> New Custom Field
Note: I am not receiving any errors in the apache2handler log or in the mysql logs

I have also not edited any data manually in the database

**Comment by uberbrady** [comment]
Hrm - what was the name of the custom field you were trying to create? If it somehow conflicts with another custom team field, this error can occur. Though it shouldn't ever happen (that's why the error is so terse, sorry about that).

Do you have the ability to look at your database - using phpMyAdmin or MySQL command-line? I'd be interested to see the schema for the 'assets' table.

**Comment by brightonhouseholder** [comment]
I was trying to have a field name of IMEI. Yes I do have the ability to do that I have attached a screenshot.
Thanks for the help! I appreciate the speedy response :D 
![screen shot 2016-01-14 at 12 59 38 pm](https://cloud.githubusercontent.com/assets/16247685/12335917/cefff792-babe-11e5-9b40-2b60ffabaa4a.png)

Also want to note.. I think I see what you are saying might be an issue here with the _snipeit_imei Field?
I just dont understand why it wouldn't be available for use but would be there? Maybe there was the ability to partially create the field but throw an error at the end and not show it in the custom fields?

**Comment by uberbrady** [comment]
Yes, that's what I'm saying.

If you create a custom field and call it something else - "IMEI2" or something similar - you should be able to create it OK.

We already have a bug report asking for the ability to rename custom fields; it's something we'd like to do. But it's not possible yet.

I bet we can also change a little bit of the logic around how we do the 'save' check so that we don't end up with weird dangling fields like what you have here.

But first off - can you create a field called "IMEI2" instead and use that in the meantime?

**Comment by brightonhouseholder** [comment]
Ok, yes that one works. Thanks for the help! Was driving me crazy! I agree some logic around a save check would be great. 
Thanks again!
