### ISSUE TITLE
Assign assets/software to non- "account" individuals

### ISSUE THREAD

**Issue by BHollowell** [snipe/snipe-it#165]
Presently you have to setup an “account” for a user before you can checkout an asset or software license to a user. In my specific environment, I won’t ever have more than a few ITAM employees accessing this site, so they don’t really need accounts persay. It would be nice to have the ability to choose between assigning the asset to a pre-existing account or typing a name in the field that would go into a separate database table which is strictly a name an GUID to identify them. Is this something that is possible?

**Comment by snipe** [comment]
I think an easy win here might be to switch to using a username instead of a an email address for the login. We can randomly generate a username if an email address isn't given, and that way the user never even needs to know that they have an account.

**Comment by BHollowell** [comment]
I think that's a fantastic idea. Allowing us to create arbitrary usernames while still requiring an email address would be perfectly fine, as we could just use a generic email for conference rooms and the sort.

**Comment by snipe** [comment]
Or even not require email addresses. Email addresses are required to be unique, currently, so re-using one over and over wouldn't be possible. Plus, some folks want to have users that basically never have any interaction with the system, so they don't want to have to find email addresses for everyone.

I think the process would basically be:

- [ ] Write a migration to copy all of the email addresses into the username field in the DB
- [ ] Update the auth system to use username instead of email
- [ ] Update the user model so that email is no longer required (but still validated if one is provided)
- [ ] Update the user import to generate a username automagically if none is given, and store the email address if a valid one is giving
- [ ] Double check everything else that may email the user to make sure it only fires if an email address is given

**Comment by BHollowell** [comment]
I think this is a perfect solution. My only recommendation would be to truncate the usernames start at the @ symbol so it only contains the first portion of the email.

**Comment by snipe** [comment]
I think it would be smarter to leave them as they are for the copying, so no one gets confused. If you were always logging in with an email address, and suddenly have to login with a username, that could be problematic. Presumably the user can update their own username, so if they prefer to use the shorter version, they could change it. Not sure how I want to go with that just yet.

**Comment by BHollowell** [comment]
Just as a follow up to a previous question in this thread - do you still intend to add a field to the asset creation process that will allow us to create a new user at the same time as the asset is added to the database?

**Comment by snipe** [comment]
Yeah, that's still planned

**Comment by BHollowell** [comment]
Great to hear! I'm really excited for this feature. Now that you have a preliminary asset acceptance process, and this seems to be on the horizon, the only thing left for my environment would be LDAP integration. That feature is definitely just a convenience thing, though. Being able to create user accounts at the time of asset entry will be a major win for me.
