### ISSUE TITLE
[Feature request] Leased assets

### ISSUE THREAD

**Issue by danpospisil** [snipe/snipe-it#1692]
We don't buy laptops, monitors and computers in our company. We have it all leased from another company and it would be really cool if we would be able to put monthly cost for every asset and snipe it would show us how much we have paid for the asset since the month we have received it. 
Also, after 3 years we get lower monthly price for every piece of hardware we keep, so it would be cool, if we could "transfer" the amount we have paid since the first month to the cost of the hardware and then we could change the monthly cost to the new value and we could see total price (paid for first 3 years plus the new lease cost starting from the day when the 3 year period had passed)

For example, we get new LCD monitor for $10 per month. 
So, after 3 years we paid $360 for it. But if we decide to keep it, the monthly price drops to $2 per month. So we would need to transfer $360 to purchase cost and then it should display $360 + months_after_3_years \* $2

PS: 3 years period is not fixed, so I think there should be some kind of button to do the transfer.

I hope it's all clear

**Comment by ddreier** [comment]
This is my opinion, and mine alone.

I think you're looking more for a cost accounting solution, rather than an asset management solution. I definitely understand your use case, but it seems pretty niche. Snipe-IT does have depreciation calculation, but I think that what you're asking for is several levels above that and definitely would not be trivial to implement.

However, you're more than welcome to implement it yourself and submit a pull request!
