### ISSUE TITLE
LDAP import limited to 1000 users?

### ISSUE THREAD

**Issue by olivermarshall2** [snipe/snipe-it#1714]
Hi

v2.1.0-8-g1b1a733 running on Ubuntu. Installed via install.sh. 

Is there a limit to the number of records supported by the ldap import function? We have thousands of users but each time we import we only seem to see 1000 users imported. I've copied the list in to excel each time and it's always 1000. 

All our users are under the same base DN so they should all be accessible to the query, and a query tool returns all the users. 

Anyone else see this?

Olly

**Comment by tmongero** [comment]
I'm almost positive this used to be documented on the LDAP/User Management page (http://docs.snipeitapp.com/manual/user-management/index.html) but it seems as though this page has been updated since I've last visited it.

If I remember correctly, the LDAP user importer tool does have a 1000-user limit. I have also noticed the behavior you described, yet have not found an issue with running the importer multiple times to successfully import all LDAP user accounts.

**Comment by olivermarshall2** [comment]
Hi Thomas

Reimporting doesn't work as it just imports the same users and marks them
as existing. It's not 1000 new users it's 1000 users total per import.

Is that set in a PHP file somewhere that I can edit? Even if I have to edit
the file after each upgrade it would be an option.

Currently we still have a thousand or so users not on the system but whom
all have devices.

Olly

**Comment by snipe** [comment]
Well, I wrote it, and I don't remember anything about 1000 users. We did mention in the asset importer that your install may time out with multiple thousands of records because of memory issues, but there is no limit coded in. Perhaps check your LDAP server to see if it caps at 1000 for the number of results returned?

**Comment by olivermarshall2** [comment]
Right. It appears to be a tweakable parameter in Windows AD. Tweakable with
caveats as it comes with its own issues.

Could I suggest a mod for future versions? A great solution would be to
support multiple "LDAP Authentication Query" entries in the LDAP.php file.
The limit is per search result page. MS say that LDAP queries should
support multiple pages. However another solution is to process smaller
queries.

If you were to support multiple query lines the user could then do
something like "samaccountname=a*", "samaccountname=b*" etc, thus making
each query far smaller, and getting around that limit.

Could that be done?

Olly

**Comment by olivermarshall2** [comment]
For those looking to solve this issue, this article helps. However changing the setting is not without risk so do so at your own risk.

http://blogs.technet.com/b/qzaidi/archive/2010/09/02/override-the-hardcoded-ldap-query-limits-introduced-in-windows-server-2008-and-windows-server-2008-r2.aspx
