### ISSUE TITLE
Multiple Alert Email Addresses

### ISSUE THREAD

**Issue by lutherpros** [snipe/snipe-it#1738]
Can we add functionality to add multiple email addresses in the Send Alerts to field?

Thanks

**Comment by ddreier** [comment]
Good idea. Also, at least for now, you could create a Distribution Group and put that into Snipe-IT.

**Comment by snipe** [comment]
Yes, this is typically handled through a distribution group

**Comment by ddreier** [comment]
@snipe FWIW, it looks like you can [pass an array of email addresses](http://stackoverflow.com/a/26586288) to the `to` function in the `Mail::send()` Closure.

Do you think it would be worth the effort to wrap `$settings->alert_email` in a helper function that would take, for example, a semi-colon delimited list and split it into an array?

**Comment by snipe** [comment]
@ddreier I mean, yes and no. This is a problem that people typically solve through distribution lists (which IMHO is a better way to handle it anyway, since that's usually handled via LDAP or AD, so you can add/remove people when they are hired/fired without remembering to login to the Snipe-IT system). It wouldn't be difficult to do, it's just not a huge priority right now.

**Comment by ddreier** [comment]
Totally agree. I just had an itch and did the research. :P

**Comment by snipe** [comment]
This is completed for the upcoming v3. 

@ddreier if you're curious what I did, check out this commit.
https://github.com/snipe/snipe-it-laravel5/commit/b08a333396abecc61917e4b27f752d8a99a8f34b

**Comment by snipe** [comment]
@ddreier the challenge wasn't getting the array into SwiftMailer, it was validating the email addresses individually, even though they're submitted as a string.

**Comment by ddreier** [comment]
@snipe cool beans, and makes sense.
