### ISSUE TITLE
List of variables for use in emails and custom fields

### ISSUE THREAD

**Issue by olivermarshall2** [snipe/snipe-it#1744]
Hi

Is there a list of variable names that can be used in the email blade files? Such as item_name, item_tag etc

Also are we able to add custom fields to emails? I want to be able to add MAC addresses where we have it on file.

Olly

**Comment by snipe** [comment]
There aren't any variable names available in the email blades - each value would have to be coded into the controller and passed through to the email blades.

The challenge isn't adding the values, it's that I'm sure some users won't want custom fields in their emails, so that's another setting that will need to be built in.
