### ISSUE TITLE
The installer was unable to determine your OS

### ISSUE THREAD

**Issue by lmsequeira2016** [snipe/snipe-it#1767]
The install.sh exited with following error:

------------------------------------
Welcome to Snipe-IT Inventory Installer for Centos and Debian!

The installer was unable to determine your OS. Exiting for safety.
------------------------------------

The server is running with "CloudLinux Server release 6.5"

Any advice?

**Comment by merid14** [comment]
Currently only Centos/redhat and debian/ubuntu is supported via the installer. but you can install it manually: http://docs.snipeitapp.com/installation/index.html

**Comment by jennlevbird** [comment]
I was running RHEL 7.2 and the installer couldn't determine my OS.

I updated the snipe-it.sh to be this to install:
#  Lets find what distro we are using and what version
distro="redhat"
#distro="$(cat /proc/version)"
#if grep -q centos <<<$distro; then
#       for f in $(find /etc -type f -maxdepth 1 \( ! -wholename /etc/os-release ! -wholename /etc/lsb-release -wholename /etc/\*release -o -wholename /etc/\*version \) 2> /dev/null);
#       do
#               distro="${f:5:${#f}-13}"
#       done;
        if [ "$distro" = "centos" ] || [ "$distro" = "redhat" ]; then
                distro+="$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))"
        fi
#fi


Because the output of cat /proc/version is this:
Linux version 3.10.0-327.18.2.el7.x86_64 (mockbuild@x86-020.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Fri Apr 8 05:09:53 EDT 2016

**Comment by snipe** [comment]
@merid14 Is that looks like a viable fix, can you create a PR?

**Comment by merid14** [comment]
@snipe here you go: Fix supported distros #2065

**Comment by snipe** [comment]
Thanks, @merid14! I'll merge that over to v3 as well.

![hackerman](https://cloud.githubusercontent.com/assets/197404/15439755/a54b486c-1e86-11e6-8160-9ad1ed00e497.gif)
