### ISSUE TITLE
Ability to assign ID to users and make it searchable - mainly for card scanning purposes

### ISSUE THREAD

**Issue by suiciety** [snipe/snipe-it#183]
This one can probably fit under the custom fields section or part of the broader authentication system but I would find it pretty handy to have an employee identifier other than email that was integrated into the asset search and checkout process.

We have cards issued to all users that use this identifier and being able to search a user on this field means we can checkout items out or search for checked out items from the asset screen a lot quicker using a scanner.
e.g. Scan asset to go out, press checkout, scan users card, all done.

**Comment by maarbu** [comment]
New to your project and github, so go easy on me if this isn't the place.  

I think this may help suiciety accomplish the task of scan, click checkout, scan, save ->done

I modified AssetsController.php around line 442 to be:
        $users_list = array('' => 'Select a User') + DB::table('users')->select(DB::raw('concat_ws(" ",first_name,last_name,employee_num) as full_name, id'))->whereNull('deleted_at')->orderBy('last_name', 'asc')->orderBy('first_name', 'asc')->lists('full_name', 'id');

the concat_ws will add a space separated list which includes the employee number so that if you scan their barcode in the select a user field it will pull up that user. 

Potential issues:  the employee_num is a text field in the database which could have unfriendly results if the employee id is really long or has sequences that could be derived as code.
