### ISSUE TITLE
Accessories break when deleting a category with accessories in it

### ISSUE THREAD

**Issue by Master00Sniper** [snipe/snipe-it#1932]
#### Expected Behavior (or desired behavior if a feature request)

If you delete a category with accessories in it, it should either A) inform you that there are accessories in that category, and you need to delete the accessories first, or B) delete the category and the accessories inside of it.

-----

#### Actual Behavior

The category is removed, but all accessories are now 'removed' from the system. There are no accessories visible on the accessory page. This has been reproduced on the demo.

-----

#### Please confirm you have done the following before posting your bug report:

- [] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

- I have not enabled debug mode... but I have tested it on the demo site and reproduced the issue.

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
(v2.1.0-55)

- What OS and web server you're running Snipe-IT on
Ubuntu LAMP server

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- If you're getting an error in your browser, include that error
N/A

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Accessories and Categories for accessories

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
This is reproduceable

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
N/A

- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A

- Indicate whether or not you've manually edited any data directly in the database
I have not edited anything manually

**Comment by snipe** [comment]
Okay, I have a fix out for v3, but it still needs some work. The link when you click through to the category detail will always point to hardware, even if it's not a hardware item.

I need to rethink the way I'm handling those controllers so I can avoid a ton of copypasta, but at least it should prevent you from deleting a category with stuff in it for now. (This is currently only available on v3 though, and v3 is coming out soon, so not sure if I'll have time to push out a hotfix for v2. I normally hotfix master/develop first, but v2 to v3 is pretty huge, enough so that just switching branches can sometimes mangle my local dev environment.)

**Comment by Master00Sniper** [comment]
@snipe Can you provide any guidance as to how I can fix my broken accessories? Will the upgrade to 3.0 fix the issue if it's already broken? Is it possible I can fix it on my current version, v2.1.0-55?

**Comment by snipe** [comment]
The only way I can think of is to un-delete any categories you have marked as deleted.
