### ISSUE TITLE
Departmental support

### ISSUE THREAD

**Issue by blortox** [snipe/snipe-it#1954]
## **Desired Behavior - Feature Request**

Departmental Support.
Assets and people can belong to departments, And select assets can only be requested by certain departments (E.g each department has an IPad, A Dev wants to check one out, they can only see the one that is allocated to their department)

**Comment by ebonweaver** [comment]
It appears that Department has been added in v4, but it only applies to people.  Conversely, Company does NOT apply to people, only to Assets.  This seems disjointed.  Both fields should be available to all things, so you can have a person or asset or consumable etc that belongs to Department IT/HR/Finance/whatever in each of company1/company2/etc.

**Comment by dantothebert** [comment]
First off, this asset management system is absolutely wonderful. I cannot say how much hope this brings to me in being able to keep track of things. Thank you.

Having the Department field is fantastic, however I agree it is a bit backwards with the company field. We also want departments managers to help keep track of inventory. We do not want department managers to be managing assets for other departments, but only their own.
Use case: Large team of 10+ people all sharing devices. The team manager can check in/check out devices to their employees. All team members can see who has what device. Makes it very easy to see what's going on. Helps IT manager as they no longer have to worry about 100's or 1000's of devices, they can let it be micromanaged.

Suggestions if this is going to be built out. Adding an option for the asset to be "shareable" so that department managers can check this and assign the asset to a user not on their team. My suggestion would be to add a Department called "Shared Assets" and let people be a part of their own department AND the Shared Assets department. That way users could see all the devices that are shared and can either contact the person that is using the device if they would like to borrow it, or alternatively browse through devices that are in stock under the shared asset department.

The workflow would be simple for the end user. If you do not want the device to be shared, you simply would not make that device a part of the "Shared Assets" department. All users could have access to the "Shared Assets" department, so they could use that as a place to rent devices. I'm sure IT would typically manage those devices, however you could train users to look at what Department the device is in so they can contact that department manager to acquire the device.

Thanks,
Dan

**Comment by snipe** [comment]
@dantothebert As mentioned in other issues, this additional level of scoping is unfortunately non-trivial.

**Comment by dantothebert** [comment]
@snipe No worries,
I will just set up all the departments as companies and check out assets to the company-departments.  They desired result will be similar.

Thanks for the fast response.
