### ISSUE TITLE
LDAP Sync 

### ISSUE THREAD

**Issue by SynchronGmbH** [snipe/snipe-it#1988]
#### Expected Behavior (or desired behavior if a feature request)

During the synchronization with LDAP we expect that the users get the right location ID. 

---
#### Actual Behavior

For the Import we select a Location, for example "Stuttgart", the synchronization suceeds, but 
all users have the Location "Stuttgart" as default location. 
But we have some more locations in Germany and after the import the location should be right... 

I took a look at this file: /var/www/snipeit/app/controllers/admin/UsersController.php
Into the file I saw some code to match the users to the selected location. 
But the match dosen't succeed... 

So I need to know which field does SnipeIT need from LDAP for the Location 
and which value does SnipeIT expect (numeric or an alphabetical)? 

The same problem we have with the company name, after the import all users haven't a company, 
but the company name is given in LDAP. 

Is there any way to get location and company name through the LDAP import? 

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running:   **v2.1.0-8-g1b1a733**
- What OS and web server you're running Snipe-IT on: **Linux 14.04 LTS (Linux 3.13.0-24-generic x86_64), Webserver is Apache2**

**Comment by snipe** [comment]
It is not currently possible to get those fields through LDAP

**Comment by abeloveless** [comment]
Would it be possible to associate through the Locations panel (or a new one) each location to an OU pulled via LDAP.  Then the Sync could process through each Location and import from the appropriate OU.  

As a school district, we have many different locations all with Staff checking equipment out.  Right now, I have all staff in a location called Staff, to make the import easier, but I would rather have them assigned correctly.  My only alternative right now, would be to adjust the BaseDN down to the OU and import each Location at a time... but that's too much of a hassle to deal with right now.

Thoughts?

Btw, thanks for an awesome app!  I'm loving it, and have only been a user a couple weeks.

![image](https://cloud.githubusercontent.com/assets/19696942/15725775/0a9188a4-2813-11e6-9f91-adc7fe0620af.png)

**Comment by fredno** [comment]
Is this still a problem after upgrading to Snipe-IT V3?
Another solution to this problem would be to be able to change the default query on the import page
We could then create a default query as an template, something like this  "&(co=ChangeMECountry)(l=ChangeMECity)" that were never overwritten. 
The importer would have to change the query before anything would be imported.

**Comment by snipe** [comment]
We're planning on adding the ability to associate an OU with locations

**Comment by abeloveless** [comment]
Hopefully, I will get the system upgraded today.



Thanks!





*From:* fredno [mailto:notifications@github.com]
*Sent:* Thursday, July 28, 2016 7:03 AM
*To:* snipe/snipe-it <snipe-it@noreply.github.com>
*Cc:* abeloveless <abe.loveless@estl189.com>; Comment <
comment@noreply.github.com>
*Subject:* Re: [snipe/snipe-it] LDAP Sync (#1988)



Is this still a problem after upgrading to Snipe-IT V3?
Another solution to this problem would be to be able to change the default
query on the import page
We could then create a default query as an template, something like this
"&(co=ChangeMECountry)(l=ChangeMECity)" that were never overwritten.
The importer would have to change the query before anything would be
imported.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/snipe/snipe-it/issues/1988#issuecomment-235875395>, or mute
the thread
