### ISSUE TITLE
License - Checkout History

### ISSUE THREAD

**Issue by rafaelmendonca** [snipe/snipe-it#2024]
It's just a little improvement ... when I do a checkout for one license, I can select the Asset and Checkout to User right. However if the asset have owner (user signed) in the Checkout history of license on field User don't show the user, I need to select the User too to show there!

**Comment by snipe** [comment]
I'm not sure I understand what you're asking for. Can you elaborate?

**Comment by FriedCircuits** [comment]
Since this is still open I will add to it. I think what he is talking about is in the checkout history for licenses it show the device instead of user under the user column. In my case this happens when you select asset only or both asset and user. If you do user only it shows the user. The user column should show the user regardless of how you check out the license. Its a bit confusing with the two options and the results of which you use. It seems to be the most complete currently you should select both asset and user during checkout, except as mentioned the history takes and extra click to see who has the license.

Thanks, hope that helps.
