### ISSUE TITLE
CLI Installation on Windows 2008 R2 / IIS 7

### ISSUE THREAD

**Issue by alixo91** [snipe/snipe-it#2105]
Expected Behavior

OS: Windows Server 2008 R2 Standard
 DB: MariaDB 10.0.14 X64
 PHP: V5.5.36
 Composer: V3.0
 Snipe: V2.1.1
 PHP Extensions and Requirements: Enabled - http://docs.snipeitapp.com/requirements.html
 Configuration: Done as per http://docs.snipeitapp.com/installation/configuration.html
 Dependencies: Installed - http://docs.snipeitapp.com/installation/composer.html
 CLI Install: Failed - php artisan app:install --env=production

-----

#### Actual Behavior

C:\inetpub\wwwroot\snipe-it>php artisan app:install --env=production
=====================================

  Step: 1

    Please follow the following
    instructions to create your
    default user.

-------------------------------------

Please enter your first name: Alixo
Please enter your last name: Alex
Please enter your username: alexu
Please enter your email: example@hotmail.com
_# **---After entering the email address---**_
Please enter your user password (at least 8 characters): The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

Please confirm your user password: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

Password is invalid. Please try again.Please enter your user password (at least 8 characters): The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

Please confirm your user password: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

Password is invalid. Please try again.Please enter your user password (at least 8 characters): The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

Please confirm your user password: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

Password is invalid. Please try again.Please enter your user password (at least 8 characters): The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

Please confirm your user password: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### The following is error gets generated in Windows Event Viewer

Activation context generation failed for "C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Symfony\Component\Console\Resources\bin\hiddeninput.exe". Dependent Assembly Microsoft.VC90.CRT,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8" could not be found. Please use sxstrace.exe for detailed diagnosis.

**Comment by snipe** [comment]
When you enter a password that is at least 8 characters, and push past the errors, does a record get created in the database?

**Comment by snipe** [comment]
http://answers.microsoft.com/en-us/windows/forum/windows_7-pictures/error-the-application-has-failed-to-start-because/df019c0d-746e-42d0-ad68-465e18e3f3ef

Error message: "Side-by-side configuration is incorrect"
The machine is missing the correct C++ runtime components for your type of system. (x86 or x64).
Installing the following update resolved the issue.
Microsoft Visual C++ 2008 SP1 Redistributable Package (x86) 
http://www.microsoft.com/downloads/en/details.aspx?familyid=A5C84275-3B97-4AB7-A40D-3802B2AF5FC2&displaylang=en
Microsoft Visual C++ 2008 SP1 Redistributable Package for (x64)
 http://www.microsoft.com/downloads/en/details.aspx?familyid=BA9257CA-337F-4B40-8C14-157CFDFFEE4E&displaylang=en
Microsoft
Visual C++ 2010 Redistributable Package (x86) 
http://www.microsoft.com/downloads/en/details.aspx?FamilyID=a7b7a05e-6de6-4d3a-a423-37bf0912db84
Microsoft
Visual C++ 2010 Redistributable Package (x64) 
http://www.microsoft.com/downloads/en/details.aspx?FamilyID=bd512d9e-43c8-4655-81bf-9350143d5867

**Comment by alixo91** [comment]
Wow! Thanks @snipe
