### ISSUE TITLE
[v3] Custom Fields break Create Asset page when using HTTPS

### ISSUE THREAD

**Issue by XSF-GH** [snipe/snipe-it#2174]
Hello,

#### Expected Behavior (or desired behavior if a feature request)

When selecting the Model on the Create Asset page, any assigned Custom Fields should then appear underneath.

-----

#### Actual Behavior

Selecting the Model loads the entire Dashboard inside of the _custom_fields_content_ div:
![bug_0](https://cloud.githubusercontent.com/assets/20032687/16180296/7df11522-364f-11e6-9c16-d05ceca00cfe.png)
![bug_1](https://cloud.githubusercontent.com/assets/20032687/16180301/80a8b608-364f-11e6-91b9-2a2354ac6b09.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [**Y**] I have enabled debug mode _(no errors)_
- [**Y**] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----

#### Please provide answers to these questions before posting your bug report:

**- Version of Snipe-IT you're running**
Branch v3-master at commit 412756b651654d764c58369b0dcef6a07022c3d5
**- What OS and web server you're running Snipe-IT on**
Debian 8.5/x64, Apache2 (2.4.10) + Nginx (1.10.1)
**- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)**
Manual installation
**- If you're getting an error in your browser, include that error**
None
**- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error**
Create Asset, Model + Custom Fields
**- If a stacktrace is provided in the error, include that too**
None
**- Any errors that appear in your browser's error console**
Only error in Console is: _"Failed to parse SourceMap: https://<DOM>/index.php/hardware/all.js.map"_, but I think that might be coming from the page being loaded inline
**- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo)**
It is not :(
**- Include any additional information you can find in `app/storage/logs` and your webserver's logs**
Nothing relevant
**- Include what you've done so far in the installation, and if you got any error messages along the way**
Everything's worked great up to this point. I've been able to add users, categories, models, custom fields.. This is the only (big) issue I've encountered. _(see below)_
**- Indicate whether or not you've manually edited any data directly in the database**
I have not
**- Additional info**
This may very well be caused by my setup, but any help/insight would be greatly appreciated!

Per our company's IT requirements, we need to use SSL for all internal tools (including this one). For consistency, performance, and ease of maintenance, we've used the same approach we use for other tools: Nginx for serving static assets and SSL termination with Apache handling the PHP rendering. The only way I've managed to get that working smoothly is with the following setup: https://gist.github.com/XSF-GH/fd0fe3940fb84269dcf28f241d94fdd4

P.S.: Without that change to _app/Http/routes.php_, URIs within the page would still be HTTP and the browser would throw errors about insecure content being loaded.

Are custom fields being loaded in a particular way that could explain this behaviour?

Thanks!

**Comment by lostdesign** [comment]
Sorry for complete OT, but why does your design look so much different to mine?

**Comment by XSF-GH** [comment]
@lostdesign I'm running v3 (https://snipe-it.readme.io/blog/v3-is-coming). :)

**Comment by snipe** [comment]
@XSF-GH Can you confirm that your APP_URL in your .env file is set to the https protocol? The error you're describing usually happens when the APP_URL and the url you're accessing the site from are different.

**Comment by XSF-GH** [comment]
Hi @snipe, it is indeed.

Also, not sure if it'll help but.. I've added some Apache and Nginx logs to: https://gist.github.com/XSF-GH/fd0fe3940fb84269dcf28f241d94fdd4

Thanks!

**Comment by snipe** [comment]
@uberbrady can you take a look at this please?

**Comment by uberbrady** [comment]
First off, I think you deserve an award for spectacular logs and supporting documentation and screenshots. Thank you!

So, looking at what we've got going on here...wow this one looks really difficult. I haven't seen a setup like this, so it's hard for me to piece together what's going on, but I'll give it a shot - 

First off, a slightly easier approach might be to use php-fpm (the FastCGI PHP process manager) - then you don't have to proxy across to an entire webserver. Or, since this thing isn't going to get hit *that* hard, just use Apache by itself and have *it* terminate SSL. That'd certainly be at least easier. But regardless of that (standards are standard, of course), let me see what else I see.

In your Apache logs I'm seeing some funny URL's - and I'm wondering if that could be it - 

```
127.0.0.1 - - [20/Jun/2016:20:53:26 -0400] "GET /index.php/hardware/create HTTP/1.0" 200 14138 "https://<FQDN>/index.php/hardware" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [20/Jun/2016:20:53:28 -0400] "GET /index.php HTTP/1.0" 200 6378 "https://<FQDN>/index.php/hardware/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
127.0.0.1 - - [20/Jun/2016:20:53:29 -0400] "GET /index.php/api/statuslabels/assets HTTP/1.0" 200 1249 "https://<FQDN>/index.php/hardware/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
Raw
```
They ought to look more like `/hardware/create`, `/api/statuslabels/assets`, etc. The `index.php` should be completely invisible.

We do plenty of setups and usually don't have to throw that `URL::forceSchema` piece in there yet, so I don't know how related that could be.

In your nginx logs, I'm seeing URL's looking the same way: Some that say `/index.php/hardware/create`, and plenty that don't - `/hardware/models/1/custom_fields?` - And, come to think of it, that may be the AJAX URL we use to grab the contents of the custom fields. Your `/index.php` mapping glitch could be internally converting that to `/index.php` - thus you get the dashboard loaded up in your custom fields div.

So, I'd see if you can find a way to get rid of that `index.php` thing showing up inside your URL's, and see if that makes your problem go away. That's, at least, my best bet for now. Tough setup, lots of moving parts!

**Comment by XSF-GH** [comment]
Hi @uberbrady!

I have been using Apache on its own since I wanted to get the app working for us as soon as possible. It's been working great so far (as you pointed out, the site won't get that much traffic so it likely won't benefit a whole lot from an Nginx frontend). I still do however want to get Nginx working since I'm planning to eventually make use of its load balancing features (doesn't apply directly to our SnipeIT instance but to our infra as a whole).

php-fpm on Nginx directly might be an option but I haven't used it in the past (also not sure how well the app would react if `.htaccess` files were ignored - I'd need to dig into it).

You might be right about index.php (and the `location / { try_files $uri $uri/ /index.php; }` directive). Nginx needs a way to figure out which files are php so that only those get proxied back.. I'll have to try a few things out.

As for `URL::forceSchema`, SnipeIT/Apache was still returning HTTP content even though the site was HTTPS (with SSL terminating at Nginx) no matter what headers I passed.

I'll mess around with this set up again soon and will let you know what I find. Thanks again!

**Comment by uberbrady** [comment]
Hi there @XSF-GH - just wanted to check in to see if there's any progress on this front.

**Comment by XSF-GH** [comment]
Hey @uberbrady: I've honestly been swamped, but now that v3 is officially out of beta (congrats!), I'm planning to give it another try when I upgrade my beta instance. I'll definitely keep you posted.
