### ISSUE TITLE
Sub directory install on debian 

### ISSUE THREAD

**Issue by gravyflex** [snipe/snipe-it#221]
Hi

Trying to install this in a sub-directory (http://servername/snipe-it) on Debian. Is this possible? I have not been able to locate any documentation.

**Comment by garcia-g** [comment]
Could you please update this issue? I cannot make it work by following the instructions here. To start with, the referenced files do not exist or the names are different.
The purpose is to install SnipeIT in a subfolder (i.e., http://sub.mydomain.com/snipeit).
The problem is that I receive a "Too many redirections" error.
This is my conf file in enabled sites: 
`<VirtualHost *:80>
        ServerAdmin admin@sub.mydomain.com
        ServerName sub.mydomain.com
        UseCanonicalName Off

        DocumentRoot "/home/www/public_html/"
        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory "/var/www-data/public_html/">
                Options Indexes FollowSymLinks
                AllowOverride None
                Order allow,deny
                Allow from all
        </Directory>
        <LocationMatch "^/$>
                Options -Indexes
                ErrorDocument 403 /error/noindex.html
        </LocationMatch>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        
        ########################################################
        # This directory parameter is needed for mod_rewrite to work properly!
        <Directory "/home/www/public_html/snipeit/public">
                AllowOverride All
        </Directory>
        <IfModule alias_module>
                # ADD THIS LINES FOR YOUR VIRTUAL DIRECTORIES
                Alias /snipeit "/home/www/public_html/snipeit/public"
        </IfModule>
        ########################################################

</VirtualHost>`

This is the 
This is the .htaccess in the public subfolder.
`<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On
    
    #settings to make it work in a subfolder
    RewriteBase /snipeit

    # Uncomment these two lines to force SSL redirect
    # RewriteCond %{HTTPS} off
    # RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>`

This is beginning of the .env file:
APP_ENV=production
APP_DEBUG=true
APP_KEY=(omitted in this comment)
APP_URL=http://sub.mydomain.com/snipeit/public

Could you please help me to set this up?
