### ISSUE TITLE
Viewing asset causes exception leading to full path disclosure

### ISSUE THREAD

**Issue by 0x27** [snipe/snipe-it#2291]
Found this while clicking around the demo site (https://demo.snipeitapp.com/) to get a feel for the software.

#### Expected Behavior

Click on asset (URL: https://demo.snipeitapp.com/hardware/1223/view) to view asset.  
Expect to view asset information.

-----

#### Actual Behavior

Laravel exception occurs, leading to full-path disclosure and a nice stack trace, as per screenshot below.

![snipeit-fpdbug](https://cloud.githubusercontent.com/assets/9094330/17016912/27ac8fb4-4f29-11e6-8b04-0fae26f26bad.png)

-----

Unsure if bug is only affecting the demo instance or not, still need to set up a local instance to test at some point in the near future. This seems to affect all of the assets I clicked on in the demo site so far.  
I don't think this should happen if debug mode is disabled, honestly unfamiliar with the Laravel framework, but it appears debug is enabled on the demo.  
Apologies if raising it in public is out of line (due to the somewhat-security-relevance).

**Comment by snipe** [comment]
We leave debug on specifically because it's open source. We want people to be able to report more useful bugs, see what queries are being executed, etc. Error output in production mode would only disclose a "Whoops. Something went wrong" error, which is what you want in production.

That error was coming from bad data, I think. Someone deleted a status label that has assets assigned (that they can do that is a bug in and of itself). It's corrected now, and we'll have a patch out to prevent people from deleting status labels that are in use.
