### ISSUE TITLE
Support multiple companies [$500]

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#23]
This is a fringe case, but it just so happens to apply in my case. My IT team services two sister companies within a parent holding company. Adding this as an enhancement, but unless I hear from other folks who really want this, it's low priority for now.

**Comment by stuba** [comment]
One vote for this!

**Comment by DWSR** [comment]
I would love this as well. My IT department actually services 3 organizations under the same brand. It's...challenging to keep track of everything.

**Comment by jonesluster** [comment]
Would definitely use this feature.

**Comment by dc53000** [comment]
This would be really useful to us, as well. What ballpark size of a bounty would be needed to get this to higher priority?

**Comment by snipe** [comment]
It's a pretty massive project. I don't have any idea how much of a bounty would be needed, but it's a non-trivial change. It's on our roadmap, but not for the next few releases.

**Comment by Ahimta** [comment]
Hi @snipe, I just finished the initial implementation for multiple-companies support.

You can find the PR here: https://github.com/snipe/snipe-it/pull/1321
And the screenshots and other related files here: https://www.dropbox.com/sh/wugnzqepwgzwlnh/AAAwNWA5hIKrP0y2VTu-LMHHa?dl=0

I also fixed a security issue relating to CSRF in `AdminController` [here](https://github.com/Ahimta/snipe-it/commit/6bf2a2875f7da7e2d9740acbfb6b6ef8983ec343#diff-54d7b516dd9ce8144b2a9d367a1e50a4R17)

In addition, I noticed you have some other CSRF issues, pertaining mainly to using GET requests
instead of POST, PUT or DELETE. Mostly for deletion routes.

Note that these issues still persist even if requests are authenticated.
In fact, [CSRF](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet) by definition, happens when the user is authenticated.

It may be tempting to use GET and pass a CSRF token as a query string.
I would advise against it. Web browsers treat GET differently than other methods.
So in general (almost) never use GET for anything that changes the DB state,
unless you really know what you're doing.

And please don't use tabs `\t` :)

**Comment by snipe** [comment]
This is now on develop
