### ISSUE TITLE
FR, expose reverse proxy config in docker.env

### ISSUE THREAD

**Issue by cmitz** [snipe/snipe-it#2301]
#### Expected Behavior (or desired behavior if a feature request)

In the docker.env file, a line like
`APP_PROXY=<IP.ADDRESS>`

Instead of `'proxies' => array('YOUR.IP.GOES.HERE'),` in `app/config/packages/fideloper/proxy/config.php`

-----

#### Actual Behavior

It is needed to modify files inside my container as explained here: https://snipe-it.readme.io/docs/reverse-proxies

-----

#### Please confirm you have done the following before posting your bug report:

- [NOPE] I have enabled debug mode
- [YES] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
v3.0-ebc74a65
- What OS and web server you're running Snipe-IT on
Docker (on Synology/DSM5) behind Apache reverse proxy
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker

**Comment by uberbrady** [comment]
It's difficult, in that I think that directory only exists *after* composer-install - but that being said, I suspect we can modify the `Dockerfile` creation script to replace `array('YOUR.IP.GOES.HERE')` with something like `env('APP_PROXY,array('YOUR.IP.GOES.HERE'))` - so that way, if you don't set anything, it works like before, but if you do set `APP_PROXY` - then it will respect it.

@cmitz - any chance you would be able to try and take a stab at a pull request? I'd love your help, and since you have the Proxy setup to test against, you'd be well-suited to implementing it and then testing it.

**Comment by cmitz** [comment]
Sorry for not updating this issue.

I managed to solve the issue by editing my apache settings. Here are the important parts of my config:
```apache
# after </IfModule>
ProxyRequests Off
ProxyVia Off
ProxyPreserveHost On
Options +FollowSymLinks
```
and 
```apache
# SnipeIT config
<VirtualHost *:80>
  ServerName snipe.domain.example
  ProxyRequests Off
  ProxyVia Off
  <Proxy *>
    Order deny,allow
    Allow from all
  </Proxy>
  ProxyPass / http://localhost:8081/web/index.html
  ProxyPassReverse / http://localhost:8081/web/index.html
</VirtualHost>
```
Since it's on my home network I don't use SSL, even though I know I should 😛

**Comment by uberbrady** [comment]
It looks like the correct setting is already available, and is `APP_TRUSTED_PROXIES`. Setting that in `docker.env` or `whatever.env` or via `-e` on run should be enough.
