### ISSUE TITLE
Site support

### ISSUE THREAD

**Issue by mpmel** [snipe/snipe-it#231]
It would be useful to be able to create Sites and assign users and assets to a particular site. Many companies, including ours, have multiple sites, and it would be nice to have some controls based on site for assigning assets and allowing requests.

Also, many pieces of software we buy are licensed with a site license. This means we can install it on any number of computers we like as long as it is within the same geographical location. Some management of these types of licenses seem to always be missing in this type of software.
##

**Comment by ze1234567890** [comment]
Why dont you take a look at IBM Maximo and its 1000s of tables to get some ideias... btw your demo site dont have a working login

**Comment by snipe** [comment]
Demo site login is working again. 

I don't think I can look at Maximo without paying for it. I'm also not trying to copy other people, I'd rather learn what my users need and address that. Enterprise products often overlook smaller companies and their workflow.

**Comment by uberbrady** [comment]
Huh. I think the new 'companies' functionality might actually handle some of this. It makes it so that a super-admin can see everything, but individual admins can only see their own 'company'. Although it may not be fully fleshed-out in that form.

In your example, I would create one 'company' for USA, one for CANADA, and one for PERU.

If you're still interested in this functionality, can you check out the latest and see if that's along the lines of what you're looking for, @dac91 ?
