### ISSUE TITLE
Software maintenance additions

### ISSUE THREAD

**Issue by mpmel** [snipe/snipe-it#232]
It would be nice to be able to keep up with maintenance contracts for licenses as well.

The common model for licensing, especially for development components, is that you buy a license up front, then pay yearly maintenance to get access to support and upgrades.

It would be nice to be able to:
- mark a license as being maintained or not, duration of maintenance, and cost
- get notifications when payments are nearly due
- view a report that shows when all currently maintained licenses need to be renewed for budgeting 
##

**Comment by snipe** [comment]
A queuing system seems overkill (and will add a level of complexity with respect to supporting this application for me, as lots of our users don't know what any of that means), since it's something that needs to run once daily or weekly. I think a nightly cron would be fine. I have a rough notification email option for warrantees on develop right now.

To set up the cron to run every day, set up your crontab as:

`@daily /path/to/php /path/to/your/snipe-it/artisan alerts:expiring`

To set it to run every week, use:

`@weekly /path/to/php  /path/to/your/snipe-it/artisan alerts:expiring`
