### ISSUE TITLE
Feature Request - Add 'change password' to user profile

### ISSUE THREAD

**Issue by RobMSP** [snipe/snipe-it#2399]
#### Expected Behavior (or desired behavior if a feature request)

User profile page contain some sort of change password feild, prompt to allow users to update thier passwords.

#### Actual Behavior

When connected to SnipIT as a user, unless they have admin privileges (user:edit) there is no method to update their password. 
User profile page has no change password option.

Only applies to non-ldap integrated installs. 
-----

#### Please confirm you have done the following before posting your bug report:

Reported in : v3.2.0-53-gfff2bce

**Comment by snipe** [comment]
This was actually a feature, not a bug. We used to allow users to change their password, but removed that in v3 after asking our users if that's something they would typically ever want a user to be able to do. 

We could perhaps make it a setting.

**Comment by RobMSP** [comment]
Feature . . . .  Bug  . . . . . Depends on who you ask lol
Not the end of the world for me, but as a setting would be nice.

**Comment by snipe** [comment]
Apologies, I tagged the wrong ticket in that commit. Too many GH windows open :(

**Comment by RVANNECK** [comment]
I too would love to see this ability return

**Comment by ebonweaver** [comment]
I was just about to open this as an issue when I Googled and found this one  :)  Yes expectation is that a user can under their settings change their password, especially given they can change their name which we do NOT want them to do.  So right now these things are opposite of expectation of most systems.  As is we have the problem that everyone has to visit a super admin to change their password, and that's a real issue.  Otherwise, they have the random starter one in plain text somewhere.
Ideally any system with accounts should have these settings:
Allow users to change passwords?
Allow users to change name?
Allow users to change login ID?
For this system, Allow users to change other attributes? (location, company, etc. etc.)
Security settings:
Password minimum length?
Passwords must be alphanumeric (include both letters and numbers)?
Passwords must include symbol?
Password history? (how many previous can not be repeated on reset//change)
Passwords can not include name or ID
Passwords must be mixed case?

I realize that is a lot to add, but that's security in IT systems.
