### ISSUE TITLE
Feature Request: LDAP fields added to user section

### ISSUE THREAD

**Issue by mattgann** [snipe/snipe-it#2449]
#### Expected Behavior (or desired behavior if a feature request)

Can there be an option to add certain LDAP fields to the user section, such as department when the ldap import occurs. 'Department' would be extremely help full for our companies asset management.

---
#### Actual Behavior

Check what LDAP fields are available in USER section

---
#### Please provide answers to these questions before posting your bug report:

3.2
Windows IIS

**Comment by snipe** [comment]
it's certainly possible, but I'm not sure how we'd execute that in a way that wasn't really messy. We'd have to either alter the users table on the fly, or create a join table, which will complicate some already heavy queries in the listing pages.

Departments is already in the works, so that would simply be another table, but if a department doesn't exist, that's another thing we'd need to validate + add on the fly on import. 

What outside of department would you want?

**Comment by mattgann** [comment]
Basically anything that relates to locations or any Phone numbers and department related info. Plus we could really benefit from AD credentials we have it working in Tracmor but I am moving over to Snipe-It and having auto sync and credentials from AD I would be a super hero

**Comment by pvhkai** [comment]
Hi we are also searching for an Import functionality for "Phone" and "Managers"...

**Comment by snipe** [comment]
@mattgann Not sure what you mean by "Plus we could really benefit from AD credentials" - Snipe-IT has supposed AD/LDAP login/syncing for a while.
