### ISSUE TITLE
backup

### ISSUE THREAD

**Issue by philknab** [snipe/snipe-it#2453]
i don't know if there is an issue open about this, but is it or will it be possible
to automatically backup the data let's say every morning at 8?

greetings from austria!

**Comment by holyoaked** [comment]
Probably not, as automated backups are a feature of their paid-for Hosted solution.

**Comment by snipe** [comment]
@holyoaked there is literally nothing offered in the paid hosting solution that isn't possible with the free version. They are the exact same software.

@philknab Check out https://snipe-it.readme.io/docs/configuring-alerts#bypassing-the-scheduler - you'd just want to configure the cron job manually instead of using the built-in scheduler, and set the cron time to whatever time/interval you want.

**Comment by philknab** [comment]
so if i write this **@daily /etc/php5  /var/www/snipeit/artisan snipeit:backup** in my cronjob it should do a backup every day.
please correct me if i'm wrong, this is my first time with cronjobs hehe

**Comment by philknab** [comment]
for everyone who wants to do this:
you need to write **@daily /path/to/your/php /path/to/your/snipeit/artisan snipeit:backup** in your cronjob. 
everyday at 00:00 a fresh backup of data will be stored in the backups directory!
hope i could help someone out!
