### ISSUE TITLE
Provide an Ubuntu(/Debian) repository for installation

### ISSUE THREAD

**Issue by toddjames** [snipe/snipe-it#2471]
Snipe, please consider providing an Ubuntu/Debian repository, which contains a package that installs and configures all requirements needed for a fresh installation of Snipe-IT on a fresh installation on Ubuntu or Debian with a sane set of default options.

As an example, please see how easy the [GitLab installation](https://about.gitlab.com/downloads/#ubuntu1604) is. They used to have a manual installation/upgrade process that was extremely cumbersome. Now, with only a few steps for installation, someone can get up and running in minutes without configuring a web server or database. This has been a huge improvement in overall administration of that system as one of many in a typical sysadmin's responsibilities.

It seems that you are working in this direction with the inclusion of an installation script, but installation should be much easier than it currently is. I've noticed that you receive a non-insignificant amount of "issues" related to installation. On the other hand, perhaps a majority of your revenue comes from people who just can't figure out this process and decide to use a hosted solution. In the case that you actually do care about improving your installation process, I hope you consider my suggestion.

I understand that this will be a huge task, but please let me explain how I became frustrated enough that I got to the point of opening this issue and writing what essentially has become an essay at this point. I started using Snipe-IT around version 2.0. The installation was tedious, but doable. As someone who had previously experimented in writing my own rudimentary PHP code and using Apache as a server, I was familiar with vhosts, setting up Apache, and enabling modules and getting PHP to work on Apache (many of your typical sysadmins probably aren't). Setting up Snipe-IT was annoying, but I got it running after an hour or so (and [got it running through an Apache reverse proxy after another hour or so](https://github.com/snipe/snipe-it/issues/1157)).

We weren't ready for an inventory system as an organization then, but now we are. I wiped the VM and decided to start from scratch with the latest version of Snipe-IT, which seems to contain many improvements. I saw that there is now an automated install script. I installed Ubuntu Server 16.04.1, Apache, a number of [listed requirements](https://snipe-it.readme.io/docs/requirements) (note that the actual package names are not included, so figuring those out was another task), and started with the installation script (by the way, perhaps the installation script should handle these requirements?). It froze at the step where it was trying to download Snipe-IT. I waited about 10 minutes and it was still hung there. I apologize that I can't provide any logs in this respect.

I figured I'd do it the old fashioned way, wipe the server and reinstall Ubuntu Server 16.04, set up Apache and requirements myself, and get started that way. There is a single line about adding a MySQL user and database. I recall the old documentation had actual commands here but the current documentation is lacking. Okay, so I'll re-learn how that's done since this is not an every day task for me. Not too bad.

As I'm going through the documentation, I notice I'm eventually led to [this page](https://snipe-it.readme.io/docs/configuration) about configuration, which suggests running `php artisan key:generate` to generate a key, which does not work in the current root context, as well as setting `MAIL_ENCRYPTION`, which does not list possible options for this configuration setting. Okay, I'll get to those later.

Moving on... I see [here](https://snipe-it.readme.io/docs/install-dependencies) that I should download a script, run it with `php`, then run `php composer.phar ...` all as the user the webserver is running as. Okay, but I assume I should use sudo? For which parts of which commands that are piped together? The default on Ubuntu is to use www-data to run Apache, but there is no shell for that user, so now I have to look up the syntax presuming that is the user I should use? But if I do it wrong and run something as root that shouldn't, apparently I'll break things and won't know that they're broken until later and they'll be hard to debug.

So here I am.

The documentation is lacking. The automated installation script on a clean Ubuntu 16.04 Server was hanging. Manual installation at this point seems like it might be futile if I make the wrong move, so I'm making snapshots at every stage.

Please take this as a suggestion to revisit the new user experience at install time. Automate as much of a base system as possible and provide after-the-fact configuration via a single file or page after the base installation.

It's the year 2016. I should be able to wget a script that essentially adds an apt repo (or add a PPA), then apt-get update && apt-get install snipe-it and be done. As a bonus, if I use Ubuntu's automatic update feature (hint: most people do), Snipe-IT will be automatically updated if you update the repo.

Hope this helps make your product better. Do with this suggestion what you will.

Sincerely,
Todd James

**Comment by snipe** [comment]
@toddjames I'm certainly sorry that you're having trouble installing Snipe-IT. You're always welcome to make suggestions to improve our documentation. It seems odd to me that you wouldn't ask for help along the way as you were hitting issues with each of these steps. We have people in Gitter just about all the time, and are always willing to help.

> I've noticed that you receive a non-insignificant amount of "issues" related to installation.

Classic confirmation bias, as you only see issues from people who have had problems, not from the people who had no issues.

> On the other hand, perhaps a majority of your revenue comes from people who just can't figure out this process and decide to use a hosted solution. In the case that you actually do care about improving your installation process, I hope you consider my suggestion.

You know, it's really hard for me not to take a comment like that personally. I spend HOURS every day in Gitter and Github helping free users use the software I created and give away and support for FREE. To imply this is an elaborate scheme to frustrate users into paying for hosting is quite simply offensive, diminishing of the sheer time and effort we have put into this project over the years, and frankly just disrespectful. 

I'm also not sure why the composer side of things should be confusing to you, if you got Snipe-IT v2.0 running, since they both use composer with identical permissions, etc.  We specifically say not to run it as root/admin, so I'm not sure why you'd think you should run it with sudo.

The old documentation did not specify how to create a MySQL DB/user, because frankly it's outside the scope of the project. It's web-based software, so we have to make *some* assumptions about what basic knowledge people have about setting up a web server. We've added [a page on setting up a MySQL user](https://snipe-it.readme.io/docs/creating-a-database-and-db-user), but I honestly feel like you if you can't Google that much, maybe you shouldn't be running a web server and should stick with something desktop like Spiceworks. In the same way that we expect you to know how to install Apache/Nginx - or at least have a setup like Cpanel where it's already installed - we can't walk every user through Webserver 101 (and maintain that documentation over time).

We already provide multiple installation methods (which most people seem to be able to manage), in addition to a Docker image (which is automatically updated on Dockerhub with new versions and tags). Each one of these processes is an additional point of maintenance, and we're a very small group. 

While we're not averse to someone building an Ubuntu/Debian repository package (and would consider merging a PR that provided one), every new version of Ubuntu/Debian/Snipe-IT will require additional maintenance to keep it updated. We already run into that issue for the install.sh script, which is why it falls out of date and occasionally hiccups until we can patch it, which is what it sounds like you ran into. 

You consider the documentation lacking, but many of our users feel it's pretty comprehensive. Some users complain that we over-explain the web server configuration aspects. It always depends on how much experience you have with web servers to start with. 

> The automated installation script on a clean Ubuntu 16.04 Server was hanging

That sounds like it could be a bug, and it should have been reported.

This app works like just about any modern PHP app, and has the same requirements. Any modern PHP app uses composer, and the vast majority use Laravel or Cake or Symphony as frameworks, which all share common libraries and requirements. This isn't special or unique to Snipe-IT. It's how PHP works now, because it had to grow up.

Perhaps instead of blaming the developers when you're a little out of your depth, you could focus on using the resources we make readily available to assist people who aren't as good with web server administration, and actually asking for help. You benefit more from learning, and you can skip the part where you make developers feel unappreciated for the work they've already (and continue to) put in.
