### ISSUE TITLE
Snipe-IT 3 on XAMPP v3.3.0 and Windows 7

### ISSUE THREAD

**Issue by hiboucochon** [snipe/snipe-it#2517]
I followed the steps on #2421 and #2467. Everything went smooth until the last step, I got "Access forbidden!" page, 

![image](https://cloud.githubusercontent.com/assets/21266193/18014086/37565d00-6b76-11e6-8eca-463a9d27d76a.png)

Could someone help me please? I'm new to this.

**Comment by snipe** [comment]
Could you provide a little more info? Screenshots of your server settings, at least?

**Comment by hiboucochon** [comment]
Here is my .env settings

![image](https://cloud.githubusercontent.com/assets/21266193/18111263/fc542920-6ed2-11e6-910d-0d72163ca914.png)

My httpd-vhosts.conf

![image](https://cloud.githubusercontent.com/assets/21266193/18111275/1a2a16a8-6ed3-11e6-9fd1-9c650660ab6d.png)

**Comment by snipe** [comment]
First off, your APP_KEY is like your underwear. Don't share it with anyone. 

Seriously though, it's meant to be kept secret, always. You should regenerate your APP_KEY (using `php artisan key:generate`) so that all of Github doesn't know what your key is. 

Can we see screenshots of the permissions you have set up? You're getting a permissions error, so it sounds like the server doesn't have access to the files.

**Comment by hiboucochon** [comment]
I gave the entire xampp folder full control, not sure where else needs to change.

![image](https://cloud.githubusercontent.com/assets/21266193/18133905/38b2f936-6f51-11e6-9d24-9e9495b91b73.png)

Thanks for remind me about the APP_KEY, I just generated a new key :)

**Comment by hiboucochon** [comment]
Hi, could anyone help?
