### ISSUE TITLE
Installation documentaton (with screenshots) for WAMP and XAMPP

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#2530]
If anyone is interested in helping out, a tutorial and/or video of how to install Snpe-IT v3+ on WAMP and XAMPP would be greatly appreciated. I don't have the time to write it up.

Markdown format is fine, I can convert it into the docs.

**Comment by shahima** [comment]
hi snipe
can you please tell  how import license if the file in excel format

**Comment by snipe** [comment]
Export your XLS to CSV

**Comment by shanakadissanayake** [comment]
Hi I can do a video tutorial. Ill upload to YouTube and send you the link

**Comment by cgtechuae** [comment]
Any one have step by step method for installing snite IT with Xamp?

**Comment by cgtechuae** [comment]
Any one have step step installation method for snipe it with Xamp?

**Comment by pavan137049** [comment]
Can anyone help with step by step installation method for snipe it on ubuntu using Install.sh .
editing .env and email setup.

**Comment by huyem83** [comment]
_Here's a quick guide for WAMP._

**Download install visual c++ redistributable for visual studio 2012 update 4. Install both x86 and x64 version**
http://www.microsoft.com/en-us/download/details.aspx?id=30679

**Download and install WAMP 32 bit: I haven’t try 64-Bit version of WAMP yet.**
https://sourceforge.net/projects/wampserver/files/WampServer%203/WampServer%203.0.0/wampserver3.0.6_x86_apache2.4.23_mysql5.7.14_php5.6.25-7.0.10.exe/download

**Download and install composer**
https://getcomposer.org/Composer-Setup.exe

![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556153/20db708c-cdd3-11e6-9781-814b4815a1ca.jpg)


**Browse to C:\wamp\bin\php\php7.0.10\php.exe**
![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556201/7494f5fe-cdd3-11e6-9a57-6c82c4da7025.jpg)

 
**I use PHP version 7.0.10**
![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556210/94ae5f24-cdd3-11e6-9405-5e899d569aa9.jpg)
 

**Open MySQL console**
![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556219/a51f3626-cdd3-11e6-8b75-dc715fbd4164.jpg)


**Press enter for default password**
![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556227/b4cc00f4-cdd3-11e6-8976-9eb53356a14d.jpg)

![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556233/c6ebb6f8-cdd3-11e6-92f1-68ea56e3acf5.jpg)


**Run the following commands to create and verify database:**
create database snipeit;
show databases;
![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556246/e2c93328-cdd3-11e6-9788-d176125079ef.jpg)

**Create user and grant access to snipeit database:**
create user snipe_user;
grant all on snipeit.* to 'snipe_user'@'localhost' identified by 'password123';
![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556283/2969dd28-cdd4-11e6-85e1-38a071a2157d.jpg)


***Download and exact Snipe-IT to c:\wamp\www\snipe-it\***
![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556297/3c370714-cdd4-11e6-8929-0f57eab1fde7.jpg)


**Edit .env.example**
![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556309/558d95c0-cdd4-11e6-8226-cb6d717cbae8.jpg)

 

**Save as .env**
![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556316/65e22486-cdd4-11e6-95f9-ac144f639355.jpg)


***Open command prompt then change directory to c:\wamp\www\snipe-it\***
Run composer install --no-dev --prefer-source
![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556335/7ba0458c-cdd4-11e6-8926-5a6a1c4f47a0.jpg)

**Run php artisan key:generate after**
This should update the app key in .env file
 ![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556355/8c54978e-cdd4-11e6-931c-946dcc4fa415.jpg)

![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556363/a9aa6426-cdd4-11e6-99ee-79e4f09db77e.jpg)



**Edit httpd.conf file: remember to the change http://yourcomputername** 
Note: It seems like everything inside the red boxes might be case sensitive
![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556370/bc7fadea-cdd4-11e6-898f-0b7f9add2ef0.jpg)


**Restart WAMP**
![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556379/cef434c8-cdd4-11e6-82d7-d5747b130f0e.jpg)


![2016-12-29 14_28_29-download install visual c docx - word](https://cloud.githubusercontent.com/assets/6405334/21556394/e53b4938-cdd4-11e6-9fb0-c43e48bb2e0c.jpg)

**Comment by snipe** [comment]
Awesome work, @huyem83! Thanks!! I've added the docs here: https://snipe-it.readme.io/docs/wamp

![adventure-time-sparkly-jake](https://cloud.githubusercontent.com/assets/197404/21559057/c6754ec0-cdf9-11e6-844d-b8d4325d84d1.gif)

**Comment by huyem83** [comment]
I forgot to mention that you'll need to reboot the computer after composer install.


For 64-Bit Version of WAMP:
https://sourceforge.net/projects/wampserver/files/WampServer%203/WampServer%203.0.0/wampserver3.0.6_x64_apache2.4.23_mysql5.7.14_php5.6.25-7.0.10.exe/download


Install, Visual C++ Redistributable for Visual Studio 2015 
https://www.microsoft.com/en-us/download/details.aspx?id=48145

instead of Visual C++ Redistributable for Visual Studio 2012

Note: Might need to install Apache Service if option to "Start/Resume" is greyed out

![2017-01-03 15_22_23-greenshot](https://cloud.githubusercontent.com/assets/6405334/21626870/aa7a2eca-d1c8-11e6-8ba2-4d047a6cc3b7.jpg)

**Comment by jmathias59** [comment]
**Edits for WAMP documentation:**

**Pre-Install
ReadMe for WAMP 3.0.6 Install**
--- Installation of Wampserver 3.0.6 ---
BEFORE proceeding with the installation of Wampserver, you must ensure that certain elements are installed on your system, otherwise Wampserver will absolutely not run, and in addition, the installation will be faulty and you need to remove Wampserver BEFORE installing the elements that were missing.
Make sure you are "up to date" in the redistributable packages VC9, VC10, VC11, VC13 and VC14
See --- Visual C++ Packages below.
--- Do not install Wampserver OVER an existing version, follow the advice:
- Install a new version of Wampserver: http://forum.wampserver.com/read.php?2,123606
If you install Wampserver over an existing version, not only it will not work, but you risk losing your existing databases.
--- Install Wampserver in a folder at the root of a disk, for example C:\wamp or D:\wamp. Take an installation path that does not include spaces or diacritics; Therefore, no installation in c: \ Program Files\ or C: \ Program Files (x86\
We must BEFORE installing, disable or close some applications:
- Close Skype or force not to use port 80
Item No. 04 of the Wampserver TROUBLESHOOTING TIPS:http://forum.wampserver.com/read.php?2,134915
- Disable IIS
Item No. 08 of the Wampserver TROUBLESHOOTING TIPS:http://forum.wampserver.com/read.php?2,134915
If these prerequisites are not in place, Press the Cancel button to cancel the installation, then apply the prerequisites and restart the installation.
This program requires Administrator privileges to function properly. It will be launched with the "Run as administrator" option. If you do not want a program to have this option, cancel the installation.
--- Visual C++ Packages ---
The MSVC runtime libraries VC9, VC10, VC11 are required for Wampserver 2.4, 2.5 and 3.0, even if you use only Apache and PHP versions with VC11. Runtimes VC13, VC14 is required for PHP 7 and Apache 2.4.17 or more
-- VC9 Packages (Visual C++ 2008 SP1)
http://www.microsoft.com/en-us/download/details.aspx?id=5582
http://www.microsoft.com/en-us/download/details.aspx?id=2092
-- VC10 Packages (Visual C++ 2010 SP1)
http://www.microsoft.com/en-us/download/details.aspx?id=8328
http://www.microsoft.com/en-us/download/details.aspx?id=13523
-- VC11 Packages (Visual C++ 2012 Update 4)
The two files VSU4\vcredist_x86.exe and VSU4\vcredist_x64.exe to be download are on the same page: http://www.microsoft.com/en-us/download/details.aspx?id=30679
-- VC13 Packages] (Visual C++ 2013)
The two files VSU4\vcredist_x86.exe and VSU4\vcredist_x64.exe to be download are on the same page: https://www.microsoft.com/en-us/download/details.aspx?id=40784
-- VC14 Packages (Visual C++ 2015 Update 3)
The two files vcredist_x86.exe and vcredist_x64.exe to be download are on the same page:
http://www.microsoft.com/fr-fr/download/details.aspx?id=53840
If you have a 64-bit Windows, you must install both 32 and 64bit versions, even if you do not use Wampserver 64 bit.
Warning: Sometimes Microsoft may update the VC ++ package by breaking the download links and without redirect to the new. If the case happens to you, remember that item number 20 below will be updated and the page http://wampserver.aviatechno.net/ section Visual C++ Redistribuable Packages is up to date.
This is item number 20 of TROUBLESHOOTING TIPS of Wampserver: http://forum.wampserver.com/read.php?2,134915
____________________________________________________________________
**Edit .env.example**
Edit .env.example, Save as... .env,  and make sure “Save as type”  All Files (*.*)  is selected to prevent the .txt extension from being added (can’t see extension if hide file extensions is enabled)  Generate key fails if .env is a .txt file
____________________________________________________________________
**Edit httpd.conf**
**Edit httpd-vhosts.conf instead of httpd.conf**
To access SnipeIT from another pc requires editing the httpd-vhosts.conf file to allow All, certain subnets, or specific IPs and restarting all services.
Now you should edit the \wamp\bin\apache\apache{version}\conf\extra\httpd-vhosts.conf file. In WAMPServer3.6 there is actually a menu that will open this file in your editor
left click wampmanager -> Apache -> httpd-vhost.conf
just like the one that has always existed that edits your httpd.conf file.
It should look like this if you have not added any of your own Virtual Hosts
#
# Virtual Hosts
#

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot c:/wamp/www
    <Directory  "c:/wamp/www/">
        Options +Indexes +FollowSymLinks +MultiViews
        AllowOverride All
        Require local
    </Directory>
</VirtualHost>
Now simply change the Require parameter to suite your needs
If you want to allow access from anywhere replace Require local with
Require all granted
If you want to be more specific and secure and only allow ip addresses within your subnet add access rights like this to allow any PC in your subnet
Require local
Require ip 192.168.1
Or to be even more specific
Require local
Require ip 192.168.1.100
Require ip 192.168.1.101
__________________________________________________________________________________

# Virtual Hosts
#

<VirtualHost *:80>
	ServerName "http://msnipeit1"
	ServerAlias msnipeit1
	DocumentRoot "c:/wamp/www/snipe-it/public/"
	<Directory  "c:/wamp/www/snipe-it/public/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require all granted
	</Directory>
</VirtualHost>
#

**Comment by meisaputra** [comment]
i add the line to /opt/lampp/etc/extra/httpd-vhosts.conf

```
<VirtualHost *:80>
  ServerName "http://snipeit.local"
  ServerAlias mysnipeit.local
  DocumentRoot "/opt/lampp/htdocs/snipeit/public"
  ServerAdmin webmaster@dummy-host.example.com
  <Directory "/opt/lampp/htdocs/snipeit/public">
        Options +Indexes +Includes +FollowSymLinks +MultiViews
        #Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
  </Directory>

    #
    # ScriptAlias: This controls which directories contain server scripts.
    # ScriptAliases are essentially the same as Aliases, except that
    # documents in the target directory are treated as applications and
    # run by the server when requested rather than as documents sent to the
    # client.  The same rules about trailing "/" apply to ScriptAlias
    # directives as to Alias.
    #
    # We have to use this script alias for Snipe-IT because
    # XAMPP has a built-in URL for /licenses.
    # See https://github.com/snipe/snipe-it/issues/4031 for more info
    ScriptAlias /licenses/ "/opt/lampp/htdocs/snipeit/public"

</VirtualHost>

```
after restart xampp, i got this message below when i type `http://snipeit.local` or `http://mysnipeit.local` in url browser.

```
This site can’t be reached
snipeit.local’s server IP address could not be found.
Search Google for snipeit local
ERR_NAME_NOT_RESOLVED
```

but when i type `http://localhost/snipeit/` i got message like this below

D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.

fyi, i use ubuntu 16.04 and lampp 5.6.30

my questions are: why i can't use `http://snipeit.local` or `http://mysnipeit.local`? if i have to use `http://localhost/snipeit` how to fix the message above?

**Comment by DerekPhelps** [comment]
Initial link above leads you to WampServer64 download. (will work with above instructions but with a couple config changes).  Direct link for [WampServer32](https://sourceforge.net/projects/wampserver/files/WampServer%203/WampServer%203.0.0/Applications/wampserver3_x86_phpsysinfo3.2.10.exe/download)
