### ISSUE TITLE
Cannot install snipe it 3.4 what so ever.

### ISSUE THREAD

**Issue by Sawridge** [snipe/snipe-it#2618]
we cannot get Snipe it installed in our enviroment what so ever.
We have centos 7.2 with latest updates.
We try to follow the totally unclear documentation of Snipe IT with Docker.

" Options Have Changed From v2.x!

Please note some of the options have changed, and some new options are now required!

The best way to handle all of the various settings for your various containers is to use an env-file.
See the Docker documentation for more details. It should be just a simple text file with environment
variable names and values, separated by = signs."

Seriously!!.. where should we find the "env" file. Should we create it. Where it should be put. no idea. 
Can't you guys put a simple and straight forward documentation in english how to to set it up step by step. so much of research work on and on for days... useless piece.. of sh...

Also tried the centos based installation from source github. That's again a night mare.
The logs for this installation is:
=================================================================
--2016-09-16 09:18:33--  https://raw.githubusercontent.com/snipe/snipe-it/master/snipeit.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.100.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.100.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21049 (21K) [text/plain]
Saving to: ‘snipeit.sh.1’

100%[==============================================================================================================================>] 21,049      --.-K/s   in 0.05s

2016-09-16 09:18:34 (395 KB/s) - ‘snipeit.sh.1’ saved [21049/21049]

           _____       _                  __________
          / ___/____  (_)___  ___        /  _/_  __/
          \__ \/ __ \/ / __ \/ _ \______ / /  / /
         ___/ / / / / / /_/ /  __/_____// /  / /
        /____/_/ /_/_/ .___/\___/     /___/ /_/
                    /_/

  Welcome to Snipe-IT Inventory Installer for Centos and Debian!

  The installer has detected centos version 7 as the OS.
  Q. What is the FQDN of your server? (localhost.localdomain):
     Setting to localhost.localdomain

  Q. Do you want me to automatically create the snipe database user password? (y/n) y

## mariadb-server Installed
 ## git Installed
 ## unzip Installed
 ## php56u Installing...
 ## php56u-mysqlnd Installing...
 ## php56u-bcmath Installing...
 ## php56u-cli Installing...
 ## php56u-common Installing...
 ## php56u-embedded Installing...
 ## php56u-gd Installing...
 ## php56u-mbstring Installing...
 ## php56u-mcrypt Installing...
 ## php56u-ldap Installing...

##  Securing mariaDB server.

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none):
OK, successfully used password, moving on...

Setting the root password ensures that nobody can log into the MariaDB
root user without the proper authorisation.

You already have a root password set, so you can safely answer 'n'.

Change the root password? [Y/n] n
 ... skipping.

By default, a MariaDB installation has an anonymous user, allowing anyone
to log into MariaDB without having to have a user account created for
them.  This is intended only for testing, and to make the installation
go a bit smoother.  You should remove them before moving into a
production environment.

Remove anonymous users? [Y/n] n
 ... skipping.

Normally, root should only be allowed to connect from 'localhost'.  This
ensures that someone cannot guess at the root password from the network.

Disallow root login remotely? [Y/n] n
 ... skipping.

By default, MariaDB comes with a database named 'test' that anyone can
access.  This is also intended only for testing, and should be removed
before moving into a production environment.

Remove test database and access to it? [Y/n] y
 - Dropping test database...
 ... Success!
 - Removing privileges on test database...
 ... Success!

Reloading the privilege tables will ensure that all changes made so far
will take effect immediately.

Reload privilege tables now? [Y/n] y
 ... Success!

Cleaning up...

All done!  If you've completed all of the above steps, your MariaDB
installation should now be secure.

Thanks for using MariaDB!
##  Please Input your MySQL/MariaDB root password
Enter password:
## Configuring .env file.
./snipeit.sh: line 573: php: command not found
curl: (23) Failed writing body (0 != 16133)
./snipeit.sh: line 574: php: command not found

  ***If you want mail capabilities, edit /var/www/html/snipeit/.env and edit based on .env.example***

  ***Open http://localhost.localdomain to login to Snipe-IT.***

##  Done!
------------------------------------------------------------------------------------------------------------------

My issue and request,
CORRECT YOUR DOCUMENTATION TO CREATE SIMPLICITY and Ease of installation.
And please test your releases at least of basic setups.

YOU MAY BE EXPERTS but dont expect everyone to be to understand whatever you put. 
VERY VERY VERY FRUSTRATING Installation Experience.

#### Actual Behavior

nothing. 

Cant understand where to put the .env file in docker. how to setup the docker instance of snipte it
with maria db on cent os 7.2
Cannot understand why the installtion fails via github 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by Sawridge** [comment]
PS. the log is for 3.2. The same issue for 3.4 of snipe it

**Comment by Sawridge** [comment]
also i have changed the hostname to assets.xxxx.com from localhost.localdomain. still in snipe installation it takes it as 
"Q. What is the FQDN of your server? (localhost.localdomain):" 
This is so dumb.

**Comment by dmeltzer** [comment]
Patches to documentation are always welcome :)

**Comment by snipe** [comment]
Wow.  "Useless piece of sh..."

I'm not sure what world you live in, but in real-life, treating people like garbage while you're demanding help because you don't know how to do something isn't usually the best approach. 

What reaction were you hoping for with this post? 

What possible good outcome did you have in your head? Would you respond well after receiving a post like that? I get that you're frustrated, but there is literally no good outcome when you ragepost like this. You end up thinking we're dicks, we end up thinking you're a dick and no actual problems get solved.

Did you consider for a moment that actual people are on the other end of this? People who have worked tirelessly for years to make a free product for you to complain about because we give a shit.

Posts like this make us not want to give a shit.

Literally thousands of people have been able to install this software (and the ones who trouble weren't assholes about it - they asked for help along the way, and they got it, without all the histrionics).

If you don't know docker, maybe starting with the docker install was a bad idea? We have a recommended way of installing (git clone), which does require basic knowledge of how web servers work. This is web-based software. Some understanding of webservers is sort of necessary. We even say so, early on the docs. 

I'm not feeling particularly inclined to help you right now. Perhaps some of the more patient community members will be more charitable.

**Comment by Sawridge** [comment]
First you guys., Sorry for my language. I was totally freaked out after sitting and wasting time for 3 consecutive days. I was referring to my installation setup as shit and it has nothing to point on you guys. 
But sometimes we go crazy on people we like... 
I understand so many people working hard for this software. I sincerely appreciate the work.

These are my issues:
First I tried Docker type installation. I couldn't understand how to configure the ENV file and where to put it. I cannot find any related material explaining that part. So I Stopped it.

So I tried the Github installation on Cent OS 7.2
My installation stops at this line : 573 and 574 in the ./install.sh file.
I have open ssl installed. Still the same issue.

This is the story. 

I am not expecting a pardon but requesting you guys to put you in my shoes - a beginner to such software and make it better.  

1. Docker type installation should be made more clearer.
2. Give it a more interactive installation steps. 

Regards,
----------------

**Comment by snipe** [comment]
Hi @Sawridge - thanks for the clarification, and cooler head. 

We've updated the Docker walkthrough to hopefully address some of the points where you were getting confused. Docker is pretty complex, and the env file we talk about is very common in Docker installs, which is why we don't spend a lot of time documenting how it should work. If you're familiar with Docker, you probably know what it is and how it works, and if you're not, Snipe-IT might not be the best place to start, since we use some more advanced aspects of Docker, such as linking storage volume, and multiple images. While Docker isn't *hard*, per se, the way we implement it is probably not the best example to cut your teeth on if you're not familiar with Docker. We've updated the docs to clarify the env file a little more, and to mention that Snipe-IT on Docker might not be best for beginners.

https://snipe-it.readme.io/v3.0/docs/docker

For the install.sh version, the error you're seeing, `./snipeit.sh: line 573: php: command not found`, implies that PHP isn't installed on the CentOS machine. We're trying to reproduce that on our end now.

**Comment by snipe** [comment]
For the CentOS install, are you running the install.sh as a user that has sudo privileges? We were able to run the installer without an issue on the test we just ran.

**Comment by uberbrady** [comment]
Can you get the contents of this file: `/var/log/snipeit-install.log` and paste it in here? I'm hoping we'll have some clues there.

I just ran an install several times on a CentOS VM running 7.7, and it worked just fine each time. I may want to drop down to 7.2 to see if I can replicate your issue. I haven't been able to so far.

**Comment by Sawridge** [comment]
Thanks for extending your help.

We managed to fix the issue. It was a mismatching php common lib conflict which we were not able to find in the installation screen, but on the log. Sucessfully installed snipe it now on cent os 7.2.

 

Thanks for the help.

**Comment by snipe** [comment]
Glad you got everything sorted.
