### ISSUE TITLE
note able to create database in mysql on gadday its give error

### ISSUE THREAD

**Issue by umeshpoman** [snipe/snipe-it#2663]
note able to create database in mysql on gadday its give error its giving error "Name has already been taken. Please specify a different name."

**Comment by dmeltzer** [comment]
Well, if the name has already been taken, I'd probably choose a different name for the database.

**Comment by ranX** [comment]
Did you use the shell script "install.sh" ?
Did you use it more than one time ?
When the database is once created, it can't be done a second time.
Also be aware, a second run of the script will overwrite your .env file,
which will remain your installation disfunctional.

In this case take the following steps:
- reset the password of the DB-User "snipeit" manually
- regenerate the app key 
- recreate the .env file manually according to the install documentation
- fill in new app key an DB password

install.sh comes in handy but is far away from beeing bulletproof, as ist does not check for remains of earlier executions and existing installations.
It also needs some manual edit before you run it on a bare naked headless Debian with no "sudo" installed

**Comment by mtucker6784** [comment]
I agree, it's not fair to say it's anywhere near bulletproof. It just provides a very basic blanket install (I truly envision it for VMs, to be honest), although I'm sure others have adapted to it / with it otherwise.

I did edit the Debian portion of the script and forewent the sudo command since you have to get the sudo package apt-get, which was a pain.

Probably wouldn't be a bad idea to have it try to discover an existing install (or ask the user ahead of time) so it can try to avoid futzing everything up.
