### ISSUE TITLE
Mattermost Integration Support

### ISSUE THREAD

**Issue by mr-gosh** [snipe/snipe-it#2764]
#### Expected Behavior (or desired behavior if a feature request)

I want to use the OpenSource Alternative to Slack named MatterMost https://www.mattermost.org/

---
#### Actual Behavior

when i enter the outgoing webhook to my MatterMost instance i get a "Whoops - Something went wrong" Pop-Up

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running

Version v3.4.0-9-g67315d8
- What OS and web server you're running Snipe-IT on

docker Container on Ubuntu 16.04.1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

docker container
- If you're getting an error in your browser, include that error

"Whoops, looks like something went wrong."
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

when i do something the triggers the outgoing webhook
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

nope

**Comment by mr-gosh** [comment]
I tried to use the Slack integration (cause it works for example in gitlab out of the box) but its implemented a little bit different - so it didn't work that way...

**Comment by snipe** [comment]
We use a slack library, so it would be pretty remarkable (tho not impossible) for that to have worked

**Comment by mr-gosh** [comment]
yeah - i tried it - and wasn't suprised it didn't work ;-)

do you think it's a big deal to support mattermost? just using webhooks for that would be enough right?

**Comment by dVoCex** [comment]
Working fine for me. 

You just have to be sure that you type the channel name lower case in your snipe-it settings. Otherwise you see "channel not found" inside your mattermost system-console.

For channels with special characters look at url in the channel info view.

`https://mattermost.somewhere.local/someteam/channels/thisisthechannelname`

more info:
https://docs.mattermost.com/developer/webhooks-incoming.html#known-slack-compatibility-issues

**Comment by mr-gosh** [comment]
I don't get it - what did you paste into the two fields in the snipe config?

**Comment by mr-gosh** [comment]
i once again tested it - and it really works.
To use Mattermost with snipeit you really just need to do the following:

1. create an [incoming webhook](https://docs.mattermost.com/developer/webhooks-incoming.html#setting-up-existing-integrations)
2. add the incoming webhook url to the "slack-endpoint field" in snipeit
3. add the channelname in lowercase letters with a "#" in front of the channel name without whitespaces to the "slack channel" field...

@snipe you could rename the config area to "slack or MatterMost under these circumstances... ;)

**Comment by snipe** [comment]
@mr-gosh that's a good idea, thanks for checking that it works!

**Comment by stuartm** [comment]
Sorry to revive a closed ticket, but this ticket at least has the history so far and it was closed by bot, not because it was actually implemented.

According to https://docs.mattermost.com/developer/webhooks-incoming.html#known-slack-compatibility-issues using # in front of the channel name with mattermost does NOT work and that's my experience. Instead the message goes to the default channel for the webhook, not the one specified in the SnipeIT config.

If SnipeIT didn't insist on the # character in the configuration then this feature would also work for mattermost since the APIs are otherwise identical.

<blockquote><img src="../_static/favicon.ico" width="48" align="right"><div><strong><a href="https://docs.mattermost.com/developer/webhooks-incoming.html#known-slack-compatibility-issues">Incoming Webhooks — Mattermost 5.29 documentation</a></strong></div></blockquote>

**Comment by kirill934** [comment]
@stuartm I have found the solution for that problem. Using # in front of the channel name doesn't affect on the channel name where notification is send. The problem is missing the channel name parameter in functions `toSlack()`.
For example we need to add some code in file `app/Notifications/CheckinLicenseSeatNotification.php` 

```php
    public function toSlack()
    {

        $target = $this->target;
        $admin = $this->admin;
        $item = $this->item;
        $note = $this->note;
        $botname = ($this->settings->slack_botname) ? $this->settings->slack_botname : 'Snipe-Bot' ;


        if ($admin) {
            $fields = [
                'To' => '<'.$target->present()->viewUrl().'|'.$target->present()->fullName().'>',
                'By' => '<'.$admin->present()->viewUrl().'|'.$admin->present()->fullName().'>',
            ];
        } else {
            $fields = [
                'To' => '<'.$target->present()->viewUrl().'|'.$target->present()->fullName().'>',
                'By' => 'CLI tool',
            ];
        }




        return (new SlackMessage)
            ->to($this->settings->slack_channel)           //need to add this line---------------------------------------------
            ->content(':arrow_down: :floppy_disk: '.trans('mail.License_Checkin_Notification'))
            ->from($botname)
            ->attachment(function ($attachment) use ($item, $note, $admin, $fields) {
                $attachment->title(htmlspecialchars_decode($item->present()->name), $item->present()->viewUrl())
                    ->fields($fields)
                    ->content($note);
            });
    }
```
Add this line for all files in folder `app/Notifications` where `toSlack()` function is present.

**Comment by snipe** [comment]
I would really not recommend this method of changing local files. It's going to make upgrading your Snipe-IT a real bear. If you can confirm this fix works on Slack and also on Mattermost, I'd welcome a PR for this, although I'm not sure this is the best solution overall. Using something like https://github.com/gnello/laravel-mattermost-driver and integrating that into the options is a better choice most likely, as future versions of Snipe-IT will likely perform more strict validation on webhook URLs, etc.

<blockquote><img src="https://avatars.githubusercontent.com/u/19245006?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/gnello/laravel-mattermost-driver">gnello/laravel-mattermost-driver</a></strong></div><div>A Laravel integration for the php-mattermost-driver - gnello/laravel-mattermost-driver</div></blockquote>

**Comment by kirill934** [comment]
Yes, integrating Mattermost support as an option is the best solution. But now Slack integration works pretty well with Mattermost except for channel name. Ok, I'l try to open PR for that small changes.
