### ISSUE TITLE
MAC Adress not saved when entered during Asset Creation

### ISSUE THREAD

**Issue by mr-gosh** [snipe/snipe-it#2803]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running

 v3.4.0-9-g67315d8 

- What OS and web server you're running Snipe-IT on

Ubuntu 16.04

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

docker

- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

.../hardware/create

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

Nope - it is not cause the Field "MAC" is not appearing when I create a new Asset with Custom Field MAC selcted in the demo application.

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by delinski111** [comment]
(the reason it wasn't showing up in the demo, is because you did not select an asset model with the correct field-set assigned, you need to do that manually, just as you would in a real database)

Are you putting the MAC into the field correctly? You need to use " : " [colon] between the sets of characters. (ex. 01:24:1d:12:b2:fc).
Verify that the asset model IS using a fieldset, that has MAC field as a value.

If you absolutely are sure the above is correct. Make the asset, and than go back and edit the asset, and fill in the MAC. See if that works.

**Comment by mr-gosh** [comment]
I will test that tomorrow...
