### ISSUE TITLE
Hand-drawn Signatures: I NEED YOU

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#2848]
Hey gang,

I've just pushed out some improvements on a feature branch that let you require an actual signature when the user is accepting an asset.

![screenflow](https://cloud.githubusercontent.com/assets/197404/19832670/04b3303a-9ddf-11e6-9ee0-331b7a8ee6bc.gif)

I've been working for over 24 hours straight on this and #2847 though, so I haven't had time to kick the tires on the behavior across multiple browsers (tested in Chrome and Safari so far) and on mobile (which is probably going to be a nightmarish hellscape.)
### How to Help Test

First of all, DO NOT USE YOUR PRODUCTION DATABASE FOR THIS. While I don't think anything we've done should cause breakage, it's just a good idea to duplicate your production database on a development box and use that. You'll need to pull from the `features/drawn_signature` branch instead of master.

You'll probably need to make the `storage/private_uploads/signatures` directory writable.

Enable Signature Requirements in Admin > Settings:

<img width="487" alt="update_settings____snipe-it" src="https://cloud.githubusercontent.com/assets/197404/19832692/ac1bdf48-9ddf-11e6-9d74-6ca24b215360.png">

And then assign some assets out (to a test user or a user whose email account you can access). Make sure the assets you're assigning belong to models that belong to a category that requires asset acceptance, otherwise you'll never get the email.

Test with EULAs and without, test on as many browsers as you can bear. Test on mobile. Make sure the signature section works, and that it stores your signature correctly. Try to view signatures when you're not logged in, or don't have asset view rights. Etc etc.

Once a signature is saved, view the asset page and check that it shows up under the "History" tab, with a clickable thumbnail to view the large version.

<img width="656" alt="view_asset_769342208____snipe-it" src="https://cloud.githubusercontent.com/assets/197404/19832744/10c6f4a4-9de1-11e6-9616-6197cbe21135.png">

Once I've gotten some rest, I'll be kicking the tires on it a bit more as well.

Looking forward to hearing your feedback!

**Comment by vinotnj21** [comment]
Hi Snipe,
   How I can do pull feature. Kindly assist me.

**Comment by delinski111** [comment]
@vinotnj21 
(as you did not specify, I will assume you are a linux user)
cd /var/www/snipe-it
sudo git checkout features/drawn_signatures

This will need to validate over some files, in my case, it needed permission to overwrite /var/www/snipe-it/config/app.php, as I changed a line in that file. To allow this overwrite;
sudo git checkout -r features/drawn_signatures

Then you would need to go back and fix any files it needed to overwrite.

Then you need to run the usual commands for upgrading;
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
php artisan config:clear
php artisan config:cache
sudo service apache2 restart

**Comment by delinski111** [comment]
@snipe 
Below are some tests regarding the drawing specifically, HOWEVER, an issue I am having, after hitting submit, I get the whoops page, and even with DEBUG=true, that whoops page will not give me a specific error. nothing in laravel.log either.
|
|
|
So far in my tests.
Server:
Ubuntu 14.04, fresh SnipeIT install manual

Settings
Category has a EULA.
Signatures are set required in settings.
Users are set required to validate checkouts.

From a windows 10 machine, using chrome.

User "Request" asset.
Asset was checked out to user. (the asset still did the checkout, without issue, even though the user did not sign yet. am not sure if this is intended or not).

User got email, the format of the email matches as before enabling signatures.
Hyperlink at bottom of email with "I have read and agree to the terms of use, and have received this item".

The link brought me to correct page, with EULA and signature box. 
Tested Clear Button. Worked fine.

Pixel width seems a little large? Using a mouse is hard enough to draw with.

TESTING THE ACTUAL DRAWING SECTION:

Cannot hit submit without atleast a pixel of drawing in the field. (Good)

**Mouse** worked great. (chrome, IE11, (Edge refused to connect to my server) )

From phone, I remoted into my PC using VNC and Remote Desktop.
**VNC App:**
Technically worked as it should have. The issues that made this a challenge, was not Snipe-ITs issue, but was an issue with VNC.

**Remote Desktop App:**
Worked pretty good. The issue with remote connections, is that you need to kinda double click on the device to get the mouse input to trigger, but after that it feels like using a stylus

**Wacom Bamboo graphics tablet/pad:**
Obviously, worked wonderfully.

**mobile device (Galaxy Note 7, Android M)**
Using _Finger_, worked great.
Using Note7 _Stylus_, Worked Fantastically
So, the resolution (obviously) scales with the orientation of the phone. This did cause an oddity where I could input a drawing, that flip to landscape, and the drawing would vanish, and need to be re_drawn.
There was actually a nice animation of, the screen would flip, the previous drawing would be there for about .6 seconds, than fade away and drift up.

**IPAD**
Lorum Ipsum

**IPhone**
Lorum Ipsum

**HP ElitePad Tablet**
Worked Great

**SurfaceBook**
Worked Great (and they are known to break things because of their ridiculous resolution)

As stated in the beginning of this post, I cannot test anything regarding the signature after the drawing phase, as I cannot get the form to submit.

**Comment by snipe** [comment]
LOL I love that you use the same test words we do. 💩 

Can you check and make sure your `public/uploads/signatures` directory is writable?

**Comment by snipe** [comment]
Sorry, that's `storage/private_uploads/signatures`, not public. We obv don't want people's signatures to be public

**Comment by snipe** [comment]
(Side note, holy shit thank you so much for testing on all those devices. You're a rock star.)

**Comment by delinski111** [comment]
I cannot currently, as that is at my WorkPlace, but will report back tomorrow morning with the result. It should be, as I made www-data own all of snipe-it files.

**Comment by delinski111** [comment]
Sorry, forgot I had an all day meeting today (well, it was a hackathon for our website redesign). Will test the above possible solution tomorrow.

**Comment by mmcleod82** [comment]
Not an extensive test by any means, or write up (:p), but noticed the signature displayed in the history screen is fairly big almost actual size, certainly not thumbnail as in your image Snipe.

Whole process works flawlessly though, well done, love it!

**Comment by snipe** [comment]
Thanks! Can you tell me what browser you're using?

**Comment by mmcleod82** [comment]
lol, as lightweight a piece of feedback that was, I DID intend to mention the browser 😆 

IE11 !

**Comment by mmcleod82** [comment]
![capture](https://cloud.githubusercontent.com/assets/19797176/20108730/ebc5eeb6-a5d4-11e6-95ce-92d5b9960193.PNG)

**Comment by snipe** [comment]
Thanks! I'll take a look once I'm back from the Netherlands!

**Comment by hungtrungthinh** [comment]
Is it enabled for admins only? I want every check-in and check-out operation performed by the admin and user to be signed.

**Comment by snipe** [comment]
@hungtrungthinh No, it's available for anyone, based on the category of the asset: https://snipe-it.readme.io/docs/requiring-acceptance#viewing-signatures



<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/requiring-acceptance#viewing-signatures">Asset Acceptance</a></strong></div><div>If the asset model that an asset belongs to is part of a category that requires asset acceptance, an email will be dispatched to the user, prompting them to login and click on a link to confirm that they have received the device. Physical SignaturesStarting from version 3.6.0, you can require a phys...</div></blockquote>
