### ISSUE TITLE
License keys visible despite permission "Licenses: View License Keys" set to Deny

### ISSUE THREAD

**Issue by safetynuke** [snipe/snipe-it#2867]
#### Expected Behavior (or desired behavior if a feature request)

When setting permissions on a group, granting "Licenses: View" but denying "Licenses: View License Keys" should let associated users see licenses, who is assigned to them and so on, but block the license key from view. 

-----

#### Actual Behavior

Granting "Licenses: View" but denying "Licenses: View License Keys" still gives associated users the ability to view license keys. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running

3.5.2
- What OS and web server you're running Snipe-IT on

Ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

install.sh
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

Yes.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
What are the other permissions the user has? (Not admin and not superadmin, correct?)

**Comment by snipe** [comment]
> What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

**Comment by safetynuke** [comment]
User gets permissions from a group. This group has every permission that has "view" in it, except the "view license keys" permission. Admin and superadmin are not selected. 

With those permissions set, go to the licenses list. All licenses have their license key visible in that list.

**Comment by zhichien** [comment]
Hi, as users may re-used the license key (or product key) on multiple systems (work, home, share with others, or sell to others), even though they are not using it and not suppose to use it anywhere (as they can see all licenses in the same companies), I think they should be option for admin to hide this piece of information. 

It is thought that by setting the "Licenses: View License Keys" -> Deny, the "Product Key" data is hidden or not shown or display "Unauthorised", whichever is suitable.

However, with ""Licenses: View License Keys" set to [Deny], above function does not behave as thought. We are not sure whether this is the default behavior.

As shown below, the product key should not be viewable as the person has not checkout (not authorise to see them). They can see everything else except the product key that has not been assigned to them.
![image](https://cloud.githubusercontent.com/assets/20409358/23447523/85eeb4aa-fe86-11e6-826a-1f3e459a6f94.png)

In order to get the product key, the user needs to select the product and click "Checkout", which at this stage, the serial key should not be shown as well.
![image](https://cloud.githubusercontent.com/assets/20409358/23447451/0a80ffc6-fe86-11e6-839c-91852e50b7c8.png)

Once the user has checkout successfully, then the user will be able to see the product/serial key. From now on the user has been assigned the key and the system will record this moment where he gets the key. In future if the key is leaked out or has licensing violation issue, then the user will be responsible for it.
![image](https://cloud.githubusercontent.com/assets/20409358/23447479/41502fc2-fe86-11e6-9725-50e31d3bce76.png)

If the license can be check back in, the again the license shall be hidden again.

Thank you.
