### ISSUE TITLE
Integrate barcode generation

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#29]

**Comment by bailantilles** [comment]
I know this conversation has gone somewhat stale, but I'll add my use case. We don't really like Avery labels all that much because they don't really hold up to wear and tear of daily use like on laptops, nor do we pay for preprinted rolls of barcode labels either. We do however print one off laminated tape labels (even when adding in multiple machines at a time) with a Dymo label printer (450 Duo). Dymo does provide an SDK for integrating the printer into applications.
