### ISSUE TITLE
Asse barcode generation dosnt always work+ keep having to log in

### ISSUE THREAD

**Issue by EnigmaZA** [snipe/snipe-it#2908]
When generating labels it does not generate al elements of the barcode,

it then forces me to login again after the failed generation

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- v3.5.2-11-g5a835a5 
- 7.0.8-0ubuntu0.16.04.3
- install.sh

-Label generation
- No Manual Database Editing Done

**Comment by kylejvrsa** [comment]
Hi Snipe,

I can confirm, I am also experiencing this issues. When I generate labels not all labels are generated properly(The barcode images are missing for some of them) and it is a different number of images that are broken every time you try and reload. Then I press back to go back to snipe-it and that works but on the next action it redirects me to the login screen. This only happens when working with the generate labels.

System Information
OS: Debian Jessie
Web server: nginx
Snipe-IT version 	v3.6.3 build 15 (g1bf34d7)
PHP Version 	5.6.29-0+deb8u1
Laravel Version 	5.2.45 

Let me know if you need more info :)

**Comment by kylejvrsa** [comment]
Here is a screen-shot of the labels
![snipe-it](https://cloud.githubusercontent.com/assets/2302861/23010293/3a34795e-f423-11e6-85f4-8e5291dfac13.png)
