### ISSUE TITLE
Feature Request: Need Agents

### ISSUE THREAD

**Issue by kernsb** [snipe/snipe-it#2919]
#### Expected Behavior (or desired behavior if a feature request)

Major OS Agents (Windows, Mac, Linux) for device registration, data collection, and updating.

-----

#### Actual Behavior

As far as I can tell, this is 100% manual at current. I was thrilled to stumble across this project until I found that there were no agents. Complete deal breaker :(

-----

**Comment by therealjoshuad** [comment]
Try Lansweeper.

I personally prefer the fact that it's manual. Ive worked with systems with that kind of data scraping, and a lot of the time it just collects garbage data. Manufacturers seem to have little QA or consistency in how they label thins in the firmware. I like that I set the model standards and names, so that reports are simple and clean.

There can probably be lots of arguments for, or against, this is just my 2 cents. I've seen other automated systems just do a real poor job.

**Comment by carlashley** [comment]
Honestly, I'd rather there be an API to add/remove assets from the database, and build my own machine scraper (primarily deploy macOS systems here).
