### ISSUE TITLE
Dashboard assets status graph -> Deployed twice

### ISSUE THREAD

**Issue by vgsangiuliano** [snipe/snipe-it#2933]
Dear all,
I am running snipe docker container,
Version v3.6.0-g91caba0

It is not an important issue but in dashboard assets graph I have Deployed twice in labels

![image](https://cloud.githubusercontent.com/assets/10364374/20381343/5da25b22-aca7-11e6-816f-82130488ba4f.png)

Thanks
KR
Mirko

**Comment by snipe** [comment]
Can you post a screenshot of your status labels?

**Comment by vgsangiuliano** [comment]
Here you go

Thanks
KR
Mirko

![image](https://cloud.githubusercontent.com/assets/10364374/20486764/4fa10ab6-b001-11e6-80c8-fa56bf6fceac.png)

**Comment by snipe** [comment]
This isn't actually a bug. In our system, Deployed is a meta status of sorts. More of a status label "type". You don't actually need a "Deployed" status label, since any asset that has a "deployable" status label *type* and is assigned to a user is considered "Deployed", without a specific status label saying so. https://snipe-it-manual.readme.io/docs#status-labels

**Comment by vgsangiuliano** [comment]
OK.
But I didn't create any status label.
It was what I had in default configuration.

Thanks
KR
Mirko

**Comment by CLOZADA16** [comment]
I had the same issue. I assigned "Deployed" for several items as status label in my csv file. After I imported the file, snipeit created a status label "Deployed". This is the reason why I was getting 2 "Deployed" status in the dashboard graph. Leave the status label blank for items that are supposed to be deployed to a user in your csv file but make sure to include a User to which this item is deployed to. Snipe IT will automatically label it as deployed in its database. Below screenshot shows my excel, dashboard and the assets imported. 
![1](https://cloud.githubusercontent.com/assets/20469279/21168686/1b9089de-c1f1-11e6-8bb2-f9be481df08b.JPG)
![2](https://cloud.githubusercontent.com/assets/20469279/21168687/1b940f46-c1f1-11e6-8090-974400fe7042.JPG)
![3](https://cloud.githubusercontent.com/assets/20469279/21168688/1b981d8e-c1f1-11e6-9bb3-87243ced10cd.JPG)

**Comment by ZechClar** [comment]
Hi, Just wanted to give a follow up. Even though it does say deployed now as I stated in my previous comment, when I try to click the Asset # NFA-SIT10809 the status will show "Ready to Deploy"

![capture](https://cloud.githubusercontent.com/assets/20469279/21379296/e0a858dc-c787-11e6-945b-06ff95fc5e49.JPG)

**Comment by snipe** [comment]
@ZechClar that's expected https://snipe-it-manual.readme.io/docs#status-labels

Ready to Deploy + Assigned = Deployed

**Comment by ZechClar** [comment]
Sorry Snipe, I don't quite get it. Here's a sample screen shot of one of my items
![capture1](https://cloud.githubusercontent.com/assets/20469279/21380360/b63fa606-c78f-11e6-9b73-314619b04796.JPG)

Asset tag OIS25589 shows the status as Deployed to user Dale Reyes.

![capture2](https://cloud.githubusercontent.com/assets/20469279/21380380/e6546390-c78f-11e6-894d-2e4db5be4eef.JPG)

When I click the Asset Tag OIS25589. The status shows as Ready to Deploy(Deployable). Isn't it supposed to show as Deployed? At the ride side it shows Check out to Dale Reyes.

**Comment by Paulworks044** [comment]
Hi Snipe,

The time that this becomes and issue is when you are running a report, custom or otherwise you can clearly see that the asset is allocated to a user but the status column will show as ready to deply.

I get it, as do most people that use the software but when showing the benefits of us as a business moving over to snipe-it this is a question that is always raised. 

When they see
Ready to Deploy (Deployable)
Ready to Deploy (Deployed) 

They struggle to understand how an asset can be ready to deploy but be deployed all at the same time.

Perhaps if there were a custom deployed option unique only to the check-out section. 

or 

The status/custom status were visable in two seperate columns on the custom asset report.

Is there anything in v4 that might address the conflict above?

**Comment by rprvnkmr007** [comment]
Can we get multiple Dashboard on this? We have 2 office. So that we can track it easier for both office Assets.

**Comment by rprvnkmr007** [comment]
Also, it would be better if we can add more Status type manually.
Now we are having only 4 status types. It would be better if we add more than 4 status types.
