### ISSUE TITLE
Documentation Suggestion - Outline Installer

### ISSUE THREAD

**Issue by LowGravitas** [snipe/snipe-it#2983]
Hi there,

I'll start off by saying I'm a complete Linux/coding/web hosting novice who's had his feet planted in Windows all my life (ducks thrown toaster for admitting this). So apologies if this is in the wrong place or offends anyone's Linux, coding or web hosting skills.

I've largely muddled through installation and setup of Snipe through the documentation and Google however I'd like to make one suggestion on the Installation/Downloading page. Would you be able to make a note of what the installer does and where what other outstanding items there are to complete once the installer has run its course? I just think that would be a useful addition as I've noticed things have changed from the last time I've installed Snipe.

Only suggestion, otherwise, love the work and keep it up. Couldn't work without Snipe in the office.

Cheers,
Richard

**Comment by snipe** [comment]
Hi @LowGravitas - thanks so much for the kind words! It's always nice to know people find value in the app :)

That's not a bad idea. We haven't really documented it before because it's not the preferred way to install Snipe-IT (tho necessary for folks who don't know how to set up a web server at all), and because if you run it on something that has other sites on it, bad things can happen. That said, people seem to keep finding it, so it's probaly best to document it. (It's documented within the code itself, but unless you open the installer, you won't see that stuff.)
