### ISSUE TITLE
No such file or directory in /var/www/html/snipeit/vendor

### ISSUE THREAD

**Issue by maulaku** [snipe/snipe-it#3032]
PHP Warning:  require(/var/www/html/snipeit/vendor/composer/../swiftmailer/swiftmailer/lib/swift_required.php): failed to open stream: No such file or directory in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/vendor/composer/../swiftmailer/swiftmailer/lib/swift_required.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by maulaku** [comment]
Thanks for respond

- Version of Snipe-IT you're running = 3.6.2

- What OS and web server you're running Snipe-IT on = OS : centos-release-6-0.el6.centos.5.x86_64,
  Apache/2.2.15 (Unix)

- What method you used to install Snipe-IT = with install.sh

- If you're getting an error in your browser, include that error : blank white screen no error

- apache error : [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.6.28 configured -- resuming normal operations
[Thu Dec 08 09:47:58 2016] [error] avahi_entry_group_add_service_strlst("snipe") failed: Invalid host name

- error logs : 
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/vendor/composer/../swiftmailer/swiftmailer/lib/swift_required.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66

- Include  what you've done so far in the installation, and if you got any error messages along the way. : only error : PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/vendor/composer/../swiftmailer/swiftmailer/lib/swift_required.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66

- Indicate whether or not you've manually edited any data directly in the database : no edited

**Comment by taylordrake** [comment]
Now, this may be a dumb question, but have you done these 2 things:

1) Changed directory permissions for your snipe-it folders? `storage` and `public/uploads`? Because that's important for running...

2) `php composer.phar install --no-dev --prefer-source`? The composer install, if I understand it correctly downloads the dependencies and sets them up the correct locations for snipeIT to use them.

A lot of problems I had were caused by these two big things. Once I set the directory permissions with `chown -R` and `chmod -R`, I was able to run composer without getting permission errors. Once that was done and the key was generated, I just activated debug mode and started hunting down errors. 

I'm pretty sure I eventually just set my entire snipe-it directory to be owned by my unprivileged user (not my server though), after I ran composer however, I changed the permissions to be writable by my server, in my case: `nginx`. In your case, it'll probably be `apache` or `httpd`.

If you've already done these things, please disregard me. Good luck.

**Comment by maulaku** [comment]
Thanks for guide,  and now done

**Comment by taylordrake** [comment]
Did that work for you? Or are you still having issues?

**Comment by maulaku** [comment]
Good work, no issues
