### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by RobbyTown** [snipe/snipe-it#3050]
I see there is a new version of snip-it.

I have snipe-it installed by this tutorial: https://community.spiceworks.com/how_to/132545-install-snipe-it-asset-management-on-ubuntu-14-04

Great it works perfect (version 3.6). Now i would like to update to 3.6.1

If i read this the update dont work
https://snipe-it.readme.io/docs/how-to-upgrade

I get the message Could not open input file: composer.phar

What i need to do to get the update?

**Comment by taylordrake** [comment]
The install.sh method uses slightly different path-names than if you just download it from github.

My method to upgrade, since I had it all working, was to simply re-install it by cloning the github repository, and then re-downloading composer from the link in the documentation, re-setting file permissions, editing paths in my server config and _then_ doing the composer.phar install etc. After migrating, everything works great and am able to update using the `git pull` method.

Granted, my way probably isn't the easiest, but it's the most obvious path with the most documentation to a working and eminently update-able install.

Granted this worked for me. As far as yours is concerned, you should be able to do what it says:
1) Back up your project folder. (I renamed mine to `snipeit-old`)
2) Copy the files into your working directory. (You can always restore from the backup)
3) Run composer.phar install --no-dev --prefer-source
4) Then follow the upgrade guide on artisan migrate, etc.

Anyone should feel free to correct me if I misinformed or missed anything
