### ISSUE TITLE
Unable to Login using AD account

### ISSUE THREAD

**Issue by siekee** [snipe/snipe-it#3083]
My LDAP connection test is successful but when i tried login using AD account, i am getting error: the username or password is incorrect. I am unable to find the location of the log file even to start troubleshooting. Please Help
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode  <- how to do that
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.2 build 10 (g927a12f)
- What OS and web server you're running Snipe-IT on
CentOS 7 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help#step-3-check-your-app-and-server-logs

**Comment by siekee** [comment]
Thank you for your immediate respond. The error i get from the laravel.log is

production.Error: there was an error authenticating the LDAP user: could not find user in LDAP directory

**Comment by snipe** [comment]
Your LDAP filter is likely wrong then. It's able to connect, it just can't find the user within your directory using the filter you provided.

**Comment by siekee** [comment]
Not sure what is the right filter that i shall be using. I tried different filter and some listed in the discussion board by other user, none working for me

**Comment by therealjoshuad** [comment]
Can you post your settings?

**Comment by snipe** [comment]
Please see the documentation here: https://snipe-it-manual.readme.io/docs/ldap

**Comment by siekee** [comment]
![screen shot 2016-12-20 at 12 00 54 pm](https://cloud.githubusercontent.com/assets/24662033/21337883/27d7f960-c6ac-11e6-8055-724a78b6f3c8.png)

**Comment by aglasson** [comment]
Hi @siekee

You look to be using some fields names that are used for LDAP but different to AD field names.
"uid" for instance is not used in AD by default.

Generally for AD you should probably have these, the LDAP filter is a suggest, perhaps go as per the doco:
LDAP Filter: &((objectcategory=person)(objectclass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
Username Field: samaccountname
LDAP Authentication query: samaccountname=


For example this is my LDAP Filter:
&(!(sAMAccountName=svc*))(!(sAMAccountName=test*))(mail=*)(objectcategory=person)(objectclass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
This ensures service and test accounts are excluded and user accounts without an email address are excluded.

**Comment by siekee** [comment]
Thanks for the advise. I had change the LDAP filter, username field and auth query to as shown above but still getting the same error

**Comment by aglasson** [comment]
Is that the correct structure of your OU?
Do you have an OU called "am" within the OU "Staff"?

**Comment by siekee** [comment]
i have the OU "am" and i can sync the user over to snipe-it without any issue, just having issue login the user into snipe-it

**Comment by aglasson** [comment]
Hmm. Could be LDAP Filter related maybe.
I think I've exhausted my expertise now.

**Comment by therealjoshuad** [comment]
I can't tell what you have the **LDAP Bind username** set to, but I had trouble using the DN, I had to switch to the UPN (**user@domain.com**), but if you're getting a successful sync of users into Snipe-IT, then it's probably good.

Also Are you willing to try a more generic LDAP filter? Again, probably won't make a difference, but just to rule that out. For example, in the ldap article, the example is **&(cn=*)**

Lastly, make sure the **Username Field** is set to **samaccountname**, and that the **LDAP auth query** is set to **sAMAccountName=** as shown in the guide.

![image](https://cloud.githubusercontent.com/assets/3893036/21381241/be484260-c71f-11e6-8ef3-e1412f588c50.png)

**Comment by siekee** [comment]
Thanks for your reply. I changed the LDAP filter to &(cn=*) and also the username field and auth query to what you suggest but still not able to login too

**Comment by therealjoshuad** [comment]
And you've checked the box on the LDAP settings that says this is an Active Directory domain?

**Comment by siekee** [comment]
This is an Active Directory server is not ticked. I ticked it and it make no different, still not able to login

**Comment by denihanca** [comment]
how about set the LDAP filter to simpler query such as: 

objectCategory=user

does it work?

**Comment by siekee** [comment]
@denihanca  same, not working

**Comment by ittugi** [comment]
We got exact same problem.. I found that our AD domain name was missing. After adding that I was able to log in with AD account. It is strange because I was able to sync all my AD accounts without any error messages.
![asset manager](https://cloud.githubusercontent.com/assets/22468953/21388292/418d64d4-c784-11e6-9932-0d8206f952c1.png)

**Comment by siekee** [comment]
@ittugi  Glad that it is working for you. That particular field is not empty for me

**Comment by aglasson** [comment]
And to confirm you're entering just the username with no "domain\" prefix?

**Comment by siekee** [comment]
@aglasson Do you mean the website login or in the LDAP setting. For website login, i tried keying the username with "domain\username" and "username" both are not working

**Comment by aglasson** [comment]
Yes the login to access Snipe IT.
To simplify your testing you should be using just the username.

**Comment by denihanca** [comment]
To confirm that you have the correct base settings, and testing simple ldap queries, I would recommend using http://vadimtabakman.com/ldap-query.aspx . With that tool, you can confirm that you have the correct ldap path (active directory domain and or ldap server), username and password (ldap bind username and ldap bind password) to access the ldap server, working ldap query (ldap filter), and return you the correct column names for LDAP Properties (for the fields below). To get the correct base bind DN, I would recommend running dsquery from your ldap server (example: dsquery ou -name "sysaccount" ).

**Comment by siekee** [comment]
@denihanca for that software, when i select ldap scope as base, it dont show any user but when i choose one level or subtree, the user will showup. LDAP property i used (objectClass=user). Not sure if that is the reason?

**Comment by denihanca** [comment]
from https://msdn.microsoft.com/en-us/library/ms677937(v=vs.85).aspx :

- Base. A base search limits the search to the base object. The maximum number of objects returned is always one. This search is useful to verify the existence of an object for retrieving group membership. For example, if you have an object distinguished name, and you must verify the object's existence based on the path, you can use a one-level search. If the search fails, you can assume that the object may have been renamed or moved to a different location, or you were given the wrong information about the object. Be aware that you should store the globally unique identifier (GUID) of the object instead of the distinguished name, if you wish to revisit an object. The GUID will always reference the same object, regardless of where the object is located within the directory hierarchy.

- One-level. A one-level search is restricted to the immediate children of a base object, but excludes the base object itself. This setting can perform a targeted search for immediate child objects of a parent object. For example, consider a parent object P1 and its immediate children: C1, C2, and C3. A one-level search evaluates C1, C2, and C3 against the search criteria, but does not evaluate P1. Use a one-level search to enumerate all children of an object. An IADsContainer enumeration translates to a one-level search. 

- Subtree. A subtree search (or a deep search) includes all child objects as well as the base object. You can request the LDAP provider to chase referrals to other LDAP directory services, including other directory domains or forests.

I think you should use a "subtree".

For the base bind DN, I use the fully qualified name for the OU I search into. This fully qualified name I obtain by running "dsquery ou -name "nameOfTheOU" in the AD server. For the LDAP filter, I use "objectCategory=user". Logically, this means I tell snipe-it to search for users in the OU I specified. It's a pretty simple query. @aglasson above has a working complex query.

For reference of the returned fields, I refer to http://www.kouti.com/tables/userattributes.htm

**Comment by IxFail** [comment]
Make sure to use the following settings:

Avtive Directory: Checked
LDAP Filter: cn=*
Username Field: samaccountname
Last Name: sn
LDAP Firstname: givenname
LDAP Authentication query: samaccountname=

Let me hear if that works.

**Comment by siekee** [comment]
Hello everyone,

Sorry for the late respond as i was away due to the festive holiday. It is working now after everyone's assistant. Attached is the screenshot, hopefully will be helpful for those that having same issue with me.

![screen shot 2016-12-28 at 9 35 28 am](https://cloud.githubusercontent.com/assets/24662033/21511902/69525e9a-cce1-11e6-8524-bd2f57f89970.png)

**Comment by IxFail** [comment]
@snipe This is I think the third time I responed to this sort like problem with the same response:

> Make sure to use the following settings:
> 
> Avtive Directory: Checked
> LDAP Filter: cn=*
> Username Field: samaccountname
> Last Name: sn
> LDAP Firstname: givenname
> LDAP Authentication query: samaccountname=
> 
> Let me hear if that works.

Maybe it's an idea to split the LDAP and AD documentation at the readme.io page into 2 different table's or pages?

**Comment by aglasson** [comment]
Only suggestion I'd make from a personal security preference point of view.

Turn off LDAP Password Sync. I certainly do not want a second database of my LDAP passwords. Creating a larger attack surface for my network.
If your AD is not available you've got bigger problem's than "I can't log into the inventory".

**Comment by jmathias59** [comment]
I had to add the domain\username for the ldap bind username

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by subramanyad** [comment]
Thanks a lot guys. I'm also facing same issue since many days. This Git thread help me lot to resolve the issue.

**Comment by Guenny0488** [comment]
Are you sure you are talking to a Domain Controller to get LDAP up and running?
