### ISSUE TITLE
[Feature Request] Fail2Ban filter

### ISSUE THREAD

**Issue by tx7** [snipe/snipe-it#3090]
Hello,

The current auto lock out is working good.
However, I think the security can be improve if you guys add the blacklist/whitelist to it such as IP address.
The current lock out feature only lock the specific username with an X time duration, but not IP.
Meaning the hackers can still attack the server with DDOS attack.

In the mean time, is there a Fail2Ban reg that I can use?

Thanks.

**Comment by snipe** [comment]
Blacklists/whitelists don't protect you from a DDoS attack, since the server still needs to handle those requests to determine whether or not they should allow the request to continue.

**Comment by snipe** [comment]
You're welcome to change your apache configs (or mod_security) to only permit specific IP addresses though. You can use the examples here: https://incapsula.zendesk.com/hc/en-us/articles/200627570-Restricting-direct-access-to-your-website-Incapsula-s-IP-addresses-

(using your own IP addresses instead of theirs, of course.)

**Comment by tx7** [comment]
I see.
I'm using Nginx.
Should I put the whitelist of IP addresses in the `.htaccess` of Snipe-IT or in my Nginx virtual host?

**Comment by snipe** [comment]
Nginx

**Comment by tx7** [comment]
Ok. Is there a way I can see the fail login attempts from the admin control?
Maybe this feature in the future release?

**Comment by benrubson** [comment]
_See #4629 for a related request._
