### ISSUE TITLE
Multiple categories for model/model #

### ISSUE THREAD

**Issue by xxtheatrainxx** [snipe/snipe-it#3107]
#### Desired behavior

Be able to apply 2 or more categories to the same model/model # of an asset

-----

#### Actual Behavior

If one Dell Optiplex 3020 is "categorized" as a Dashboard it changes all 3020s to the Dashboard category

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Version v3.6.2 build 10 (g927a12f)
- What OS and web server you're running Snipe-IT on
Win2k8/IIS

It would be helpful for those of us that like to keep our assets separated by what they're purposed for rather than what model # they have.

**Comment by snipe** [comment]
We may consider adding tags or something, but I don't see us doing multiple categories for a single asset or asset model any time soon. What's your actual use case here?

**Comment by SotoDucani** [comment]
I think tags would be a nice way to handle that sort of need. I can think of a few ways I would use it around here.

Specifically, I could have a certain Desktop model. Some of those machines I could spec out to handle large engineering workloads with hefty graphics cards (Engineering tag), and others with more basic specs (Office tag).

I believe his use case is similar, they have 3020's for employees (Desktop tag), and a few repurposed ones that they use as dashboards for their monitoring system or something(Dashboard tag).

**Comment by xxtheatrainxx** [comment]
Soto's description is pretty much spot on.

**Comment by nghia-dang** [comment]
What happens if you have a desktop model but 5 groups of employee or customer type that all require different EULA ..and have differing check in out or confirmation response requirements ? 

Currently we have to create 5 of the exact same model and assign a category to each which can be quite cumbersome. Would tags solve this with emails, check in out and terms acceptance requirements ? If so would their be a heirarchy based system to determine which EULA gets emailed ? What is intended workflow for this type of situation ?
