### ISSUE TITLE
[Bug] No quantity validation when checking out - Quantity goes in the negative [3.6.2]

### ISSUE THREAD

**Issue by abaalkh** [snipe/snipe-it#3119]
Hi there,

Absolutely love the app, great work!

There doesn't seem to be quantity validation when checking out to a user.
Even though the button is 'disabled' you can still click it and checkout as usual, the quantity, however goes in the negative.
The screenshot included is from the 'accessories' tab, i cannot try the other types since it's in production.

I'm running the latest version (v3.6.2 build 18 (g6f1e0d6)) on CentOS 7.
I'm not sure if this is a bug or intended. Please have a look at it.

Thank you.

![00dce908b3b9416d9bfaf32993401859](https://cloud.githubusercontent.com/assets/2372747/21600783/bcf66d4c-d192-11e6-8347-897ffdb2faca.png)

**Comment by snipe** [comment]
> There doesn't seem to be quantity validation when checking out to a user.

What section is this in? Assets, accessories, etc?

**Comment by Damdomy** [comment]
> The screenshot included is from the 'accessories' tab, i cannot try the other types since it's in production.

**Comment by Oreios** [comment]
#### Expected Behavior 

**In the consumables view**
The checkout button becomes unclickable.

-----

#### Actual Behavior

**In the consumables view**
The blue checkout button becomes a lighter blue. Indicating it's not clickable. It even has a mouse hover icon change to indicate this again.

However It's still clickable and I can checkout to a user making it become -1.

I clicked it by accident that's how I found out.
-----

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running (v3.6.3 build 15 (g1bf34d7)
- What OS and web server you're running Snipe-IT on (Ubuntu debian 16.04, Apache2)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) (git copy)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error (n/a)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error (consumables)
- If a stacktrace is provided in the error, include that too. (n/a)
- Any errors that appear in your browser's error console. (n/a)
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). (Yes, it's reproducible)
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
