### ISSUE TITLE
Email Issue using gmail or sendinblue (mandrilla like service)

### ISSUE THREAD

**Issue by dastrixuk** [snipe/snipe-it#3236]
Just to confirm I am getting the following error when trying to email a user there account details. 

We are using the following versions
Snipe-IT version	v3.6.3 build 15 (g1bf34d7)
PHP Version	5.6.29
Laravel Version	5.2.45

I have run through the items needed to do for a gmail account but to no avail, anyone able to help with the following?

Error in the logs
[2017-01-26 08:31:57] production.ERROR: exception 'ErrorException' with message 'stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed' in /home/oatforgeco/public_html/asset/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:95

**Comment by snipe** [comment]
Next time please provide us all of the answers we ask for in the Github issue template. We ask for a reason.

This most often happens when you have an invalid or missing SSL root bundle.

https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#php-56-certificate-verification-failure
http://stackoverflow.com/a/32694532/200021
https://laracasts.com/discuss/channels/laravel/error-sendmail-using-laravel-xampp-php-7-windows/replies/180810
https://akrabat.com/ssl-certificate-verification-on-php-5-6/
http://stackoverflow.com/a/32366242/200021

There's a ton of info out there, based on a quick google search of your error.
