### ISSUE TITLE
Auto generate PDF Protocol

### ISSUE THREAD

**Issue by kpawelski** [snipe/snipe-it#3295]
It would be nice to have a automatically generating eg. (checkin/checkout) protocol (in PDF format).   
(sometimes you need a paper and signature not only db entity)
When will be this feature available, if only?

-----

**Comment by lorenzolewis** [comment]
We were just talking about having this feature for when we checkout assets and how it would be nice to have a verification to send to the user.

**Comment by chrstmnn** [comment]
Are there any news to that?
We also would like the feature to get a PDF protocol.
At the moment we can just see the signature of accepting an asset, but there is the context (EULA) missing, which could be changed in the meantime.

Proposal: Instead of showing only the signature, offer a PDF with the EULA plus signature plus date and time of signature.

Would love this feature!
