### ISSUE TITLE
Bulk Checkout to Location and Person

### ISSUE THREAD

**Issue by EQPShedrick** [snipe/snipe-it#3343]
feature request

**Comment by EQPShedrick** [comment]
Love how easy it is to checkout assets to a person but would love for it to include a location as well

**Comment by vanillagranilla** [comment]
We would also like to see this feature - the ability to update the location of an item during checkout.

**Comment by Cintel** [comment]
Please add this feature - we use the system to check assets out to remote locations and not having that option on the bulk checkout page is painful.

**Comment by Gridlok** [comment]
Please add this feature, really need it.

**Comment by mankdhodi** [comment]
Hello Team, Is there any progress on this feature? We need it on the priority to handle 1000 around assets. Looking for the response at the earliest.

**Comment by 5quirrel** [comment]
@mankdhodi this feature was added in v4.3.0

**Comment by mankdhodi** [comment]
Hi Team, Everytime i fetch asset from the csv file, it misses on the checked out to field and it turns out to be blank..I have also tried to map checked out to field with full name it converts the asset into user in the checked out to column and makes new entry of an user in the people section in navigation tree....It will be great if you can tell me the proper field name for this to map it to snipe/IT...
