### ISSUE TITLE
feature-request: automatically add an additional column into assets table when creating new assets

### ISSUE THREAD

**Issue by it-world** [snipe/snipe-it#3478]
#### Expected Behavior (or desired behavior if a feature request)
When creating new assets, id like to automatically add the url to the new asset into a column (lets call this row URL).

The reason why id like to get this working:
I export the assets table into an excel sheet and feed my label printers software (p-touch editor) with this excel sheet .
From there i print my labels to an P-900W.
At the moment i update this by hand but, it will be more effective if its done automatically during creation of the new asset.

**Comment by snipe** [comment]
It doesn't really make sense to store that as a database field, since 1) it could change if you changed your URL and 2) the patterns already exist to generate that on the fly. Just export your asset's ID number in the exported column and use an excel formula to generate the asset url.  Something like http://stackoverflow.com/questions/16361620/how-do-i-create-urls-in-excel-based-on-data-in-another-cell
