### ISSUE TITLE
Issue terminating SSL on HAProxy

### ISSUE THREAD

**Issue by kitzy** [snipe/snipe-it#3495]
I'm having trouble getting SSL termination working on HAProxy. I've read this: https://snipe-it.readme.io/docs/reverse-proxies and followed the instructions. I've added `http-request set-header X-Forwarded-Proto https if { ssl_fc }` to the frontend listener in HAProxy. I'm still getting a warning from Chrome that the page contains insecure elements.

I've enabled debug mode, however storage/logs is empty. No logs to be found. /var/log/apache2/snipeIT.error.log is also empty.

Not sure where I'm going wrong here.

-----

#### Please confirm you have done the following before posting your bug report:

- [/] I have enabled debug mode
- [/] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Unsure. I cloned the Github repo this morning, so I would imagine I'm running the latest version.

- What OS and web server you're running Snipe-IT on
Ubuntu 16.04, Apache2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation with Github clone

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Debug is on, not seeing any errors

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/setup

- If a stacktrace is provided in the error, include that too.
n/a

- Any errors that appear in your browser's error console.
"Your connection to this site is not fully secure" (Chrome)

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
n/a

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
storage/logs is empty

- Include what you've done so far in the installation, and if you got any error messages along the way.
We followed the instructions in the documentation. Everything works as expected until we try to terminate SSL on HAProxy.

- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by kitzy** [comment]
It's worth noting that we have other services successfully running behind this HAProxy server with SSL termination and `X-Forwarded-Proto https` enabled.

**Comment by kitzy** [comment]
from our .env

`# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=sandbox
APP_DEBUG=true
APP_KEY=********
APP_URL=https://sandbox-things.**************
APP_TIMEZONE=UTC
APP_LOCALE=en

# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_TRUSTED_PROXIES=*
ALLOW_IFRAMING=false`

**Comment by kitzy** [comment]
And the relevant bits of our HAProxy config

```
frontend https
         bind :80
         bind :443 ssl crt /etc/haproxy/ssl
         mode http
         http-response set-header Strict-Transport-Security "max-age=31536000"
         http-response set-header X-XSS-Protection "1; mode=block"
         http-response set-header X-Frame-Options "SAMEORIGIN"
         http-request set-header X-Forwarded-Proto https if { ssl_fc }
         option forwardfor

         # redirect all HTTP traffic to HTTPS
         redirect scheme https if !{ ssl_fc }  

         acl is_things hdr(host) -i sandbox-things.***********
         use_backend snipeit if is_things

backend snipeit
         mode http
         acl network_allowed src **********************
         http-request deny if !network_allowed
         option forwardfor if-none
         http-request set-header X-Forwarded-Port %[dst_port]
         http-request add-header X-Forwarded-Proto https if { ssl_fc }
         balance roundrobin
         cookie SERVERID insert indirect nocache
         server snipeit01 sand-snipeit1.*************:80 check cookie snipeit01
```

**Comment by kitzy** [comment]
We were able to work around this by inserting our trusted proxy IPs directly into `config/trustedproxy.php`.

**Comment by snipe** [comment]
You should generally avoid editing the config files themselves, as your changes can get blown out when you update.

Instead, you should use the available .env settings, in this case, `APP_TRUSTED_PROXIES`:
https://snipe-it.readme.io/docs/configuration#section-optional-misc

Additionally, if your issue is resolved, please remember to close it.

**Comment by kitzy** [comment]
We did add the IPs to `APP_TRUSTED_PROXIES` in .env, however this did not work for us, hence the issue.

**Comment by snipe** [comment]
Did you clear the config cache afterwards have have it pick up the new .env settings? All that original line in the .env does is explode out any comma-separated values into an array. https://github.com/snipe/snipe-it/blob/master/config/trustedproxy.php#L16

**Comment by kitzy** [comment]
Yes, we ran `php artisan config:clear` from the working directory after making the changes.

**Comment by kitzy** [comment]
What I didn't check was if the data made it successfully into the config file. I'll check for that and report back.

**Comment by snipe** [comment]
Cool, thanks. If it's an issue, we'll push out a fix to develop for the upcoming 4.0 release

**Comment by kitzy** [comment]
Ok, so I made a change in .env, ran `php artisan config:clear` and reloaded apache, but the value in `config/trustedproxy.php` did not update.

**Comment by sgi-ch** [comment]
Hello All.

We've the same Issue like @kitzy wrote. Last comment of him (14. Apr 2017) - same here. When we do `APP_TRUSTED_PROXIES=*` in the .env File it is not working. When we change it directly in the `config/trustedproxy.php` it is working.

Also the Pre-Flight Check says that we're connecting over https:// but the real url should be http://. So the thing with Proxy seems not to be working correct or does anyone have other informations?

**Comment by nbuonin** [comment]
I'm having exactly the same issue, and I solved it in the same way - by overwriting `config/trustedproxy.php`.

I think [the docs](https://snipe-it.readme.io/v4.6.3/docs/reverse-proxies) could be more clear on this point. Its confusing to start describing a "broken" scenario.  Its especially so because the pattern described is a pretty common method for terminating SSL for apps running within a private network.  What's broken about it: the pattern, or how Snipe-IT responds to a request from a proxy configured in that way?  Does the configuration offered fix this broken scenario?  I think thats the intention but it doesn't explicitly say.

The two scenarios labeled "Works" are also confusing, because its unclear if you're suggesting that folks should use them.  Ingress over http really should be avoided, and https between proxy and upstream makes sense in certain situations, but not all.  Does Snipe-IT have an opinion about that?  I don't think it does, but again its unclear.

In my mind it would be much more clear to simply state the config for each scenario, without labeling them "works" or "broken".  If https => http is broken because of a bug, which it seems like that could be the case, then I'd suggest note it and link to some work-arounds until its fixed.

**Comment by snipe** [comment]
> I'm having exactly the same issue, and I solved it in the same way - by overwriting config/trustedproxy.php.

What exactly did you overwrite it with? That's generally not a good idea, as any future changes that we push out will break things for you.
