### ISSUE TITLE
Feature Request - Nested Models

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#3566]
#### Expected Behavior (or desired behavior if a feature request)

Ability to create generic model types, and then specific nested model numbers. 

Example: Toyota Carola as the Model Type
Then you'd have the L, LE, LE ECO, XLE, SE, 50th Anniversy and lastly XSE

Example 2: (**way more in depth**) Apple iPad

Pad (aka iPad 1)	A1219 (Wi-Fi version)
	                        A1337 (Wi-Fi + cellular version)
iPad 2	A1395 (Wi-Fi version)
	        A1397 or A1396 (Wi-Fi + cellular versions)
iPad (third generation)	A1416 (Wi-Fi version)
	                                A1430 or A1403 (Wi-Fi + cellular versions)
iPad (fourth generation)	A1458 (Wi-Fi version)
	                                A1459 or A1460 (Wi-Fi + cellular versions)
iPad Air	A1474 (Wi-Fi version)
	        A1475 (Wi-Fi + cellular version)
iPad Air 2	A1566 (Wi-Fi version)
	        A1567 (Wi-Fi + cellular versions)
iPad mini 1	A1432 (Wi-Fi version)
	                A1454 or A1455 (Wi-Fi + cellular versions)
iPad mini 2 (aka iPad mini with Retina display)	A1489 (Wi-Fi version)
	                                                                        A1490 (Wi-Fi + cellular version)
iPad mini 3	A1599 (Wi-Fi version)
	                A1600 (Wi-Fi + cellular version)
iPad mini 4	A1538 (Wi-Fi version)
	                A1550 (Wi-Fi + cellular version)
iPad Pro 12.9in	A1584 (Wi-Fi version)
	                        A1652 (Wi-Fi + cellular version)
iPad Pro 9.7in	A1673 (Wi-Fi version)
	                A1674 or A1675 (Wi-Fi + cellular version)
iPad (fifth generation, 2017)	A1822 (Wi-Fi version)
	                                        A1823 (Wi-Fi + cellular version)

-----

#### Actual Behavior

Currently when creating models and model numbers, you are forced to recreate a Model with a different name, and Model Number to have varying models. 

This should be a nested sql table, where everything can be (in the iPad example) an Apple iPad with a specific Model # (aka Apple iPad : A1219 or Apple iPad : A1822)

Simplifies the overarching model tables, and while providing the flexibility of the asset models as it appears to be intended.

**Comment by snipe** [comment]
This isn't a bad idea, but my bigger concerns are a) we already have some pretty crazy joins happening for the text searches, and adding another layer of abstraction is going to make it even hairier and b) users already have a tough time understanding the relationship between categories and models, so it would be a real UX challenge to implement this in a way that wouldn't be really confusing to admins.

**Comment by sjwk** [comment]
This would definitely be helpful.  I'm just experimenting with the software and have spent the last hour pulling my hair out on this.  Specifically for me, the issue was wanting to assign custom fields (MAC and IP address) to [all] models.  I actually just went through my spreadsheet changing all occurrences of 'Optiplex 9010, 9020 etc' to just 'Optiplex' and using the model number field to handle the model number on the assumption I could then assign a custom fieldset to just the asset model 'Optiplex', only to find that the backend effectively concatenates model+number to make an asset model, so would still need to manually add fieldsets to every permutation of Optiplex.  And then repeat for the Latitudes, the Apple iMacs,  Macbooks, ... and try to train others to remember to do this when adding every new model of an existing model range later.

In its current way of working (or is it *my* way of working?), I can't actually see any advantage of having different fields for model and model number over just having one field.

Alternatively, applying custom fieldsets to device types (all desktops have a MAC address for instance) or just all devices but that's out of scope for this query.

**Comment by snipe** [comment]
> only to find that the backend effectively concatenates model+number to make an asset model

Thar's not actually true though. It displays it that way on the frontend, so that you can visually tell the difference between asset models that have the same name but different model number - if there's an asset model number provided - however they are separate models. 

In the upcoming v4, you'll be able to bulk-edit asset models to assign custom fieldsets to them all at once.
