### ISSUE TITLE
Feature Request: Map Fields on Import

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#3639]
We should have an intermediate screen after the user clicks "process" to allow them to map their CSV headers to the appropriate fields for the asset/accessory/etc. This will allow users to export from the assets listing and re-import with updates, and will also handle any misspellings in header rows, etc,

**Comment by snipe** [comment]
@dmeltzer - I've started fleshing some of this out - it might be something you can take a look at this weekend as you're investigating the vue issue. 

I don't know if we want to try to incorporate this mapper page into the modal? I feel like probably not - it could get long.

### To-Do:

- Figure out best UX/workflow for mapping and how it relates to the modals
- Pass an import number or filename to the mapper - currently just hardcoded
- Dynamically update the first row's output somewhere on the screen to show what the first row will look like if imported as-is

<img width="719" alt="screen shot 2017-06-09 at 4 04 56 pm" src="https://user-images.githubusercontent.com/197404/26997769-433820a2-4d31-11e7-81cb-11645c50061e.png">
<img width="792" alt="screen shot 2017-06-09 at 4 05 24 pm" src="https://user-images.githubusercontent.com/197404/26997768-432caf2e-4d31-11e7-9a1b-b16273eb1d46.png">

**Comment by dmeltzer** [comment]
So.. the only part of this I didn't really implement was the slugification of headers... Instead we rely on a mapping provided by the user when importing, and just use the case extacted from the file.  If the case matches exactly we prefil the field, otherwise it's blank by default... probably need some validation still to make sure enough items are selected... and then possibly look at fuzzy matching.
