### ISSUE TITLE
Custom Fields disappeared after one day of working 

### ISSUE THREAD

**Issue by Snipeuser** [snipe/snipe-it#3641]
I created new custom fields and added into newly created fieldset. Then I added this fieldset in asset models and added in asset list dashboard also. We have hosted in our own premises. Yesterday it was working fine but today its started not to appear.

Our process was like while  creating a new asset, after selecting an asset model, the custom fields should appear and we can select from the list box. Yesterday it was working fine. But from today while creating asset, after selecting asset model, the custom fields are not at all appearing and also after selecting status as Ready to Deploy, the checked out to user field also not appearing. Its ended up with loading process in green circle near the status field.

But editing an asset process everything is fine. Custom fields are there.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by aglasson** [comment]
I had this exact same issue but I just resolved it myself by turning debug mode on. I've turned it off again and the issue is no longer present. So somehow turning debug on and off (restarting httpd inbetween) has resolved the issue. No other changes have been made.

- Version of Snipe-IT you're running
- - 3.6.6 (I upgraded from I think 3.6.3 because of this issue but it persisted)
- What OS and web server you're running Snipe-IT on
- - CentOS, Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- - install.sh
- If you're getting an error in your browser, include that error
- - None that I could see.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- - Any asset edit page "https://serveraddress/hardware/298/edit"
- If a stacktrace is provided in the error, include that too.
- - None
- Any errors that appear in your browser's error console.
- - None that I could see.
- Confirm whether the error is reproduceable on the demo.
- - Issue not discovered in Demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- - Everything worked fine on 3.6.3 (I think that was our last version) for a while until one day I noticed it just not working. I upgrade to 3.6.6 (stopped httpd, copied files over the top, ran all listed php commands as per the release note, started httpd) in the hope it would resolve but it did not. Further investigation and I turned on debug mode and noticed all of a sudden it was working. Turned debug mode off and the issue was no longer present.
- Indicate whether or not you've manually edited any data directly in the database
- - Definitely not.

**Comment by msterri** [comment]
I'm having the same problem, I setup some fieldsets the other day that only worked until I closed the browser. I went back in a couple of hours later and the fieldsets would no longer work when creating an asset and selecting a model with a fieldset. I have tried above advice to enable debug mode but that hasn't worked. I'm worried I'm going to have to reinstall from scratch which is frustrating as I have just started adding all my assets in.

**Comment by aglasson** [comment]
You could try update which might restore it's functionality.. Maybe.

**Comment by msterri** [comment]
and today its back to not working again without making any changes. This time debug mode hasn't solved it.

**Comment by snipe** [comment]
There's no reason I know of (other than an inaccurate APP_URL) that would cause custom fields to have issues. Turning debug mode off and on also shouldn't have any effect on whether it works or not.

**Comment by snipe** [comment]
When you view the HTML source, can you tell me the URL of the ajax call it's making for those custom fields, and also tell me the URL you use to access your app?

**Comment by msterri** [comment]
thanks for the quick reply, I actually decided to do a reinstall so if the issue creeps up again once reinstalled I will create a new issue.  cheers!
