### ISSUE TITLE
Centos 6.5 Installation

### ISSUE THREAD

**Issue by jrtoman** [snipe/snipe-it#366]
I am looking at testing your Snipe IT management tool as a side project, but I am by no means an apache, mysql, or web server guru. This would be running on an independent Centos 6.5 developer workstation server updated to 6.6. I have tried a few times to get this to run properly, but all I have been able to do is to get it to navigate to the folder directory and list the contents of that Snipe IT folder. Any help would be appreciated.

**Comment by knspradeep** [comment]
Hey I am getting this error after installing it 

##  Installing Snipe-IT
PHP Fatal error:  Class 'Maknz\Slack\SlackServiceProvider' not found in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Maknz\\Slack\\SlackServiceProvider' not found","file":"\/var\/www\/html\/snipeit\/vendor\/laravel\/framework\/src\/Illumin[  OK  ]ndation\/ProviderRepository.php","line":157}}Stopping httpd:
Starting httpd: [Wed Jan 11 18:07:38 2017] [warn] module rewrite_module is already loaded, skipping
[Wed Jan 11 18:07:38 2017] [warn] module rewrite_module is already loaded, skipping
[Wed Jan 11 18:07:38 2017] [warn] _default_ VirtualHost overlap on port 80, the first has precedence
                                                           [  OK  ]

**Comment by snipe** [comment]
@knspradeep: 

Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Also please create a new issue instead of necrobumping an old one that is unrelated.

**Comment by knspradeep** [comment]
>2.1.2 
>centos 6.6
>tried both install.sh & Manual Installation 
>Browser i am getting "Whoops, looks like something went wrong."
>Nothing under app/storage/logs/
>Nothing i have edited manually apart adding domain ip on bootstrap/startup.php

**Comment by knspradeep** [comment]
I have tried it on latest version and it is working on centos 7 but my exact requirement is on centos 6.6
So which version should be feasible to install it on centos 6.6 version

**Comment by snipe** [comment]
We are not supporting new installations of version 2.x anymore.

**Comment by knspradeep** [comment]
so new version should work on centos 6.6

**Comment by snipe** [comment]
There is no requirement on a specific version of linux, except for the install.sh method of installation.

**Comment by knspradeep** [comment]
install.sh method used systemctl start <> but centos 6.6 method used service start <>

**Comment by knspradeep** [comment]
do we have a manual installation steps

**Comment by snipe** [comment]
> There is no requirement on a specific version of linux, except for the install.sh method of installation.

>> install.sh method used systemctl start <> but centos 6.6 method used service start <>


Literally just said that. 

https://snipe-it.readme.io/docs/installation

**Comment by knspradeep** [comment]
Q. Do you want me to automatically create the snipe database user password? (y/n) n
  Q. What do you want your snipeit user password to be?
Unable to Handle Centos Version #.  Version Found:  6.6
./snipeit.sh: line 532: return: can only `return' from a function or sourced script

  ***If you want mail capabilities, edit /snipeit/.env and edit based on .env.example***

  ***Open http://10.40.1.11 to login to Snipe-IT.***


* Cleaning up...
* Finished!

**Comment by knspradeep** [comment]
Few of the pages are showing 404 pagenot found error
<img width="1271" alt="screen shot 2017-01-11 at 6 34 38 pm" src="https://cloud.githubusercontent.com/assets/23522601/21849648/d6d70cd0-d82c-11e6-8dc9-088e96777758.png">

**Comment by snipe** [comment]
Just find them in the sidenav. We've recently reorganized the docs

**Comment by knspradeep** [comment]
i dint find it in sidenav

**Comment by knspradeep** [comment]
sorry got it

**Comment by knspradeep** [comment]
after following the steps on document i got the error on web page ERR_CONNECTION_REFUSED

**Comment by snipe** [comment]
I have already asked you to create a new issue for this. Every time we reply to this one, people who were previously on the thread are notified via email. It's rude to resurrect an old thread, especially when your issue is unrelated. 

In other words, create your own issue if you must, but once again, please stop replying to this one. And if you do create your own issue, you'll need to give us more information than just "i got the error on web page ERR_CONNECTION_REFUSED".
