### ISSUE TITLE
Field values of custom field list box clipped to 255 characters

### ISSUE THREAD

**Issue by scranfor** [snipe/snipe-it#3682]
#### Expected Behavior (or desired behavior if a feature request)

I would like to be able to enter greater than 255 characters for the Field Values of a List Box custom field. 

-----

#### Actual Behavior

Entered text is silently clipped to first 255 characters of entered Field Values. DB has it as varchar(255). 

-----

v3.6.6 build 1 (gee2c67a)

**Comment by snipe** [comment]
This is fixed in the upcoming v4.

**Comment by scranfor** [comment]
Good to hear. This, and the ability to edit custom fields after creation (which I saw was also fixed for v4), are the only two blockers to using this in my department. 

Any rough eta on v4 availability?

Thanks for the great tool!

**Comment by snipe** [comment]
Unfortunately no ETA yet. We’re working through a few final issues, but they’re a little complex, so it’s hard to say when it will be ready. Hopefully another week or so, although we’ve been saying that for a while. We won’t release until we know it’s soliud for everyone.

**Comment by snipe** [comment]
One way you can help us ship faster would be to set up a separate instannce of the dev branch (if that’s something you’re comfortable doing) and report bugs that you find. I know many of our users are not devs, so that’s easier said than done, but we always appreciate more testers before a release! :)
