### ISSUE TITLE
Permissions error installing composer

### ISSUE THREAD

**Issue by el-ahrairah** [snipe/snipe-it#3694]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior
cd /etc/snipeit/snipe-it-3.6.6
curl -sS https://getcomposer.org/installer | php
All settings correct for using Composer
The installation directory "/etc/snipeit/snipe-it-3.6.6" is not writeable
-----
which makes sense in that those files are owned by root.  But the instructions say "Never run composer as super-user".  So what's the solution to getting this installed if I don't use sudo?  Thanks.
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
_3.6.6_
- What OS and web server you're running Snipe-IT on
_Ubuntu server 16, Apache_
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
_downloaded .gz file_
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by el-ahrairah** [comment]
I went ahead and downloaded composer as root, per every other instruction page I could find.

I changed ownership of my snipe directory (/etc/snipeit/snipe-it-3.6.6) from root to myself (for now) to get around the problem above: sudo chown -R me /etc/snipeit/snipe-it-3.6.6

If someone knows that is simply not going to work, please let me know.

thanks

**Comment by el-ahrairah** [comment]
Yeah, after spending several hours on this Snipe thing, we gave up and are looking for an alternative.  We'd heard good things about Snipe, but if it's this hard to install, it's going to be too costly to maintain.

**Comment by snipe** [comment]
It's not that hard to install, I promise. This is basic web file/folder permission stuff. 

It sounded like you got your situation sorted. The issue is just that you installed composer globally (which is fine), but a normal (non-root) user needs to have access to it. You're correct to chown the Snipe-IT directory to your non-root user. (No web stuff should ever be owned by or run as root. If a malicious file got uploaded to your web space, it would have enhanced permissions and could do real damage outside of your web directory.)

Running composer as root is a bad idea simply because certain meta directories are created when you run composer install/update, and if you run it as root the first time, those meta directories will be owned by root. If you forget to run them as root next time, you'll hit permissions issues. 

The short answer is that nothing should be owned by root. Everything should be owned by and run as you (or whatever other non-privileged user you want to use). 

FWIW, you only need to install composer once. Once you're able to do `composer install` as a non-root user, upgrades don't require any reinstallation of composer.
