### ISSUE TITLE
[v4 UI] Cannot set Department to be a part of a Company

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3776]
Inside of the web interface, users can not set a Company to be associated with a Department, which is a function inside of the API.

<img width="833" alt="screen shot 2017-07-26 at 2 10 58 am" src="https://user-images.githubusercontent.com/16108587/28606970-b4c5d04e-71a7-11e7-8a62-6874210fcc6a.png">

**Comment by snipe** [comment]
Fixed on dev :)

**Comment by ebonweaver** [comment]
While the company drop down shows for a Department, this association doesn't seem to actually do anything.  The expectation is that the Department field will show up for Assets, and once you choose a Company you can then choose from the list of associated Departments.  And, to avoid any possible issues for single company use, just like multiple company support can be enabled, Company use should be able to be disabled, or at least the field hidden when you only have one company (unless that already magically happens and we can't see it because we used companies as departments as Departments didn't exist and still can't be used for Assets).
