### ISSUE TITLE
I cant create app key

### ISSUE THREAD

**Issue by Ataoglan** [snipe/snipe-it#3809]
I am using Win10 and I downloaded Putty but I dont know how to I get the key? Is there anyone can explain it? thank you

**Comment by dkmansion** [comment]
Hi Ataoglan,  You may get more of a response if you provided the details asked when opening an issue.  No one knows what your setup is. Nor how you are serving the site, if you installed the prerequisites, etc.

If you fully setup a web server (xamp) and the composer prereqs try this...

Open cmd on your windows machine.
cd to your website project folder. (where your .env file is.)
type **php artisan key:generate**

Show us the error or results here.  Though if it returns successful **DO NOT** show us your key it should be kept private since it's used to encrypt data in your database.

Not sure if putty is needed, just try cmd and if you are getting a php not recognized and using xamp try this fix
http://www.johnbhartley.com/2013/php-not-recognized-as-an-internal-or-external-command/

I'm not using windows so I'm not sure I can assist more that this.  Good luck.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues
