### ISSUE TITLE
Users having permission issues when trying to check-out a device assigned to them. 

### ISSUE THREAD

**Issue by JuniorSheret** [snipe/snipe-it#3815]
#### Expected Behavior (or desired behavior if a feature request)

After having their device added to the asset list, and having received the automated email saying to check-out their device, they should be able to do so without any issues if their permissions are correct. 

-----

#### Actual Behavior

When the email is received by the user, they are hit with an error saying they have insufficient permissions, some users are having no issue with this and most are getting the error message (they all have the exact same permissions).

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I'm not sure I understand the workflow to reproduce this. Users aren't typically checking anything out to themselves, and they're not notified to do so via email. They can confirm receipt of an item. Is that what you mean?

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues

**Comment by jonayreyes** [comment]
Sorry for reopening, but I have the same exact behavior. I have 25 users and 3-4 of them receive this message after clicking the email link of "I have read and agree to the terms...". They are on different locations (I have 3 locations set up) but I logged in as them from my PC, clicked with their link and received the same message. They have are all members of the "employees" groups, so I don't think it's an "in-app" permissions problem, but maybe file permissions. I had to tinker with folder permissions since I had to go back and forth with the installation procedure due to the fact that Linux Mint was not supported in the .sh file. 
I tried to `LOG::debug` here and there in the relevant controllers but with no avail, I don't know how to even trace the code and diagnose it myself, so I'm reopening this issue :(

So:

**Please confirm you have done the following before posting your bug report:**
 
- [x]  I have enabled debug mode
- [x]   I have read checked the Common Issues page

**Please provide answers to these questions before posting your bug report:**
Version of Snipe

- [x] -IT you're running **5.4.35**
- [x] What OS and web server you're running Snipe-IT on **Linux Mint, Apache**
- [x] What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **install.sh and manual**
- [x] WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **[2018-07-27 14:05:26] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to App\Models\Asset::prepeareSearchTerms() must be of the type string, null given, called in /var/www/html/snipe-it/app/Models/Traits/Searchable.php on line 26 in /var/www/html/snipe-it/app/Models/Traits/Searchable.php** (it appears in every single view though)
- [x] What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **http://x.x.x.x/account/accept-asset/XXXXX**, after clicking the checkout email
- [x] If a stacktrace is provided in the error, include that too. **Only the prepareSearchTerms error, not relevant to this issue**
- [x] Any errors that appear in your browser's error console. **/api/v1/account/requestable/hardware?requestable=1&sort=name&order=asc&offset=0&limit=20:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)**
- [x] Confirm whether the error is reproduceable on the demo. **Demo won't send me an email**
- [x] Include any additional information you can find in app/storage/logs and your webserver's logs. **laravel.log doesn't have any other error than the 'Searchable.php' one**
- [x] Include what you've done so far in the installation, and if you got any error messages along the way. **Everything else runs fine**
- [x] Indicate whether or not you've manually edited any data directly in the database **not yet :)**
