### ISSUE TITLE
could not access http by host name

### ISSUE THREAD

**Issue by newcomer01** [snipe/snipe-it#3959]
#### Expected Behavior (or desired behavior if a feature request)

I have done manual install as per installation guide and my snipeIT is running well.

I can access it by http via IP but I cannot access it by host name as per below error url. Could you please advise me what I am wrong as I am a newbie both CentOS and snipeIT. Many thanks in advance.

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.6 build 1 (gee2c67a)
- What OS and web server you're running Snipe-IT on
CentOS7 -Apache web server.
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
https://photos.app.goo.gl/Dsd2Bpdh3ozjRoA13
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Sounds like you need to set up DNS for your instance. DNS is what tells a computer that `foo.blah.com` should point to a specific IP address. 

This is a networking issue, not a Snipe-IT question. I've included a few basic suggestions below, but If you're still stuck, you can try googling "Setting up DNS" and try to narrow it down based on your needs.

Firstly, you can run Snipe-IT using just an IP address. Just make sure the `APP_URL` in your `.env` correctly reflects the IP address.

But if you want to access Snipe-IT through a name, instead of an IP address, it depends on what your environment is and what you're looking for.

### Snipe-IT accessed ONLY by YOUR computer... 

You can add a line in the `/etc/hosts` file of whatever computer on the network needs to access it that points whatever name you want to the IP. That would look something like this in your `/etc/hosts` file:

```
192.168.1.2 snipe-it.local
```

(assuming your Snipe-IT instance's IP is `192.168.1.2` and the name you want to use to access it is `snipe-it.local`.) 

### Snipe-IT accessible to ONLY those in your internal network...

For example, if you're running Snipe-IT on a private, internal IP that cannot be reached outside of your network, contact your network administrator and ask them to set up DNS for the IP of your instance. 

### Snipe-IT accessible to the entire internet

You'll need to make sure the IP address for your instance is accessible outside of your network. (For example, IP addresses that start with `127.0.*.*` or `192.168.1.*` are internal and cannot be accessed outside of the network they live on.)

If the IP address is an externally facing IP address and you want to use something like `assets.mycompany.com`, you'll need to have whoever manages the domain name for `mycompany.com` set up an A record pointing `assets.mycompany.com` to your Snipe-IT external IP address.
