### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by jamesoglesby** [snipe/snipe-it#397]
Hello.

Not urgent, by any means - but nice to haves.

I think it would be nice to have support for UK (and other countries) currency's when viewing assets etc... With this in mind, would it be possible for somewhere to have a 'total asset value'. This could be done in different ways - so a reporting page which displays things such as lost assets (i.e. any assets marked as lost, it would add up this value and display it). Or a full 'financials' page.

Also, it would be nice if the reporting section could have graphs etc... I appreciate that this would be a lot of work so feel free to tell me to p*ss off if you dont think this is a good idea, or you dont have the time :)

Sorry for all the requests, I'm just thinking out-loud before I show it to my boss :)

**Comment by smaloba1** [comment]
Hello Snipe, It would really be great to have a display of the total value of assets right on the dashboard. Is there a way the models can be twerked in order to achieve this? Like in the image below
![capture](https://user-images.githubusercontent.com/12434671/29306474-7c76b474-81a6-11e7-81a5-c43ecf2e0fa6.JPG)
