### ISSUE TITLE
Snipe-IT Installation Issues

### ISSUE THREAD

**Issue by Karnauday** [snipe/snipe-it#3977]
Hello 
I am following all steps while installing Snipe-IT. 
Key has been generated and updated on .env file. 
But I am not able to go "Pre-flight" page. It's saying "The page can't be displayed". 

DNS name:assets.portal.local
port:8080
HTTP
All database setting is good.

- Version of Snipe-IT  --v4.0-beta5
- Windows Server 2012--WAMP stack
-  install Snipe-IT--manual installation

Can someone help me out. Will highly appreciate.
Thanks

**Comment by snipe** [comment]
Sounds like you need to set up DNS for your instance. DNS is what tells a computer that `foo.blah.com` should point to a specific IP address. 

This is a networking issue, not a Snipe-IT question. I've included a few basic suggestions below, but If you're still stuck, you can try googling "Setting up DNS" and try to narrow it down based on your needs.

Firstly, you can run Snipe-IT using just an IP address. Just make sure the `APP_URL` in your `.env` correctly reflects the IP address.

But if you want to access Snipe-IT through a name, instead of an IP address, it depends on what your environment is and what you're looking for.

### Snipe-IT accessed ONLY by YOUR computer... 

You can add a line in the `/etc/hosts` file of whatever computer on the network needs to access it that points whatever name you want to the IP. That would look something like this in your `/etc/hosts` file:

```
192.168.1.2 snipe-it.local
```

(assuming your Snipe-IT instance's IP is `192.168.1.2` and the name you want to use to access it is `snipe-it.local`.) 

### Snipe-IT accessible to ONLY those in your internal network...

For example, if you're running Snipe-IT on a private, internal IP that cannot be reached outside of your network, contact your network administrator and ask them to set up DNS for the IP of your instance. 

### Snipe-IT accessible to the entire internet

You'll need to make sure the IP address for your instance is accessible outside of your network. (For example, IP addresses that start with `127.0.*.*` or `192.168.1.*` are internal and cannot be accessed outside of the network they live on.)

If the IP address is an externally facing IP address and you want to use something like `assets.mycompany.com`, you'll need to have whoever manages the domain name for `mycompany.com` set up an A record pointing `assets.mycompany.com` to your Snipe-IT external IP address.
