### ISSUE TITLE
LDAP Sync - CLI vs GUI

### ISSUE THREAD

**Issue by rwwest7** [snipe/snipe-it#4127]
#### Expected Behavior (or desired behavior if a feature request)

I expect the "php artisan snipeit:ldap-sync --location_id=1 --summary" and the GUI sync to do the same thing.
-----

#### Actual Behavior

The GUI sync reads the "LDAP Search OU" setting and only pulls that OU into the Location.

The "php artisan snipeit:ldap-sync --location_id=1 --summary" sync ignores the "LDAP Search OU" setting and instead dumps everyone into the "Location 1".

-----

#### Please confirm you have done the following before posting your bug report:

- [Y] I have enabled debug mode 
- [Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Fresh
- Version of Snipe-IT you're running? 4
- Version of PHP you're running - 7.1
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on - CentOS 6 / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No Errors

- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> Version of Snipe-IT you're running? 4

Could you be more specific please?

**Comment by rwwest7** [comment]
v4.0.6 build 47

The way the sync works in the gui is AWESOME!

Was excited about making cron jobs, but the CLI seems to ignore what's in Settings...Locations...LDAP Search OU.

**Comment by rwwest7** [comment]
I've been doing testing and this is how it appears to work for me:

GUI Sync of a location: Reads the "LDAP Search OU" setting and only pulls in users from that OU, adds them to the Location.

CLI Sync of a location: Ignores the "LDAP Search OU" setting, BUT pulls in users matching it and all other accounts not matching another locations "LDAP Search OU" setting.

So the CLI doesn't mess with other locations, but sucks in every single account not already synced. I have about 10,000 accounts in my AD and really need to be able to only sync the users I want to sync, while allowing anyone to log in on demand.

Is it possilbe to have two base OU's in LDAP settings?

**Comment by richardhofman6** [comment]
> GUI Sync of a location: Reads the "LDAP Search OU" setting and only pulls in users from that OU, adds them to the Location.

You definitely shouldn't be seeing that behaviour... Looking at both the CLI and GUI implementation, it looks like the "location" parameter has the same effect in both. The effect is that any user who *does not* fall into a location's specified OU, will be assigned the group that you select in the GUI (or specify via `--location[-id]`).

For example, if you had locations `New York` with LDAP Search OU `OU=NY,OU=Users,DC=example,DC=com`, and `Chicago` with LDAP Search OU `OU=IL,OU=Users,DC=example,DC=com`, then you specified location "USA" in the location, all users not in the first two OUs would be placed in "USA".

In terms of specifying a specific search OU, there is actually already a parameter for that within the code for LDAP user import, but it isn't exposed anywhere that I can see! It's possible to make a CLI option so that you could do something like: `$ php artisan snipe:ldap-sync --base-dn='OU=NY,OU=Users,DC=example,DC=com' --summary`. The effect would be that (as long as you've set the LDAP Search OU for your location), you don't even need to specify the location - it'll just only search that subtree of your domain, and add matching users it *does* find to the correct location.

If you reckon that'd be useful I'm happy to contribute it!

**Comment by rwwest7** [comment]
You are correct! I did some more testing and what you describe is exactly what happens.

It's weird though because I swear I imported one location at a time and the only location that updated was the one I picked, but I just blew away the users table and tested it. Works like you say.

Something like this: "$ php artisan snipe:ldap-sync --base-dn='OU=NY,OU=Users,DC=example,DC=com' --summary" would be awesome for doing cron CLI imports!!

**Comment by rwwest7** [comment]
FWIW, I did more testing. A GUI sync only imported accounts matching locations. A CLI sync import every account matching the LDAP filter.

The CLI sync pulled in 60 additional users after running multiple GUI syncs. Something is definitely different about the two.

**Comment by richardhofman6** [comment]
Sorry for the long wait, I somehow lost this issue! I've just created a PR for the discussed `--base_dn` argument.

**Comment by snipe** [comment]
PR is merged - thanks!
