### ISSUE TITLE
list all filter problem

### ISSUE THREAD

**Issue by Pintu206** [snipe/snipe-it#4156]
list all -> laptop 

only laptops shall come

(what you expect to happen goes here)

all the assets of similar name shall get populated

#### Actual Behavior

all assets are getting populated instead of just required
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by it-world** [comment]
I found the error myself, this errors where caused by mod_security 

example:
##############################

--60cd8274-H--
Message: JSON parser error: parse error: premature EOF

Message: Access denied with code 400 (phase 2). Match of "eq 0" against "REQBODY_ERROR" required. [file "/usr/local/etc/modsecurity/modsecurity.conf"] [line "60"] [id "200002"] [msg "Failed to parse request body."] [data "JSON parser err
or: parse error: premature EOF\x0a"] [severity "CRITICAL"]
Action: Intercepted (phase 2)
Stopwatch: 1507197929571738 2895 (- - -)
Stopwatch2: 1507197929571738 2895; combined=64, p1=50, p2=8, p3=0, p4=0, p5=5, sr=0, sw=1, l=0, gc=0
Producer: ModSecurity for Apache/2.9.1 (http://www.modsecurity.org/).
Server: Apache
Engine-Mode: "ENABLED"
####################################

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues
