### ISSUE TITLE
restoring assets and user names of previous deployement 

### ISSUE THREAD

**Issue by saupher** [snipe/snipe-it#4171]
#### Expected Behavior (or desired behavior if a feature request)

I backed up all the information from our previous snipe-it deployment and it is now sitting in a .sql file. I have no idea how to import all this data onto our new Ubuntu box, I have snipe it running and functioning but no clue at all how to get the old database up onto the new. I have been searching and scouring and nothing has worked so far. please send help! sos!
-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
If you had bothered to answer the questions in the issue template, I could give you a more specific answer, but I don't know what OS you're running this on. Google `mysql import sql file <OS>` and you should find some tutorials that explain how to import a SQL file into an existing database. Make sure you run `php artisan migrate` after you've imported your data though, to pick up any migrations.

**Comment by saupher** [comment]
wow most unfriendly worst customer expierence I have gotten online ever. congratulations. I completed all of that and its not working for me.  Il make sure to leave a great review for snipe it no worries.

**Comment by snipe** [comment]
Seriously? You ignored the questions that we literally need to be able to help you. Completely ignored them. Without knowing what OS you're running this on, I can't tell you how to import a SQL file - which frankly is outside the scope of support for Snipe-IT in the first place. That said, when people give us the info we need (and that we ask for, very explicitly), we try to help folks with basic server admin stuff. It is a google-able question, but we still usually try to help, when people give us the information we need. We literally say "Please do not post an issue without answering the related questions above." in the issue template because we CANNOT help you without that info.

And, rather than accusing us of bad customer service you could have apologized for not giving us the info we need, actually provided it, and we could still have helped you. 

You're entitled to a full refund of every cent you paid for Snipe-IT. 

We're still willing to help you, but we need more information - as stated, multiple times.

**Comment by saupher** [comment]
I just find you very rude, I supplied the OS I was using and other information you immediately close the ticket and move on. Just saying this is the worst experience I have had with a company and I was shocked to see you are a higher up in the company.  That's fine if that's your business model but its a very poor one.

**Comment by snipe** [comment]
@saupher Can you imagine how frustrating it must be to have people open tickets all day long, and completely ignore the list of questions you ask them? Imagine how aggravating it must be to offer something to for free, support it for free, and then have people not follow the most basic of instructions. We make it quite clear that we need ALL of the info in that list in order to help people. 

Have a shred of empathy for the people on the other end of this GH repo. Yes, I am a "higher up". This is my software. I made it. And I spend countless hours every day trying to help people who for some reason don't feel the need to answer the simple questions we for the ticket. Do you have any idea how much time I end up wasting, literally just asking people to answer the questions they ignored or deleted to open their issue? 

We do this because we give a shit, and when people flat-out ignore us when we're *trying* to help them, it can be enormously frustrating. We care enough to tell you what we need from our users and try to help them through it, and we expect that you care enough to answer our questions so we can help you. For free. 

As I have said before, we are still willing to help you, but you need to give us more information. For example, what was the result of you importing the SQL? What are the issues you're still encountering?

**Comment by saupher** [comment]
I was trying to explain the problem, I used the Ubuntu install script to get it up and running, I exported our database from our  snipe-it  account. I then got a file that is a .sql file, I was just explaining I have no idea what this is , I never do any web dev stuff or hosting of websites. I did googling and looked into this issue and cannot figure out where the database is that I need to overwrite with the one I exported from the website.  I tried to run the commands but they are generic. Example database_name , what is that supposed to be the .sql file I exported? I don't know where these files resides and the commands always fail out because I'm lacking the correct paths and names.   I am just at a loss and I did the research and tried all sorts of combinations of commands and passwords and flags with no success.  I am on Ubuntu 16.04 and I used the set up script to get it going, not sure what else to provide :(

**Comment by snipe** [comment]
The database name will be whatever you've got as your `DB_NAME` in your working Snipe-IT .env file.

You'll have to get the backed up SQL file onto the ubuntu box somehow.

Once it's on the box, 

> mysql -u <username> -p <databasename> < </path/to/snipe-it-filename.sql>

**Comment by saupher** [comment]
which one is the snipe-it env file? 
![image](https://user-images.githubusercontent.com/32580402/32020781-252dab6a-b986-11e7-98dc-4613d71b3cc4.png)

**Comment by saupher** [comment]
ok this should have all the information,  what am I missing here?  thank you for your time I really appreciate it
![image](https://user-images.githubusercontent.com/32580402/32064108-ce724490-ba2d-11e7-9939-2511935ff187.png)

**Comment by saupher** [comment]
actually I was able to get it working, thanks anyway
