### ISSUE TITLE
Feature Request: Acknowledge Minimum Quantity Levels Alert

### ISSUE THREAD

**Issue by gwal86** [snipe/snipe-it#4316]
#### Expected Behavior (or desired behavior if a feature request)

If an accessory has reached the minimum quantity level, an alert is displayed under the flag.  It would be nice to have the ability to clear these alerts as needed.  This would ensure that I am paying attention to the alerts instead of ignoring them because I can't clear/acknowledge the alert.

-----

#### Actual Behavior

Example:

I have purchased one display port adapter.  Upon receiving the item, I then check it out to a user.  The alert is triggered that this accessory is below or almost below the minimum quantity, but remains in the alert section.  As time goes on I foresee the number of alerts growing, and eventually I stop looking at them because there are so many.

-----
![minimumquantityalert](https://user-images.githubusercontent.com/16780835/32021676-00687104-b9a2-11e7-98d7-bb169f61c824.PNG)

**Comment by morgs** [comment]
I care about this too!

**Comment by amdow** [comment]
We care about this too. Admin users ignore the alerts for quantity levels because they never go away. For example we might have a minimum of 2 for one consumable and 5 in stock. It will always be "almost below minimum quantity". We're sitting at 14 now (screenshot attached).

![chrome_2018-10-01_15-29-04](https://user-images.githubusercontent.com/28748212/46271254-18b04300-c58f-11e8-9137-c2930cc3db93.png)
