### ISSUE TITLE
Feature Request: multi-company access without admin

### ISSUE THREAD

**Issue by Jhamende** [snipe/snipe-it#4386]
Dears,

It's just a suggestion but it would be great to assign people to be able to manage the assets for different companies without having full admin access (admin settings). 
Actually people are only able to manage the assets of the 1 company they are assigned to. 
Only Super admin can access assets of all companies. 

Thanks in advance
Jonathan H.

**Comment by ebonweaver** [comment]
Throwing in a me too here.  The new permissions are great except they are still useless for my inventory manager.  I have to make him super admin because otherwise he can't see the list of companies in the drop down when making an asset, it says "results could not be loaded".  This would be fixed for us if the new "Departments" field was actually available for assets.  As is we use Companies for departments because Departments didn't exist until now, but since they still aren't available anywhere but People it's not useful and we can't migrate fields (as I'd like to).

**Comment by ebonweaver** [comment]
Ok Stalebot, since this is still a problem, and it was marked feature request by the chief, how about you and your wontfix tag go back in the closet?

**Comment by snipe** [comment]
It's not a "problem", it's a feature request - and it's not one we'll be tackling any time soon.
