### ISSUE TITLE
Request function not working

### ISSUE THREAD

**Issue by victoriapak** [snipe/snipe-it#4408]
#### Expected Behavior (or desired behavior if a feature request)

click the request button and be able to request an asset from the Requestable Assets screen

-----

#### Actual Behavior

the color changes on the button, but no action is occurring

-----
RE: /tickets/3700

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? upgrade
- Version of Snipe-IT you're running v4.1.3
- Version of PHP you're running 
- Version of MySQL/MariaDB you're running 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by the-r0cket06** [comment]
#### Expected Behavior (or desired behavior if a feature request)
**Click the request button to request an asset.**

-----

#### Actual Behavior

**Click the button and nothing happens.**

-----

#### Please confirm you have done the following before posting your bug report:

- [**Yes**] I have enabled debug mode 
- [**Yes**] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Upgrade**
- Version of Snipe-IT you're running? **v4.1.4. Also occurred on v4.1.3**
- Version of PHP you're running? **5.6.32**
- Version of MySQL/MariaDB you're running?  **5.5.51-38.1**
- What OS and web server you're running Snipe-IT on? **Ubuntu 16.04/Apache2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)? **Git**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error? **/account/requestable-assets**
- If a stacktrace is provided in the error, include that too. [stacktrace-snipeit-4408.txt](https://github.com/snipe/snipe-it/files/1479616/stacktrace-snipeit-4408.txt)
- Any errors that appear in your browser's error console? **None**
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. **Yes**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. **Nothing**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Everything else is working**
- Indicate whether or not you've manually edited any data directly in the database? **Nope**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help
