### ISSUE TITLE
Generate labels from "view asset" page

### ISSUE THREAD

**Issue by epiepenburg** [snipe/snipe-it#4416]
#### Expected Behavior (or desired behavior if a feature request)

It would be nice if we could generate a label from the view asset page. It would be one less step when editing an asset's information. We then have to back out to the "all assets" or the assets' status (ready to deploy, etc.) page.

**Comment by chrstmnn** [comment]
+1

**Comment by jpsv** [comment]
I'd like this. Almost made a new topic:

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.15 build 4011
 - OS: Debian
 - Web Server: Apache
 - PHP Version - 7.1.28-1

**Is your feature request related to a problem? Please describe.**
Machines with existing labels allow me to go directly to the "View Asset" page when using the "Lookup by Asset Tag" field. I am swapping labels as I go, so in order to generate a single label for a single asset, I need to go back to the list view. From the "View Asset"page, click counts are as such:
* 1 click to go to the list
* 6 keystrokes to filter for the Asset
* 3 clicks for the Generate Label action to occur (Dropdown, select, "Go")

**Describe the solution you'd like**
A button that will automatically generate the label on the View Asset page, so that the click count is reduced to two.

**Describe alternatives you've considered**
A standalone "printer" icon near the page title would reduce click count to one, but, the "Actions" dropdown is ideal, I imagine, for maintenance purposes.

**Comment by snipe** [comment]
This is a duplicate of #3088
