### ISSUE TITLE
New Install, Error 500 on Preflight

### ISSUE THREAD

**Issue by GiantKiwi** [snipe/snipe-it#4497]
#### Expected Behavior (or desired behavior if a feature request)
Load preflight page
-----

#### Actual Behavior

Error 500
-----

#### Please confirm you have done the following before posting your bug report:

- [*] I have enabled debug mode 
- [*] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Fresh Install
- Version of Snipe-IT you're running - 4.1.5
- Version of PHP you're running - 7.1.1
- Version of MySQL/MariaDB you're running - MySQL5.5.58-0ubuntu0.14.04.1
- What OS and web server you're running Snipe-IT on - Ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - n/a, no error given
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - what would be the domain root ie domain.com which as required is pointed at /public/ directory
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - Error 500
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. - Not repeatable
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

Apache Error Logs reference this:

PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /var/www/html/computerassets/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 444

- Include what you've done so far in the installation, and if you got any error messages along the way. - was about to begin 'pre-flight & setup' segment in the docs.

- Indicate whether or not you've manually edited any data directly in the database

Nothing has been touched 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
That error is caused by the [splat operator](https://wiki.php.net/rfc/argument_unpacking), seen when using a version of PHP < 5.6.4 Please check that the version of PHP you're using on the cli is the same as the version you're using for the web server, and that your web server is actually using the correct version of PHP.

https://laracasts.com/discuss/channels/laravel/parse-error-syntax-error-unexpected-expecting-or-variable-t-variable-in-pathsitevendorlaravelframeworksrcilluminatefoundationhelpersphp-on-line-475
https://laracasts.com/discuss/channels/laravel/syntax-error-unexpected-expecting-or-variable-t-variable

**Comment by GiantKiwi** [comment]
Well, seeing as i disabled the PHP5 module on the server in question 6 months ago, and nothing else has any such problem, that's not the issue.

**Comment by snipe** [comment]
Again, see the links I pasted. It is absolutely a PHP version issue/webserver config issue. The splat operator was introduced after 5.6.4, and that error is what you're seeing. There must be a module (cli or web server) leftover that's causing the issue.

**Comment by GiantKiwi** [comment]
Seeing as other Laravel applications have no problems running on this server, coupled with the screwy way outgoing mail has been setup, we won't be using it. I've read through a lot of the other support requests, and you just sound like a broken record blaming server configuration almost every time.

**Comment by snipe** [comment]
> Seeing as other Laravel applications have no problems running on this server

Laravel doesn't use semver, so what looks like small point releases can bring big dependency changes. 

- Laravel 4.2 = PHP >= 5.4
- Laravel 5.2 = PHP >= 5.5.9
- Laravel 5.3 = PHP >= 5.6.4

So just because other Laravel apps run on the server doesn't actually mean much unless they're also using Laravel 5.4.29 like we are.

> and you just sound like a broken record blaming server configuration almost every time

I'm sure you're [capable of Googling](https://www.google.com/search?source=hp&ei=gUgVWu_gE-LS0gLO5IGwBQ&q=PHP+Parse+error%3A+syntax+error%2C+unexpected+%27.%27%2C+expecting+%27%26%27+or+variable+%28T_VARIABLE&oq=PHP+Parse+error%3A+syntax+error%2C+unexpected+%27.%27%2C+expecting+%27%26%27+or+variable+%28T_VARIABLE&gs_l=psy-ab.3..35i39k1j0.922.922.0.1587.3.1.0.0.0.0.494.494.4-1.1.0....0...1.2.64.psy-ab..2.1.494.0...0.tWHhmooIeFg) just like we are. Google that error (or check our Common Issues and/or past issues). 

If you can find ANY other explanation other than PHP version, we would *love* to know about it. Literally every single time a user has that issue, they're running the wrong version of PHP, even if they don't realize it - with the single exception of [the link I pasted for you](https://laracasts.com/discuss/channels/laravel/syntax-error-unexpected-expecting-or-variable-t-variable/replies/192852) where there was an nginx config requirement. You never actually told us what web server you were running (Apache v Nginx), despite us asking you in the issue template, so we weren't able to narrow it down to a potential Nginx issue. But we *still* tried to point you in the right direction by way of helpful links.

If there is another explanation, we'd be thrilled to update our docs - but every single time we've encountered it, it's a PHP version. Sometimes users are confused because their php-cli is running a different version than their Apache module/php-fpm, but it has always come down to their PHP version.

You're certainly welcome not to run it, but you don't need to be rude about it.
