### ISSUE TITLE
Feature request: Room Numbers

### ISSUE THREAD

**Issue by wisdude** [snipe/snipe-it#4539]
Feature request: It would be nice to have Room Numbers and nested them under locations.   Along with assigning assets to the room numbers and making users owners of the room number.

We have a high turnover of staff, and if we could change owners of the rooms, it could save us some time.

The current workaround is to create a custom field for room numbers and bulk change the "Checked Out To" every time there is a turnover.

**Comment by snipe** [comment]
Just create child locations using the room number.
![750ab57f-09c5-451b-8032-6ff5890850b6](https://user-images.githubusercontent.com/197404/33387060-2c64620e-d4e1-11e7-857f-04d804309b4b.jpeg)

**Comment by matthttam** [comment]
I can create a new issue if need be but this issue is exactly what I would put. No, creating a child location for room numbers is not a good solution. Location Name must be unique. We have 11 locations and each have between 10 and 100 rooms. On top of that some rooms are named generically like 'cafe' or 'front office'. This prevents us from creating child locations for every location since the name will collide at multiple sites.

There really should be a "Room" metadata. Rooms would be their own setting and would be assigned to a location. Then assets could be assigned to a location, then a room at that location, and a person if need be.

When importing assets a Room field would create a new room if that room doesn't exist for the location. Room would be optional.

For now there really isn't a good way besides using a custom field.
