### ISSUE TITLE
Can't bulk edit and remove users location on People page

### ISSUE THREAD

**Issue by Gelob** [snipe/snipe-it#4583]
#### Expected Behavior (or desired behavior if a feature request)

I want to remove the location assignment for multiple people. I select the checkbox for all of them and then click Bulk Edit and click Go. On that page I click Clear Selection which shows as my selected choice and I click save. Then the users location is cleared.

-----

#### Actual Behavior

I want to remove the location assignment for multiple people. I select the checkbox for all of them and then click Bulk Edit and click Go. On that page I click Clear Selection on the Location dropdown but it doesn't ever appear to select properly and stays on Select a Location. If I click Save no change is made to the users location assignment.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh
- Version of Snipe-IT you're running 4.1.7 - build 3031 (master)
- Version of PHP you're running PHP 5.6.25
- Version of MySQL/MariaDB you're running 5.5.56-2
- What OS and web server you're running Snipe-IT on CentOS 7 & NGINX
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error /users (people) and Bulk Edit page.
- If a stacktrace is provided in the error, include that too. N/A
- Any errors that appear in your browser's error console. N/A
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. Yes it is reproducible in the online demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. N/A
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by MSTigers** [comment]
This is also the same for device locations. I incorrectly bulk edited a location on several devices and when trying to remove them. Version v4.1.6


Scenario: I accidentally added (via bulk edit) several devices to an incorrect location. They were reported to me as 255-279 when really it was 1255-1279. Went to correct my edits on 255-279 and move them back to pending and to clear device's default location (as 255-279 have not yet been placed/verified so don't have a location.) until I was ready to work on those. Problem exactly the same as above.

If I individually edit each asset, I have no problem selecting "Clear Selection" as a savable edit. Bulk-edit will not allow it. I thought perhaps if I trick it since it appears blank (assumption: blank means will not make any changes to that field), that if I added a temp location just during selection then clicked "Clear Selection" it would behave similarly to the individual edit, but that was not the case.

**Comment by marwinism** [comment]
I feel like this should be a feature. or the import function should be reworked. I importet 2k users into a location. I don't want to do that all over again.
