### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by cbranham23** [snipe/snipe-it#459]
Can you open up the search function to be able to search for any criteria that may be entered in when creating an asset? Especially a serial number.

**Comment by snipe** [comment]
@cbranham23 Serial numbers are already searchable.
![screen shot 2015-01-22 at 1 47 25 pm](https://cloud.githubusercontent.com/assets/197404/5865303/479a50f8-a23d-11e4-8448-921566f8d241.png)
![screen shot 2015-01-22 at 1 47 33 pm](https://cloud.githubusercontent.com/assets/197404/5865305/47b11bd0-a23d-11e4-8a8e-f6d4b8c21a2d.png)

**Comment by cbranham23** [comment]
Alright great! Maybe I typed the SN in incorrectly when I tried it.

Thank you!

Clare Branham \  *Operations Ninja*

*Fearless Solutions*
5520 Research Park Drive \ Suite 100 \ Baltimore, MD 21228
cell (443) 216-9602 \ fax (410) 779-3706 \ tel (410) 394-9600
<bhalteman@fearsol.com>cbranham@fearsol.com \ www.fearlesssolutions.com
*HUBZone & 8(a) certified*

**Comment by snipe** [comment]
@cbranham23 - I removed your email sig from your last comment so the universe doesn't have your phone number. (That happens with reply via email.)

I'm going to leave this open as an enhancement, since searching on more fields (especially onces that are not visible in the display) is a reasonable (and planned) feature.

**Comment by cbranham23** [comment]
Awesome! Thanks for looking out!

Clare Branham

**Comment by snipe** [comment]
My pleasure :)
