### ISSUE TITLE
Avery Label - 3474

### ISSUE THREAD

**Issue by schmidiij** [snipe/snipe-it#4595]
#### Expected Behavior (or desired behavior if a feature request)

We use the Avery 3474 Labels. But i can't find a working solution. so, i ask you.
Also i have problem with "zoll", we us cm
Have some a solution for Avery 3474
Thanks for your help!

-----

#### Actual Behavior

my config doesn't want work

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

Version of Snipe-IT you're running
4.1.6

Version of PHP you're running
7.1.9

Version of MySQL/MariaDB you're running
MySQL - 5.7.19

What OS and web server you're running Snipe-IT on
Windows Server 2012 R2 - WAMP64

**Comment by asuman1179** [comment]
I spent about half the day trying to get the Avery 61533 to work with the built in printing of Snipeit but had no luck.  What I ended up doing was exporting the asset data to a CSV from Snipeit making sure to put in Hardwareid and Asset Tag.  I updated the ID field so that it would be the mapping to my website with the ID at the end and called it QR. (http://$yourdomain$/hardware/$IDVariable$)  Then I went to use the online avery printing program by importing the csv. It will allow you to import the QR code from the csv file and you will be all set.  It also gives you more options how you want to customize the labels also!

One request I would have it to be able to export in the csv the audit data information.  

Thanks for a great product.

**Comment by chrstmnn** [comment]
Hi,

can you tell me how to export the hardware id or do you enter the id manually? I also use your way, but with asset tag only I cannot generate a QR code...

**Comment by chrstmnn** [comment]
Just took a look at the .label file used by DYMO. It´s just an XML-File.
Would be nice, if we could download such an .label file for every asset due to problems printing labels using the label generator...

**Comment by chrstmnn** [comment]
And found another version for generating QR-Codes without hardware id:
https://§yourDomain$/hardware/bytag?assetTag=

**Comment by asuman1179** [comment]
You just have to add hardware ID from the column selector on the page and download the CSV.  I am doing it that way since that is how the current QR codes are working it should never go away since that would be a breaking change.  I guess the good thing is you could always use URL rewrites if something did change on the webserver side.  See below the harware ID
![capturehardwareid](https://user-images.githubusercontent.com/6841555/33999140-e664a828-e0a6-11e7-8b97-082d2004ea4c.PNG)

It would be nice to do an xml export to the Dymo so that you can do one off type prints.
