### ISSUE TITLE
[Feature Request] Ability to specify fields for label Printing

### ISSUE THREAD

**Issue by kagashe** [snipe/snipe-it#4610]
#### Expected Behavior (or desired behavior if a feature request)

Possibly tick boxes in the label setup page that lets you choose the fields that are shown on the label. Would be amazing to have custom fields as well.
-----

#### Actual Behavior

Very basic choices of label composition.

-----

**Comment by Zhaobab** [comment]
It would also be awesome to give the possiblity to add an image (like company's logo) :)

**Comment by lucmilland** [comment]
Hi there,
I just made a test to implement the ability to add the company logo to the labels. 
Since I do not have the time to test it fully, I only can tell that it works for my use case and that it should meet most use cases by playing with the labels size settings.

Impacted files are:
* app/Http/Controllers/SettingsController.php
* resources/lang/en/general.php
* resources/lang/fr/general.php
* resources/views/hardware/labels.blade.php
* resources/views/settings/labels.blade.php

And I had to make a migration to record the new setting to the database:
database/migrations/2018_02_22_093620_labels_display_company_logo.php

If this sounds like a good approach to you, I will be happy to publish a pull request, knowing that I won't be able to test it further. Anyway, this is a very light patch, it is very unlikely that I broke something elsewhere.

By the way, thanks for this awesome app and the very good documentation. I am not a php guy but I could find my way through the code easily and code the stuff in a couple of hours. Respect !

cheers,
Luc

**Comment by kagashe** [comment]
Any chance you would be willing to add the custom fields to the labels as well, would save me a bucket load of time, as I have these printers I manage that have 3 different serial numbers that need to be tracked but they don't come stick on the printer, currently making custom labels for each printer.
