### ISSUE TITLE
Feature request: print QRcode for assets

### ISSUE THREAD

**Issue by ledzgio** [snipe/snipe-it#464]
Print QRcodes would be a great but simple to implement feature.

**Comment by snipe** [comment]
Hi @ledzgio - can you explain more what you're looking for here?

**Comment by danielheene** [comment]
Hey @snipe i would appreciate this feature too! 
or even if its possible to add the asset id as written words to the QR image for printing them because sometimes it's faster to read the id than scanning it.

**Comment by snipe** [comment]
@danielheene Can you tell me more about your use case here? Are you looking to print a sheet of stickers with QR codes?

**Comment by kobie-chasehansen** [comment]
Atlassian had a nice implementation using QR codes, maybe something similar?

http://blogs.atlassian.com/2014/04/jira-asset-management-physical-implementation/

**Comment by danielheene** [comment]
@snipe Yes, i am looking forward to print the QR codes on stickers and put them on our mobile assets like notebooks. In this case it would be very helpful if you can also read the id directly from the sticker if you have no QR reader around you.

**Comment by snipe** [comment]
I assume you'd have some standardized label sheet to work from. I do worry that I'll have to accommodate a metric ass-load of sticker sizes and sheets.

**Comment by danielheene** [comment]
@snipe i don't even did it yet but i'm looking forward to do so in future. i just meant putting the asset id to the png file the system already provides. so you can pick the png file from the website and print it on stickers. but i didn't really think about optimized sizes and resolutions for special sticker sizes. then it should be my problem to look for an correct sticker size :)

**Comment by thedaftbadger** [comment]
@snipe just adding the asset number or serial number to the PNG would be ok like @danielheene mentioned

**Comment by snipe** [comment]
@thedaftbadger How is that different from what we already have? 

<img width="684" alt="screen shot 2015-08-05 at 1 38 09 pm" src="https://cloud.githubusercontent.com/assets/197404/9097250/46d20eee-3b77-11e5-9117-290c4c9ef2c6.png">

**Comment by thedaftbadger** [comment]
@snipe sorry only realised this after the comment earlier. They look informative ok.
Maybe for the future the ability to add a company logo or "Property of" custom text?

**Comment by snipe** [comment]
That's already an option in the settings.

<img width="696" alt="screen shot 2015-08-05 at 1 47 22 pm" src="https://cloud.githubusercontent.com/assets/197404/9097442/8772b4fc-3b78-11e5-9b58-2b02231d8146.png">

**Comment by mnlabs** [comment]
2.0 looks really nice! I'm on demo right now. How did you generate this sheet of QR codes 2 posts earlier? Thanks!

**Comment by snipe** [comment]
http://docs.snipeitapp.com/manual/labels.html

**Comment by mnlabs** [comment]
Ah, I missed that! Thank you. Great feauture. Although labels are not evenly spread on a page, they're squeezed more to the top. Is it a bug (which I should report?) or something you're aware of?

**Comment by snipe** [comment]
I don't actually know what you mean. The screenshot you saw was from the demo. If something looks differently for you, please provide screenshots.

**Comment by mnlabs** [comment]
Label generator works the same way as it is shown on your screenshot. The issue is that it's not compatible with "Avery 5027, 5026* and 8425 in portrait mode". Here's rough mocap:

![labels](https://cloud.githubusercontent.com/assets/12913971/9601190/49b30b7a-50a0-11e5-9b1a-dc53ed537bd0.png)

It doesn't fit on US Letter or A4. I don't think that this whole Avery thing is worldwide compatible. It looks like worldwide commercially available labels are made with A4 paper divisions in mind, something like this:

![110466766_333](https://cloud.githubusercontent.com/assets/12913971/9601385/6c627f88-50a1-11e5-98fa-525aeae40b08.jpg)

I know there's probably *a lot* of label sizes but do you think maybe we could get something more flexible? It is possible to just ask before label generation for paper size, label size and grid layout, then just scale QR/Bar coded to fit those constraints appropriately. It would be hell of a lot more useful for people who actually need to print those labels. Not to mention you could just print hundreds of them without any post-processing or save to pdf from web browser and print later.

**Comment by JochenLeppin** [comment]
Unfortunately, we can't use Snipe-IT because of this limitation, too. Will something like this be available soon?

**Comment by snipe** [comment]
@JochenLeppin v3 has more customizable options for labels. You're welcome to check out the demo. htttps://v3.snipeitapp.com

**Comment by mnlabs** [comment]
In version 3 it's finally doable! Thank you. It's a little bit cumbersome without presets (maybe we could provide particular settings with time?) but still a great improvement!

If we could just ask for a units switch box (i.e. millimeters vs inches), that would be most appreciated.

Little howto for others because of documentation differences between v2 and v3:
Settings -> Edit settings -> Labels
Menu -> Assets -> select assets -> top left drop-down menu -> Generate Labels -> Go

**Comment by jarbro** [comment]
Can you include a company logo on the labels?
