### ISSUE TITLE
Feature Request - List of Components checked out to Asset - Report

### ISSUE THREAD

**Issue by worthy92** [snipe/snipe-it#4650]
Please could there be an ability to to export/see all components that have been checked out to a particular Asset?

For example, I work in a school and we want to use this as follows:
1. Create each Classroom as an asset
2. Create different components such as chairs, tables, etc.
3. Check out x number of chairs and tables to the Asset (Classroom)
4. Then the Site Manager runs a report on an Asset (Classroom) and see what components (furniture) and quantity is meant to be in each one. Being able to run an audit that compares what Snipe-IT says  and that actual physical contents of the room.

This would be good in an IT environment - such as check out a power supply (for example) to a laptop asset and run a report that show the asset and the power supply as a checked out component to it.

Hope this makes sense.

Once again - keep up the fantastic work with Snipe-IT - it really is awesome!! 👍 💯

**Comment by worthy92** [comment]
Bump

**Comment by ebonweaver** [comment]
Just came looking for this same answer and see stalebot has once again killed a feature request with no response.  That bot is not helpful.
This is a critical feature for us as we need to see the components checked out to our assets.  For us the computer (asset) is the primary thing around which all other things rotate.  Because accessories are deficient in being able to check out to assets and only allow checkout to users (this should be fixed so it's an option just like with Licenses) we have to use components.  Either way, when we run a report, we need a column that lists all components (and accessories if those worked) and for that matter licenses checked out to an asset.  This is the only way lifecylce reporting actually works, if we can see all the items with a computer, so we know if they have dual displays and other peripherals.
From what I'm gathering, we've painted ourselves into  corner because Snipe can't actually give us this report?

**Comment by svhss** [comment]
It seems so basic function, is there any progress on it?

**Comment by snipe** [comment]
@svhss That's been available for a long time. https://demo.snipeitapp.com/hardware/3#components

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/3#components">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by svhss** [comment]
My bad, somehow I wanted a feature, and posted my frustration here.

What I actually want is a list with licenses and next to them who it is checked out to. Is it also a feature?

**Comment by snipe** [comment]
https://demo.snipeitapp.com/hardware/3#software
https://demo.snipeitapp.com/licenses/2#history

You'll find in open source that venting your frustrations on the very  people who give you software for free is not a winning strategy.

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/3#software">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/licenses/2#history">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by svhss** [comment]
I'm terribly sorry for acting out, and thank you for your help, I guess I did use the software maybe wrong? Because for each seat I made a new license. The features seemed better suited for my needs, because each "seat" use a different license key, also each seat needs to be canceled with a different ID if i need to.
