### ISSUE TITLE
locationPresenter custmize 

### ISSUE THREAD

**Issue by amarbhanu** [snipe/snipe-it#4653]
i did use.
Version v4.1.4 
windows
install.sh

Query:
I did add one column 'mySite' in locations table, API is working show my data in API but LocationPresenter.php have not got data. please suggest where will be modification

**Comment by snipe** [comment]
Be very careful about adding columns to the database - if we add stuff later, it could conflict, and you'll have to manage the differences moving forward. 

You'll need to edit the Locations API controller to select your new column, otherwise the presenter won't be able to access the value.

**Comment by amarbhanu** [comment]
I did Add column in API
LocationController.php
$array = [
...
....
'locations.country',
 'locations.mySite',
];
AND also in 
LocationTransformer.php

 'country' => e($location->country),
 'vmID' => e($location->mySite),

then AP have show my db value in mySite. but not show on my location list

**Comment by snipe** [comment]
What is `$array = []`?

**Comment by snipe** [comment]
In order to add a new column to Locations, you need to edit:

- `app/Http/Controllers/Api/LocationsController.php`
- `app/Http/Controllers/LocationsController.php`
- `Presenters/LocationsPresenter.php`
- `Transformers/LocationsTransformer.php`
- `resources/views/locations/index.blade.php`
- `resources/views/locations/view.blade.php`

**Comment by amarbhanu** [comment]
thanks. working

Also add in lang/en/general.php for display name
