### ISSUE TITLE
Feature Request - Show linked Assets within Asset-Page

### ISSUE THREAD

**Issue by kineese** [snipe/snipe-it#4705]
My current setup looks like this:

- Asset 0001 is a Desktop PC
- Asset 0002 a 16:9 Monitor
- Asset 0003 a 16:9 Monitor

When checking out, I got the option to select another asset as a deployment-target. 
What I did was:

- Asset 0001 deployed to user
- Asset 0002 deployed to Asset 0001
- Asset 0003 deployed to Asset 0001

When I open the data-sheet of Asset 0001 I can not see any links to connected Assets (0002 and 0003); I can only see the connection when I am on the Assets-Page (/hardware) or when looking into the data-sheet of Asset 0002 or Asset 0003.

Maybe my assumption that a Monitor is an Asset might be wrong. But I can not see any usecase where an Asset should be deployed to another Asset

**Comment by pako-pl** [comment]
We also use Assets in this way. We actually stopped using Components completely because Assets have a lot more useful fields (like selecting a Model) and have maintenance history (individual computers parts get maintaned too, for example SSD firmware upgrade). The only thing missing is an ability to view assets checked out to the asset being viewed (similar to the Components tab on the View Asset page).

**Comment by Cintel** [comment]
We use the same method and would also like to see the sub assets on the main asset view - Please add this feature.

**Comment by snipe** [comment]
Fixed on develop with e6259eb6e1b228bf6c7f9ba13cb9733aa92f8036
