### ISSUE TITLE
Feature Request - Allow Instantly Checking Out Assets from CheckIn Page

### ISSUE THREAD

**Issue by DannyHolyoake** [snipe/snipe-it#4719]
My workflow often involves checking an asset in and instantly checking it out to someone else.

To streamline this workflow, it would be great if the following were possible - 

On the Asset CheckIn page, when I set the status to 'Ready To Deploy', bring up the Checkout button and User/Location/Asset Search box. This way, I could simultaneously check in and check out an asset in one action.

Obviously this isn't a must-have or necessary in any way, and I don't know if others' workflows match mine.

**Comment by snazy2000** [comment]
+1 save so much time

**Comment by ckinsler** [comment]
I like the idea, as there are many times where we may need to bulk move assets from one user to another.

In my opinion, I'm not sure I'd mix that on the Checkin screen though.  Would it maybe make more sense to have an additional menu option for "Reassign Asset" that handles a check-in\check-out simultaneously?   Same thing for a "Bulk Reassign"?

Thoughts?

**Comment by cslucian** [comment]
I would like such a feature myself.!

I think the best workflow would be "Transfer" from one user to another.

**Comment by snipe** [comment]
Perhaps a good workflow might be a checkbox on the checkin screen, like "Checkout again", which would redirect the user to the checkout screen right after checking in if it's selected?

**Comment by lostmydog** [comment]
I think what the OP is asking is for the same functionality as creating a new asset. If you create a new asset and assign it a ready to deploy status, it brings up the ability to assign to user/asset/location. This would make the workflow much better for checking in an asset, because when you checkin you want to assign a status (re-image, storage, broken, active, etc) and at the same time reassign it.

**Comment by goludiaOH** [comment]
Agree! Really wish we had a transfer/re-assign option as our workflow also will frequently require us to move assets immediately from one person to the next.

I would also prefer it if only admins had the permissions to leave assets in the checked-in state.  For example any user who receives an asset can log in and transfer it to a coworker who needs it next. But any user could not check in and leave it checked in (effectively losing the asset to our tracking because now we have no idea who is holding it). Only a snipe admin can check in an asset whereby we take the asset from the employee and don't immediately transfer it to someone else.

**Comment by cslucian** [comment]
This would be a nice feature.

Maybe you can find a easy way to implement it. 
Maybe like this.

Actual behaivour 
when you are in a asset page and check in the item you are returned in to all assets page.

Desired behaivour
Mybe the process can return to the asset page so you can perform additional tasks

**Comment by bveina** [comment]
ive started using this to manage several university labs across multiple departments, the ability to bulk transfer a rooms' worth of equipment to a new custodian or location would be very useful to me. 

desired behavior: goto assets, select all the items i need to transfer,  in the edit dropdown box select reasign and choose the new location. checking every item in and then out again would be rough.

**Comment by bveina** [comment]
not for nothing, this is still important. but in the mean time i've written a collection python scripts that automates this through the web api. what would the rules/protocols for sharing the scripts ive put together to interface with the web api?

**Comment by snazy2000** [comment]
Yes its important

**Comment by bveina** [comment]
yes i would still like this feature

**Comment by captain-hack** [comment]
I know we can definitely still use this feature.

**Comment by bveina** [comment]
ive needed this feature for a while, but ive resorted to using the web api to accomplish most of what i need.  https://github.com/bveina/snipeIt-tools

**Comment by bveina** [comment]
Yes, still relevant for reasons outlined above.
