### ISSUE TITLE
Ready to deploy vs deployed

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#4761]
#### Expected Behavior (or desired behavior if a feature request)

Learned the hard way: Version 4.1.9 - Checkout, flag issue

(what you expect to happen goes here)
When checking out items, I'd expect that the item's status flag would automatically change to deployed. 
-----

#### Actual Behavior
If you edit an item the status flag never changes to deployed; you have to manually change this. If you don't it throws off reports and the "Assets By Status" graph on the dashboard. The available quantity is off because deployed items appears as "Ready To Deploy"

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by secure-77** [comment]
+1
Got the same problem. I understand that there is a difference between status and meta-status. But the dashboard is very confusing because it only shows the status (independent from meta-status) and there is no possibility to change the meta-status and the status in one step. 

I think the best solution is a feature to change the status automatically by changing the meta-status.
So:
e.g. creating two custom status "in use" and "ready".
checking out an asset will set the meta-status to "deployed" and also the status to "in use".
checking in an asset will set the meta-status to "ready to deploy" and also the status to "ready"

Then you have nothing to change on the meta-status logic and the dashboard / status views will work a little bit clearer.

**Comment by tbradsha** [comment]
The current behaviour, as mentioned by secure-77, is by design. I've collected the confusion at #4538.
