### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by peelman** [snipe/snipe-it#48]
Let somebody else handle password hashing and storage.

Might not be feasible with Sentry, I'm not familiar enough with it to know how flexible it is. Rudimentary research shows others have forked it to add support for LDAP with mixed results.

[phpipam](http://phpipam.net) uses adLDAP with great success (was the easiest AD integration I have ever experienced with a php app).

Awesome work so far! Let me dig in a little deeper and I hope to contribute and not just gripe about complicated stuff!

[This](https://github.com/ccovey/ldap-auth) might be another option.

**Comment by utsysadmin** [comment]
Any rough idea on a date to be implemented :)

**Comment by rp-tech** [comment]
+1 for LDAP can't wait for this feature!

**Comment by BHollowell** [comment]
Can we get an ETA on when this should be included? I'm very anxious for this.

**Comment by snipe** [comment]
I don't currently have an LDAP setup to be able to work on this. If anyone else does I'll gladly accept pull requests on it.

**Comment by snipe** [comment]
Test server here may work for anyone looking to work on this feature: http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/

**Comment by vabue** [comment]
Looking for this feature too.

**Comment by TheLilleorg** [comment]
Would love to see this feature rolled out. 

Tested it with sentry but found the configurations too unfamiliar to my liking. 
Found another plugin to try : http://packalyst.com/packages/package/wells/l4-ldap-ntlm

The setup was rather easy considering. 

My issue was I could see that snipe-IT was communicating with the server (had to remove the @ from the vendor package to work with my openldap setup) user was able to bind to the ldap server. 

Couldn't get further.

**Comment by rp-tech** [comment]
Call me crazy but have you guys ever considered partnering this with another FOSS project - check out OsTicket; I absolutely love their software and I am planning to use it alongside Snipe - if these 2 projects somehow worked together to create an integrated ticketing and asset management system, it would absolutely destroy the competition in many ways!

The reason I am bringing this up is because they have quite a mature development team over there, and their LDAP integration is already implemented and working well - perhaps they would be willing to share some of that information with another great FOSS team and help bring the cost of IT within reach for small providers!

**Comment by ippup** [comment]
hi, any word on when we can expect LDAP integration, this is the only thing stopping me from deploying snipeit

**Comment by brusch** [comment]
+ 1

**Comment by hughevans** [comment]
I notice both this and SAML are tagged for v3.0. I would contest that only SAML is required. Everyone is seemingly moving in that direction and it isn’t hard to set up an IdP that works with AD such as ADFS.

**Comment by snipe** [comment]
@hughevans - agreed

**Comment by misilot** [comment]
What about people that don't have AD, and just have LDAP?

**Comment by hughevans** [comment]
You could try [SimpleSAMLPHP](https://simplesamlphp.org/docs/stable/ldap:ldap).

**Comment by ESWBitto** [comment]
or this...
https://www.freeipa.org/page/Main_Page

**Comment by rp-tech** [comment]
I just wanted to bring this topic up in case anyone hasn't thought of it already - the benefits of LDAP stretches beyond a simple sign in option / user import.

One of the biggest benefits of LDAP is the ability to read AD user properties such as Office, Location, etc - not having to set any of those manually (because all of our users already have these fields filled in AD) would be a huge benefit in terms of managing the users in the system.

**Comment by rp-tech** [comment]
PS - earlier I had mentioned a suggestion to possibly design an integration with osTicket, an amazing open-source ticket system that I think would work very well with Snipe. They have a github repo as well - it turns out their LDAP is done through a plugin; check out Jared's code here:

https://github.com/osTicket/core-plugins/tree/develop/auth-ldap
