### ISSUE TITLE
 Error:  Backup failed because The dump process failed with exitcode 1 : General error : . 

### ISSUE THREAD

**Issue by woolleyGil** [snipe/snipe-it#4862]
#### Expected Behavior (or desired behavior if a feature request)

Trying to generate a backup using the backup feature in snipe 
-----

#### Actual Behavior

 Error:  Backup failed because The dump process failed with exitcode 1 : General error : . -----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode /Enabled 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)/I have read 

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Yes Fresh install 
- Version of Snipe-IT you're running, Listed below 
- Version of PHP you're running, Listed Below 

System Information
 
Snipe-IT version v4.1.4 build 173 (gba38b84)  
PHP Version 5.6.31 
Laravel Version 5.4.29  

- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by cepacs** [comment]
I am getting this issue also, just clicked Generate Backup logged in as admin.
![image](https://user-images.githubusercontent.com/36515590/36609410-bd75f18e-189a-11e8-8784-351e5bef765b.png)

Provide answers to these questions:
- Is this a fresh install or an upgrade? **Fresh**
- Version of Snipe-IT you're running **Version v4.1.11-pre - build 3299 (master)**
- Version of PHP you're running **PHP version: 7.1.14**
- Version of MySQL/MariaDB you're running **MySQL Server version: 5.7.21**
- What OS and web server you're running Snipe-IT on **Windows Server 2016 / IIS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **GIT**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error  **/admin/backups**

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in storage/logs and your webserver's logs.
**[2018-02-23 18:00:35] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 1 : General error :**
**[2018-02-23 18:00:35] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 1 : General error :**   

- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - **No**

**Comment by snipe** [comment]
Is your `DB_DUMP_PATH` in your .env set correctly?

**Comment by cepacs** [comment]
Looks like it isn't, I see..
DB_DUMP_PATH='/usr/bin'
Since I see this on the screen..
Backup files are located in: C:\inetpub\wwwroot\snipe-it\storage/app/backups
should it be DB_DUMP_PATH='/app/backups' or DB_DUMP_PATH='storage/app/backups' maybe?

Thanks

**Comment by snipe** [comment]
Per [the docs](https://snipe-it.readme.io/docs#section-required-database-settings), if you're on Windows:

Windows users should use something like: `'C:\\PROGRA~1\\MARIAD~1.0\\bin'` or `'C:\\PROGRA~1\\MARIAD~1.1\\bin'`, depending your version (note the double-slashes).
If you're not sure what the path is to mysqldump, linux users can run which mysqldump and Windows users can use cmd /c for %A in ("C:\Program Files\MariaDB 10.1\bin") do @echo %~sA via command line to reveal the path information.

**Comment by cepacs** [comment]
OK, I'll update the path and give it a try. 

Thanks for the info..

**Comment by cepacs** [comment]
I found the path (1) did the conversion to 8.3 format (2) and put it into the .env (3)
I cleared the cache (php artisan config:cache) and even rebooted the server but I still get that same error?

![image](https://user-images.githubusercontent.com/36515590/36619131-af090e44-18bb-11e8-8bae-001750409911.png)

I can't think of anything else I may be missing..
Thanks

**Comment by snipe** [comment]
Try double quotes  around the path and clear your config cache?

If you run `php artisan backup:run" via command line, what do you get?

**Comment by cepacs** [comment]
Nevermind.. I got it. :)

Because it is IIS I had to give the IIS_IUSRS Modify permissions to the C:\Windows\Temp folder.
![image](https://user-images.githubusercontent.com/36515590/36619429-c8701656-18bc-11e8-9b5d-23781383286e.png)

Thanks for the help.. https://github.com/snipe/snipe-it/issues/2454 :+1:

**Comment by cepacs** [comment]
Single or double quotes do seem to work for this parameter.

**Comment by sjlaird** [comment]
Sorry to say that I do not see anything in the Documentation about changing this setting on Windows. I had the same issue which has now been resolved by setting the DB_DUMP_PATH to my MariaDB BIN path in 8.3 format (with single quotes). I already had the permissions set on my Windows Temp folder as that is in the installation and upgrade instruction.

> 
DB_DUMP_PATH='C:\\PROGRA~1\\MARIAD~1.1\\bin'

**Comment by snipe** [comment]
We do cover that [in the documentation](https://snipe-it.readme.io/docs/configuration#section-required-database-settings).

<img width="781" alt="screen shot 2018-06-20 at 12 40 45 am" src="https://user-images.githubusercontent.com/197404/41644349-a395c490-7422-11e8-99f1-dcda46044b9f.png">

It's sometimes different on different systems, which is why we try to help folks understand how to find the correct path.

**Comment by sjlaird** [comment]
Hi, thanks for the reply. Just to clarify, I probably missed the addition of this feature as my original install was v2.

Anyway, after running in to the problem I searched the docs for 'backup' and the sections I was provided with did not mention this setting:

Admin/Backups --> https://snipe-it.readme.io/docs/backups
The above link also provides a link to - Configuring alerts and backups  
-> https://snipe-it.readme.io/docs/configuring-alerts-backups

The problem was never really an issue for me as I backup the DB and OS using other methods.

**Comment by brwa-ata** [comment]
I know I'm too late to ask, however, the backup is ok on local but I have an issue while I uploaded to online (cPanel) it gives me an error The dump process failed with exitcode 127 : Command not found : sh: /var/lib/mysql/mysqldump: No such file or directory

**Comment by farizazmi** [comment]
This Fixed for me. (XAMPP user)

change the path to:
> DB_DUMP_PATH='C:\xampp\mysql\bin'

**Comment by mpkr** [comment]
I back up successfully with the command `php artisan backup:run` but got the error "Error: Backup failed because The dump process failed with exitcode 1" when press Generate backup button on the web page. I already set the permission for IIS_IUSRS to Modify folder /storage/app/backups. Any ideas? 
Thank you

**Comment by pakorn269** [comment]
![1606113366628](https://user-images.githubusercontent.com/55436744/99934624-12920780-2d91-11eb-8d55-f57ceba11b0e.jpg)
 Help me please @snipe 
 Error: Backup failed because The dump process failed with exitcode 1 : General error : Access is denied. . #0 C:\inetpub\wwwroot\snipe-it\vendor\spatie\db-dumper\src\DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully() #1 C:\inetpub\wwwroot\snipe-it\vendor\spatie\db-dumper\src\Databases\MySql.php(190): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul() #2 C:\inetpub\wwwroot\snipe-it\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(250): Spatie\DbDumper\Databases\MySql->dumpToFile() #3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}() #4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Collection.php(638): array_map() #5 C:\inetpub\wwwroot\snipe-it\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(253): Illuminate\Support\Collection->map() #6 C:\inetpub\wwwroot\snipe-it\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(167): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases() #7 C:\inetpub\wwwroot\snipe-it\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(143): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest() #8 C:\inetpub\wwwroot\snipe-it\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(56): Spatie\Backup\Tasks\Backup\BackupJob->run() #9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle() #10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(32): call_user_func_array() #11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #12 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure() #13 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod() #14 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call() #15 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call() #16 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute() #17 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run() #18 C:\inetpub\wwwroot\snipe-it\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(16): Illuminate\Console\Command->run() #19 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(1001): Spatie\Backup\Commands\BaseCommand->run() #20 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(271): Symfony\Component\Console\Application->doRunCommand() #21 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(147): Symfony\Component\Console\Application->doRun() #22 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run() #23 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php(185): Illuminate\Console\Application->run() #24 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(273): Illuminate\Console\Application->call() #25 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Foundation\Console\Kernel->call() #26 C:\inetpub\wwwroot\snipe-it\app\Http\Controllers\SettingsController.php(1053): Illuminate\Support\Facades\Facade::__callStatic() #27 [internal function]: App\Http\Controllers\SettingsController->postBackups() #28 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array() #29 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction() #30 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch() #31 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController() #32 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(681): Illuminate\Routing\Route->run() #33 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}() #34 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckPermissions.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #35 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckPermissions->handle() #36 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #37 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle() #38 C:\inetpub\wwwroot\snipe-it\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #39 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle() #40 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #41 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle() #42 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #43 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckLocale->handle() #44 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #45 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle() #46 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #47 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle() #48 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #49 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle() #50 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #51 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(683): Illuminate\Pipeline\Pipeline->then() #52 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Router->runRouteWithinStack() #53 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(624): Illuminate\Routing\Router->runRoute() #54 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(613): Illuminate\Routing\Router->dispatchToRoute() #55 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Routing\Router->dispatch() #56 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() #57 C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #58 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle() #59 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #60 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle() #61 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #62 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #63 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #64 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle() #65 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #66 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle() #67 C:\inetpub\wwwroot\snipe-it\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #68 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle() #69 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #70 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle() #71 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #72 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle() #73 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #74 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle() #75 C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-cors\src\HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #76 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle() #77 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #78 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then() #79 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #80 C:\inetpub\wwwroot\snipe-it\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle() #81 {main} Backup failed because: The dump process failed with exitcode 1 : General error : Access is denied. .

**Comment by farizazmi** [comment]
> 'C:\xampp\mysql\bin'

This worked for me! Thanks

SnipeIT Version v5.0.11 - build 5695 (master)
OS: Windows

**Comment by varunnaresh1992** [comment]
As a MySQL DB user on Windows Server, i fixed similar error by:

Editing .env file:
`DB_DUMP_PATH='C:\PROGRA~1\MySQL\MYSQLS~1.0\bin'`

Ensuring Folder Permissions for IUSR & IIS_USRS for:
`C:\PROGRA~1\MySQL\MYSQLS~1.0\bin`
`C:\Windows\Temp`

and ofc, you need to give appropriate permissions for your website root folder.

Afterwards,
Add the following lines to your Web.Config file in root folder if it is not already there:

       
 `<security> `
            `<requestFiltering> `
              ` <fileExtensions> `
                   ` <add fileExtension=".zip" allowed="true" /> `
               ` </fileExtensions> `
              ` <requestLimits maxAllowedContentLength="104857600" /> `
            `</requestFiltering> `
       ` </security>`

 add the above code just before closing the `</system.webServer>`

Hope this helps,

Thanks,
Varun
