### ISSUE TITLE
No Page Content After Installation

### ISSUE THREAD

**Issue by mikethornac** [snipe/snipe-it#4871]
#### Expected Behavior (or desired behavior if a feature request)

I completed a fresh install of SnipeIT on a fresh Centos7 VM, using install.sh. Had a few hiccups along the way but got there in the end with success confirmations along the way. Followed the instructions to the letter. Apache is running fine, able to view a phpinfo page in my snipeit folder, DNS is resolving, the works. So far so good.

-----

#### Actual Behavior

 Get all the way to the end, launch a browser, point it to localhost/snipeit, and...nothing. Blank page. I checked the instructions for running SnipeIT in a subfolder, even though this VM will be running ONLY SnipeIT, made the adjustments, tried again. Double-verified that my httpd and .htaccess are configured to point to /var/www/html/snipeit/public. 

No errors are thrown, no logs are written, the browser reports nothing...not even a 40x message. It's like it loads *something* and returns OK, but there's just nothing there. 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

_- Is this a fresh install or an upgrade?_ 

Brand new fresh install. 

_- Version of Snipe-IT you're running_

v4.1.9

_- Version of PHP you're running_

v5.4.16

_- Version of MySQL/MariaDB you're running_

MariaDB v5.5.56

_- What OS and web server you're running Snipe-IT on_

CentOS 7 build 1611

_- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)_

Followed install.sh instructions exactly.

_- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error_

Debug turned on, no error reported.

_- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error_

I believe this would be the index.html launch page. 

_- If a stacktrace is provided in the error, include that too._

No stacktrace occurs.

_- Any errors that appear in your browser's error console._

Console is open, no errors reported.

_- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo._

Naturally, no.

_- Include any additional information you can find in `storage/logs` and your webserver's logs._

storage/logs contains nothing. 

_- Include what you've done so far in the installation, and if you got any error messages along the way._

Described above.

_- Indicate whether or not you've manually edited any data directly in the database_

No, I have not modified the database at all. 

Many thanks for any assistance you can provide.

**Comment by snipe** [comment]
Check the [permissions on your `storage` directory](https://snipe-it.readme.io/docs/common-issues#section-browser-redirects-to-login-but-page-is-blank-with-a-500-error). it and all subdirectories should be writable. Also [check and see if you're running SELinux](https://snipe-it.readme.io/docs/linuxosx#section-notes-on-selinux).

**Comment by snipe** [comment]
Try checking your webserver/PHP logs and see if anything useful is there. I'd be more curious about your PHP logs over the web server logs for this, but either might have something useful.

Also, make sure the `bootstrap` and `storage` directories __and__ their subdirectories are writable.

**Comment by mikethornac** [comment]
Haaaaa. Despite DEBUG being turned on, the php log led us down the breadcrumb trail indicating a php version too old.

Odd, considering I installed what I thought was the latest repo version, but ended up getting 5.4.1...

Will report back when updated.

**Comment by snipe** [comment]
Yeah, when you see a white page, that means something happened *above* the framework level, at the server or PHP level. It's far enough up the stack that the framework can't function properly, so it can't respect the debug settings in your .env. A low version of PHP or problematic directory permissions are usually the issue.

**Comment by jaltgen** [comment]
I seem to have a similar issue, got php 7.2 installed by the installer.sh on Ubuntu 18.04, went through the hoops of getting rid of it, installing php5.6 from PPA. Now when calling the index.php I get a required() failing when finding stuff in /usr/share/php/ . When checking, the required files are in /usr/share/php5.6 I'm at a loss.

**Comment by snipe** [comment]
@jaltgen can you provide more information please, specifically the exact error message.

**Comment by jaltgen** [comment]
@snipe thanks for the quick response. hm, it seemes I since solved the issue by --purge removing all components (apache2, php7, php5, mariadb) and re-running the installer script. currently I've gotten to the pre-flight page but mariadb keeps crashing upon startup (not an issue I reckon that is in the scope of your software). thanks for helping.

**Comment by snipe** [comment]
Is Maria crashing, or are you getting a db error on the screen? There is a known issue with Maria 10.2.7+

**Comment by senthil83p** [comment]
Configuration cache cleared!
Configuration cache cleared!
Configuration cached successfully!
2023-03-12 00:59:38,033 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-03-12 00:59:38,035 INFO supervisord started with pid 1
2023-03-12 00:59:39,039 INFO spawned: 'exit_on_any_fatal' with pid 43
2023-03-12 00:59:39,044 INFO spawned: 'apache' with pid 44
2023-03-12 00:59:39,048 INFO spawned: 'run_schedule' with pid 45
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
No scheduled commands are ready to run.
2023-03-12 00:59:40,332 INFO success: exit_on_any_fatal entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 00:59:40,333 INFO success: apache entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 00:59:40,333 INFO success: run_schedule entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2023-03-12T06:30:39+05:30] Running scheduled command: '/usr/bin/php7.4' 'artisan' auth:clear-resets > '/dev/null' 2>&1
No scheduled commands are ready to run.
No scheduled commands are ready to run.

**Comment by VewDev** [comment]
> Check the [permissions on your `storage` directory](https://snipe-it.readme.io/docs/common-issues#section-browser-redirects-to-login-but-page-is-blank-with-a-500-error). it and all subdirectories should be writable.

That's a dead link, the section it points to no longer exists.

**Comment by snipe** [comment]
@je-sendra Yes, because we made it its own section. https://snipe-it.readme.io/docs/debugging-permissions

You're commenting on an issue from 5 years ago. A search of our docs would have given you the new documentation.

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/debugging-permissions">Debugging Server Permissions</a></strong></div><div>❗️This article refers to web server file system permissions onlyIt does not address Snipe-IT application permissions.One of the most common issues folks newer to running web servers run into is how to manage the Linux/Windows/etc owners and groups of the Snipe-IT filesystem.As we mention many times ...</div></blockquote>
