### ISSUE TITLE
Feature Request : Doc Upload

### ISSUE THREAD

**Issue by tkinsella** [snipe/snipe-it#490]
Would be great to have a document upload function for license keys. The ability to upload a purchase document or the physical key card would be great!

**Comment by snipe** [comment]
I think this is a duplicate of #81.

**Comment by tkinsella** [comment]
I'm going to say yes it is. I was looking around and must of missed that one. Sorry! On the other hand, This would be great! I just started looking through the source code and if I get a solution implemented any time shortly, i'll upload. Thanks!

**Comment by snipe** [comment]
It's okay, it's kind of an old one, so it was pretty far down the list. It's not even that hard to implement, just having a hard time finding the time.

**Comment by tkinsella** [comment]
If you can point me at a few files to save time, I'd gladly help!

**Comment by snipe** [comment]
Heh, it's been a while, not sure I would trust that branch anymore. Laravel makes file uploads pretty easy, so then you just need to randomize the name (so no conflicts/overwriting) and add an auth filter to the route for viewing the file so that people not logged in or without permission cannot view the file. The files should be stored outside of the web root, so that URL fuzzers can't randomly guess filenames and start collecting license keys.

**Comment by snipe** [comment]
I've got this up on develop right now, if you want to give it quick run-through. 

![screen shot 2015-02-06 at 10 02 27 pm](https://cloud.githubusercontent.com/assets/197404/6091038/136fa6aa-ae4c-11e4-9c32-d78309cd6359.png)

Demo info if here if you want to try it on the demo site before messing with it. :)

**Comment by snipe** [comment]
Oops, forgot the link with the demo info :P http://snipeitapp.com/demo/

**Comment by snipe** [comment]
Completed as of release 1.2.3
