### ISSUE TITLE
Pre-release installed rather than production release

### ISSUE THREAD

**Issue by busy86** [snipe/snipe-it#4939]
#### Expected Behavior (or desired behavior if a feature request)

After installing from git, we received a pre-release version of 4.1. A php-upgrade has taken us to version v4.1.11-pre - build 3299 (master). How is it possible to revert this to a production release, rather than beta/test please?

-----

#### Actual Behavior

git clone install method resulted in a pre-release version of snipe-it

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode NO
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) YES

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **install and then upgrade, both resulted in a pre-release**
- Version of Snipe-IT you're running **v4.1.11-pre - build 329**
- Version of PHP you're running **7.0.7**
- Version of MySQL/MariaDB you're running **15.01**
- What OS and web server you're running Snipe-IT on **SUSE and Apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **git**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **N/A**
- If a stacktrace is provided in the error, include that too. **N/A**
- Any errors that appear in your browser's error console. **N/A**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **N/A**
- Include any additional information you can find in `storage/logs` and your webserver's logs. **N/A**
- Include what you've done so far in the installation, and if you got any error messages along the way. **N/A**
- Indicate whether or not you've manually edited any data directly in the database **no**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Hi there - if you installed from master, you’re on the stable release. We only push stable to master - and its even what we deploy customers from, so it’s not an unstable branch, it’s just the version numbering that can be a little confusing. Basically once an official release is issued, the very next version number, even for master, is tagged as a pre. Pre in the master version number means it’s not in an official release yet, but it’s stable and should be used, as it contains important bugfixes. 

I know it’s confusing. I’ve been trying ti find a way to make this less confusing for folks, but it can be tricky since we have people deploying from master, from releases only, from develop, etc. Trying to clearly communicate what they’re actually using is a surprisingly challenging thing.
