### ISSUE TITLE
More assest in a single Maintenance item

### ISSUE THREAD

**Issue by raffo1987** [snipe/snipe-it#4981]
#### Expected Behavior (or desired behavior if a feature request)

If I have a sigle contract of maintenance for all my printers (for example) I expect to create only one maintence item for all my printers (each one is an asset). Seems ugly to me create more items for the same contract replicating information
-----

#### Actual Behavior

Now only one asset is linkable to a maintenance
![image](https://user-images.githubusercontent.com/36234646/35930248-b58be2f0-0c31-11e8-910b-af6f72228552.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [* ] I have enabled debug mode 
- [* ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh install
- Version of Snipe-IT you're running
the last
- Version of PHP you're running
7.0
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
Ubunti 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual with a we tutorial in LAMP
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
no

**Comment by lravelo** [comment]
I have this same issue as well.  Usually we buy two of something (i.e., two firewalls, two routers, two switches, etc) and I'm not seeing anyway to either link existing documents to a new asset or a better way to filter the costs so that we don't have to split the costs down per asset. Would love to know if there's a good approach in the current build to be able to do this or perhaps classify this as a feature request.
