### ISSUE TITLE
Licenses: no "Checked Out To" view.

### ISSUE THREAD

**Issue by mkola-greenliff** [snipe/snipe-it#5002]
Snipe-It version 4.1.11.

Not sure if this is a bug, but in general: how can I check which license is assigned to which user? With "Assets" it's very simple: there is "Checked Out To" field in Assets table. But there is no such field for Licenses.

Thanks!

**Comment by snipe** [comment]
@mkola-greenliff Licenses don't work that like. Licenses act more like asset models, where individual seats are checked out to users. Clicking on the license in the Licenses Listing shows you who (who anyone) license seats are checked out to.

**Comment by greg-jaunt** [comment]
Individual seats can have individual license keys, though, and you need to track which user has been assigned which individual key.  The way to track individual key assignment is to create a new License entry for each key, which is perfectly fine.  However, once you have 100 (or even 10) license key entries, having to click on every single one to discover the full list of users to know who you could perhaps ask if they still need their software is unacceptably time consuming.  There should be a column that provides the full list of users that have access to each license so that it can be scanned at-a-glance.  A "Checked out to" column would work just fine for that.
