### ISSUE TITLE
Dashboard button not clickable

### ISSUE THREAD

**Issue by cepacs** [snipe/snipe-it#5085]
#### Expected Behavior (or desired behavior if a feature request)

click the dashboard on the left side

-----

#### Actual Behavior

does not allow clicking when screen is not full screen

-----

Not a big deal but I just noticed this on a screen that wasn't maximized.  If the right side of the screen has two rows at the top it doesn't allow the dashboard on the left side to function..
![image](https://user-images.githubusercontent.com/36515590/36571366-57d27f1e-1804-11e8-928e-0fedee05eb48.png)

If I stretch it enough to make it one row again then it becomes available..
![image](https://user-images.githubusercontent.com/36515590/36571411-85375cf4-1804-11e8-94c0-4ee9db1b83e4.png)

The funny thing is if I squeeze the screen so that the tool bar goes to three rows the left side autoadjusts so that I can click the dashboard.
![image](https://user-images.githubusercontent.com/36515590/36571457-c2b6ba5c-1804-11e8-9dfe-5081fdfc4337.png)

I get the same behavior even with the tool labels hidden..
![image](https://user-images.githubusercontent.com/36515590/36571494-fa0c7b4a-1804-11e8-9718-295ef351ac13.png)

But with only 1 row or 3 rows it becomes functional again..
![image](https://user-images.githubusercontent.com/36515590/36571525-1f4db8ce-1805-11e8-9150-2816fcaef2b9.png)

Thanks :)

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh**
- Version of Snipe-IT you're running **Version v4.1.11-pre - build 3299 (master)**
- Version of PHP you're running **PHP version: 7.1.14 **
- Version of MySQL/MariaDB you're running **MySQL Server version: 5.7.21**
- What OS and web server you're running Snipe-IT on **Windows Server 2016 / IIS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **GIT**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by vogtmh** [comment]
Same problem for the assets button. All other buttons below work fine on any size. 
This only occurs as a **superadmin**. Admin view is perfectly fine :) 

![image](https://user-images.githubusercontent.com/37808063/39039608-19f7fc88-4486-11e8-9ab3-38b6eae04cf8.png)

**Comment by vogtmh** [comment]
Seems to be fixed now - can anyone else confirm?

**Comment by cepacs** [comment]
I'm on v4.3.0 build 3559 (master) and it is still exhibiting the same behavior when the logo and icons take up two rows.  I am also running on IIS, though I am hoping that doesn't make any difference..

**Comment by n-v-o** [comment]
This is still an issue unfortunately as of 4.6.3. I plan on doing some more testing. @cepacs could you reopen?

**Comment by f-fritz** [comment]
This issue is still present in version 4.8:

**Server (please complete the following information):**
 - Snipe-IT Version: 4.8.0
 - OS: Raspbian GNU/Linux 10 (buster) (on Raspberry Pi 3B+)
 - Web Server: Apache/2.4.38 (Raspbian)
 - PHP: PHP 7.3.11-1~deb10u1 (cli)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser Safari 13.0.5, Chrome 79.0.3945.130

It looks like the `<nav class="navbar navbar-static-top" role="navigation">` inside the html header is too big and covers the Dashboard item in the sidebar so that you can't click it.

<img width="1293" alt="dashboard" src="https://user-images.githubusercontent.com/46245228/74589387-3a379080-5005-11ea-890c-56c51fa73a65.png">

**Comment by cepacs** [comment]
Nice catch.. Is there anyway around this issue so that it would respond properly?

**Comment by f-fritz** [comment]
Just some more information about it:
The horizontal navbar goes from the left browser window margin to the right browser window margin - regardless of whether the sidebar is toggled or not.
If the window is too narrow, the nav-bar may be split into multiple rows with a height of 50px each.
As the navbar covers the whole windows width, it covers the sidebar area as well.
The problem is: If the navbar is split into two rows, the sidebar doesn't change. But as the nav-bar just doubled its height, it now covers the area of the first sidebar entry. Result: it cannot be clicked.
If the nav-bar is split into three rows, you may even not be able to click the Assets entry as well.

If the window's width fells below 991px (this is in the css file), the `<ul class="sidebar-menu">` (nested in `<aside class="main-sidebar">` > `<section class="sidebar">`) gets the following css applied:
```
@media (max-width:991px) {
    ul.sidebar-menu {
        padding-top: 120px
    }
}
```
This css moves the list of sidebar entrys down. But as the 120px is static this may look maladjusted if the nav-bar is only split into two rows, as the first sidebar's entry is not aligned with that, but a little further down than it is needed to be.
Furthermore, if you narrow the window even further, the nav-bar may be split to four rows (if width < 767px). The 120px is no longer sufficient. The first sidebar entry ("Dashboard") now partly covers the toggle sidebar button as the whole sidebar moves below the nav-bar.

I guess the issue can be solved by checking the nav-bar's height, devide it by one nav-bar row's height of 50px and apply an dynamic padding-top on the ul element.
Or making the nav or header element collide with the aside element so that the aside element begins just below.
Or by increasing the sidebar's z-index (currently 810) to move it in front of the header / nav-bar (currently z-index 1030).

(This was tested on Google Chrome 80.0.3987.106 for Mac)

**Comment by cookierun22** [comment]
Hi, I also have this kind of issue. Is there any ways to solve it? My version is Version v8.0.0 - build 16962 (master), PHP Version:8.3.28, Laravel Version:11.38.2
