### ISSUE TITLE
Adding an Asset Rule

### ISSUE THREAD

**Issue by nioidai** [snipe/snipe-it#509]
Dear reader,

I want to add some rules to the page where i can create an asset, is this possible?

The rule i want to add is a mac address.

Thanks!

**Comment by snipe** [comment]
I have a rough version of this on develop right now. In the asset models, you can enable MAC address tracking, and assets with that model will display a MAC Address field. 

I need to make it so that it's a little more dynamic - so that if while you're editing the asset, you pick a new model, it automatically knows whether to display the MAC address field. Right now, you have to save the new model to the asset, and then edit again to get the MAC Address prompt. But I don't expect people will be changing the asset model of an asset very often, so it should work for your purposes.
