### ISSUE TITLE
Not getting license expire notifications

### ISSUE THREAD

**Issue by beilinder** [snipe/snipe-it#5113]
#### Expected Behavior (or desired behavior if a feature request)
Getting a notification when a license is about to expire (30 days in advance)
-----

#### Actual Behavior

Nothing happens :)

This is where I should see a notifications right?
https://i.imgur.com/5Zer22q.png

Email settings:
https://i.imgur.com/uyT6gVx.png

.env settings for email:
https://i.imgur.com/vGXKs4u.png
(Set to our relay server)

Also, I set up a emailing service, tested and working, but am not getting notifications for expiring licenses.
I even set the threshold to a year in advance to check.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Fresh
- Version of Snipe-IT you're running

v4.1.11-pre build 3307 (gf06852f)
--
- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
Don't know sorry, is it this?
Laravel Version | 5.4.35
- What OS and web server you're running Snipe-IT on
CentOS 6.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Email me or show notification for expired licenses
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
No
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Yes
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by k2trf** [comment]
I'd suggest adding screenshots of your Notifications/Alert page in settings, to make sure that's set up right. Also your assets/whatever, a screenshot of those settings would be good, again to confirm settings.

For the email bit, what settings are in your .env file for SMTP? Don't include your username/password of course, but we could look if the settings are wrong.

**Comment by beilinder** [comment]
@k2trf added pictures of what you asked :)
The thing is it's not about the assets, just the licenses. And there are no settings for licenses from what I see?
https://i.imgur.com/ddVXyBt.png

the .env file is set to our relay server. Image is also attached.

Shouldn't I see alerts of expiring licenses not only by email, but also in the corner of the right screen?
https://i.imgur.com/OWYlnQk.png

Thanks

**Comment by k2trf** [comment]
Nono, not the settings pane on the left -- in the top right, there'll be some cogs, click that to get to the settings page (it calls it Admin). Then click on notifications and screenshot that -- it could be they're disabled or set up for much further out.

Are the assets notifying when their warranty is almost up? If its just the license keys, then its more likely something with your licenses, not the notification settings.

The screenshot/dump of your SMTP settings isn't there -- think it failed to link. If it's easier/quicker, instead of taking a screenshot, you can copy/paste into https://gist.github.com/, and then share that link here.

Just remember what I said, we're only interested in SMTP, and *don't* share your username/password. Neither of those would help us, and nobody else needs to know them anyways.

That is where notifications would be; the fact that you have none means either the entries (licenses or otherwise) are misconfigured, or your notification settings are wrong.

The email may be a separate issue (if .env isn't set up right) or the same (if notifications aren't enabled or configured).

**Comment by k2trf** [comment]
I can see the same problem in the demo on my phone, and its settings look like it should be throwing alerts based on license expiry. It isn't though when I set a license to expire in a week or so. Ima add snipe as a participant, since I'm fairly sure there's something wonky here, and I can't debug very far from a phone. :P

**Comment by beilinder** [comment]
@k2trf The email notifications should work if I get the regular notifications right? Or did I not understand correctly and these are not the same things?

I've set up the notification now to 30 days, and added a license to expire a day before that, so tomrrow I'll see what happens.

About the settings, I'm a real linux noob, so I'll just take screenshots of my .env file instead :P
I blurred out whatever seemed personal
https://i.imgur.com/qYLJGDJ.png
https://i.imgur.com/ZWbFPA4.png
https://i.imgur.com/q6uH5m5.png
https://i.imgur.com/T9cRWFN.png

Let me know if I shared too much, or not enough of course.
Thank you for the help!

**Comment by k2trf** [comment]
On phone, so not had a good look, but take that first photo down until you blur the app_key at the very least; you're doxxing yourself mate!

All we wanted from .env was the Skype settings. I do notice you appear to have two SMTP Servers; afaik you have to specify one, not multiples.

Will have a proper look later when I can.

On March 1, 2018 12:26:17 PM UTC, beilinder <notifications@github.com> wrote:
>@k2trf The email notifications should work if I get the regular
>notifications right? Or did I not understand correctly and these are
>not the same things?
>
>I've set up the notification now to 30 days, and added a license to
>expire a day before that, so tomrrow I'll see what happens.
>
>About the settings, I'm a real linux noob, so I'll just take
>screenshots of my .env file instead :P
>I blurred out whatever seemed personal
>https://i.imgur.com/qYLJGDJ.png
>https://i.imgur.com/ZWbFPA4.png
>https://i.imgur.com/q6uH5m5.png
>https://i.imgur.com/T9cRWFN.png
>
>Let me know if I shared too much, or not enough of course.
>Thank you for the help!
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/snipe/snipe-it/issues/5113#issuecomment-369576036

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by k2trf** [comment]
I've had a bit better of a look now; what host/provider are you trying to use?

I thought it might just be really long with a dot, but that's definitely two hosts in there, where you should only have one. Tell me the provider you're trying to use, and I can give you the right settings (gmail, yahoo, etc.)

You're also missing things; you have no username/password set, and you blurred other bits so I don't think you backspaced it for the screenshot (I don't need to know what it is, but it does need a valid user/password for the mail server you want to use).

You also need to set encryption. Depending on the provider you want to use, port 25 may be right, but you'd have to set MAIL_ENCRYPTION=null. Most cases you actually want tls or similar these days, which typically makes the port 587 if I remember right off hand.

Here's the example from the config guide, assuming you were using an Amazon AWS hosted mail account. Like I said, lemmie know what provider you're trying to use, and I can help with those settings. Because they're definitely the reason you're not getting email -- it doesn't know where to send it.

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=email-smtp.us-west-2.amazonaws.com
MAIL_PORT=587
MAIL_USERNAME=YOURUSERNAME
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=you@example.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=you@example.com
MAIL_REPLYTO_NAME='Snipe-IT'

Do me a favor, break the issues up. Change the title here to `Need help with SMTP settings` just to keep this issue separate, since this is simple. Then make another (new) issue for `License Notifications not working on install or demo`, as I can confirm that in the demo and my own install too.

That one is a bigger issue that snipe may have to investigate, but the email is likely just your settings, and I don't want the notifications issue being lost here while we work on the other one.

**Comment by beilinder** [comment]
@k2trf Thanks for your reply!
I use a relay server. So no need for encryption, username/password, etc. It's a local server, and after testing if emails work, they are. So all is good on that end.

What I mean is that I simply don't see an alert for a license which is about to expire.

**Comment by k2trf** [comment]
Can you receive emails from snipe-it as the config stands?

You appear to have two hosts -- even with a relay, you'd just use one, like `smtp-relay.gmail.com` for GMail. If you don't want to use encryption, you'll need to set MAIL_ENCRYPTION=null.

If its null, then it will use IP Address rules to determine if it can use the relay.
If its tls, then it will use username/password.

If you can absolutely receive emails from snipe-it as the config stands, then despite looking very odd, that isn't the issue, and its just the licenses not throwing notifications upon expiration (no notification means no email), and that appears to be an actual bug.

**Comment by beilinder** [comment]
@k2trf I can receive emails using the currect config. Clicking "send test" sends an email as expected. I added null like you suggested. Still, I didn't get a notification to my email about an expiring license :(

**Comment by beilinder** [comment]
Just bumping it up in case someone has a solution.

**Comment by chreichwein** [comment]
I have the same issue. I can receive e-mails like "assets checkout to users who must sign" I also can receive the test mail. But I don't receive any email alarm threshold if quantity is at the alarm level. Also no license expiere emails.

![grafik](https://user-images.githubusercontent.com/36449487/37341770-dfad478a-26c2-11e8-8c9e-121e2724a0c8.png)

![grafik](https://user-images.githubusercontent.com/36449487/37341818-17ff2d06-26c3-11e8-9152-13ab72421a59.png)

![grafik](https://user-images.githubusercontent.com/36449487/37341870-4826fe50-26c3-11e8-9100-b38834974f7b.png)

![grafik](https://user-images.githubusercontent.com/36449487/37341905-5f4041f0-26c3-11e8-8017-2e9c38350484.png)

Runing: Version v4.1.14 - build 3446 (master)
Maria DB 10
Windows Server 2012 R2
IIS 
PHP 7.1

**Comment by chreichwein** [comment]
With "php artisan snipeit:expiring-alerts" an email will be send with the expriring licenses:

![image](https://user-images.githubusercontent.com/36449487/37356929-6529153c-26e7-11e8-9b03-dc7f985e7f15.png)

But still no email with quanitity notification of accessories. And also no emails without using the command line tool.

**Comment by snipe** [comment]
Do you have a cron set up to actually trigger those emails?

**Comment by chreichwein** [comment]
@snipe 
I use Windows, so I don't have any cron set up.
Notification (alarm) emails will be send if I use the php artisan command manually, but emails (automatically) won't be send by the webserver itself.

**Comment by beilinder** [comment]
@chreichwein when I type php artisan snipeit:expiring-alerts it says 3 expiring license and sends the email to snipe-it@domain.com instead of what I configured it to send emails to, where is that line? In my .env file everything seems to be correct.

@snipe 
Sorry for noob question but what is cron and how do I set it up?

**Comment by snipe** [comment]
> I use Windows, so I don't have any cron set up.

Then you have to use the task scheduler.

**Comment by snipe** [comment]
@beilinder Why do you need to put that in a .sh file? Just put the commands in your crontab. https://snipe-it.readme.io/docs/configuring-alerts-backups

**Comment by sandiskajins** [comment]
I have different issue/bug. I am receiving e-mail about expiring licenses,warranty or quantity, but in snipe-it notification area, there are only quantity items and nothing about license and warranty expiration. Any ideas?
