### ISSUE TITLE
Location field question

### ISSUE THREAD

**Issue by bondo05** [snipe/snipe-it#512]
I'm having an issue with the location field. 

My scenario is as follows:
I have people that have equipment at the office location and at their home location (eg. Teleworker phone). When I add an asset and deploy it to this person it always shows on the deployed assets screen as being at the office location even if I set the asset default location to "home". It seems to be using the location of the person and not of the asset if I've set it to something different. If the asset has not been deployed to a person, it shows the default location as defined in the asset which is fine.

Is this the intended behaviour of the location field? That an asset shows the location as defined on the asset screen unless it has been deployed to a person in which case the location is overridden and uses the location of the person instead? 

Thanks.
##

**Comment by kobie-chasehansen** [comment]
Have a similar use case as well. In my example we've got equipment at our data center and its address is set as the default location but I checked it out to our general IT Operations account so it now shows it's located in our HQ.

Trying to think if there is a use case where you would want the location to reflect where the user is assigned. Think how it is now makes sense as the asset is in the default location till assigned and then assumes the location of the user in case that user is a remote employee/branch.

I see use cases for both... think in my case i will create a user for the data center site.

**Comment by snipe** [comment]
I can tell you the use case I wrote it with :) We had multiple offices, one main one in NYC, and a few smaller officers (without their own IT dept) in LA and SF. I wanted to make sure that data stayed consistent as they moved around (they did sometimes), so that a person who moved to the NYC office didn't still have a laptop assigned to LA because IT people are busy (and occasionally lazy). Having that discrepancy would screw up the depreciations, since the finance team needed to know where the equipment was for tax reasons.

**Comment by kobie-chasehansen** [comment]
What about an option to assign the asset to an existing location during the checkout process? This would preserve the existing work-flow for asset checkouts.

Would be handy for things like projectors, tv's, conference phones, etc.

**Comment by snipe** [comment]
@bondo05 "When I add an asset and deploy it to this person it always shows on the deployed assets screen as being at the office location even if I set the asset default location to "home". It seems to be using the location of the person and not of the asset if I've set it to something different."

This is intentional behavior, as a default location is just that, default unless overidden because it's been assigned, in which case it may have moved. 

So it sounds like the order of checking should be:

**If there is an `assigned_to` id and a `location_id` in the `asset_log`**, the asset is deployed to a user and the location should show up as whatever the location_id in that record is, ignoring the user's location AND the default location.

**If there is an `assigned_to` id and NO `location_id` in the in the `asset_log`**, the asset is deployed and the user's location should be used.

**If there is NO `assigned_to` id and there IS a `location_id` value, it's checked out to a location and that location should be used.

Otherwise use the default location for the asset.

Does that make sense?
