### ISSUE TITLE
Can't run pre-flight, web page is blank

### ISSUE THREAD

**Issue by earanaus** [snipe/snipe-it#5163]
#### Expected Behavior (or desired behavior if a feature request)

I install snipe by instruction, last step i will  see pre-flight page, But didn't, I see BLANK PAGE. All snipe folders is with read&wirte permissions, (storage too) where is problem? please don't close my isssue while i not inform you about resolve.

#### Please confirm you have done the following before posting your bug report:

- [ * ] I have enabled debug mode 
- [ * ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
FRESH
- Version of Snipe-IT you're running
NEWEST
- Version of PHP you're running
7.0
- Version of MySQL/MariaDB you're running
MYSQL
- What OS and web server you're running Snipe-IT on
LINUX UBUNTU
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
MANUAL
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
NO ERROR
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
MAIN PAGE
- If a stacktrace is provided in the error, include that too.
NONE
- Any errors that appear in your browser's error console.
NONE
- Include any additional information you can find in `storage/logs` and your webserver's logs.
none logs
- Indicate whether or not you've manually edited any data directly in the database
none

**Comment by earanaus** [comment]
I have checked my permisions on storage directory: I attaching a printscreen photos:
[https://imgur.com/bNRC9Sa](url)
[https://imgur.com/bNRC9Sa](url)
MY os Ubuntu Server 16.04.4 LTS
My logs files is empty, from which place you need log?

**Comment by snipe** [comment]
> My logs files is empty, from which place you need log?

We need your web server's error log. If you're getting a blank screen, that's the only way we'll be able to help you. 

Additionally, please confirm whether or not you're running SELinux, per my original comment.

**Comment by earanaus** [comment]
No, I'm not use SELinux,
My web server log from /var/log/apache2/error.log.1


[Wed Mar 07 07:35:05.930321 2018] [mpm_prefork:notice] [pid 2944] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Mar 07 07:35:05.930411 2018] [core:notice] [pid 2944] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 07 11:42:07.222357 2018] [mpm_prefork:notice] [pid 2944] AH00169: caught SIGTERM, shutting down
[Wed Mar 07 11:42:53.639553 2018] [mpm_prefork:notice] [pid 1393] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Mar 07 11:42:53.642248 2018] [core:notice] [pid 1393] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 07 11:59:09.403494 2018] [mpm_prefork:notice] [pid 1393] AH00169: caught SIGTERM, shutting down
[Wed Mar 07 11:59:10.416809 2018] [mpm_prefork:notice] [pid 3003] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Mar 07 11:59:10.416889 2018] [core:notice] [pid 3003] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 07 11:59:54.667364 2018] [mpm_prefork:notice] [pid 3003] AH00169: caught SIGTERM, shutting down
[Wed Mar 07 11:59:55.984870 2018] [mpm_prefork:notice] [pid 3181] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Mar 07 11:59:55.984959 2018] [core:notice] [pid 3181] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 07 12:00:58.433225 2018] [mpm_prefork:notice] [pid 3181] AH00169: caught SIGTERM, shutting down
[Wed Mar 07 12:00:59.775359 2018] [mpm_prefork:notice] [pid 3283] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Mar 07 12:00:59.775446 2018] [core:notice] [pid 3283] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 07 12:01:25.117671 2018] [mpm_prefork:notice] [pid 3283] AH00169: caught SIGTERM, shutting down
[Wed Mar 07 12:01:26.342822 2018] [mpm_prefork:notice] [pid 3373] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Mar 07 12:01:26.342911 2018] [core:notice] [pid 3373] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 07 12:02:13.090728 2018] [mpm_prefork:notice] [pid 3373] AH00169: caught SIGTERM, shutting down
[Wed Mar 07 12:02:14.825452 2018] [mpm_prefork:notice] [pid 3471] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Mar 07 12:02:14.825537 2018] [core:notice] [pid 3471] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 07 12:03:43.584782 2018] [mpm_prefork:notice] [pid 3471] AH00169: caught SIGTERM, shutting down
[Wed Mar 07 12:03:45.096331 2018] [mpm_prefork:notice] [pid 3568] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Mar 07 12:03:45.096456 2018] [core:notice] [pid 3568] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 07 12:08:33.119102 2018] [:error] [pid 3595] [client ::1:50728] PHP Warning:  require(/var/www/snipeit/vendor/composer/../psy/psysh/src/Psy/functions.php): failed to open stream: No such file or directory in /var/www/snipeit/vendor/composer/autoload_real.php on line 66
[Wed Mar 07 12:08:33.119145 2018] [:error] [pid 3595] [client ::1:50728] PHP Fatal error:  require(): Failed opening required '/var/www/snipeit/vendor/composer/../psy/psysh/src/Psy/functions.php' (include_path='.:/usr/share/php') in /var/www/snipeit/vendor/composer/autoload_real.php on line 66
[Wed Mar 07 12:09:10.662191 2018] [mpm_prefork:notice] [pid 3568] AH00169: caught SIGTERM, shutting down
[Wed Mar 07 12:09:11.811633 2018] [mpm_prefork:notice] [pid 3799] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Mar 07 12:09:11.811731 2018] [core:notice] [pid 3799] AH00094: Command line: '/usr/sbin/apache2'
[Thu Mar 08 07:35:04.191052 2018] [mpm_prefork:notice] [pid 3799] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message

**Comment by letizia66** [comment]
I have the same problem with docker image: snipe/snipe-it:v5.4.2.

After the very first start I got an empty page, setup page received 500 Internal server error.

I found that the problem is a permission of file and folder in /var/www/html/storage/framework/cache that are owned by root:root.

After a stop/start of the container, those file are owned by docker:root and everythings are fine. 

The error are printed in /var/log/apache2/error.log but not on the standard output, so docker logs doesn't show any error.

[Mon May 02 09:21:18.898067 2022] [php7:error] [pid 68] [client 138.132.16.203:55990] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents()\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put()\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put()\n#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\FileStore->forever()\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(418): Illuminate\\Cache\\Repository->forever()\n#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheMana in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133
[Mon May 02 09:21:18.899925 2022] [php7:error] [pid 68] [client 138.132.16.203:55990] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/storage/framework/cache/cf/90/cf906e7195218453e4ff6f1bdcdc6b2d9f6cae71): failed to open stream: Permission denied in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents()\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put()\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put()\n#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\FileStore->forever()\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(418): Illuminate\\Cache\\Repository->forever()\n#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheMana in /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133

Should I mount /var/log on volume? This is not described in docker snipe-it image documentation.
Thanks
