### ISSUE TITLE
Issues upgrading

### ISSUE THREAD

**Issue by fitzy1989** [snipe/snipe-it#526]
Hi Snipe,

I have copied the new files (v1.2.4) into my directory and have ran the two commands as per your instructions.

I am running v1.0 on Windows server 2008 R2 Standard, IIS, PHP 5.4

Below is the output.
C:\inetpub\wwwroot\snipe-it-1.1>php composer.phar dump-autoload
Generating autoload files

C:\inetpub\wwwroot\snipe-it-1.1>php artisan migrate

  [InvalidArgumentException]
  Database [] not configured.

migrate [--bench[="..."]] [--database[="..."]] [--path[="..."]] [--package[="...
"]] [--pretend] [--seed]

I have ensured that database.php is in the location as per the install instructions.

Are you able to assist?

**Comment by snipe** [comment]
Which location did you put it in? If it thinks your app is in production mode (which is what it defaults to), it will look for `database.php` in `app/config` or `app/config/production`

**Comment by fitzy1989** [comment]
My database.php is in app\config\local.

**Comment by snipe** [comment]
Are you actually running this as a local install? (If you see the debug bar at the bottom, you're running as local, otherwise probably prod)

**Comment by fitzy1989** [comment]
yes as a local install

**Comment by snipe** [comment]
Are you looking to develop on this, or just install and use it? If you're looking to develop, local is the best environment for you, since you'll get all kinds of good debugging info, but if you're just planning to use it, you should run it as production. 

The only other thing I can think of is that in `bootstrap/start.php`, you may not have set your hostname correctly, so it may be trying to use the production config file. If you copy the `database.php` over to `app/config/production` or `app/config`, does it work then?

**Comment by fitzy1989** [comment]
By moving the database.php to app/config worked.

Thanks for your help.

**Comment by snipe** [comment]
Great, sorry for the confusion. I need to update the docs to make it a little clearer on what to do in local (if you plan to dev), and production (if you just plan to use). This issue has come up a few times before.

![fight-club-punching](https://cloud.githubusercontent.com/assets/197404/6238726/613814e4-b6b2-11e4-8fe7-3968a3927e7b.gif)
