### ISSUE TITLE
New Feature : GDPR Personal Data Management

### ISSUE THREAD

**Issue by pedrovieira-zz** [snipe/snipe-it#5278]
#### Expected Behavior (or desired behavior if a feature request)

It could be great have some functionalities about personal data, here in Europe we must start handle this kind of work, and would be great if we have something to index people identification and to manage all data location, permissions and log.

#### Actual Behavior

This could be a new Feature!

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----

**Comment by pedrovieira-zz** [comment]
Hi Snipe, i was wondering if we could have some repository with Personal Data's location, and some info about who have access to it and who have changed or accessed some information. 

With some integration with Windows File Shares and other Systems.. 

I was just thinking about this because after all process changes i must index all personal data to let people ask me where are they information, ask me to delete their data, etc. .  

But by other side, this is a kind of everybody responsability and it should be something outside of Snipe IT and not inside SnipeIT .. 

Well... just and idea... i will need something like this and maybe i will develop something for that.

**Comment by colinerd** [comment]
I am actually more concerned with the fact that deleted users are still present in the database. According to GDPR, I will have to delete them completely once I do not need the data anymore, including any attachments I uploaded with the user (e.g. signed forms of received equipment)

This would mean I will have to delete any users who have left the business from the system.
Another option is to anonymize the data (name, username, email), which might be the better alternative.

**Comment by snipe** [comment]
@colinerd you'd just need to purge your deleted records - but ultimately, "once I do not need the data anymore" is pretty subjective. As an IT manager, I will __always__ want to know who had an asset throughout that asset's lifetime, and possibly after that asset is archived.

**Comment by colinerd** [comment]
@snipe I know you can purge deleted records but I do not want to purge any asset records. I may want to clarify that I meant "personal data" specifically and not all data.

Perhaps it is an option to add a way to anonymize the personal info inside the user records and make it configurable. I take adding the option to only purge deleted users will also purge the asset history for any asset the deleted user was involved in?

I fully understand your last comment and as an IT manager myself, I do agree however I have to take into account any legal regulations as well. I am happy this system allows me a good control and keep track over my assets, been doing it manually until I found this system but I need to question any personal information that I save, therefore I might question myself, why would I still need to know who used the asset, say, 2 years ago? I think I just need to know for 6 months, 12 at the most.

There is still a large "grey" area around GDPR and I am just thinking out loud here....

**Comment by snipe** [comment]
> There is still a large "grey" area around GDPR and I am just thinking out loud here....

That's certainly true. 

What personal info do you feel you'd want to redact?

**Comment by colinerd** [comment]
I am using LDAP for user accounts so I do not believe there is a lot of data for me currently. I believe most important would be:

- Firstname
- Lastname
- Username
- Email
- Manager

For company's who might have more personal info of their users in LDAP and/or if you were to populate any other fields through a script or so (snipeitPS module) you may want to include other fields like the ones below. To be fair, I would expect business details to be on the below fields and not personal ones, yet would not be surprised if that is not the case somewhere in the world....

- Phone
- Address
- City
- State
- Country
- Zip

**Comment by colinerd** [comment]
This would still be a feature request. Is there any update?

**Comment by snipe** [comment]
This isn't something that's on the roadmap at this point. Maintaining user data in a system like this falls well within legitimate use for most cases, since you want to retain information on the person themselves for down-the-line liability.

**Comment by colinerd** [comment]
You have a point however you always need to set a term of saving the data for when a person leaves the company and the data is not relevant anymore. I would say 6 months in my personal preference. After that, you have no longer a legal foundation to retain the info.

Also, in the event a person executes their right to forget, You must have the option to delete it since the person revokes their permission to process their data.

**Comment by snipe** [comment]
> for when a person leaves the company and the data is not relevant anymore

And my argument is that because of the very nature of what this system does, that data will never not be relevant. A year from now, you may need to see who owned a laptop because (for example) it was tracked back to criminal activity or there was damage that was done that is only just now becoming an issue.

> You must have the option to delete it since the person revokes their permission to process their data.

Again, that's assume there is not [legitimate interests](https://www.gdpreu.org/the-regulation/key-concepts/legitimate-interest/), which in this case there would be.

**Comment by snipe** [comment]
We may consider adding some GDPR tools (in addition to the custom privacy policy link added in the last version), but it's not on our short term roadmap, as ultimately the policies on handling of that data depends on the Snipe-IT admin.

**Comment by jeirix** [comment]
Hello any news about this important topic?

**Comment by nikolajbrinch** [comment]
We are looking into using Snipe-IT for all asset management, and would rather run the hosted edition. 
GDPR wise the safe bet would be EU location (Frankfurt). But we also require Data Processor Agreements, and those kinds of things. 
Several US SaaS solutions are a no go, since they do not have any support for GDPR and other EU regulations. As CTO I really want to support Snipe-IT and the Open Source model, and pay you - but I need answers on this.

I failed to find an email to contact Snipe-IT regarding purchase of their solution, so I have come here.

If you could contact me on nbj@nine.dk it would be great.

**Comment by snipe** [comment]
Hi @nikolajbrinch - you can reach out to us at support@snipeitapp.com and we can give you the documentation you need :)

**Comment by snipe** [comment]
(Or one of our people will reach out to you - whichever comes first :) )
