### ISSUE TITLE
Error Uploading Model Images

### ISSUE THREAD

**Issue by davideveritt** [snipe/snipe-it#531]
I'm having an issue uploading images to our asset models. I read through the previous issues regarding this and double checked my permissions on everything but I'm still getting an error. I'm running snipe on IIS. I've attached a screenshot of the error. I don't know if this matters but the slashes switch from back to front in the middle of the referenced file path. Any help you can give will be greatly appreciated.
![image](https://cloud.githubusercontent.com/assets/9324231/6240747/7b98cb48-b6c7-11e4-941e-7d24b8628fd1.png)

**Comment by snipe** [comment]
@madd15, any insight here?

**Comment by madd15** [comment]
@davideveritt, can you please check if `IUSR` user has write permission to the `public/uploads` folder

**Comment by davideveritt** [comment]
It actually has full control at the moment. I kept increasing rights when
write permission didn't work.

Sent from my iPhone

On Feb 17, 2015, at 5:19 PM, madd15 <notifications@github.com> wrote:

@davideveritt <https://github.com/davideveritt>, can you please check if
IUSR user has write permission to the public/uploads folder

—
Reply to this email directly or view it on GitHub
<https://github.com/snipe/snipe-it/issues/531#issuecomment-74792676>.

**Comment by madd15** [comment]
Can you check that the models folder is inheriting the permissions also please

**Comment by davideveritt** [comment]
It is.

Sent from my iPhone

On Feb 17, 2015, at 6:15 PM, madd15 <notifications@github.com> wrote:

Can you check that the models folder is inheriting the permissions also
please

—
Reply to this email directly or view it on GitHub
<https://github.com/snipe/snipe-it/issues/531#issuecomment-74798717>.

**Comment by madd15** [comment]
The only cause for this error is if `IUSR` (not `IIS_IUSRS`) doesn't have permissions to the folder.

![uploadperms](https://cloud.githubusercontent.com/assets/3274937/6241475/d3be0b52-b76d-11e4-8087-cd081c562e8e.png)

**Comment by davideveritt** [comment]
I've actually given permission to both those accounts and the users group
because I read that in another thread.

Sent from my iPhone

On Feb 17, 2015, at 6:29 PM, madd15 <notifications@github.com> wrote:

The only cause for this error is if IUSR (not IIS_IUSRS) doesn't have
permissions to the folder.

[image: uploadperms]
<https://cloud.githubusercontent.com/assets/3274937/6241475/d3be0b52-b76d-11e4-8087-cd081c562e8e.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/snipe/snipe-it/issues/531#issuecomment-74800104>.

**Comment by madd15** [comment]
Could you please screenshot your permissions so i can see thanks

**Comment by davideveritt** [comment]
Thanks for all the help.
![image](https://cloud.githubusercontent.com/assets/9324231/6241879/1d96bd26-b6da-11e4-853d-d65994b7cf61.png)

**Comment by madd15** [comment]
I assume you have been trying to upload images since posting this issue but could you try once more and post a screenshot thanks.

**Comment by wvanhiele** [comment]
perhaps this might help someone else, we are running snipe on Windows IIS. When uploading images (models) we got an error message "Image Source not readable" form same intervention class.

From the error message i noticed it was uploading to c:\windows\temp\ dir on the server
I gave IUSR also write permission to this temp directory and directly started working. :+1: 
I didn't see this in the installation guide so this might save someone else some time

**Comment by snipe** [comment]
Hi @wvanhiele - thanks for the follow up. I've updated the documentation here: http://snipeitapp.com/documentation/installing-on-iis/

Can you take a look and see if this makes sense? (I haven't worked on IIS in literally 10+ years)

**Comment by wvanhiele** [comment]
Great stuff! It makes sense yes. And a new website I see ☺
Just for your info, full control is not needed, I just gave modify permissions.

I noticed you also added the part about the private_upload folder which wasn’t in the previous documentation. What is that used for?

Thanks for the quick follow up and great work with this software, also the new features/updates since 1.1 are really good!

**Comment by wvanhiele** [comment]
One more thing, I installed on Windows Server 2012 R2 with IIS and works the same, so you might want to change the title to include 2012 R2 and prevent a few questions about it ☺

From: Wouter van Hiele
Sent: woensdag 18 februari 2015 12:26
To: 'snipe/snipe-it'; snipe/snipe-it
Subject: RE: [snipe-it] Error Uploading Model Images (#531)

Great stuff! It makes sense yes. And a new website I see ☺
Just for your info, full control is not needed, I just gave modify permissions.

I noticed you also added the part about the private_upload folder which wasn’t in the previous documentation. What is that used for?

Thanks for the quick follow up and great work with this software, also the new features/updates since 1.1 are really good!

**Comment by snipe** [comment]
Hi @wvanhiele - good to know, I'll update the docs when I get a chance, thanks! 

The `private_uploads` directory is for license and asset file uploads (released in v1.2.4 and v1.2.5). Since we don't want those available in a publicly-accessible directory (or else people could link to them, fuzz filenames to try to hit the jackpot on license keys, etc), we put them in `public_uploads` above the web root. The code then checks to make sure the user is logged in and has access levels to permit them to access the file to download it.

**Comment by wvanhiele** [comment]
Ok clear thanks!

**Comment by davideveritt** [comment]
Came in this morning removed the permissions, rebooted, reapplied the permissions and it seems to be working flawlessly now. Thanks for all the help.

I gave read/write on the uploads folder and read on the temp folder. FYI.

**Comment by snipe** [comment]
![off-and-on-again](https://cloud.githubusercontent.com/assets/197404/6253925/bf8fcfa8-b759-11e4-88ec-65538c1a4804.gif)

Glad it's sorted for you!

**Comment by davideveritt** [comment]
Exactly!



David Everitt
IT Director
Gonzaga Preparatory School
1224 E Euclid Ave
Spokane, WA 99207
(509) 483-8511 x460
