### ISSUE TITLE
Passwords Always Invalid

### ISSUE THREAD

**Issue by JackWetson** [snipe/snipe-it#5342]
#### Expected Behavior (or desired behavior if a feature request)

User is able to login with valid credentials

-----

#### Actual Behavior

User is unable to login with valid credentials even after a reset.

1. User tries to login with known valid credentials, fails.
2. User successfully resets the password, is auto-logged into the system at this point as a part of the password resets
3. User Logs Out
4. User tries to login with new credentials, failes login

-----

#### Please confirm you have done the following before posting your bug report:

- [YES ] I have enabled debug mode 
- [ YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh Install

- Version of Snipe-IT you're running
4.2.0 - build 3497 (master)

- Version of PHP you're running
PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.28-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

- Version of MySQL/MariaDB you're running
mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper

- What OS and web server you're running Snipe-IT on
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No
- Include any additional information you can find in `storage/logs` and your webserver's logs.
None
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Matthewrbowker** [comment]
@JackWetson Have you perhaps configured the cookie domain in `.env`?  An invalid cookie domain can cause passwords to fail (I know, I messed up our setup).

A valid config entry is thus: 

> COOKIE_DOMAIN=assets.website.com

**Comment by snipe** [comment]
Also if you have `SECURE_COOKIES=true` but you're not running over SSL.

**Comment by JackWetson** [comment]
COOKIE_DOMAIN wasn't set as it was marked as optional in the .env file. This has now been set and the same issue prevails.

SECURE_COOKIES is false, running without HTTPS as a test

Notably, the only change is that the user is no longer auto logged in after changing the password.

**Comment by snipe** [comment]
The only thing I can suggest here is to check that there aren't any password managers, stored browser passwords, or keychain managers that might be quietly replacing the password right before login. Logins definitely still work normally - we'd have a lot more issues about it if they didn't. 

One other thing to check is that the user is logging in with their username, not their email address. Sometimes the username *is* the email address, but sometimes it's not. We've had folks get stuck on that one before.

**Comment by abwjedi** [comment]
I would just like to add on that I've had this exact same issue. Login works on the first attempt after reset, but not afterwards.

In my specific case, my server is not yet public. I created a test user "test_staff" and a test password "test123".

My password security settings are such that they require at least ten characters to be valid, however, password reset links are accepting insecure passwords, in this case only being seven characters. Maybe just a gap in validation with respect to reset links? 

Also I apologize if this is a bit off topic. I'm new to GitHub. Would a new topic be more appropriate?

**Comment by fahadkhan82** [comment]
yes problem still persists

**Comment by atalz163** [comment]
i have this problem does anyone knows how to solve this issue?

**Comment by snipe** [comment]
> i have this problem does anyone knows how to solve this issue?

Not trying to be a dick here, but this has never, ever been a valid bug.

Remember to login using your *username*, not your email address. That's about all I can tell you, unless you're using SAML or LDAP or some third party system to auth you. Our authentication works just fine. 

Every single time we've seen this in the wild, it's because:

- a browser password manager is overwriting the password in the form, so what you're logging in with isn't what you think it is
- there's a third-party config issue in your LDAP
- one of the other reasons I've already mentioned in this *three year old* ticket

When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.

**Comment by ate-it** [comment]
> i have this problem does anyone knows how to solve this issue?

This bug which "doesn't exist", I've only ever been able to resolve by re-installing snipe

**Comment by krisjanis-nesenbergs** [comment]
This bug is definately a real bug - more specifically it affects users un user per user basis.
A specific user cannot log in with password from any computer/browser (no saved password, using normal user name not email), while others can log in to their accounts. Also at the beginning the user could log in, but now cannot.
Also - when the user is logged in automatically, and have this problem - they can actually change the password (in change password form which checks old password for correctness) to another password (so it is not a bug in password reset, which would assign incorrect password, as it was hinted before with reset allowing shorter passwords). Our first idea was that reset accepts illegal characters which the password form discards or something, but haven't been able to validate this.
EDIT (our version is v4.6.3 build 3866 (g3de1de9dc))

**Comment by snipe** [comment]
> Our first idea was that reset accepts illegal characters which the password form discards or something, but haven't been able to validate this.

Definitely not a thing. The password is hashed before inserted, so we don't know or care what the password is, outside of whatever constraints you have set up in Admin Settings > Security. We validate those rules first, then do a one way hash and store it. When a user logs in, we're only comparing hashes.

**Comment by krisjanis-nesenbergs** [comment]
Thank You for the clarification. So in that case, the password hash comparison for the login form and the change password form old password box are the same comparison function - no differences? If that is true, then I am at loss, where the problem could lie. Is there some place I can get more debug information on login failures?

**Comment by snipe** [comment]
> So in that case, the password hash comparison for the login form and the change password form old password box are the same comparison function - no differences?

Correct.

I'd maybe try tailing the logs at `storage/logs/laravel.log` while you walk through the reset process. (Also make sure to try this in a few different browsers to make sure it's not a weird browser extension getting in the way.)
