### ISSUE TITLE
Encode .env

### ISSUE THREAD

**Issue by masterofdesaster2999** [snipe/snipe-it#5350]
Is there any way to encode the .env or maybe  only the parameter Email Password and Database Password. 

Actually the Passwords are in clear text. This is safety critical.

Thanks 
You do a good work

Tim

**Comment by snipe** [comment]
@masterofdesaster2999 There isn't a way to encode it, but you can set them as actual environmental values in your server config, instead of using an .env. We don't usually recommend this only because most of our users aren't web server sysadmins, and that step can make it confusing down the line if you're not familiar with it.
