### ISSUE TITLE
Import users and associate to department

### ISSUE THREAD

**Issue by meyerf99** [snipe/snipe-it#5382]
Hi Dev Team

Is it possible to import users with csv and associate them with the department field?
I see only other fields but not department field when i want to import .csv file and match them together with fields.

Kind regards,
Flavio

**Comment by MSTigers** [comment]
Definitely need this. Would pretty much make #3486 of no use for me.

**Comment by snipe** [comment]
@MSTigers can't you just bulk edit them for now?

**Comment by MSTigers** [comment]
If they were all going to the same department I could. Though I can't think of any meaningful way to sort and organize them in Snipe that bulk edit would be doable since I'm splitting them into 12 different departments.

Our personnel information systems software holds the personal data. We export that and convert some of the data into something we can use for AD. Update our Active Directory and shove them into an OU based off of that data.

I then use a powershell script `snippet: @{Label = "Distinguished Name";Expression = {$_.distinguishedName}},` that exports whatever I need, but most importantly here is the Distinguished Name that pulls their OU and dumps that info into a CSV.

Excel `=RIGHT(LEFT(E2,LEN(E2)-73),4)`  code pulls all irrelevant characters out of the distinguishedName dump and leaves me with the last portion of the OU. This correlates with the Department in Snipe (12-14 of them).

That OU is the only piece of information I have that will allow me to distinguish differences between the users.

I had a long internal discussion on why I needed departments over locations. The tl;dr of it is while it's not consistent and will be a little extra math later on if I wanted to pull numbers of people from certain areas, locations should be sufficient.
