### ISSUE TITLE
Asset Names are missing in Maintenances Report

### ISSUE THREAD

**Issue by CronKz** [snipe/snipe-it#5387]
#### Expected Behavior (or desired behavior if a feature request)

/reports/asset_maintenances
Should show the Asset Names.

-----

#### Actual Behavior

/reports/asset_maintenances
Asset Names are missing. (Also on the official Demo)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
> git master
- Version of Snipe-IT you're running
> git master 4.2.0 build 3497
- Version of PHP you're running
> 7.1.12
- Version of MySQL/MariaDB you're running
> Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1
- What OS and web server you're running Snipe-IT on
> CentOS Linux release 7.4.1708 (Core)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
> install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
> No.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
> /reports/asset_maintenances
- Any errors that appear in your browser's error console.
> No.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
> Yes it is. https://demo.snipeitapp.com/reports/asset_maintenances

**Comment by snipe** [comment]
I cannot reproduce this on the demo. (The assets in the demo typically do not have names, that's why you don't see them listed.)

<img width="1262" alt="screen shot 2018-04-23 at 1 41 53 pm" src="https://user-images.githubusercontent.com/197404/39152137-2dc9e848-46fc-11e8-86f9-4ee137598ed0.png">

**Comment by vuuet** [comment]
I deployed in local and it has the same issue in Maintenances Report. I used version 4.3.0.

**Comment by snipe** [comment]
@vuuet The asset maintenances report just duplicates the data in the asset maintenances section, so will likely be removed or modified in the future.

**Comment by vuuet** [comment]
@snipe grateful for the prompt reply :)

**Comment by sheppyh** [comment]
@snipe All reports duplicate data listed elsewhere. That is the nature of reports. The difference is the Asset Maintenance Report lists maintenance across ALL assets. It would be a nightmare for our internal auditor to click every asset and ensure that firewall firmware upgrades were completed on schedule. This is the purpose of the report. Please don't remove the report in the future. I also have this issue with missing asset names (v4.6.6) and for some reason Asset Tag has been removed as a selectable column since your screenshot on May 15 - so we have no way to identify which asset had maintenance completed or not. I'll see if I can identify the issue, but haven't coded PHP in about 15 years!
