### ISSUE TITLE
Nomenclature of PDF

### ISSUE THREAD

**Issue by Vhize** [snipe/snipe-it#5422]
Hi there !! :) 

I will have a little question that seems a bit silly but to which I have not found an answer. When I want to import a pdf for an asset the name of my pdf is changed. For example I add a pdf called testingReport.pdf and I end up with " hardware-573-qKZ8VkQ8-testingreport**pdf.pdf** ". Is it possible to separate from the beginning (hardware-573-qKZ8VkQ8-) and not have a PDF file that ends with pdf.pdf ? Thanks for your time ^^" and excuse me for this answer because i'm supposing that no possible. But I think (maybe) it will interesting for you to know than when you import a pdf it will be naming **xxxpdf.pdf**

- Fresh install
- Version of Snipe-IT : v4.2.0
- Version of PHP : PHP 7.0.27
- Version of MySQL/MariaDB  : 10.1.26-MariaDB-0+deb9u1

**Comment by snipe** [comment]
@Vhize we add the hardware-85958 bit to the beginning of the filename so that you can't accidentally overwrite a file if you upload something with the same name. For example, if you had a file named manual.pdf, and you uploaded that file to asset ID 3, any other manual.pdf you uploaded to an asset could overwrite the one you uploaded for asset ID 3. 

The **pdf** part being there is just because it's a pain in the ass to remove it, but it's not impossible.
