### ISSUE TITLE
LDAP Sync For User Info ONLY

### ISSUE THREAD

**Issue by damienmz** [snipe/snipe-it#5440]
LDAP Sync functions as documented however I want to just bring the users in, disable them so they cant login, and be able to manage thier local Snipe-IT password. Basically I only want the users info to be brought in so that assets can be assigned to them. Also, some of the users that will be brought in I want to make them so that they are assest managers of the system using a local Snipe-IT account instead of the AD password. The only issue is once a user is synced with LDAP, I cant manage their local, Snipe-IT, password.

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?    Fresh
- Version of Snipe-IT you're running.     v4.2.0 - build 3479
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on - Cent OS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual Install

**Comment by snazy2000** [comment]
Couldn’t you just import the users using CSV ? I don’t really understand why you would control the password locally because that would confuse users if you did want them to login..  you could use my powershell module (SnipeitPS) to create local users instead of ldap users, the script could loop your ad users and create based on that.
