### ISSUE TITLE
Targeted PHP 7.1.3 is not Debian stable (9 / Stretch) compatible !

### ISSUE THREAD

**Issue by benrubson** [snipe/snipe-it#5481]
Hi,

As seen in [v4.3.0 release message](https://github.com/snipe/snipe-it/releases/tag/v4.3.0), as well as in #5183, sounds like Snipe-IT will require PHP 7.1.3 or more in future versions.

Unfortunately, as time of writing, **Debian stable** (9 / Stretch), uses PHP 7.0 :
https://packages.debian.org/stretch/php/php

Perhaps it would be nice to keep compatible with PHP 7.0, so that Debian stable, mainly used in hosting environments, will still be supported ?

Many thanks 👍

**Comment by snipe** [comment]
It is, unfortunately, not up to us. The newer version of the framework (Laravel) requires 7.1.3 minimum.

**Comment by snipe** [comment]
(I definitely didn't want to force anyone's hand on anything higher than 7.0, but there is a minor security issue in earlier versions of Laravel, so we kinda have to pull the project forward, which means requiring 7.1.3. ☹️)

**Comment by benrubson** [comment]
What about going with Laravel v5.5.40, which has been corrected and then does not suffer from the security issue ?
It supports PHP 7.0, whereas Laraval v5.6.x needs PHP 7.1.3.
Would be nice I think 👍

**Comment by snipe** [comment]
I mean, I guess we can consider it, but we've already done all the work to port everything over to 5.6 on a different branch. I'll have to re-do or roll back a lot of the work that was already done.

**Comment by benrubson** [comment]
Mmmh I understand.
But I think risk is to face issues from people running Snipe-IT on such (common) hosting environments.

It would be a nice thing to still be compatible with Debian stable.
You would then also be compatible with Ubuntu 16 which is a Long Term Support version.
It would be worth it, I think, really.

Installing non-supported package on Debian (or Ubuntu) is really non convenient at all, of course it's non-supported, you miss the distribution security patches, and take the risk to encounter side effects, break other things... Well it's discouraged :)

Perhaps moving from 5.6 to 5.5 (or 5.4 to 5.5) will not require as much work as moving from 5.4 to 5.6 ?

Thank you @snipe 👍

**Comment by snipe** [comment]
> Perhaps moving from 5.6 to 5.5 (or 5.4 to 5.5) will not require as much work as moving from 5.4 to 5.6 ?

But that work was already done, so now it's more work on top of that, and trying to diff the two to see what could potentially be ported. It seems unlikely that Debian 9 wouldn't ever support PHP 7.1.3 or higher - and we can't wait around in perpetuity for systems to catch up, as new features get added to the framework and would improve the product.

**Comment by benrubson** [comment]
> It seems unlikely that Debian 9 wouldn't ever support PHP 7.1.3 or higher

Debian 9 / Stretch is sticked with PHP 7.0.
https://packages.debian.org/stretch/php
But next version 10 / Buster (currently testing version) will run PHP 7.2.
https://packages.debian.org/buster/php

I think it's sort of "best practice" to support Debian stable, as it is widely used in web-hosting environments, exactly for its security practices.

> But that work was already done, so now it's more work on top of that, and trying to diff the two to see what could potentially be ported.

I understand.
Perhaps then that re-working a whole update would be faster, gaining from the experience of the already done 5.4 -> 5.6 migration.
Perhaps, as a good news, Laravel 5.5 would also allow Snipe-IT to run with PHP 7.2, which [seems to hang](https://github.com/snipe/snipe-it/commit/835c10d6352242bbd1d9f2cd7d4172cf5cadc2a2) for now with 5.6 ?

> We can't wait around in perpetuity for systems to catch up, as new features get added to the framework and would improve the product.

Sounds like perhaps you would have kept Lavarel 5.4 if no security issue would have been found ? :)
Do we really need some specific 5.6 features ? :)

Thank you again @snipe.
I'm the first to report this, but many users will be stuck in this situation.
I hope that makes sense :)

**Comment by snipe** [comment]
> Debian 9 / Stretch is sticked with PHP 7.0.

So Debian 9 / Stretch has no intention of supporting 7.1.x+? If that's true, then Debian 9 users will be screwed now if we upgrade to 5.5, or in the near future when we upgrade to 5.6. We can't be held hostage by Debian's choices. Upgrading to 5.5 only briefly delays the issue, but we're not going to just *not* upgrade to later versions of Laravel.

> I think it's sort of "best practice" to support Debian stable, as it is widely used in web-hosting environments, exactly for its security practices.

I understand that, but we support a shitload of environments already. Hobbling ourselves because the Debian community has made their own questionable decision doesn't seem fair to everyone who isn't running Debian 9 (which in my experience is the majority of people).

> Perhaps then that re-working a whole update would be faster, gaining from the experience of the already done 5.4 -> 5.6 migration.

I'm sure it will take less time, but you can see how I don't really want to do the same work all over again - only to then have to re-re-apply my original patches when we move to 5.6.

> Perhaps, as a good news, Laravel 5.5 would also allow Snipe-IT to run with PHP 7.2, which seems to hang for now with 5.6 ?

We have been fixing the 7.2 issues over the past few releases. It's just a small issue with how `count()` works on null items that behaves differently than it's previous versions. 

> Sounds like perhaps you would have kept Lavarel 5.4 if no security issue would have been found ? 

Absolutely. At least for several more months. Laravel 5.6 gives us some really cool features that we're excited about, but we weren't in a huge hurry, and we wanted to make sure we gave everyone enough time to upgrade their PHP. The security issue escalated things several months before we were planning on upgrading the framework.

**Comment by tiagom62** [comment]
PHP 7.0 goes EOL in 6 months. It shouldn't even be considered.

http://php.net/supported-versions.php

**Comment by ra-uk** [comment]
Any time scale for 7.1.3  compatible release? Currently having issues as hosting is upgrading to PHP7+  (and local machine will be soon) and hosters seem to prefer not to run >7

Thank you :)
