### ISSUE TITLE
Convert LDAP-Users to local users

### ISSUE THREAD

**Issue by clavis-jme** [snipe/snipe-it#5581]
**Server (please complete the following information):**
 - Snipe-IT Version: Current
 - OS: CentOS
 - Web Server: Apache
 - PHP Version: 5.6.32

**Is your feature request related to a problem? Please describe.**
I moved my installation to an environment without LDAP, i still have the users and can checkout assets etc. to them but I can't login with those former LDAP Users. 

**Describe the solution you'd like**
I'd like to have the possibility to change the Users to "normal users", set a new password etc, so I can fully use them again.

**Describe alternatives you've considered**
I've considered just deleting the user creating them new and checking out the assets manually but this would be a very very big task and probably take me a couple weeks.

**Comment by Mynty100** [comment]
I have a crazy idea, and wouldn't recommend doing it unless you can take a **snapshot or backup** of the entire database/setup. Also there is not currently a way to do a bulk password reset on selected users and then to set password must be change next login. Be advised, it would be far easier to remain connected to LDAP. However I also like the challenge. So depending on what you care about, read the following in full first and good luck.

**Option 1)** Basic
**Step 1)** With the users table you could do a CSV export. 
**Step 2)** Then delete users. 
**Step 3)** Separate the first names from the last names, currently the export seems to join them in the same field. When importing it looks to separated fields for first and last name. Reminder the 'Note' field will have LDAP import in it. delete this row or put your own note in.
**Step 4)** Process the import
**NOTE!!** However!! doing this will not link the users to there 'id' in the users table inside the snipeit mysql database. so if any assets are currently set you will find the assets that are currently checked out are linked to the 'id' number of the user in the users table not the username. Just deleting the user does not remove them from the user table. This is due to insure records and history of checkouts etc is kept. if you don't care about this then this will do the job. You will have to reset passwords one by one. however the account will no longer look to LDAP.

**Option 2)** Advanced
So other option is the following, and again no guarantee here.  Install and setup phpmyadmin if you haven't already. Using the username and password from .env file login and do the following.
**Step 1)** Do Steps 1 - 3 from Option 1.
**Step 2)** Using phpmyadmin you can login and **purge** the users table. 
**Step 3)** Process the import.
This should insure that user id's match though are no longer LDAP. Again there is no way to currently mass change/set passwords or set "user must change passwords next login" This would be a great future request. However I digress. 

All in all its not a simple process for most, but Option 2 will make sure your history is maintained. 
There maybe a much simpler way, but from what I can see this is what I would do in your situation. EEEK!
Good luck!
**Side note:** I recently spent a day manual migrating from 1 server to another from v4.1.5 to v.4.3.0. Following this idea I was successful in lining everything up in the new setup.

**Comment by snipe** [comment]
Disable LDAP in your settings, then run:

`update users set ldap_import='0'` 

That will remove the LDAP flag. Users can then use their old LDAP password (if you had LDAP password syncing enabled and if they logged in before) or do a password reset request to set a new password.
