### ISSUE TITLE
increase toner quantity

### ISSUE THREAD

**Issue by ppestime** [snipe/snipe-it#5606]
Lets say i have already added a toner cartridge model to my inventory. After a certain time i buy other cartridges of this same model. How do i input it into the app. should i edit the consumable and type in the sum of the quantity remaining and the quantity i just bought? or is there somewhere i can add the new cartridges so i can keep track of my consumable purchasing and usage?

**Comment by EarlRamirez** [comment]
@ppestime it truly depends on how you want to manage your system, you can add it to your total since it is the same model or if you want to track purchase orders you can create a separate one. The only problem I see with having multiple of the same consumable is reporting and notification. I personally will just update the existing numbers, again it depends on how you would like to manage your inventory.

**Comment by SylentBobNJ** [comment]
We add to the total. It's cumbersome and has lead to issues with our toner inventories but I believe it's been requested elsewhere to improve the process.

**Comment by dinorhythms** [comment]
Hello,

Any update on this issue?
I stopped using snipe-IT because of this issue and i have been watching and monitoring for update to install it again.

**Comment by hexagonzo** [comment]
i am also just updating the quantity number on my snipe-it for toner. would be nice to have something like an adding feature with time/date -> same would be nice to be able to assign consumables to an asset instead of user..
