### ISSUE TITLE
Feature: Pre-defined "kits" for quick assignment [$30]

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#563]
#### Use cases:

New accounting needs the same standard setup as most new accounting employees need. Laptop, monitor, mouse, external keyboard. Software installed - Quickbooks, Office, etc.

New graphic designer needs the same standard setup as most graphic designers, which is different than the accounting folks. Desktop with more firepower, mouse, wacom tablet, Adobe Photoshop, etc.

To be able to create predefined kits for quicker checkin could be pretty useful. 

Thoughts?
##

**Comment by kobie-chasehansen** [comment]
Like the idea, we have a few variations of what we call our standard configuration include anywhere from 8-12 items, mix of assets, software, accessories.

this feature would be helpful.

**Comment by jghanlon** [comment]
This would be great.  Usually the hiring managers or HR just tell us to setup a new system just like so-and-so.
I might also include security and server access as well.

**Comment by citizenkepler** [comment]
I am in favor of this.  My most organized equipment is in kits.  I currently handle this by setting the location plus a dash then the kit name, but it would be ideal if kits were supported natively.

**Comment by aalaily** [comment]
I would like to add my vote to this as well.  I think a "kit" concept would be very advantageous.

**Comment by joeykhan** [comment]
Add vote. Will see about adding bounty for this as would be very useful. 

Our use case, film company.

In our case, if someone wants to check a camera, they're not just going to check out the camera body

It would include

body
2 batteries
memory card
charger

The package would preferably not be a separate asset itself, but a collection of the assets grouped together.

Also, the package would preferably not contain specific assets, but just asset models. So when you go to checkout a camera kit for example, it just compiles an available asset corresponding to each model in the package. That way I can checkout camera or battery or charger number 302 to someone without worrying that its part of camera package 1 because the package will just pick a camera and batteries etc. that are not checked out.

**Comment by nextonphotos** [comment]
Is there any likelihood of this feature making it in anytime soon?

**Comment by bxchang04** [comment]
Any chance this feature can be implemented? Or would it be possible to implement it myself? Any tips or documentation on this would b great.

**Comment by VELIKII-DIVAN** [comment]
I started to implement it. But, I'm not sure how to define a specific item (iPad, MacBook, etc) inside the kit.
I guess 2 ways:
1 user specify a model, and the app search only this model asset. 
2 user specify a name pattern, and the app search an asset by name. 
Which option should I choose? Or, maybe, you will suggest another option?

**Comment by citizenkepler** [comment]
This is still a desired feature for me.   It is useful as if someone is to check out a DSLR camera, they would check out the kit that contains a battery, charger, memory card, and a lens, plus the camera bag.

Another use case is laptops, where the laptop kit is checked out and it includes the laptop, charger, battery, external mouse, and a carrying bag.

In both examples it would be nice to be able to check out a complete kit and on check in be alerted/reminded of the items in the kit and ensure all are scanned in.

**Comment by danielmny** [comment]
Also very interested in this! we use this in a school where we have a kit that includes X number of various elements and Y computers per kit.

Thanks much!

**Comment by Compuche** [comment]
+1 for needing this.  I recently had started using Asset Tiger to get a better handle on our tool kits (I work at a car dealer service center.)  We have a LOT of service took lots that I want to be able to check out the whole kit with its 10-20 tools at one time to a technician.  This works well with A.T.  but they only allow 250 tools until you have to buy their labels. I have at least that many kits.  Any idea if we'll see the parent/child feature anytime soon?   Until then, I'll manage...

**Comment by niteowl099** [comment]
+1 for wanting this feature. I am new to snipe-it but really appreciate the well thought out implementation of it so far and the surprisingly consistent responsiveness of snipe herself.  Thank you!

The workaround I came up with doesn't really work for me fully, but I created kits by assigning assets to other assets which would be the container they are in (bag, case, etc). However, we also utilize kits within kits because we have gear that gets typically gets checked out in a standard configuration to a user as a gig kit in a large wheeled duffel or airplane hardcase, but some of the standard configurations can be modified. For example a standard configuration gig kit which we keep at station #1 in the warehouse can have a camera kit, a microphone kit, standard power cord kit, standard audio cord kit, standard accessories/adapters, etc. However, sometimes the user doesn't need the entire standard gig kit, or needs two or more of some of the kits or individual items. When pulling the equipment for that user, we would update the gig kit at station #1 (a location) with the modified standard (which can be done far ahead of user checkout time) and then when the user is actually there, they simple check out that station. 

The problem I have is in the reporting. If something goes missing, I would have to nest upward (or whatever the term would be) and keep track of dates to find the user it was assigned to which isn't too bad for a few missing items at audit, but is a pain for many items especially if there are several layers of nesting. Also it isn't easy to see everything a user has because of the nesting. E.g. do they have 3 camera batteries? I would have to go into the user, then to gig kit and then each camera kit to see how many batteries each has. Would be great to be able to select a user and see the kits checked out and the kit contents all at once. Okay so that is my use case. 

I am not sure if this would be useful to anyone, but If I were a better programmer, this is the avenue I would pursue to contribute because it seems like it wouldn't need a lot of program wide structural changes (possibly only an extra field and some updating code that traces parent/child relationships recursively, but maybe that isn't so easy): 

 ---- Track the top level parent

The top level parent in my case would always be a user or a warehouse location. Then running a report on a user by top level parent would still give the same information as written now when running a report on a user, but could also show any nested assets as well. 

I wish I could be of more help directly but hopefully I can contribute in other ways.

**Comment by Compuche** [comment]
Alright..  I have gotten approximately 30 kits and their tools in and we're playing with it now, but things are not working like they should.  We need to ability to search individual tool part numbers, find out what kit they belong to, then check out the kit (along with all the tools it contains) to a technician.  There doesn't seem to be a way to do this easily, unless I have things all mucked up. This is where the Parent/Child relationship work well with Asset Tiger.  I would like to hear other's suggestions on how to get this done in Snipe-It.  Thanks in advance!

**Comment by snipe** [comment]
We have a rough version of this now on develop in https://github.com/snipe/snipe-it/pull/6756 - still needs some refinement, but worth testing if you're into that kind of thing.

**Comment by jovibroz** [comment]
Any new progress with this "kits" feature?
