### ISSUE TITLE
Checkout Asset show people from different companies when typing name.

### ISSUE THREAD

**Issue by Hsherif90** [snipe/snipe-it#5649]
#### Please confirm you have done the following before posting your bug report:

- [NO] I have enabled debug mode 
- [YES ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Able to assign assets to people from different companies in checkout asset page by typing in last name in search bar.

Tested on Demo v4 snipe-it, was able to recreate successfully.

**Expected behavior**
Names from different companies should not pop up.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.3.0
 - OS: [e.g. Ubuntu, CentOS] Windows 7 x64
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.1.6

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 7 x64
 - Browser [e.g. chrome, safari] Firefox 
 - Version [e.g. 22] 60

**Comment by Hsherif90** [comment]
Is there a quick fix for this?
Am I the only one facing this issue?

**Comment by Hsherif90** [comment]
@snipe any clue on this??

**Comment by dmeltzer** [comment]
Is full multiple company support enabled?

**Comment by paulhite** [comment]
For what it's worth, we are using 'companies' within Snipe to separate our individual departments that want their own silo of assets (otherwise they would be able to see and modify each others), but we rely on the fact that they can check out items to a single set of users. Although I understand it probably makes more sense to have this set where you can only see users from your company, it would break the way we use Snipe. I put in a feature request in the past to add "full multi-department" support, but it was shot down.
