### ISSUE TITLE
Ability to change the person it's checked out to, without checking it back in.

### ISSUE THREAD

**Issue by BarryCDV** [snipe/snipe-it#5663]
v4.2.0 - build 3508 (master)

It gets frustrating to have to check in an asset before it can be issued to another person, there are occasions where an assets person needs to change but it doesn't require any work to be carried out by IT so often doesn't need to be "checked In". 

It would also be helpful for when we are awaiting the return of an item to be able to assign it to the Technician who is expecting it to show that they have the responsibility to chase the existing user to send it back.

Several times an Item has been left "Awaiting Return" for weeks, because the Technician simply forgot about it.
 
To get around this I would like the ability to assign it to the Technician to help keep on top of the assets true status.

**Comment by snipe** [comment]
> To get around this I would like the ability to assign it to the Technician to help keep on top of the assets true status.

You'd still need to check it in and back out. That's just the nature of how the system is intended to work. Otherwise, it would get very confusing as to what's *really* checked out to someone versus assigned to someone. Checking an asset out to someone is how it gets assigned, and I don't imagine that changing any time soon. We are considering a faster "checkin and check back out" option on the checkin screen, but I don't think we're prepared to change the fundamental way assignment/checkouts work.
