### ISSUE TITLE
LDAP Sync not not working: The first name field is required.The username field is required.

### ISSUE THREAD

**Issue by spirritus** [snipe/snipe-it#5719]
#### Please confirm you have done the following before posting your bug report:

- [* ] I have enabled debug mode 
- [* ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
LDAP (AD) login works, however when trying to use ldap snyc the following error is reported:
The first name field is required.The username field is required.

Username Field: sAMAccountName
LDAP First Name: givenName
Last Name: sn
LDAP Authentication query: sAMAccountName=

**Expected behavior**
Do the sync.

**Server (please complete the following information):**
 - Snipe-IT Version 4.4.1
 - OS: Debian Jessie
 - Web Server: Apache2
 - PHP Version 7.0

**Comment by snipe** [comment]
This is almost always a settings issue. LDAP sync does work. Try using `givenname` (instead of `givenName`) and `samaccountname` (instead of `sAMAccountName`), per [the recommendation in the docs](https://snipe-it.readme.io/docs/ldap-sync-login#section-configuration). 

<img width="408" alt="ldap_sync___login" src="https://user-images.githubusercontent.com/197404/41733634-4c94de0c-7539-11e8-902a-fcbceb79a791.png">

**Comment by spirritus** [comment]
awesome thx, that worked!

**Comment by spirritus** [comment]
Awesome thx, that worked!
