### ISSUE TITLE
Change the name on a table header

### ISSUE THREAD

**Issue by dschaffer152** [snipe/snipe-it#576]
Hello. I have a question about changing the name on something. The thing I'd like to change I'm going to call a table header because I'm not sure what else to call it. To give a better understanding, when your looking at the assets there's a setting you can turn on called "Display Asset Name". After you turn that on and look at your assets you can see a "Name" table header show up. What I'd like to know is if there is a way to change that from "Name" to something else like "Shelf"

![snipe-it](https://cloud.githubusercontent.com/assets/11162496/6414112/1cf2e300-be63-11e4-8852-68d799577f55.JPG)

**Comment by snipe** [comment]
As other have mentioned in Gitter, you can change this in the language file, but the issue is that when we update that language file (to add more strings for new features, for example), your change will get overwritten. If you can remember to change that string back whenever you update it, language files may be your best bet here. (I would suggest creating your own language files by copying the `en` directory, but then when we add new language files, your version won't have the new strings.)
