### ISSUE TITLE
Importer changing the category of assets already in the database

### ISSUE THREAD

**Issue by Arsenal10108** [snipe/snipe-it#5855]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have created Custom Categories for our Chromebook inventory (Cart Chromebooks, 1:1 Chromebooks, Loaner Chromebooks etc) 
When I upload CSV file of assets of the same model but different category it changed all the of the assets of that model to the category of the last import. I don't know if it matters but this seemed to happen after I Imported a CSV of Assets with mixed Category's and only seems to change the assets of the same model. Leaves the other Models (same Category) alone. 

**To Reproduce**
Upload CSV of assets with category of "Cart Chromebooks" - Everything looks good
Go to upload a CSV with a category of "Loaner Chromebooks" and it changes all of the Cart Chromebooks (of the same model i may add) to that category. (doesn't matter if I check or un-check the update existing values)

**Expected behavior**
The imports would not modify existing assets categories if they are not on the CSV file. 

**Screenshots**
no really applicable?

**Server (please complete the following information):**
 - Snipe-IT Version  - 4.4.2
 - OS: [e.g. Ubuntu, CentOS] Ubuntu 16.04 LTS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version - 7.0.30-0ubuntu0.16.04.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] WIndows 10
 - Browser [e.g. chrome, safari] Chrome and firefox (tried both)

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on Ubuntu 16.04 LTS and Apache 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Composer
- Include what you've done so far in the installation, and if you got any error messages along the way. Nope Install was good
- Indicate whether or not you've manually edited any data directly in the database Have not. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by EarlRamirez** [comment]
Can you share the header of your CSV, please ensure you omit any private details. I am looking at a similar issue where the models are also being changed; however, I am not able to reproduce it.

**Comment by EarlRamirez** [comment]
@Arsenal10108, I was able to reproduce this using the below sample.

Original import sample
Company,Item Name,MAC Address,Model Name,IP Address,Servicing Location,Model Number,Serial Number,Manufacture,Category,Location,Status,Asset Tag
Company1,AP001,d8:b1:90:cd:03:1c,Cisco 3700E Access Points,1.1.1.1,Default Location,AIR-CAP3702E-A-K9,FTX1924S0PQ,Cisco,**Access Point**,Production,Deployed,sam0000347

As expected everything went well.
![image](https://user-images.githubusercontent.com/12306859/42802922-f64ef48a-89d6-11e8-83f6-28f53d678f3d.png)


Same details with the exception of the Category, this time the category is _Cisco Access Point_ 
Company,Item Name,MAC Address,Model Name,IP Address,Servicing Location,Model Number,Serial Number,Manufacture,Category,Location,Status,Asset Tag
Company1,AP008,d8:b1:90:dd:03:cc,Cisco 3700E Access Points,2.2.2.2,Default Location,AIR-CAP3702E-A-K9,FTX1924S0PQ,Cisco,Cisco Access Point,Production,Deployed,sam0009000

The Category changes as 
![image](https://user-images.githubusercontent.com/12306859/42802955-11df945c-89d7-11e8-988f-42725c701d0c.png)

Coming to think about it, it makes sense because categories are unique so this behaviour is expected, check out the code below 
-----------------------------------------------------------
 public $rules = array(
        'user_id' => 'numeric|nullable',
        _'name'   => 'required|min:1|max:255|unique_undeleted',_
        'require_acceptance'   => 'boolean',
        'use_default_eula'   => 'boolean',
        'category_type'   => 'required|in:asset,accessory,consumable,component,license',
    );
--------------------------------------------------------------------

**Comment by Arsenal10108** [comment]
Thanks for the reply Earl, Wouldn't the two category names be unique in this instance? other than they have the same ending. 
Where would I go for the label settings? I cant find anything other than the obvious printable labels under admin settings but I don't think that's what your talking about. Are the labels something I could put on my Import?

**Comment by dmeltzer** [comment]
This is a result of the fact that in the importer we treat asset model names as unique currently, even though they do not need to be.  Need to think about what the unique constraints are on an asset model  (model name+number+category(+manufacturer?)) And enforce that somewhere, and then adapt the importer to match.

**Comment by EarlRamirez** [comment]
@Arsenal10108 was referring to status labels and yes! It can be imported or you can create a _cart_ and _loaner_ location, which can also be imported, at my organisation we I use status labels which also appears on the dashboard under Asset by Status

**Comment by EarlRamirez** [comment]
@dmeltzer thanks for the correction :)

**Comment by dmeltzer** [comment]
yes

**Comment by sabsamu** [comment]
still relevant

**Comment by G13312** [comment]
I am having the same issue, when I import assets with a category it affects assets that are not in my import csv.

**Comment by amlamarra** [comment]
This is NOT fixed. It just happened to me today. Version 5.3.6 build 6567 (master).

**Comment by uberbrady** [comment]
How would you want this to work? As it is now, Asset Models live in a category. They can't live in two categories (in relational DB parlance, an Asset Model "Belongs To" a Category). You'd have to make a separate, similar model that lives in the second category I'd guess? That would be a lot of duplication and very easy to mess up though.

I wonder if your use case might be better-suited with custom statuslabels? E.g. model is "Samsung Chromebook 12345" category is "Chromebook", Statuslabel can be "Cart," "1:1," "Loaner"?

**Comment by amlamarra** [comment]
Ok, I didn't know that the category was tied to the model. I figured we could use the categories how we see fit. For instance, I wanted to have 2 different categories for our servers, a Hypervisor and a Bare Metal category. But there may several servers of the same model with different categories. I suppose I could use a custom statuslabel. Or maybe the Notes field.

**Comment by uberbrady** [comment]
Depends kinda on what you're trying to do; but having multiple "Deployable" statuses is perfectly OK.

**Comment by michaelfahy** [comment]
TIL the Model Name is the name of the Asset Model in Snipe-IT and not necessarily the name that the manufacturer gave to the Asset.  Also it seems like the Asset Model in Snipe-IT depends on the values in both the Model Name and the Model No. fields.

We have, for example, MacBook Pros that we deploy in different ways for which we want different EULAs. The EULA is part of the Category, so we created different Categories for the different EULAs and thought we could assign MacBook Pros with the same Model Name and Number to different Categories depending on how they were being deployed. 

From this thread it seems like we will need to create different Model Name and Number combinations for the different deployment scenarios in order to assign different Categories which we need for the different EULAs

So it seems like the Category is rather useless and should really have been incorporated into the Asset Model.  It only gives the ability to add a EULA.
