### ISSUE TITLE
Bulk Checkin & Checkout

### ISSUE THREAD

**Issue by itsmeowen** [snipe/snipe-it#588]
Dear Snipe
Many thanks for providing us such wonderful tool, i'm just writing to thank you and ask if it was possible for us to bulk check-in and checkout to a specific user?

**Comment by kobie-chasehansen** [comment]
We had talked about bulk user checkin a few days ago in https://gitter.im/snipe/snipe-it. I will go ahead and put that transcript in here so we can open it up to further discussion.


kobie-chasehansen February 25 2015  
what do you think of an option to check all assets in for an employee after termination? My thoughts for this feature would be a drop down when you view a user to maybe email a report to HR containing all physical assets. Once HR clicks a link in the email that user is automagically disabled and all assets get checked in/returned to inventory.
or maybe the user gets put into a pending term type status and desktop finishes the checkin process after inspection

snipe February 25 2015  
I had thought about that, but my concern is that stuff will get lost because it’s actually too easy
For example, if the employee leaves with an asset, if you one-click it, you may not realize it never actually made it back to you

kobie-chasehansen February 25 2015  
yeah so maybe the better idea is the pending term status and that users asset list has drop down boxes next to each item saying return to inventory, undeployable, archived
i know for things like keyboards and mice we throw them out pretty often after a term

**Comment by madd15** [comment]
Playing around with this on the user view for admins.
![bulkcheckin](http://i.imgur.com/f2OWZFn.png)

**Comment by snipe** [comment]
@madd15 I think this would be added as an option int he bulk actions dropdown

**Comment by rp-tech** [comment]
This would be really useful under the licensing section.

For example, I have 150 users on our managed antivirus platform. It would save me a ton of time being able to check out a license for every single one of these users using a bulk action.

**Comment by rp-tech** [comment]
I'd like to expand on this topic as well - the ability to perform bulk actions on users in general would be very useful - e.g. set 100 users to the same location, etc. or even if you wanted to do a mass password-reset having the ability to modify that field as such (at least until AD authentication comes along).

Thanks all!

**Comment by RobMSeagate** [comment]
Sorry to bring this back from the dead, but I'm interested in seeing more bulk options too. Bulk re-assignment (check-in / check-out) would be a blessing. In my case there is one person responsible for a long list of items on a manufacturing shop-floor; if that person is replaced, it would be great to re-assign all assets in as few clicks as possible.
Additionally, if a Manager leaves, it would be great to re-assign all staff linked to that manager to their replacement.
Thanks!

**Comment by dudeincali** [comment]
I would love this as well, because just importing 1000 assets tied them all to one user. Also, the location field (just like user import) is inaccurate. Need bulk check in/out.

**Comment by neilreich** [comment]
I would like Bulk check in/out ability as well

Use case - as a field tech I would like to be able to scan the asset tags of a loaner laptop, projector, diagnostic tool and cart with a bar code scanner and then click bulk check out and have those assets assign to me for 1 week.  After that week I want to click bulk check in and then use the bar code scanner to check in all the equipment that I used for that week.

As a team manager I would like to bulk assign consumable assets to a list of employees. IE have bought 30 flashlights (consumable asset)  and I would like to assign 1 to each of my 15 employees by name.

Thanks!

**Comment by veen1981** [comment]
First, thank you so much for all the work on this project! It has been a life saver! I too would love to see this feature added. I work at a Community College which has over 3000 computers deployed across campus, many of which are installed in labs. Being that these are shared systems, I have been checking them out to departments I created vs an individual user. Needless to say, checking out 30 assets to one user can become quite the monotonous task! If I could select 30 devices and check out to one user that would be amazing!

**Comment by JtothaILL** [comment]
I know i'm REALLY late to the game, but I wanted to see where the bulk check in/out conversation was. I work for a production company and generally check out 100 assets every production. This includes each camera, every microphone, every Pelican case...etc. Having a bulk check in would save a huge amount of time.

**Comment by SimoneTredoux** [comment]
I'd also really love this feature!
We deal with large numbers of assets which come in and go out in bulk (200+ assets at a time).
All assets being sent to a specific company get checked out to one specific user (the guardian) who then controls the distribution of the assets separately (using their own system). It would be so useful to be able to check-out multiple assets to a single user simultaneously?

**Comment by timwsuqld** [comment]
It seems #2349 only partially fixed this? We can bulk checkout hardware, but not licenses.
Ideally, I need to assign a seat of a license per laptop for a specific license, doing that in bulk would be very nice

**Comment by AzureusNation** [comment]
I second this to bulk checkout licenses. We have over 2000 desktops/laptops and want to put our volume licensing keys on here so we can keep track of seats. Going to be a lengthy job assigning 2000 windows 10 licenses and 2000 office licensed...
