### ISSUE TITLE
Improved view of asset warranty information

### ISSUE THREAD

**Issue by dvogelho** [snipe/snipe-it#5905]
- Snipe-IT Version: v4.6.2 build 3844 (gbbb15d610)
 - OS: Debian: Debian GNU/Linux 9 (stretch) version 9.5
 - Web Server: Apache/2.4.25
 - PHP Version: PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )

**Is your feature request related to a problem? Please describe.**
No, this is a complete new enhancement request.

During the budget planing in my organisation, I also need to take care about hardware replacements of our IT employees and it would be great to have a warranty report / view (navigation) which can be used for this to have a better overview about the warranty status of all existing assets. 

**Describe the solution you'd like**
I'd like to have a report function or view where you can easily filter or see all assets where the warranty  will expire in the next 30/60/90/180 days, will expire this year or is already expired.
In my opinion this will improve and keep the life cycle of our IT assets and to have all the information available for the budget phases.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by snipe** [comment]
That's a little trickier than it seems, unfortunately, since the warranty expiration is calculated based on the purchase date and the associated warranty length, it's not a field we can easily sort on in the database.

This could be simplified by implementing #5925, but not sure if that's something I want us to do, as I don't agree with the use-case presented there.

**Comment by achamberlain1984** [comment]
I'm certainly in favor of report options being available to report on warranty details beyond the automated email currently received.  My head of IT would like the ability to be notified at different times before warranty expiry on some hardware as negotiations over renewals can take longer on some hardware than others.

**Comment by snipe** [comment]
> My head of IT would like the ability to be notified at different times before warranty expiry on some hardware as negotiations over renewals can take longer on some hardware than others.

Not sure what you mean. If your cron is set up to daily, you can set whatever threshold you want, and you'll get advanced notice based on that threshold.

**Comment by achamberlain1984** [comment]
An example to help clarify:

Server support contracts need 30 days notice of renewal as they only require a quick audit and sign off.
Workstation warranties we don't renew so don't need notification of.
Office 365 licenses again only need 30 days for audit and sign off.
ERP support however needs at least 60 days to revisit contract terms, discuss with other potential suppliers etc.

So we have to notify based on the longest time we'd need for a renewal, whereas if I can produce regular reports (even if these are manual) I can tailor the report based on the products I'm looking at.

**Comment by andreasoc** [comment]
@achamberlain1984 i agree completly with you 
i have the same need, i'm IT in my Company and now this is the workaround for the license/contract:
- if a SERVER support expires on 31/12/2018 and the contract provide 30 days notice for renewal
- i configure the termination date on 31/12/2018
- setup the Expiration Date the date of notice , in this example, 30/11/2018, because snipe , now, check this date for the alert.
it would be enough to add a date field "need days notice of renewal" with a check box and after click on checkbox appear the calendar and setup the date or type the days. Near this field add an checkbox if i want receive alert with this field; this check exclude the expiration data for the alert.

**Comment by andreasoc** [comment]
yes!!! i cant' wait for this

**Comment by dvogelho** [comment]
Indeed, it's still required and necessary quickly

**Comment by dbotwinick** [comment]
This and #5925 are critical. Those two are essentially what I wanted when I decided to evaluate using Snipe-IT in my organization. Without those features, I'm going to look elsewhere. So from my perspective, this is pretty important...

**Comment by dbotwinick** [comment]
Ping.

**Comment by andreasoc** [comment]
yes

**Comment by dvogelho** [comment]
still required

**Comment by silver0a1** [comment]
This is still a big deal especially for MSPs.

**Comment by gaurangaschleusener** [comment]
Definitely a useful feature, one that I am relying on to present a Proof Of Concept with this program as a hosted solution.
We have all kinds of ICT equipment deployed throughout the country and would like a zoomed out, view on assets that have warranties expiring soon, regardless of location/date purchased/etc.
Some customers are across multiple locations so presenting a bigger picture is super necessary.
