### ISSUE TITLE
When checking in assets for a user, return to that user not 'all assets'

### ISSUE THREAD

**Issue by diwanicki** [snipe/snipe-it#596]
bug/feature? If I'm checking in multiple items from a user, being returned to the 'all assets' view after checking in each asset results in having to search for the user I was working on all over again.

**Comment by violetrain** [comment]
Same for checkin in multiple licenses, instead of being returned back to the assets view you are dropped to licenses overview and need to search for the asset again.

**Comment by snipe** [comment]
This is a more complicated problem to solve, unfortunately, since there are multiple ways you could have gotten to the checkin page. For example, you might be checking in multiple from one user so you want to be redirected back to the user page, but someone else (or even you in a different session) might be checking in a bunch right from the assets page and you would want to be redirected back there instead.

**Comment by snipe** [comment]
I have this on develop, but it needs to be tested. I haven't implemented for accessories yet.
