### ISSUE TITLE
when upgrading to php7.1.x

### ISSUE THREAD

**Issue by SSOHPG** [snipe/snipe-it#5984]
more an FYI but when i switched from php 5 to 7 on centos7 i had to install php71u-json.x86_64 as well because this is apparently not included in the base php7 install anymore.

apart from that the upgrade of php and of snipe went like a breeze!

**Comment by danr12** [comment]
Next version of SnipeIT suggests we need PHP 7.1.3 minimum for compatibility but the latest CentOS 7 repos only allow me to upgrade to 7.1.19?

**Comment by EarlRamirez** [comment]
This is because you most probably used the IUS repository packages
php71u* and this is okay because this version is 7.1.19 meets the
minimum requirements so you will not have any problem upgrading to
version 5.0 of Snipe-IT. 

The IUS repository contains php72u (version 7.2.x), I haven't tested
that version with CentOS but will give it a try and if successful,
update the install script and create a PR so that new installations
will have this version moving forward.

**Comment by danr12** [comment]
Thank you Earl. I deleted my comment as I realised I was just having a Monday morning moment :) And yes it was the IUS repo. I did a test install on a CentOS VM and the install script looks like it's installing php72 already from memory. 

Thanks for all your help.

**Comment by EarlRamirez** [comment]
No worries, 

hmm, that is strange, was just looking at the script and can see that
php71u* for the PHP versios

    PACKAGES="httpd mariadb-server git unzip php71u php71u-mysqlnd
php71u-bcmath php71u-cli php71u-common php71u-embedded php71u-gd
php71u-mbstring php71u-mcrypt php71u-ldap php71u-json php71u-simplexml
php71u-process"

Anyway, as long as you are good we are good :)

**Comment by danr12** [comment]
Yes you're correct, I just checked it as well. Perhaps I'm getting my wires crossed here. Either way it doesn't matter now :) 

Thank you for your contributions!
