### ISSUE TITLE
Custom Field type of checkbox

### ISSUE THREAD

**Issue by carock96** [snipe/snipe-it#6078]
**Server (please complete the following information):**
 - Snipe-IT Version - v4.5.0 build 3701
 - OS: [e.g. Ubuntu, CentOS] - Ubuntu 4.15.0-30-generic
 - Web Server: [e.g. Apache, IIS] - Apache
 - PHP Version 7.2.7

Instead of a BOOLEAN text box where a user has to type in the yes/no 0/1 value, it would be more error resistant to use a simple checkbox.

Another alternative for the BOOLEAN type is to have a select list instead of a blank text box.

**Comment by MysterAitch** [comment]
+1 

The feature is still new enough that the [documentation for v3.6.2](https://snipe-it.readme.io/v3.6.2/docs/custom-fields) still shows up when searching for details about custom fields - without any note about the boolean data type.

In addition to this, the error message of `The <fieldname> must be true or false.` that appears under the field's input box is very vague/unhelpful in that it doesn't contain any guidance that the value should be `0`/`1`. 

Perhaps one option as an intermediate solution for the confusion is that if a user enters the string "true" or "false" or "" then it gets converted behind the scenes to `0`/`1`/'null'? But I do agree that a checkbox (or `true`/`false`/`unset` radio buttons) would be a better solution.

**Comment by chemnic** [comment]
Still an issue in 4.6.6.

![image](https://user-images.githubusercontent.com/3452877/48266441-05499080-e3f5-11e8-8fee-c446a63bce4e.png)

**Comment by cliff-LINKS** [comment]
+1

**Comment by pfenning-IT-OPs** [comment]
Still an issue.

**Comment by nspaul** [comment]
I just tried making a boolean custom field and was confused that it showed a text box to fill in rather than a checkbox. The field also accepts any text, and I'd like it to be just a straight boolean, so that I can query it based on that logic using the REST API.

**Comment by ghost** [comment]
This is confusing. Why isn't boolean a checkbox. A textbox that asks for a written boolean value is very odd. If I make a listbox and enter 'True' and 'False' as values, it will allow me to save the field but when I attempt to update an asset it fails and tells me that the only valid values are 'true' and 'false'. This is even more confusing.

I changed the possible list box values to 'true' and 'false' thinking that perhaps the issue was case, but it won't accept these either. It will only accept 0 and 1. I can't imagine that some logic to interpret/display True/False instead of 1/0 is that difficult or time consuming to add.

Since these values are null when the fields are added to an asset, it makes sense that I can change them back to null but this isn't straightforward either. The value in the list box has to be changed back to "Select boolean" to set the value to null. Maybe it makes more sense to set them all to false by default when a new boolean value is added to an asset.

**Comment by inietov** [comment]
System already can use textfields as booleans.  I think I recall that when this issue was posted, the checkbox customfields weren't functioning correctly, but now they do, and I think the options that the system have about this issue are enough now. I'll try to explain myself.

Personally I believe it's a better solution than using checkboxes, because the checkboxes can be a group of different things that can be selected or not, and a boolean only can take a `true` or `false` value. For a silly example maybe, with a CustomField of type checkbox we can name the field 'Colors available' and have an array of [blue, white, silver] values and only have checked the colors that we have available for assets. Surely better examples can be thought by our users. But if the custom field have to be a boolean, a listbox made more sense, because it ONLY can take one value at a given time: `true` or `false`, which a listbox cover.

Of course that I can be wrong, and if enough users take on this issue is that they really, really need or want that a single checkbox represents a boolean field, then we can consider it again. But for now I think that the use case for this is already covered.
