### ISSUE TITLE
Ability to change status during checkout for Assets

### ISSUE THREAD

**Issue by brandenk514** [snipe/snipe-it#6081]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.3
 - OS: Ubuntu 18.04 LTS
 - Web Server: Apache
 - PHP Version: 7.2

**Is your feature request related to a problem? Please describe.**
I can not change the status of an asset when I am checking it out. I want to define the status of an asset when I am checking it out. I would like to keep track of all the asset meant for a specific purpose (ie. testing, monitoring, etc.) This also follows the issue of having deployable assets that are in storage, yet when I check them out, I get a meta-status for "deployed" and a status label for "In Storage".

**Describe the solution you'd like**
Add the status box. Similar to the one on the check-in page. 

**Describe alternatives you've considered**
I haven't thought of any yet.

**Comment by Jarli01** [comment]
Changing the status at checkout means you'd have to have custom status values. Wouldn't just supplying a note work well enough in a case like this where you want to checkout an asset for 
"Offsite photo shoot" or some other case. 

The status field isn't designed for what you're asking. 

PS, just a user providing input.

**Comment by andrefecto** [comment]
I agree this would be extremely helpful to have on the Checkout screen.

Explanation of our workflows for context:

**Scenario 1, "Reimage"**
Asset D06438 is currently checked out to brandenk514. He is having some computer problems so we bring it back to our office to reimage it. We go to the Asset, click "Checkin" and change the status to "reimaging" (assume reimaging has a meta of Deployable). We reimage the computer and then want to "Checkout" to the user. We click checkout, put the user's name in and hit save. The current status then of the Asset would read "reimaging" with a meta of "Deployed" next to it. This makes the pie chart on the dashboard inaccurate. The computer isn't still "reimaging" it's "deployed". We would like to change the status at the time of checkout to "Deployed" (or something along those lines) when we are checking it out to the user. 

**Scenario 2, "User left the organization"**
Asset D06438 is currently checked out to brandenk514. He has left the organization so we go and take his computer back. We go to the Asset and click "Checkin" and change the status to "In Inventory" because it's going to sit on our shelf for an undetermined amount of time. We finally are going to deploy that computer because we have a use for it so we go to the Asset and click "Checkout" and assign it to the user. The Asset will not have a status of "In Inventory" with a meta of "deployed" which is again misleading for the dashboard pie chart (and another other metrics by search we may run.) 

**Ways that we have thought of to understand how to use the statuses in Snipe-IT:**
1) In Scenario 1 when we check the computer in we put it as a status of "Reimaging" which has a status model of "Pending." This makes it undeployable. This kind of makes sense because the computer is being worked on so it's undeployable. But when we are ready to redeploy it, we have to navigate to the "Edit Asset" screen to change the status, then we can go and click the "Checkout" button to actually assign it to someone. This method around this kind of works but causes an extra step of editing the asset that could be solved by letting us change the status on the "Checkout" page.

2.A) Every time we do something with the computer, we check it out to a user or a location. For example Scenario 1 we would take it from the user and click "Checkin" changing the status to "Reimage" (which still has a "deployable" meta.) We then go to the Asset and click "Checkout" when we start the reimaging process and assign it to our office or the person reimaging. Once finished with the process they click "Checkin" and change the status to "Deployable" (meta of Deployable.) Then when they deliver it to the user they click "Checkout" again and assign it to the end user. This was a total of 4 checkin/checkout activities that are redundant if we could change the status on the "Checkout" page. Our IT office (and I would think MOST) already track who things like who is working on a computer or a problem with one through a ticketing system. If not, when they check the computer back in they could use the Notes field to say why they're checking it back in. 
2.B) In scenario 2 where a computer is "in Inventory" (meta deployable) because we got it back from a user, we would have to edit A) go the the full asset edit screen to change the status from "In Inventory" to whatever the new status would be, or we have to go through the 4 checkin/checkout steps outlined in 2.A to get the status where we would want it to be.

The reason we care about the "Status label" so much is because the pie chart on the dashboard could be EXTREMELY useful (and any kind of text-based searching we do) at a quick glance. We could have Status Labels as follows: "In Inventory", "Deployed", "Loaned Out", "Out for Service". The piechart would then give us an easy way to see how many computers are in our inventory that we can give to people, an easy way to see how many computers we have deployed, if we have any loaned out, and how many we have out for service. The current way that status are setup where you can't change them unless you manually go in and edit the asset or do a Checkin, makes these statuses unreliable when they take the "deployed" meta. 

Please let me know if I need to clarify anything, this is a great program and just want to help make it even better!

**Comment by lapf10** [comment]
In my case this option would be very useful because at this moment I always have to edit the article to change the state after the checkout.
I think it would be a good idea for the project to add this option

**Comment by aparis99** [comment]
Paid SnipeIT client here. I also highly support changing a status during Checkout. When we order machines and receive them, we bring them in as an In Prep status. When we check out, we want to also change them to Active.

**Comment by bricelabelle** [comment]
I also agree we would love to see this. If an asset has a status of storage and you check it out, it still shows up in the list of items assigned to the storage status which doesn't make sense. Also, we use status labels to distinguish between a primary and secondary / departmental computer for someone which is important to know during upgrade cycle time. It seems like a like of customers of Snipe-it are already setting status labels before or after checkout, so it would be nice to make it a 1-step process.

**Comment by dantothebert** [comment]
I am going to parrot what other users are saying.  It would be a great feature to have the ability to change the status in the Check Out screen.  It makes it more efficient for our IT team, because once we check out the asset, we have to go back to the asset again to edit it and change the status again.  In our case we put "deployed" It's weird to see something say "in stock" - "deployed"

**Comment by AZPacketPlumber** [comment]
Can this please be re-opened. It's one of the main gripes from our staff with SnipeIT.

**Comment by mailatbijoy** [comment]
Am also agree to what  andrefecto commented on Sep 26, 2018. Please some one look in to it.

**Comment by Cidwill** [comment]
We would love this also.  It's counter-intuitive to change status before or after a checkout.

**Comment by mpkr** [comment]
I have modified the code a little bit, and it is possible to change status when check out.
![2](https://user-images.githubusercontent.com/6811937/66288992-86f7b600-e905-11e9-8c0f-774cbaf8caa3.png)

I also made some changes:

- Add the checkin/checkout button to the view asset page.  
- When scan barcode to the "Lookup asset by tag", it will go to checkin/checkout asset page right away.
![1](https://user-images.githubusercontent.com/6811937/66289375-b5c25c00-e906-11e9-8987-abbfcb77461f.PNG)

If anyone interested in, send me an email at hnimtahn@gmail.com I'll send you the source code.
Cheers!

**Comment by Jarli01** [comment]
@mpkr I'm very interested, but would much prefer to merge this in as a part of a proper PR. 

Can you create a PR request?

**Comment by bricelabelle** [comment]
I agree, could you submit a pull request for just the status change on checkout? I don’t see us needing the other changes you mentioned. Thanks!

**Comment by mpkr** [comment]
I don't know how to create a PR, This is what I did:

`Step 1: Open File: snipe-it\resource\views\hardware\checkout.blade.php

Find:
=================================
@include ('partials.forms.edit.location-select', ['translated_name' => trans('general.location'), 'fieldname' => 'assigned_location', 'style' => 'display:none;', 'required'=>'true'])
=================================

Insert below:
=================================
<div class="form-group {{ $errors->has('status_id') ? 'error' : '' }}">
 {{ Form::label('name', trans('admin/hardware/form.status'), array('class' => 'col-md-3 control-label')) }}
 <div class="col-md-7 required">
	{{ Form::select('status_id', $statusLabel_list, '', array('class'=>'select2', 'style'=>'width:100%','id' =>'modal-statuslabel_types')) }}
	{!! $errors->first('status_id', '<span class="alert-msg"><i class="fa fa-times"></i> :message</span>') !!}
  </div>
</div>
=================================

Step 2: Open File: snipe-it\app\Models\Asset.php

Find:
=================================
public function checkOut($target, $admin = null, $checkout_at = null, $expected_checkin = null, $note = null, $name = null, $location = null)
=================================

Replace with
=================================
public function checkOut($target, $admin = null, $status_id = null, $checkout_at = null, $expected_checkin = null, $note = null, $name = null, $location = null)
=================================

Find
=================================
if (!$target) {
	return false;
}
=================================

Insert below
=================================
if ($status_id) {
	$this->status_id = $status_id;
}
=================================

Step 3: Open File: snipe-it\app\Http\Controllers\AssetCheckoutController.php

Find
=================================
use App\Exceptions\CheckoutNotAllowed;
=================================

Insert above
=================================
use App\Helpers\Helper;
=================================

Find
=================================
return view('hardware/checkout', compact('asset'));
=================================

Replace with
=================================
return view('hardware/checkout', compact('asset'))->with('statusLabel_list', Helper::statusLabelList());
=================================

Find
=================================
$asset = $this->updateAssetLocation($asset, $target);
=================================

Insert Below
=================================
$status_id ='';
if ($request->filled('status_id')) {
	$status_id =  $request->get('status_id');
}
=================================

Find
=================================
if ($asset->checkOut($target, $admin, $checkout_at, $expected_checkin, e($request->get('note')), $request->get('name')))
=================================

Replace with
=================================
if ($asset->checkOut($target, $admin, $status_id, $checkout_at, $expected_checkin, e($request->get('note')), $request->get('name')))
=================================`

**Comment by bricelabelle** [comment]
I tested the changes and created pull request #7517 for this based on the instructions @mpkr sent.

**Comment by mmgreen-edu** [comment]
Thank you for taking the time on this mpkr and bricelabelle. This looks to be very helpful for us. We have a bunch of requestable assets, and it seems strange to have them be listed as available, even if they've been checked out. By being able to, if nothing else, change the status manually, it takes it out of the list of available, requestable assets.
