### ISSUE TITLE
Allow users to set the Expected Checkin Date when Creating a New Asset

### ISSUE THREAD

**Issue by ericjsy** [snipe/snipe-it#6197]
Hello Snipe-IT world!

This is my first time posting, so I'd just like to thank you all for putting so much effort into this product. The care and attention to detail really shows! 

Now, regarding my request:

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.4 build 3881 (g522dc1db2) 
 - OS: RHEL 7.5
 - Web Server: Apache
 - PHP Version: 7.2.7

**Is your feature request related to a problem? Please describe.**
I'd like to streamline the workflow of creating a new asset that needs to be subsequently checked out. When we set the asset to a Deployable Status, the Checkout To field appears and we can select between a User, Asset, or Location. However, there does not seem to be a way to indicate the Expected Checkin Date. 

I feel like the Expected Checkin Date is an important field for bookings, and is something we regularly do when we create a new asset.

**Describe the solution you'd like**
I think it would be good if the Expected Checkin field followed the same behavior as the Checkout To field when a Deployable Status is selected. I'd like the date selector to appear as well.

**Describe alternatives you've considered**
Currently, we have to leave the Checkout To field blank when we create the asset. Once it is created, we can checkout and set the Expected Checkin Date as we normally would on the 'All Assets' page.

I don't think we can edit the checkout status afterwards either to set the Expected Checkin Date. This could also be a possible solution, but I think doing everything on the Create Asset page makes more sense.

**Comment by ZephyriusOne** [comment]
I agree with this post. Please add the "Checkout Date" and "Expected Check In Date" fields on the same page where you create an asset. Most times in our environment, we buy new laptops and they immediately get assigned to new/current employees. When creating the asset, I would rather just set the checkout/in dates here, rather than not assigning it, and then checking it out after it's created. Seems like an unnecessary step. Most of my fellow IT employees can't grasp this concept, and end up not setting any dates (when it would be very useful, like a loaner laptop for a week etc).

So far I have been really impressed with Snipe-IT. Keep it up!!
