### ISSUE TITLE
Booking system

### ISSUE THREAD

**Issue by ajaywazir** [snipe/snipe-it#6214]
**Server (please complete the following information):**
 - Snipe-IT Ve4.6
 - OS: Windows
 - Web Server:  IIS
 - PHP Version  7 or above

Hi 
We are an SI in Singapore. One of our customers is looking for asset booking cum project management system that can be made as a plugin for snipeit. 
Is any one open and willing to either develop this plug-in for us? 
Ajay

**Comment by grifu** [comment]
Hi,
In our school we also need a asset booking system.  We used phpshedulit (now, booked) for booking, but we also needed a platform for asset management and choosed snipet, which is great. 

I have no experience with Laravel and many time constraints to contribute, although I have already implemented a time  checkin Feauture in assets for snipeit with a datetime picker, which can be find in a forked snipeit in my GitHub.  

Eventhough these constraints I’m willing to contribute with this system with the help of others. I can help with the design and some development.

**Comment by grifu** [comment]
I'm starting to develop a booking system.
However, due to the lack of time for this, the system will be made gradually, in multiple steps:
1) I've made a simple form for users to define the check in and out dates and time. It is similar to the asset checkout form. This form is then sent to the manager. There is no date confirmation and users can make reservations for the same date.

Next steps:
2) When filling the form, users must define the "manager" which is the user responsible for the asset (in our case usually is a professor). The form is sent to the responsible user with a button for approval. If the reservation is approved, the mail sends a post to snipe-it to process the reservation sending it to the manager.

3) A table will be created to record reservation data (users, dates,...).
The table will allow to show in the datetime picker the available dates and time to make the reservation.

**Comment by grifu** [comment]
We are working on this feature.

**Comment by ajaywazir** [comment]
Hi
Yes. It is still very relevant to us
Ajay
