### ISSUE TITLE
Duplicate Serial Numbers Should Update Existing Values

### ISSUE THREAD

**Issue by jneljeff** [snipe/snipe-it#6228]
[Feature Request]

 - Snipe-IT Version v4.6.4 build 3885 (g05ea61421)
 - OS: Docker

Serial Numbers are more static than Asset Numbers in that they can never change whereas an asset number might change due to changes in numbering, worn stickers, re-purposing, etc...

**Describe the solution you'd like**
Make serial numbers (when set to be unique) function the same as asset numbers.  When a duplicate is entered or imported, update the existing fields and add to the device's history.

**Describe alternatives you've considered**
I realize this is a process thing, but considering that Serial Numbers are determined by the manufacturer and not the purchaser, it makes sense for this value to take priority over the asset number and it would go a long way to making this a core product for our company.

**Comment by snipe** [comment]
> When a duplicate is entered or imported, update the existing fields and add to the device's history.

I don't really understand what you're asking for here. Can you be more specific?

**Comment by jneljeff** [comment]
When data is imported, as long as the asset tag is the same, the other values will be updated rather than creating a duplicate asset, correct?  I'm suggesting since asset tags can arbitrarily change within an organization that we have the option of making the serial number the primary identifying value.

Use case: Our organizations asset numbers have a tendency of changing depending on where a machine is and what it's purpose is.  The only static identifying Mark is the serial number.  It would greatly reduce the number of duplicates imported if serial numbers behaved the same as asset tags and updated the asset tag field and created a history of all the asset tags for the one serial number.

⁣Sent from BlueMail ​

**Comment by jneljeff** [comment]
I mean... It's stale in the sense that no one else has said anything further on whether this makes sense or even possible.  I suppose it is ultimately a design choice.  I just want to make sure my suggestion is understood before this is closed.

**Comment by joemysterio86** [comment]
I had an issue while testing snipe-it where I have a device that I am trying to import. It imported correctly, so I changed the asset number on it within the csv (since we will be updating our asset tags on all devices internally). I attempted a new import with the updated csv but it created a duplicate instead. I assumed the update values check mark was not working correctly.

After searching for a while, I came across this thread. I then tried to update other values instead and it actually did update the existing asset.

So, I have to agree with @jneljeff that having the serial number instead of the asset number as the primary identifier would be most helpful. In our case, since we are starting fresh, it's not too big of a deal. But I imagine an organization who has been using snipe-it already and needs to update their asset tags will have a bit of trouble doing a bulk import.

**Comment by jneljeff** [comment]
Thanks, @joemysterio86. Glad to hear I'm not crazy in thinking this is a logical expectation. I ultimately hope to be able to script formatted reports from JAMF and SCCM to regularly update user assignments and hardware changes... Not being able to reliably catch an asset number change is really the only thing stopping me.
________________________________

**Comment by snipe** [comment]
We can look into making this an option, however many users don’t even use serial numbers, so it would break things for a lot of people if we switched it.

**Comment by jneljeff** [comment]
Just posting to keep this alive.  I've made the case with my team to build a proof of concept within our organization.  Has there been any further consideration on this issue?

**Comment by ljhsquall** [comment]
I agree on this as well. My company is using serial number as the primary identifier so it will be helpful is there is an option to switch.
