### ISSUE TITLE
SQL MARIDB error issue

### ISSUE THREAD

**Issue by abhalla89** [snipe/snipe-it#6237]
![image](https://user-images.githubusercontent.com/43584077/46104548-99db9480-c1a1-11e8-8edf-cc5974d60f39.png)

**Comment by snipe** [comment]
Please complete the issue template so that we can help you.

**Comment by EarlRamirez** [comment]
@abhalla89 This is the continuation if #6232, you don't need to create a new issue for this (duplicate issue). Will continue to work with you on the original issue after I arrived at my final destination.

**Comment by viktorfs** [comment]
I had that same issue. In my silly way of hurrying threw the install and not reading the instructions I installed the wrong version of MariaDB , Are you sure that´s not your issue because that´s the exact same error I got.
![migrateissue](https://user-images.githubusercontent.com/43443871/46152945-a1627280-c261-11e8-9a3c-137849496852.PNG)

**Comment by abhalla89** [comment]
i agree but my MARIA DB is coming from WAMP server so i cannot change it i believe , its inbuilt but i am trying to start fresh on windows server now
