### ISSUE TITLE
API Update to get licenses information by user id

### ISSUE THREAD

**Issue by NMathar** [snipe/snipe-it#6241]
**Server (please complete the following information):**
 - Snipe-IT Version: My current production version v4.1.11
 - OS: Debian
 - Web Server: Apache
 - PHP Version: 7.0

**Is your feature request related to a problem? Please describe.**
I discovered the nice Snipe IT API https://snipe-it.readme.io/v4.0/reference#api-overview  but im missed something in the API.

**Describe the solution you'd like**
I can get all assets for one user https://snipe-it.readme.io/v4.0/reference#usersidassets but i can not get the licences for the user. Something like this https://develop.snipeitapp.com/api/v1/users/1/licenses would be realy nice.

**Describe alternatives you've considered**
Another solution can be an additional filter in https://snipe-it.readme.io/v4.0/reference#licenses

**Additional context**
I think that's it. If there is already an solution for this i would love an documentation update.

**Comment by wsidl** [comment]
A cross reference would be from the licenses endpoint, provide a list of users that have licenses checked out.

Something like /api/v1/licenses provides the list of licenses while /api/v1/licenses/:id will provide more detail to the license including the users that have a license checked out.

**Comment by marcquark** [comment]
Hey @NMathar i thought i'd share my solution with you. Checkout information is already there in the API controller if you look at app/Http/Controllers/Api/LicensesController.php line 154

I simply patched the transformer (app/http/Transformers/LicensesTransformer.php) to include detailed seat information by adding the following line after 44:
`'seats_details' => $license->licenseseats,`

This is a completely dirty hack, i have no dev environment to run tests or anything, but it does the job for me. I can query the API for licenses and then iterate over them, and in a nested loop iterate over each seat, determining which seats have been checked out to which user/asset.
The seat details are a bit confusing at first. Here's what i found out through some testing:
license['seats_details'][i]['user_id'] is the admin who checked out the license
license['seats_details'][i]['asset_id'] if present, is the asset the license is checked out to
license['seats_details'][i]['user_id'] is the user the license is checked out to

user_id may be set if a license is checked out to an asset, but it's not really reliable (see bug #5155 ). so i just check if an asset_id is present and if it is, i query the API for the asset and determine the user from there. otherwise i trust what's in user_id

**Comment by marcquark** [comment]
I think the cleanest solution would be a license seat endpoint, which could also allow updating seats as needed

**Comment by NMathar** [comment]
Ok that's a first dirty workaround i think. 

I will have a deeper look into this issue after i finished some other projects. 

The best solution for our needs is to get the license for a user id directly not after many iterations but i think that's not that easy at the moment right?

**Comment by marcquark** [comment]
I don't know what would be easy and hard to implement. I'm generating reports for our finance department, which also includes assets and licenses that are not currently checked out. So i approach it from the asset/license endpoint anyway, i don't personally need a /users/:id/licenses endpoint. In fact going through users would complicate the program logic.

IMO the cleanest way would be to have a /licenseseats endpoint that can be queried, possibly with a mandatory /:id cause it has potential to generate considerable amounts of data in one query...

**Comment by wsidl** [comment]
@jwhulette looks like you've been doing some work. how are these changes coming along? Should we expect a PR for this?

**Comment by wsidl** [comment]
yes, this is still relevant

**Comment by snipe** [comment]
This fix is already on develop
