### ISSUE TITLE
Enhancement - Change to Expiration/Termination Date Fields

### ISSUE THREAD

**Issue by hansenc0705** [snipe/snipe-it#626]
Would be nice to have a list of options to pick from either as a drop down menu or as clickable buttons instead of a date field.

Would be nice to also default that selection maybe by a customized value from the settings screen

Think this should apply to both the licenses and assets
##

**Comment by snipe** [comment]
I'm not sure I understand - can you explain in more detail?

**Comment by kobie-chasehansen** [comment]
So instead of a date field where you manually input the expiration or termination dates they are calculated based off the purchase date and you just select the length of the agreement.

Example, I just purchased a software package, its under maintenance for a year. It would be nice to just select 1 year out of a drop down instead of clicking in the date field and entering a date.

and what would an enhancement request be without me producing a really bad mockup
![image](https://cloud.githubusercontent.com/assets/10247644/6567939/1fc99132-c6a6-11e4-9b73-23b37596cae6.png)

**Comment by madd15** [comment]
Maybe something like this
![hopethisworks](http://i.imgur.com/8n7dQbA.png)

**Comment by kobie-chasehansen** [comment]
that looks good as well.

With this change it will bring that field to just two clicks most the time instead of a click, date select, then year change or navigating the calendar itself an that could be 12 clicks.

While in here it might be worth setting the purchase date to todays date by default. Even with a default value it won't add any additional work to change it if the purchase was in the past.

On a somewhat unrelated note, what was the intentions of the exp date and term date?
