### ISSUE TITLE
need to remove unique in asset tag

### ISSUE THREAD

**Issue by KARTHIKEYANINDIRAN** [snipe/snipe-it#6312]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.3
 - OS: Windows 7
 - Web Server: xampp
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
Please tell me how to remove unique option in asset tag column

**Describe the solution you'd like**
I have drop column from phpmyadmin and added manually. But still its asking unique value

**Describe alternatives you've considered**

**Additional context**
I need a same value asset_tag in multiple assets. like one asset tag uses 7 assets. Please tell how to remove unique option in asset_tag column.

**Comment by snipe** [comment]
That's not possible, and would impact a lot of functionality. You'd be better off creating a custom field like "internal asset tag" and populating that. (Not to mention that it defeats the purpose of asset tags, by definition.)

**Comment by KARTHIKEYANINDIRAN** [comment]
Please let me know how to change "Please login" font color. which is available in login page. Please help on this.

**Comment by snipe** [comment]
@KARTHIKEYANINDIRAN 

Hi there - this issue is closed and doesn't seem directly related to your issue. Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)
