### ISSUE TITLE
Backup Utility Image/Attachment Capture

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#6373]
The Snipe-IT Backup utility NOT creating a SQL dump with images or file attachments uploaded, and zipping them up with a timestamp.

Generating a backup via the SnipeIT GUI or php artisan snipeit:backup creates a zipped timestamped of database but does not include any images or file attachments.

![2018-10-30_10-39-48](https://user-images.githubusercontent.com/31219479/47734570-290c1a00-dc30-11e8-9fcc-d5676c3bf113.jpg)

SnipeIT V4.6.6 
Server 2012 R2
Wampserver 3.0.6 64 bit
Apache 2.4.23
PHP 7.0.10
MySQL 5.7.14

**Comment by snipe** [comment]
It absolutely does though. I just ran a backup and this is what I see when I expand the file:

<img width="982" alt="screen shot 2018-10-30 at 12 28 34 pm" src="https://user-images.githubusercontent.com/197404/47744770-6330e800-dc3f-11e8-9b69-deff29d8107b.png">

I'd suggest tailing your app log when running a backup and seeing if there are any errors generated.

**Comment by jmartins1** [comment]
Out of curiosity, what are you running snipeit on top of?

⁣Sent from BlueMail ​

**Comment by snipe** [comment]
My local environment is MacOS, and our hosted customers run on Ubuntu. (Backing up files works for them too.)

**Comment by snipe** [comment]
(Also we have an internal dev that runs windows, but he's out on bereavement right now, so I can't ping him right now.) I do know that I've seen Windows choke on very long file paths in the past, but I don't think there's much we can do about that, as it's more of a Windows system limitation. But that's why I suggested tailing your app log (and possibly PHP logs) to see if the filesystem is kicking out any extra errors.

**Comment by snipe** [comment]
Makes sense - glad you’re all sorted!
