### ISSUE TITLE
Historical list of assets

### ISSUE THREAD

**Issue by Jorseff** [snipe/snipe-it#6385]
Hi all,
Is it possible to get a report of what assets were assigned to a particular person on a particular date? That is, rather than seeing a report of the things being checked in and out, can you put in a date and see everything that was currently with that person at that time? Many thanks.

**Comment by wghudson** [comment]
Aha! After much digging I found a request similar to mine. w00t.

Sure, we can comb through the history of an individual asset or a person try our best to figure things out, but filtering by date would be handy.  

If I may expand the idea a bit:  I'd like to be able to see what was checked out to a person (or to an asset or to a location) on a specific date or within a date range.  (Location is really what I'm after, but I would suggest a consistent history look up method for any check-out target.)

For myself, I want to be able to ask "what assets have been checked out to Location A: i) since the beginning of time, ii) before last November, iii) between May 8th and August 5th of this year."

There are some extra wrinkles with the "date range" option.  Such as, does an asset get shown only if it was checked out over the entire range, or does it get shown if it was checked out after the start of the date range (or checked-in before the end of the date range)?  Maybe showing everything but including the check-in/check-out dates cover this off...

I suppose I'm only partly extending the original suggestion, but actually proposing two separate, yet related things:

1) Filtering any history listing (activity, maintenance) by date range.
2) Adding activity history for locations.

Cheers!
