### ISSUE TITLE
Location Name - allow duplicates

### ISSUE THREAD

**Issue by jrhoades** [snipe/snipe-it#6416]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.6
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP 7.2

**Is your feature request related to a problem? Please describe.**
When trying to enter a location name that is already used, there is a uniqueness check that prevents duplicate names - "The name must be unique."

**Describe the solution you'd like**
We have multiple locations that have identically named locations eg they all have receptions, meeting rooms, board rooms, room 101 etc.  So what I'd like is for the location name uniqueness to just be for a location rather than system wide.  Eg each the uniqueness check is performed on the Parent location so we could have:

Head Office
- Reception

Branch Office
- Reception

**Describe alternatives you've considered**
Obviously I can prefix the locations with the parent location, but this seems a bit surplus. 

**Additional context**
 Internally in Snipe, each location is identified by a unique database ID, which MySQL enforces uniqueness on.  This uniqueness check must be performed in code.

**Comment by Jarli01** [comment]
The location name is the same in what you've described. This is already doable assuming you use a different location. 

![chrome_2018-11-12_14-55-22](https://user-images.githubusercontent.com/14837699/48371918-072c8180-e68b-11e8-9cf2-7b93993bd9b1.png)

**Comment by Jarli01** [comment]
If you use location like a GPS location, it is unique in the entire world. Every inch has a unique address. 

It sounds like you want to have 1 company, with multiple offices, so create multiple Locations like in the screenshot above. From that you can have duplicate departments such as Reception.

**Comment by jrhoades** [comment]
Thanks for the response.  I get what you are saying - use departments in a location as a location.

The problem with this approach is you can only checkout a device to a Location, so were we to use departments under a location, this wouldn't be specific enough as we couldn't specify the department, only the location?

**Comment by Jarli01** [comment]
So you want to be able to checkout an asset (accessory or license) to a location and department, is that what you're saying?

**Comment by Jarli01** [comment]
It sounds like you should use full company support.

**Comment by websafe** [comment]
Maybe an easier example of the problem with not being able to duplicate location names with `Full Multiple Companies Support` enabled.  We have multiple customers, each customer has an `Office` location and a `Kitchen` location and a `Warehouse` location. 

As I understand I won't be able to have:

- Customer1 -> Office
- Customer1 -> Kitchen
- Customer1 -> Warehouse
- Customer2 -> Office
- Customer2 -> Kitchen
- Customer2 -> Warehouse

and I' have to create locations in a "flat" way, like this:

- Customer1 Office
- Customer1 Kitchen
- Customer1 Warehouse
- Customer2 Office
- Customer2 Kitchen
- Customer2 Warehouse

Am I right? Is this by design? Or am I doing something wrong?
