### ISSUE TITLE
Print All Assigned - New Tab

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#6440]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.6
 - OS: [e.g. Ubuntu, CentOS] CentOS 7
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 4.1.24

**Is your feature request related to a problem? Please describe.**
When running through and auditing a team of people it's incredibly annoying to have to go back a page every time I want to "print all assigned"

**Describe the solution you'd like**
When clicking the "Print All Assigned" rather than using the existing tab, open a **new tab** for the user's report rather than using the existing tab that Snipe-IT is being run in. 

**Describe alternatives you've considered**
Using the functionality that exists and clicking "back" every time.

**Comment by jackka** [comment]
I know a hack.. But tsss! :)

**Comment by Jarli01** [comment]
I know the middle button trip to open a new tab, but that's just irritating to have to use for this.

**Comment by Jarli01** [comment]
Please reopen this feature request.

**Comment by nachoguapito** [comment]
can we add some text agreement during printing the assets?

like " I confirm that I have received the above laptop unit with the above configuration and confirm that I am personally responsible for any damage done due to mishandling and I authorize the company to deduct the cost from my salary account.

I agree that I will return the above laptop unit when I leave the company. "

**Comment by voxiox** [comment]
i still waitfor this feature. thanks a lot
