### ISSUE TITLE
Error with LDAP Filters

### ISSUE THREAD

**Issue by TwoTwenty** [snipe/snipe-it#6456]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

error on ldap test screen
ldap_search(): Search: Bad search filter  

**Screenshots**

https://pasteboard.co/HOZAnMn.png

**Server **

Snipe-IT version | v4.6.6  build 3926 (g1a10aa0dd)
Software License | AGPL3
PHP Version | 7.2.10-0ubuntu0.18.04.1
Laravel Version | 5.4.35

**Error Messages**
the test page shows:
 ldap_search(): Search: Bad search filter

messages from firefox debugging:
    [17:54:08] LOG.debug: Preparing to test LDAP logindebuglog
    [17:54:08] LOG.debug: Attempting to bind to LDAP for LDAP testdebuglog
    [17:54:08] LOG.debug: Attempting to login using distinguished name:cn=user,ou=CMS,ou=ADM,o=OUCdebuglog
    [17:54:08] LOG.debug: LDAP login faileddebuglog

when I attempt to login with a browser the snipeit app storage log:
[2018-11-26 17:54:19] dev.ERROR: There was an error authenticating the LDAP user: ldap_search(): Search: Bad search filter  

**Additional context**
- What method to install  (install.sh)
fresh install

when I am in the LDAP test and I put in my credentials with a bad password the message is 
 Login Failed. user did not successfully bind to LDAP.

when I use the right password 
 ldap_search(): Search: Bad search filter

DN: cn=user,ou=CMS,ou=ADM,o=OUC
there are attributes like sn,uid, givenname etc..

I have integrated LDAP for this directory into many other apps in the past. 

I have tried various LDAP Filters and LDAP authentication query

is there a variable assignment for the user logging in 
like %u so I can have a filter like 

&(cn=%u)

**Comment by jelockwood** [comment]
The LDAP filter is to 'filter' the list of LDAP accounts that are permitted to login. For example you could limit logins to members of a specific LDAP group or as we do limit logins to 'enabled' accounts. We do this to prevent suspended accounts from being allowed.

To allow a user account to login you otherwise need to define the based DN e.g. cn=users,dc=domain,dc=com and also define the LDAP field used for the user name e.g. uid the LDAP authentication field in our case is uid=

It would be perfectly legal to have an empty LDAP filter definition and this would mean all user accounts on your LDAP server would be permitted to login.

**Comment by TwoTwenty** [comment]
so my ldap filter of CN=*  should be permissive, then why the error :

2018-11-26 17:54:19] dev.ERROR: There was an error authenticating the LDAP user: ldap_search(): Search: Bad search filter
