### ISSUE TITLE
LDAP Works - LDAPS Fails

### ISSUE THREAD

**Issue by CaptainKaffe** [snipe/snipe-it#6470]
#### Expected Behavior (or desired behavior if a feature request)

 Connection to LDAP server established

-----

#### Actual Behavior

Could not bind to LDAP: Can't contact LDAP server

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Upgrade**
- Version of Snipe-IT you're running **v4.6.6 build 3926 (g1a10aa0dd)**
- Version of PHP you're running **7.1.10** **(Laravel version: 5.4.35)**
- Version of MySQL/MariaDB you're running **MySQL Server 5.7**
- What OS and web server you're running Snipe-IT on **Windows Server 2016 / IIS 10**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual Installation**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
**LOG.debug: Preparing to test LDAP connection debug log
LOG.debug: attempting to bind to LDAP for LDAP test debug log
LOG.debug: Bind failed debug log**

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **"/admin/ldap" --> Test LDAP** 
- If a stacktrace is provided in the error, include that too. **No stacktrace available**
- Any errors that appear in your browser's error console. **Could not bind to LDAP: Can't contact LDAP server**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **Not reproducible**
- Include any additional information you can find in `storage/logs` and your webserver's logs. **No stacktrace from laravel.log or webserver log** 
- Include what you've done so far in the installation, and if you got any error messages along the way. **LDAP Sync and LDAP Login works with LDAP, but fails with LDAPS. 
I have tested LDAPS connection successfully using LDAPAdminTool from the Snipe-IT host server and I have other applications on different servers successfully using LDAPS with the same DC. 
The application seems fully functional otherwise.**
**I have verified that the domain user credentials are correct.** 
**I have verified that no firewalls are blocking the connection.**
- Indicate whether or not you've manually edited any data directly in the database **No manual edits**

-----
**My LDAP Settings are as follows:**
- [X] LDAP Enabled
- [X] This is an Active Directory server
- [X] LDAP Password Sync
- Active Directory domain: **mydomain.com**
- LDAP Server: **ldaps://dc.mydomain.com** **_I have tried with and without port number_**
- [ ] Use TLS _**I have tried with and without this**_
- [ ] LDAP SSL certificate validation _**I have tried with and without this**_
- LDAP Bind Username: **username@mydomain.com**
- LDAP Bind Password: **user password**
- Base Bind DN: **OU=Users,OU=Accounts,DC=mydomain,DC=com**
- LDAP Filter: **&(cn=*)** **_I have tried multiple different filters_**
- Username Field: **samaccountname**
- Last Name: **sn**
- LDAP Authentication query: **sAMAccountName=**
- LDAP Version: **3**
- LDAP Active Flag: 
- LDAP Employee Number
- LDAP Email
-----

Let me know if there is any other information I can provide.

**Comment by samotelf** [comment]
Hey @CaptainKaffe try this below:

I'll share my config:

LDAP Integration LDAP enabled √
Active Directory This is an Active Directory server √
LDAP Password Sync Yes √
Active Directory domain contoso.com
LDAP Server ldap://ipaddressofyourdc:389
Use TLS NO
Allow invalid SSL Certificate √
LDAP Bind Username ldap.user
LDAP Bind Password password
Base Bind DN dc=contoso,dc=com
LDAP Filter &(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
Username Field samaccountname
Last Name sn
LDAP First Name givename
LDAP Authentication query samaccountname=
LDAP Version 3
LDAP Email mail

Save
Goto config again
Test below
Profit

Also, check this [one](https://github.com/snipe/snipe-it/issues/5352).

**Comment by CaptainKaffe** [comment]
Thanks for the feedback. I have tried your suggestions and it does not work. Let me clarify that LDAP does work, but when enabling SSL with ldap**s**:// it fails. 

Does the DC certificate need to be explicitly trusted anywhere in the settings or configuration files?

**Comment by CaptainKaffe** [comment]
**An update:**
I have solved the issue with a temporary workaround.

The issue seems to be caused by PHP Ldap module per default requires that you verify the root ca certificate, of the CA issuing the DC certificate. This is done by setting the variable LDAPTLS_CACERT.

In "app\Models\Ldap.php" --> connectToLdap()  I added the following:
`putenv('LDAPTLS_CACERT=C:\...\...\PathToCACertFIle.pem');`

Make sure that the user running the Web Server has read access to the certificate file, and it needs to be in PEM format.

I would prefer adding this as a System Environment variable in Windows, but when i do this, and run `getenv('LDAPTLS_CACERT')` it returns an empty value. Any clue why this is? Could it be IIS lacking privileges to read system environment variables in Windows?

Alternatively, you can create the ldap.conf file in "C:\openldap\sysconf\" and set the variable:
`TLS_CACERT C:\...\...\PathToCACertFIle.pem`

A bit more info info on OpenLDAP TLS variables here: https://www.openldap.org/doc/admin24/tls.html

**Comment by CaptainKaffe** [comment]
**Another Update - final solution**
I was able to solve this by adding LDAPTLS_CACERT as an environment variable in the FastCGI settings in the IIS hosting Snipe-IT.

The web server is only able to read environment variables set specifically for FastCGI in IIS. In order to set the LDAPTLS_CACERT variable for Snipe-IT, try the following: 

1. Open the IIS Manager
2. Click on the Web Server in the left side menu
3. Choose FastCGI Settings 
4. Right-click and choose edit for the PHP-CGI.exe entry
5. Under "Environment Variables", click the "..." to open the list of variables
6. Add a variable LDAPTLS_CACERT with value C:\....\....\....\RootCACert.PEM

This variable will be succesfully picked up by the Snipe-IT application.

A guide to adding environment variables for FastCGI by Microsoft here: https://docs.microsoft.com/en-us/iis/configuration/system.webserver/fastcgi/application/environmentvariables/

**Comment by conan522** [comment]
> 
> 
> **An update:** I have solved the issue with a temporary workaround.
> 
> The issue seems to be caused by PHP Ldap module per default requires that you verify the root CA certificate, of the CA issuing the DC certificate. This is done by setting the variable LDAPTLS_CACERT.
> 
> In "app\Models\Ldap.php" --> connectToLdap() I added the following: `putenv('LDAPTLS_CACERT=C:\...\...\CACertFile.pem');`
> 
> Make sure that the user running the Web Server has read access to the certificate file, and it needs to be in PEM format.
> 
> I would prefer adding this as a System Environment variable in Windows, but when i do this, and run `getenv('LDAPTLS_CACERT')` it returns an empty value. Any clue why this is? Could it be IIS lacking privileges to read system environment variables in Windows?
> 
> Alternatively, you can create the ldap.conf file in "C:\openldap\sysconf" and set the variable: `TLS_CACERT C:\...\...\CACertFile.pem`
> 
> A bit more info info on OpenLDAP TLS variables here: https://www.openldap.org/doc/admin24/tls.html

**Is add there ?**
![ldaps](https://user-images.githubusercontent.com/67681471/137061267-dc693974-f89e-48fc-81cf-3ca4bca1977c.jpg)

**Comment by Mckenzywallis** [comment]
![Capture](https://github.com/snipe/snipe-it/assets/148961743/ae51ef94-c830-4848-af61-af03d5e21ff2)

**Comment by Mckenzywallis** [comment]
Anyone faced this issue and how they solved it? 
![Capture](https://github.com/snipe/snipe-it/assets/148961743/97adfe4e-cbfb-42ef-a1d7-3ad0a1f0b169)

**Comment by markoweb2** [comment]
I would like to add a comment for future googlers, of the issue I had with getting LDAPS working in snipe-it.
**Setup:**
Windows Server 2019 + IIS
PHP 8.1 (whatever the latest version was, Non-Thread Safe, installed manually - no Microsoft Web Platform Installer etc)
Snipe-IT 6.2.3
Self-Signed certificate, made by Active Directory Certificate Authority. The root CA cert was manually added to Trusted Root Certificate Authorities, because the server I run snipe-it was not joined to the domain.
Verified that the ceritifacte used for LDAPS is trusted (no issues what so ever, chain is trusted), by exporting the cert to .cer format, copying it over to snipe-it server and opening with double-click.

I got LDAP working in Snipe-IT. Then changed it to LDAPS and immediately started to get the error Could not bind to LDAP.
I tried messing around with all the variables in the LDAPS Sync Settings page:
* turning on/off the "Allow invalid SSL certificate"
* turning on/off the "use STARTTLS"
* adding a port to the "LDAP server" field
* restarting IIS
* etc

At some point, magically LDAPS started working. But it worked for only 5 minutes, then it just stopped again. Then I started fiddeling with the above settings and at some point got it to work again only for it to stop working a few minutes later.

A few things I learned from trial and error:
* The port (389/636) is not neccessary in "LDAP server", just use ldap:// or ldaps:// and it uses the correct port.
* It is best to use the FQDN for the LDAP server name. Using an IP most likely will not work, because certificates usually don't contain IP-s, they have DNS names.
* STARTTLS will not work with ldaps://, error message changes to "500 internal server error" or such. STARTTLS is only for ldap:// connections, to start the communication in plain text, but to then upgrade it to TLS. My recommendation is to not use STARTTLS and instead opt for ldaps://
* I think it liked it better when I used the full UPN (john.doe@example.local) for the LDAP Bind Username.
* when LDAPS did not work and I ran `php artisan ldap:troubleshoot`, I got a very similar output as shown by @Mckenzywallis, with the final result being that only ldap:// was shown in the results table.
* make sure LDAP works first, before trying to use LDAPS. If you have an error in the filter or other fields, you can run up against the same error message - Could not bind to LDAP.
* You don't have to enter the LDAP Bind Password every time you change settings. Leaving the field empty (after entering the password initially) on subsequent saves is fine. It will remember the password - doesn't save empty password field

**I finally found the solution** when I figured out that OpenLDAP, which PHP uses, does not use the Trusted Root Certificate Authorities container to determine the validity of a certificate. You need to manually provide the CA certificate in pem format, like @CaptainKaffe mentioned:
```
Alternatively, you can create the ldap.conf file in "C:\openldap\sysconf" and set the variable:
TLS_CACERT C:\...\...\CACertFile.pem
```

The folder "C:\openldap\sysconf" must be created manually, also the file ldap.conf.
After editing the file, you need to restart IIS (services > World Wide Web Publishing).
I would also recommend adding _IUSR_ and _IIS_IUSRS_ with Read permission to the folder.

What is interesting, is that adding "TLS_REQCERT never" to ldap.conf also works. Although snipe-it adds the same variable into runtime memory when you tick "Allow invalid certificate", that option did not seem to work. At least when clicking Save and doing Test LDAP Connection. (maybe if you tick that option and restart IIS, then it works, and that is why at some point I got it working for 5 minutes with trial and error)
I don't recommend using this option though, as it exposes you to man in the middle attacks. Use TLS_CACERT instead.
You can export the root certificate by going to the server that hosts AD Certificate Authority > Start menu > mmc.exe > CTRL +M > Certificates > Computer Account > OK > go to Personal leaf. Look for the certificate with "domain-servername-CA" as it's name. Right click > Export > select BASE64 format > save it as .cer file. You can now simply rename .cer to .pem.

As for the issue @Mckenzywallis is facing. You are using google's LDAP, which I am not familar with, but perhaps two suggestions to try:
1) Also add the TLS_CACERT to ldap.conf. Despite Google using a trusted certificate, not self-signed, maybe OpenLDAP still fails to validate it.
After I added the TLS_CACERT to ldap.conf, the `php artisan ldap:troubleshoot` command threw less errors and found both ldap:// and ldaps:// options as viable.

2) I read somewhere Google LDAP requires you to provide client side TLS certificates, so try setting those fields as well in snipe-it LDAP Settings page.
