### ISSUE TITLE
Component management

### ISSUE THREAD

**Issue by ArchdukeNavaron** [snipe/snipe-it#6473]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.6
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version 7.2

**Is your feature request related to a problem? Please describe.**
I would like to bulk add components to assets/model.
For example: we build our own PCs and we would like to list all "components" of the PC at the "components" tab. When we built new PCs, we have to assign these components 1. manually (even when we copy them) 2. we have to manually add components to the compontents site. 
We do have several models of these PCs. 

I also would like to have just a "Add components/consumable" button. Why? Because now i have to manualy count them together. I am just lazy, thats all ;)

**Describe the solution you'd like**
We would like to add certain assets (linked to a model) which would automaticly add the required components and would also assign these components to the asset.

**Additional context**
 I know that you already introduced the user defined fields but they don't seem to be as handy as the components site and feature.

**Comment by tobiasrothen** [comment]
Is there any way to achieve this? We really like the tool, but we have a lot of asset models that come with a predefined set of components. Any plans to implement a feature like this or is there another way to solve this?

Again an example for what has already been described by ArchdukeNavaron:
An asset of asset model "A" always has 1x Component "C1", 2x Component "C2", 1x Component "C"
If we create a asset of type asset model "A", we want to automatically reduce the current stock on the components C1 by 1, C2 by 2 and C3 by 1 according to definition of the Asset Model. Doing this manually is prone to human error.

**Comment by royalpenguin** [comment]
+1 on the use case described by @tobiasrothen . We are trying to achieve something similar with snipe-it but so far unsuccessful. Instead of having to manually checkout the components to assets after creating them it would be great to define the required components in the Asset Model so it would check them out when a new asset of the type is created. Ideally this would throw an error if the stocked amount of components is not sufficient.

On a side-note: The concept of components in general seems somewhat unclear from the documentation. For example I wonder why the quantity of a components cannot be reduced without having to check it out to an asset (e.g. when using it for something else). On the contrary they cannot be "restocked" without re-adding them or altering the quantity manually. A UML like illustration of the relationship between the assets, asset models, components etc. would really be appreciated!

**Comment by Tardigroove** [comment]
I don't see that this became a feature. It would be nice to have this as a way to manage inventory for components that are attached to an asset. I'd like it if I could just "clone" an asset that has components checked out to it and automatically it would pull from the list of components. Maybe it could be a drop down option when cloning assets that have components attached to them that simply says "include components?" This could be set up during the asset model phase. 
Overall I think there is a lot of potential for components, but as of now an excel spreadsheet seems to be working better for my purposes. I think we are all trying to get away from excel spreadsheets to keep track of things though, so this feature seems to be an area for improvement.
