### ISSUE TITLE
LDAP Sync does not recognize a renamed AD User

### ISSUE THREAD

**Issue by qsthensel** [snipe/snipe-it#6474]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When renaming a User in AD with renaming the samAccountName Attribute too, Snipe-IT does not recognize the renaming and shows the renamed user as a new user. Therefore all assets are still linked to the old username and need to manually changed to the new one.

**To Reproduce**
1. Configure an AD as LDAP Server
2. Do LDAP Sync
3. rename user in AD
4. Do LDAP Sync
5. There are now 2 users. One with the old name, one with the new one.

**Expected behavior**
Snipe-IT should recognize the renaming (maybe based on a given unique attribute) an rename the user.

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.6
 - OS: debian 9
 - Web Server: Apache
 - PHP Version: 7.1.24

**Comment by snipe** [comment]
I'm not sure exactly what the solve should/could be here. The username is the unique field we use to differentiate users from one another in Snipe-IT. If that has changed, Snipe-IT has no way of knowing they're the same person.

**Comment by qsthensel** [comment]
In Tools like Nextcloud or Jira you can set a unique ID Attribute with is used to identify the user all the time.
https://confluence.atlassian.com/jirakb/ldap-username-or-samaccountname-rename-creates-a-new-user-in-jira-not-associated-with-the-previous-user-account-826875550.html
https://docs.nextcloud.com/server/stable/admin_manual/configuration_user/user_auth_ldap.html#expert-settings
Maybe something like this could be implementet in Snipe-IT too.
In our company it happens from time to time that a Employee changes his surname in cause of a marriage (or divorce). Therefore we change his Account Name (including samAccount in AD).
Its not really a blocker but its annoying work to reassign all assets.
Would be nice if you could think about such a feature in the future.

**Comment by KeenRivals** [comment]
Ran into this issue in 4.7.5.

**Comment by KeenRivals** [comment]
To add more info, renaming the user is hard, since the username field is locked with "Managed by LDAP". To get through it I deleted the old user's account and switched their assets to the new one. I think  the only other way to do it would be to modify the database directly.

**Comment by NightyLive** [comment]
Same issue and same workaround than @KeenRivals 

Not a verry smooth process, and we loose the history and dates. This is really sad since user authentification in most environnements are done with a unique and fixed ID, I mean not the username that can be changed.

Windows provide the SID attribute and Linux the UID. It would suffice to use it as a underlying identifier. Or at least provide us a (simple) way to remap the username between two users.

**Comment by ItsANoBrainer** [comment]
+1 this should have been standard from the beginning. All platforms that utilize LDAP sync use a unique identifier for users that does not change incase a users AD information, like name, email, username, changes.

@KeenRivals Is correct to where the only way we can edit a current user to change their information to match the new is with the database. 

Working in an ISD that manages all the technology for 14 school districts, with thousands of employees per district, name changes are so common that its an extra step in the process to have to go in and do this, when it should be setup so the system does it for us.

Also not a fan of Stalebot. It probably wont even reopen this ticket, and a lot of feature request tickets are closed automatically when they shouldn't be, and are lost in the void of tickets.

**Comment by playisfun60** [comment]
Does anyone have any Update or solution?

**Comment by KeenRivals** [comment]
Not really a solution but I've found it's possible to rename the user via the API. Here's my nasty, dirty, ungood python script. You'll have to make edits to suit your install: api key, url, and old/new usernames. Rename the user in AD/LDAP first, then run the script to fix the username in snipe.

``` python
import requests, json

#Snipe-IT API Key
token = 'yourkeyhere'
headers = {"Authorization":"Bearer " + token, "Accept":"application/json", "Content-Type":"application/json"}

oldUsername = "OriginalUsernameHere"
newUsername = "NewUsernameHere"
url = "https://yoursnipe.com/api/v1/users?username=" + oldUsername
response = requests.request("GET", url, headers=headers)

id = str(response.json()['rows'][0]['id'])

url = "https://yoursnipe.com/api/v1/users/" + id

result = requests.patch(url=url, headers=headers, json={"username": newUsername})

print(result.json()['status'] +" " + result.json()['messages'])
```
Be warned, no error checking here and I don't know if this has side effects since renames are very rare in my org. If it breaks something you get to keep both pieces. 👍

**Comment by playisfun60** [comment]
Thanks, @KeenRivals was hoping for something automated by now, the company goes through a lot of name changes, would not be possible to add a manual process like this in the flow. Unsure why the SID was not used, hopefully, someone has a solution.

**Comment by TenOfTens** [comment]
I just realized this was a problem for us as well. I am just going to delete new account and rename the old one to the changed name. That way I can keep the details and the history of devices assignments. Going to test now to confirm that it won't create another new one, but theory should be solid.

Edit: Added my results here: 
Cannot change the username, because it is filled in with a note saying (managed in LDAP). You have to just migrate everything to the new user created through LDAP. We really need to be able to tie this to something that doesn't change every marriage/divorce. We have Unique ID #s (in AD) for employees just for this same reason for our other systems.

**Comment by KeenRivals** [comment]
Updated the code in my comment. Had to rename a user today and found the code wasn't working. Seems snipe expects the new username in the request body instead of as url param.

**Comment by playisfun60** [comment]
Does no one have a better solution, we just did a domain migration so 1000+ UPNS changed , and now have all these users out of sync
