### ISSUE TITLE
Username Character limitation with LDAP

### ISSUE THREAD

**Issue by rodriguesjpmunch** [snipe/snipe-it#6477]
Is there any character limitations currently with usernames? 
20 Characters works but 22 characters does not work.

- Version of Snipe-IT you're running: 4.6.4
- Version of MySQL/MariaDB you're running: MariaDB
- What OS and web server you're running Snipe-IT on: Linux
- What method you used to install Snipe-IT: Clone github clone

https://snipe-it.readme.io/docs/getting-help

**Comment by rodriguesjpmunch** [comment]
So after testing abit, using LDAP with above 20 characters not able to log in.
Using local user with above 20 characters working without issues. 
Strange thing is these 4 users which can't log in, the password hash is precisly the same on the database but can confirm that the passwords is definitely not the same.

**Comment by snipe** [comment]
The field length for username is 191 characters, so I don't know why that would be happening.

> Strange thing is these 4 users which can't log in, the password hash is precisly the same on the database but can confirm that the passwords is definitely not the same.

If they were imported, that's not surprising. We generate a temporary password on import (since password is required, and when we're importing, we don't know what their password is). The first time they login, the password is updated to their LDAP password (if you have that option checked in the Admin Settings > LDAP)

**Comment by rodriguesjpmunch** [comment]
Strange yeah. We just shortend the username field in Active Directory and it solved it.
Do you want us to investigate further? 
We have a duplicate test server so can do on it what we want.
