### ISSUE TITLE
Suggestion: Sign In Page Reorganization and Alignment

### ISSUE THREAD

**Issue by dbierspb** [snipe/snipe-it#652]
Apologies if I've been flooding the board with these suggestions.  I feel it will make it better in the end.  (let me know if you want me to stop, Snipey ;))

![Move "Forgot Password" and Sign in Button](http://iaas.me/screenshots/2015-03-13_1125.png)

I would suggest moving the forgot password link under the password field, perhaps next to the remember me check box/text.  Additionally, the checkbox for "Remember Me" is not lined up with the login input fields.

Some examples of the forgot password link being under the password field:

Facebook Login:
![Facebook login](http://iaas.me/screenshots/2015-03-13_1126.png)

Office/Microsoft Login:
![Office365](http://iaas.me/screenshots/2015-03-13_1127.png)

Confluence Login:
![Confluence](http://iaas.me/screenshots/2015-03-13_1128.png)

**Comment by snipe** [comment]
Something I noticed, on 13" retinas, the most recent change actually is more problematic than the original. I'm working on trying to clean that up a little right now. 

@dbierspb One of the issues with your screenshots is that all of those are using the convention where the submit button is on the left side of the form, whereas for the rest of the application, we have the submit button on the right side of the form, with cancel or less frequently used text on the left. With the button on the right side and the forgotten password on that same line, it actually looks pretty janky. 

I'm trying to make it look less awful, but please understand that other websites don't use the same UX that we do, and consistency is better than inconsistency.

![screen shot 2015-03-16 at 8 47 38 pm](https://cloud.githubusercontent.com/assets/197404/6681084/c0853e06-cc1d-11e4-91dd-7dd53d963778.png)

**Comment by snipe** [comment]
I also disagree with the premise that this change improves usability here. I think these are all valid and different ways to present a login interface, however the forgotten password in its original location above the login fields is also quite commonplace, and serves to differentiate it from the Sign In button and remember me functionality, so that it's easily spotted by a user. Forgotten password functionality is not going to be used as frequently as Remember me or Sign In, so displaying it in a visually separate part of the login form is pretty standard.

I don't feel very strongly about it either way, especially since this is not a consumer-facing application and is used internally for companies, which is why I accepted the pull request, however I don't actually agree that the original suggestion will improve usability. (I've done a pretty hefty amount of UX work in my day, so this isn't foreign territory for me.)

I don't think it's a bad suggestion, just not one that's particularly useful, and due to this new layout bug, will now have sucked up a disproportionate amount of time given whatever modest benefits we might gain. That said, I don't want to discourage you from making suggestions. We genuinely do welcome them. We just won't agree with all of them. ;)

**Comment by madd15** [comment]
This is a SS from my LG G3
![LGG3](http://imgur.com/pu9cpja)
