### ISSUE TITLE
please help me with domain name and ssl certificate assignment to snipe-it apache server

### ISSUE THREAD

**Issue by ems294** [snipe/snipe-it#6598]
Hello,

all day was trying to add my domain name and ssl to my Apache(snipe-it) server, but no luck,
redirection to https i made, so now it is opening via https://IP
my Apache config:
any ide what i am doing wrong,

<VirtualHost *:443 >
        ServerName domain-name
        ServerAlias domain-name localhost
        #Redirect permanent / https://192.168.0.12
        ServerAdmin admin@doamin.com
        DocumentRoot /var/www/snipe-it/public

        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/f7bff14db1fb7880edrtyu78.crt
        SSLCertificateKeyFile /etc/apache2/ssl/private.key
        Alias /domain-name  "/var/www/html/snipe-it/public"
        <Directory /var/www/snipe-it/public>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride All
            Order allow,deny
            allow from all
        </Directory>

</VirtualHost>

**Comment by marcquark** [comment]
What exactly isn't working? You should not set up the redirect in the virtual host that already does SSL. You need to set up another virtual host that listens on Port 80, without SSL and configure the redirect there.

Are you using a valid certificate? What's the common name of it? Does it have a SAN extension that also contains its IP address? Otherwise certificate validation will fail if you redirect to the server's IP address. You should redirect to its hostname instead, and the hostname should match the hostname in the certificate.

**Comment by tymik** [comment]
i find it unrelated to the project, you should rather consult apache documentation.

specifically for using domain name within vhost: https://httpd.apache.org/docs/2.4/vhosts/name-based.html
i see you have required fields in your setup, so i have no idea why it might not work for you - run configtest to see if no errors are there, check logs of apache, if no errors on configtest nor in logs, restart apache and check again.
also ensure your browser did not cache the site with previous config (use private mode in browser, close and reopen it before every single test)

for redirecting from http to https you can use following code:
```
# Rewrite HTTP to HTTPS
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
```
