### ISSUE TITLE
Alternatives to seats regarding licences

### ISSUE THREAD

**Issue by stbc** [snipe/snipe-it#6649]
**Server (please complete the following information):**
 - Snipe-IT Version: **4.6.7**
 - OS: [e.g. Ubuntu, CentOS]: **Debian**
 - Web Server: [e.g. Apache, IIS]: **apache**

**Is your feature request related to a problem? Please describe.**
There are licences which are not assigned on a seat basis but on a contract basis or people count asf.

**Describe the solution you'd like**
It would be nice, if there would be a selector for switching from a seat count to unlimited or to a head count.

**Comment by Jarli01** [comment]
Can you explain a bit more how a "headcount" license operates or should operate compared to what exists today?

**Comment by stbc** [comment]
Sure:

- Contract base: We are having licence contracts which are covering the whole organisation - so there is no upper limit in terms of keys/licences/whatever. Those licences are often calculated on "how many persons are working in the org" base.

- Head count: You are not bundling a specific user OR computer but both. There are licences that are bound to a person, this person can install on a Mac AND a Win Machine for example.

**Comment by Jarli01** [comment]
_As a disclaimer, I'm not on the dev team just another user. But I'm probing as I'mm sure @snipe would ask the same thing._

Those are types of licenses, not how you are tracking them today. 

- Using the Contract based licensing. I likely wouldn't put a seat count in at all, but instead supply expiration dates only. Based on when the contract expires, but this doesn't really answer the question of what do you do to track the license. 

- Headcount licensing kind of makes sense, but instead of checking the license out to an asset, just check it out to the User. On the license type you can add details of the allowed installations. 

Lastly, how are you tracking where software is being activated with the Headcount licensing?

**Comment by Jarli01** [comment]
So in testing on the demo it appears Seat counts are a required field. Meaning in the case of a "Site" license if you added users from past the point of the start of the contract you'd have to update the "seat" count to have an honest reflection of the number of licenses.

Since all licensing is actually tied to a integer (in real world licensing). 

So maybe having an option next to Seats would be a **Site License** checkbox that allows the "Seats" box become non-required.

**Comment by stbc** [comment]
> So maybe having an option next to Seats would be a Site License checkbox that allows the "Seats" box become non-required.
Thats exactly what I am asking for :) 
>  It would be nice, if there would be a selector for switching from a seat count to unlimited

**Comment by stbc** [comment]
Would still be happy if there would be a possibility to change over to unlimited seats .. :)

**Comment by artem611** [comment]
Hi everyone!
I would also like to choose an unlimited license.
Tell me pls, did the decision find after the topic starter asked his question?
Thanks!

**Comment by Jarli01** [comment]
@artem611 as far as I know nothing has been done with this FR yet.

**Comment by pingy82** [comment]
there is to consider also the "cloud or shared" lic...
like solidworks, i have 15 lic but i can install on 20/30 different seats... the first 15 seats use it, but i'd like to know who has this lic on is pc.

**Comment by stbc** [comment]
Yeah!

**Comment by Jarli01** [comment]
Yes this is still relevant.

**Comment by Jarli01** [comment]
Please keep this open.

**Comment by alixjg** [comment]
I would also like to see this feature.  I have a couple old pieces of software with Site Licenses and I would like to be able to report what it's installed on without entering 9999 in the seat field.  Even if it just translates a 0 or blank field to "unlimited".

**Comment by cliff-LINKS** [comment]
+1

**Comment by pguinet** [comment]
Would be nice, yep.

**Comment by wilkomar** [comment]
my problem is similar, i need assign one license for example: 2,3,4,5,6,...,16,... assets. It depends on the company and the license purchased.
I described my  case in issues #7730

**Comment by stbc** [comment]
Oh no! I hate this stale bot....can anybody please change the config of that f*er not to close things on a weekend!

How to reopen this one?

**Comment by WilliamDEdwards** [comment]
+1

**Comment by MoultonAcUk** [comment]
+1

We have multiple licences that are SiteWide but it would still be useful to track their start, end and renewals.

It would also be useful to have a tick box for "Concurrent" for software where it contacts a network licence server to see if a licence is available.  E.g.   we have a software package that permits 10 simultaneous users, but there are maybe 50 people who have the software installed as we don't need them to all access concurrently.

The ability to add custom fields to licences to identify where their licence server is, or other similar things would be great too.
