### ISSUE TITLE
LDAP filter being ignored

### ISSUE THREAD

**Issue by RTodorov** [snipe/snipe-it#6674]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
No matter what I put on the LDAP filter field, it gets ignored and all users from my LDAP are able to login. Even bogus values like "$#@$#@$@" doesn't do anything.

**Expected behavior**
During login, the system should respect the filter specified in the LDAP Filter field on the LDAP configuration screen.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.8 build 3959
 - OS: Ubuntu (Dockerfile)
 - Web Server: Apache2 (Dockerfile)
 - PHP Version: 7.0 (Dockerfile)

**Additional context**
- Is this a fresh install or an upgrade? Fresh install
- What method you used to install Snipe-IT: docker
- Indicate whether or not you've manually edited any data directly in the database: no

**Comment by RTodorov** [comment]
Just to add some information: LDAP sync works just fine, it fetches users from the correct group, based on the filter. But, my problem is: all users outside of the group(s) I specified in the LDAP filter field are also able to login.

**Comment by jayscovill** [comment]
I'm experiencing this as well.  LDAP Sync respects the LDAP filter but when a user not in a group specified in memberOf for the LDAP filter logs it a user account for them is automatically created.

Is this expected behavior? Can it be changed to deny access unless an account already exists?

**Comment by pgi-mike-forst** [comment]
It appears to be the designed behaviour for the application, but I do not think it is what admins would expect.

For our LDAP enabled applications, we typically use a filter that searches for a user group in Active Directory to enable logins:

&(objectClass=person)(memberof=cn=application-enabled-group,ou=redacted,dc=redacted,dc=redacted)

When I looked at the PHP code for Snipe it doesn't take the LDAP Filter setting into account when authenticating. On line 97 of app/Models/Ldap.php, it does this:

`$filterQuery = $settings->ldap_auth_filter_query . $username;`

This just concatenates the LDAP Authentication query field and the username. This is also why that field must end with an = or you get an error about a bad search.

I found a quick way to change it by updating one line. If you change line 97 to the following:

`$filterQuery = '(' . $settings->ldap_filter . '(' . $settings->ldap_auth_filter_query . $username . '))';`

This will concatenate the LDAP Filter into the query used to bind a user and will apply it to any attempted user logins. I haven't tested this extensively for all use cases but adding and removing users to the group definitely controls the ability to login, and using a non-existent group also prevents logins without throwing any errors. This leads to the LDAP login function working as I would expect it to, and in a similar to other applications that use LDAP filters as a part of their user mapping schemes. Honestly the entire thing could probably get simplified further to:

`$filterQuery = '(' . $settings->ldap_filter . '(' . $settings->ldap_username_field . '=' . $username . '))';`

We get rid of the LDAP Authentication query field entirely. I've tested the above as well and it works the same as my first solution and I am able to authenticate with the LDAP Authentication query field blank and changing the Username field to something invalid blocks logins.

I think this should be adopted into the application as I feel admins would expect the filter to apply to authentication as well as LDAP syncs and causes Snipe-IT to behave in a manner similar to other applications that use LDAP.

Edit: I just found an edge case where my change doesn't work: if the LDAP Filter is empty you will get an error. This could easily be fixed with an if block checking to see if that field is empty:

`if ($settings->ldap_filter) {
    $filterQuery = '(' . $settings->ldap_filter . '(' . $settings->ldap_username_field . '=' . $username . '))';
} else {
    $filterQuery = $settings->ldap_username_field . '=' . $username;
}`

**Comment by Solverz-0** [comment]
@pgi-mike-forst Does this still work? As I have tried doing this but users outside the filtered group are still able to log in?

**Comment by djooberlee** [comment]
@pgi-mike-forst 
I have exactly the same problem!
I tried to edit the file `/var/www/html/app/Models/Ldap.php` as you wrote, but unfortunately it did not have a positive effect.


UPD: My apologies! Version 6.0.1 does not have this problem!
