### ISSUE TITLE
Bulk checkout Issue using barcodes. Add Bulk Check In Function

### ISSUE THREAD

**Issue by gilesytheking** [snipe/snipe-it#6819]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.13 - build 3985 
 - OS: Linux
 - Web Server: Apache (Cpanel)
 - PHP Version: 5.6.40

**Is your feature request related to a problem? Please describe.**
- The wrong asset is selected when using the bulk checkout feature with a barcode scanner. 
When I scan the first barcode, it adds the first asset from the dropdown list and not the asset I scanned.
Scanning a 2nd time inputs the correct asset tag into the drop down field, but the asset is not selected.

- There does not seem to be an option to check in multiple items at once. The only option I have found is the check in & delete user. We have many assets that are assigned to users for short periods of time based on job requirements. These are normally bulk checked out. Most of these assets are all returned together once the job has been completed. 

**Describe the solution you'd like**
- Ability to add an asset to the "Bulk checkout list" by scanning its barcode. Possibly this feature could work more like the "Bulk Audit feature. Whereby all the scanned / selected assets to be checked out are listed on the side.

- Add functionality for "Bulk Check in". This would allow multiple assets to be scanned or entered into a "Check in List" (similar to the Bulk Checkout Feature). There should be options to set the checked in items location & status. This would be similar to the check in & delete function, without deleting the user.

**Describe alternatives you've considered**
- Have to manually type an assets name when conducting bulk check in, as the barcode scanning function doesn't work 100%. This becomes a very slow process, which kind of defeats the bulk check in function.

- No other alternative for Bulk Check in. 

**Additional context**
There seems to be other requests for this feature, however It seems there has not yet been a solution added.

**Comment by bricelabelle** [comment]
Our organization uses Google Sheets + Google Script + the Snipe Web API to accomplish this. I've created a Google Sheet that you can scan all your asset tags into, highlight them, then choose menu options for Bulk Checkout, Bulk Checkin, or Bulk update. Then you pick a status and a location and it runs through and does them all programatically. I can share the code if you are interested. I'm also going to look into possibly publishing it as a Sheets add-on in the future.

**Comment by gilesytheking** [comment]
This sounds like an interesting work around. If you could share this that would be much appreciated. 

The devs should however look at fixing / adding this functionality to core. The ability to easily and quickly checkin/checkout assets is key for any business.

**Comment by bricelabelle** [comment]
I agree we shouldn't need a workaround for such basic functionality but for now this has been great for us to clean up our inventory. To set this up:

1. Create a new Google Sheet
2. Under the tools menu choose Script Editor 
3. Under the File menu, create new script files and html files with the same names as the files i've attached.
4. Copy the contents of the attached files to their corresponding google script/html files.
5. Save and then close and reopen your sheet.
6. Create a tab in your sheet called "Errors". Any assets that cannot be checked in or out for some reason will show up there each time you run the command.
7. You should now see a "Run Command" option in the menu bar
8. Go back to your main tab and scan or enter asset tags in any single column.
9. Highlight the tags you just entered and then choose an option from the Run Command menu.

Let me know how this works for you!
[Bulk_Edit.zip](https://github.com/snipe/snipe-it/files/3018327/Bulk_Edit.zip)

**Comment by kekkers23** [comment]
> I agree we shouldn't need a workaround for such basic functionality but for now this has been great for us to clean up our inventory. To set this up:
> 
> 1. Create a new Google Sheet
> 2. Under the tools menu choose Script Editor
> 3. Under the File menu, create new script files and html files with the same names as the files i've attached.
> 4. Copy the contents of the attached files to their corresponding google script/html files.
> 5. Save and then close and reopen your sheet.
> 6. Create a tab in your sheet called "Errors". Any assets that cannot be checked in or out for some reason will show up there each time you run the command.
> 7. You should now see a "Run Command" option in the menu bar
> 8. Go back to your main tab and scan or enter asset tags in any single column.
> 9. Highlight the tags you just entered and then choose an option from the Run Command menu.
> 10. Remember to enter your server URL and API key on the Setup.gs script.
> 11. You may need to run one of the test functions manually so Google will have you authorize the script's permissions.
> 
> Let me know how this works for you!
> [Bulk_Edit.zip](https://github.com/snipe/snipe-it/files/3018327/Bulk_Edit.zip)

Would you be willing to go into a bit more detail with this?

If I print off barcodes generated from snipeit, how can I scan those via Android into this google sheet to then perform a bulk checkin for example?

Also, once checked in how can I clear the scanned sheet to avoid duplicates?

Apologies, a bit nooby when it comes to google sheets!

**Comment by bricelabelle** [comment]
I'm not an android user but the app I use for scanning would probably work. It's called Barcode to PC. You install the "server" app on a Windows or Mac computer and then install the client app on your Android device. That causes the device to act as a wireless scanner, dumping the data into whichever field you have selected on your Mac or Windows computer. So if you have the Google Sheet open on your Mac or PC, every time you scan with your android device it will enter the asset tag into a cell, then automatically hit return and jump to the next cell for you. I'd recommend just highlighting and clearing the cells manually after you check things in and confirm there are no errors on the errors tab. If you wanted, you could edit the Google script to do something like highlight the cell once it's been successfully checked in or delete the row for you. We've since changed our process a bit so instead of using a pop-up box to select status and location, we just enter them in the cells next to the asset tags and then run it all at once and it deletes them when it's done. That way we can process things in multiple locations in one pass.

**Comment by kekkers23** [comment]
> I'm not an android user but the app I use for scanning would probably work. It's called Barcode to PC. You install the "server" app on a Windows or Mac computer and then install the client app on your Android device. That causes the device to act as a wireless scanner, dumping the data into whichever field you have selected on your Mac or Windows computer. So if you have the Google Sheet open on your Mac or PC, every time you scan with your android device it will enter the asset tag into a cell, then automatically hit return and jump to the next cell for you. I'd recommend just highlighting and clearing the cells manually after you check things in and confirm there are no errors on the errors tab. If you wanted, you could edit the Google script to do something like highlight the cell once it's been successfully checked in or delete the row for you. We've since changed our process a bit so instead of using a pop-up box to select status and location, we just enter them in the cells next to the asset tags and then run it all at once and it deletes them when it's done. That way we can process things in multiple locations in one pass.

Thank you for the feedback, I actually managed to get this working in the meantime. What I would like to do is to have the option to checkout to either a location or person as well as being able to get the asset by serial rather than asset tag. 

Let me know if you have the time to assist with this, or if you can point me in the right direction to achieve this, its really appreciated.

**Comment by bricelabelle** [comment]
I made the edits for checking out to a user instead of just checking out to an asset. You can pull the new files from the repo I made here: https://github.com/bricelabelle/snipe-it-bulkedit

As far as searching assets by serial, it wouldn't be too difficult. Just copy the getAssetIDByTag(tag) function and change all the instances of "tag" to "serial" in it. Then change the line where it says  if (row.asset_tag == tag) to  if (row.serial == serial). That way the function will return an asset's snipe id by searching using serial instead of tag. 

The much more time consuming part (and something I don't plan to implement) would be scripting a way for the app to tell if you are feeding it serials or asset tags. Right now it expects asset tags and has no way of knowing if you were to give it a serial instead. If you wanted it to ONLY work with serials, you could replace all the instances in the app.gs script of getAssetIDByTag(tag) with your new function, getAssetIDBySerial(serial). You could also use regex and have it look for letters in the value and if so assume it's a serial number or something like that.

**Comment by phoenix-303** [comment]
Has anyone found a fix for the first issue listed here?

_The wrong asset is selected when using the bulk checkout feature with a barcode scanner.
When I scan the first barcode, it adds the first asset from the dropdown list and not the asset I scanned.
Scanning a 2nd time inputs the correct asset tag into the drop down field, but the asset is not selected._

We're running into the same thing. I need to scan an item twice in order for the correct asset to come up in the bulk checkout section.

**Comment by DamascusElm** [comment]
Thanks for the tool! Clicking "confirm" on the script doesn't return any results, nothing happens and the check in/out/update box remains on screen. We've entered out snipe URL and API token into the setup.gs, is there anything specific you think I should take a look at?

**Comment by bricelabelle** [comment]
@DamascusElm , there are a few things you can try.
1. Do the status labels in the html templates match what you have in your inventory?
2. Have you checked the errors tab for output?
3. Open the script editor and use the Run menu to run one/some of the functions manually to make sure your account gets the permissions needed.
4. Successful completion will close the dialog box and not return anything. If you have a lot of assets to update, it could take a couple minutes. Try running it one at a time and checking the errors tab.

**Comment by DamascusElm** [comment]
Thanks! Got it working. Had left out the '/' at the end of the URL by accident, so it wasn't creating the correctly appended URL's.

**Comment by Suicufnoc** [comment]
Still an issue. This actually makes the app completely unusable for me, as does the lack of bulk check-in.  Bulk status change would be useful for me too.

**Comment by bricelabelle** [comment]
I know this is not a built-in snipe feature but we've been using it frequently to make bulk updates and it has worked out very well for us. I've updated it recently with a few improvements. Feel free to check it out and let me know if you need help. [](https://github.com/bricelabelle/snipe-it-bulkedit)
