### ISSUE TITLE
2FA Active column is incorrect

### ISSUE THREAD

**Issue by mikefourie** [snipe/snipe-it#6821]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Incorrect symbol shown for 2FA Active in users.

**To Reproduce**
1. Go to users
2. All users show an X for 2FA Active

**Expected behavior**
2FA Active column should show ticks for users using 2FA. We have it enforced.

**Screenshots**

![image](https://user-images.githubusercontent.com/1269371/54316466-16bac900-459e-11e9-9aaa-bfff56a0e5ed.png)

**Server (please complete the following information):**
Hosted

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Chrome
 - Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by snipe** [comment]
So, the code that's in charge of that:

```
if (Setting::getSettings()->two_factor_enabled !='0') {
            if (($this->two_factor_optin =='1') && ($this->two_factor_enrolled)) {
                return true;
            }
        }
```

is looking for both opted in *and* enrolled. Enrolled means they've actually enrolled a device in the 2FA (using the QR code), while `two_factor_optin` is a boolean that describes whether they have individually opted in or not. If it's universally enforced, I can see why this would return false, since it wasn't enabled on that particular user.

**Comment by snipe** [comment]
I have a potential fix in a PR here: https://github.com/snipe/snipe-it/pull/6822 - just waiting on code review.
