### ISSUE TITLE
Lost all assets images after restarting docker container

### ISSUE THREAD

**Issue by YamiFrankc** [snipe/snipe-it#6828]
#### Expected Behavior (or desired behavior if a feature request)

Have assets with images show up when viewing lists or assets pages

-----

#### Actual Behavior

No images show up, just a square as if the image doesnt exist

-----

#### Please confirm you have done the following before posting your bug report:

I have checked the common issues page, but I dont know how to apply the one that talks about images to Docker

What happened is that the server rebooted and images stopped working after restarting Snipe IT

- This was installed using the Docker instructions 3 weeks ago
- Running  v4.6.12  build 3982 (gd687e1d76)
- PHP Version  7.0.33-0ubuntu0.16.04.1
- MySQL version: 5.6
- Ubuntu server edition
- Running with Docker

**Comment by uberbrady** [comment]
What's the `docker run` command you used? Originally, as well as for when you restarted the container? The docker setup by default uses a volume for all uploaded assets; so it should work properly so long as you reattach that volume.

**Comment by EarlRamirez** [comment]
I don't use docker for Snipe-IT yet! But use docker for a few other apps, where is your data stored you can create systemd units (services) for your containers. My internet is not the greatest, but I will try to set up a couple of containers for Snipe-IT so that I can try and give you a hand with this

**Comment by YamiFrankc** [comment]
Thanks!

**Comment by sjackson0109** [comment]
This is still an issue for me.

using Docker-Compose, using installation guide posted the snipe-it website.

Upload a JPG to /admin/branding > save
Banner displays a perfectly rendered logo, matching the JPG file content.
[root@snipeitsrv ~]# docker-compose down && docker-compose up -d
Refresh the webpage, sign in...
Banner displays an image placeholder, IE: no file-found.


Looking inside the SQL DB
select logo from snipeit.settings;
"logo.jpg"


Docker-compose has a mounted volume for the MySQL container, but no mounted volume for the Snipe-it-app container. Here-in lies the problem...  file system simply isn't consistent after each reboot.

**Comment by ygurdag** [comment]
> This is still an issue for me.
> 
> using Docker-Compose, using installation guide posted the snipe-it website.
> 
> Upload a JPG to /admin/branding > save Banner displays a perfectly rendered logo, matching the JPG file content. [root@snipeitsrv ~]# docker-compose down && docker-compose up -d Refresh the webpage, sign in... Banner displays an image placeholder, IE: no file-found.
> 
> Looking inside the SQL DB select logo from snipeit.settings; "logo.jpg"
> 
> Docker-compose has a mounted volume for the MySQL container, but no mounted volume for the Snipe-it-app container. Here-in lies the problem... file system simply isn't consistent after each reboot.

This is a problem I'm having right now too. After docker-compose down, I saw that my images disappeared.
In fact, I have these image files under the /var/www/html/public/uploads/assets folder in my backup file, but the backup I just took does not have these files. I even logged into the docker image to confirm (using the command: docker exec -it snipe-it_snipe-it_1 sh) and found that the files didn't physically exist there either.

**Comment by ygurdag** [comment]
> ile system simply isn't consistent after each reboot.

Yes !! you are absolutely right. I had the docker-compose.yml file that I got from the following address; [docker-compose.yml](https://github.com/comoser/snipe-it-docker-compose/blob/master/docker-compose.yml)
There was a volume for mysql in this file, but it was not written for snipeit. Therefore, after each docker-compose down command, all images, logos, user files deleted but the sql data remained.
After editing the docker-compose.yml file as follows, the problem was solved. Also attached the composer file.
I thought it might be helpful for people having the same problem.

docker-compose.yml:
`version: '3'

services:

  snipe-mysql:
    container_name: snipe-mysql
    image: mysql:5.6
    env_file:
      - ./.env
    volumes:
      - snipesql-vol:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

  snipe-it:
    image: snipe/snipe-it:latest
    env_file:
      - ./.env
    volumes:
      - snipeit-vol:/var/lib/snipeit
    ports:
      - "3051:80"
    depends_on:
      - snipe-mysql

volumes:
  snipesql-vol:
  snipeit-vol:
[docker-compose.yml.zip](https://github.com/snipe/snipe-it/files/8095030/docker-compose.yml.zip)
`

**Comment by calebpaine** [comment]
I had this exact same issue and found this thread via google. Updated from 6.0.5 to 6.0.9 by restarting/rebuilding the docker container.

I wanted to chime in for anyone else who has this issue with one possible solution: check your proxy config if you have one. When I updated the Snipe-It container I also updated/rebooted the NPM (Nginx Proxy Manager) container, resulting in it being assigned a new IP in the docker network. I'll have to look up a more long term solution to fix this issue, but the solution was to update the `APP_TRUSTED_PROXIES` environment variable for snipe-it to match the current NPM container's IP.

Not sure why the app behaves this way, I would really rather it throw up a large banner and prohibit access at all if there's a mismatch rather than pretending to work in a broken way, and/or throw an error into the docker logs so I don't have to spend an hour hunting about in a panic trying to understand what broke.
