### ISSUE TITLE
ErrorException compact(): Undefined variable: operator & compact(): Undefined variable: operator (View: C:\xampp\htdocs\snipe-it\resources\views\hardware\index.blade.php)

### ISSUE THREAD

**Issue by vihangad** [snipe/snipe-it#6835]
image 01 - plz help

![FireShot Capture 001 -  - localhost](https://user-images.githubusercontent.com/47201517/54618127-804c4300-4a88-11e9-8dae-1e8cb882d762.png)

image 02 - plz help

![FireShot Capture 002 -  - localhost](https://user-images.githubusercontent.com/47201517/54618223-ab369700-4a88-11e9-973c-1c372abae77e.png)

**Comment by snipe** [comment]
@vihangad In the future, please complete the entire issue form. It's there for a reason. 

My guess would be you're using PHP 7.3. 
https://snipe-it.readme.io/docs/installation-issues#section-php-version-issues

Per the release notes: Snipe-IT v4.x is not compatible with PHP 7.3. You'll need to use a version of PHP between 5.6.4 and 7.2.x. This is due to a limitation of the underlying framework. The upcoming v5 will support 7.3+.
