### ISSUE TITLE
API: Only the creator of the custom fields can access the custom fields by the API

### ISSUE THREAD

**Issue by shubhamdipt** [snipe/snipe-it#6859]
Steps done:

1. A user (admin) creates some custom fields.
2. Admin created a new user having access to custom fields.
3. The new user has now access to custom fields in the user interface.
4. However, the new user cannot access the custom field via API token created by him (403 response to /api/v1/fields).
5. The new user is now made as admin but he still does not have access to custom fields via the same API token (the one created by the new user).
6. However the new user gets the access to the custom fields via API token created by the admin (or rather the creator of the custom fields). 

Hence a user can only access the custom fields by API using the API token generated by the custom fields creator.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

#### Confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Add any other context about the problem here.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)
