### ISSUE TITLE
Advanced search on custom fields returns nothing

### ISSUE THREAD

**Issue by pvnick** [snipe/snipe-it#6866]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Advanced search of custom fields returns no entries

**Screenshots**
I recorded a screen recording at https://www.youtube.com/watch?v=ZKsQr_RU9nk

**To Reproduce**
1. Go to hardware list
2. Click Advanced Search icon and type some stuff in a custom field

**Server (please complete the following information):**
- Centos 7.5
- Newest SnipeIT master

**Comment by romannazarenko** [comment]
I really don't understand why this bug present such a long time. Sorting, searching assets its one of core features of assets manegement software. Every time i need to see, how many laptops left in some cost center i need use excel because i can't filter by 2 custom fields in same search. This bug is really showstopper

**Comment by Speed1** [comment]
Sorry for OT but how do you added the custom fields to the advanced search?

**Comment by snipe** [comment]
Duplicate of #4275
