### ISSUE TITLE
Updating Encrypted Custom Field via API 

### ISSUE THREAD

**Issue by kmain4** [snipe/snipe-it#6880]
#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When using an encrypted custom field, you can't update it via API.

**To Reproduce**
1. Create a custom encrypted field and attach it to a model.
2. Pick an asset of that model and update the field via API.
3. Result shows: ` Error Decrypting: The payload is invalid.`

**Expected behavior**
The value is updated and re-encrypted.

**Server (please complete the following information):**
Snipe-IT version | v4.6.6 build 3926 (g1a10aa0dd)
Software License | AGPL3
PHP Version | 7.0.32-0ubuntu0.16.04.1
Laravel Version | 5.4.35

It appears that the API is expecting a value that has already been encrypted prior to submitting to the API. Are there any docs on how we can do this?

**Comment by andrefecto** [comment]
What does your API PUT/PATCH call look like?

**Comment by kmain4** [comment]
All success. I suspect it is related to this: https://github.com/snipe/snipe-it/pull/6642

**Comment by kmain4** [comment]
If I'm interpreting correctly, the AssetsController.php that updates the custom fields doesnt handle any encrypting.
https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/Api/AssetsController.php

I can't seem to find the encrypting information in order to pass the value pre-encrypted to the API.

**Comment by andrefecto** [comment]
Looking at the PR you referenced, it failed some CI test and that's why it never made it into a release. 
https://travis-ci.org/snipe/snipe-it/builds/484562005?utm_source=github_status&utm_medium=notification

That would have to be something someone at Snipe-IT looks at. I also looked through all the releases from 4.6.6 to the current version and don't see them adding this feature themselves, but I also could have just missed the bullet point.
