### ISSUE TITLE
Change Backup Location for SQL-DUMP

### ISSUE THREAD

**Issue by michaelhaerri** [snipe/snipe-it#6952]
Hi

Is there any way to change the default Backup-Location of the SQL-Dump from "C:\inetpub\wwwroot\snipe-it\storage/app/backups" to another location?

I use Snipe-IT v4.6.15.

Many thanks for any feedback.

Regards

Michael

**Comment by snipe** [comment]
That's not currently possible.

**Comment by mexx3001** [comment]
I am using version 4.9.5 build 4482 it is already possible to set the default backup path to a network share

**Comment by roratonet** [comment]
> I am using version 4.9.5 build 4482 it is already possible to set the default backup path to a network share

Where can I find this option/setting in your build?

**Comment by mexx3001** [comment]
Maybe it is expressed wrong,
The question was or is whether I can change the default backup path to a network share?

**Comment by roratonet** [comment]
> Maybe it is expressed wrong,
> The question was or is whether I can change the default backup path to a network share?

You cannot do it from the settings (Snipe-IT please implement the feature), but you can create a Symlink to the network drive path from the backup path. Make sure to set right permissions for the webserver/laravel

**Comment by uberbrady** [comment]
Part of this is built-in to the backup package we use. So we don't have a lot of options there.

Can you help me understand your use case a little bit better? I'm assuming you're on Windows, and need to have backups live on, like, `D:\blah\blah` instead of `storage\whatever\whatever`?

I guess on Windows (sorry, I'm not really good at it), you can't say "Mount this filesystem at this point in my directory structure," is that right? What are you trying to solve - you want to make sure that your backups live on a different box?

**Comment by Montana420** [comment]
> I am using version 4.9.5 build 4482 it is already possible to set the default backup path to a network share

God i hate idiot like you. XD 

> > Maybe it is expressed wrong,
> > The question was or is whether I can change the default backup path to a network share?
> 
> You cannot do it from the settings (Snipe-IT please implement the feature), but you can create a Symlink to the network drive path from the backup path. Make sure to set right permissions for the webserver/laravel

Literally the only helpful reply.
