### ISSUE TITLE
Time is 2 hours behind

### ISSUE THREAD

**Issue by MrFlat** [snipe/snipe-it#696]
Hello,
First of many thanks for this great project, I loved it, I am running it on Debian, everything went well however I have a small issue and I cant figure how to resolve it, when I checkin / checkout assets I have the wrong Time logged (Date is correct, just the time 2 hours behind) ... the date and time are correct on my server and it is correct in other places (Like Cacti) and couldn't find a variable to fix it.

Also I would like to know if I can delete entries from asset_logs table in the database myself in phpmyadmin, as I made some test items and checked in and out many times, I want to get rid of them, I tried to delete something before from the database directly and it messed things up, so is it safe to delete logs from the asset_logs table ?

**Comment by snipe** [comment]
Hi @MrFlat - the time zone is set in `app/config/app.php`. It defaults to UTC, but you can change it to whatever you want.

It should be safe to delete fro, the asset logs table, but I'm almost never going to recommend manually deleting data that the system generates, because unexpected things can happen. That said, the logs table effectively acts as your paper trail, so it shouldn't harm anything. Back up your database before monkeying around with it just to be safe tho.

**Comment by MrFlat** [comment]
Hello snipe, that did the trick :)
Also I was able to delete logs from the db without any issues, many thanks for your support.
