### ISSUE TITLE
Configure Snipe IT with Synology Directory Server (Ldap)

### ISSUE THREAD

**Issue by gilesytheking** [snipe/snipe-it#6976]
Has anyone been able to configure LDAP using Synology Directory or Active Directory Server?

I want to use the LDAP feature to sync user login details from my synology NAS.

Any settings / help would be appreciated.

**Comment by cdcs68** [comment]
Yes.  Active Directory Server.  What problem are you having?

**Comment by gilesytheking** [comment]
I have configured active directory on my Synology device.

I'm just looking for some general guidance / settings to set AD with snipe IT, in order to sync users.

**Comment by cdcs68** [comment]
Ok.  I'll share my settings with you.  We are running Snipe It v4.6.15 on Windows Server 2016 (upgraded the server from Windows Server 2012)

**LDAP/AD Settings**

LDAP Integration  **LDAP enabled**
Active Directory  **This is an Active Directory server**
LDAP Password Sync  **Yes**
Uncheck this box if you do not wish to keep LDAP passwords synced with local passwords. Disabling this means that your users may not be able to login if your LDAP server is unreachable for some reason.  **Our box is checked.**

Active Directory domain  **domain.com or your.domain.com**
This is sometimes the same as your email domain, but not always.

LDAP Server   **ldap://FQDN  (i.e.  ldap://your.domain.com or ldap://IP Address**
This should start with ldap:// (for unencrypted or TLS) or ldaps:// (for SSL)

Use TLS  This should be checked only if you are running STARTTLS on your LDAP server.  **We are not using TLS.  Instead, our security is handled on our enterprise next generation firewall.**

LDAP SSL certificate validation  Allow invalid SSL Certificate.  **We are not using any certificates.**
Select this checkbox if you are using a self signed SSL cert and would like to accept an invalid SSL certificate.

LDAP Bind Username  **username@domain.com**

LDAP Bind Password binduserpassword  **Type in the password of the Bind Username account**

Base Bind DN  **My example:  OU=Sync,DC=your,DC=domain,DC=com**  

![image](https://user-images.githubusercontent.com/25690788/57041600-4befa900-6c28-11e9-8ebf-fb59659512c1.png)

![image](https://user-images.githubusercontent.com/25690788/57042816-6414f780-6c2b-11e9-866a-2e7ccfdb5240.png)

LDAP Filter **&(cn=*)**

Username Field  **samaccountname**

Last Name **sn**

LDAP First Name  **givenname**

LDAP Authentication query **samaccountname=**

LDAP Version **3**

LDAP Active Flag **active**

LDAP Employee Number  **We aren't using Employee Numbers**

LDAP Email **mail**

**STOP HERE -- click on the SAVE button.**

**Open the LDAP/AD Settings again.  Scroll down to the Test LDAP Sync area.**

Test LDAP Sync
This only tests that LDAP can sync correctly. If your LDAP Authentication query is not correct, users may still not be able to login. YOU MUST SAVE YOUR UPDATED LDAP SETTINGS FIRST.

![image](https://user-images.githubusercontent.com/25690788/57042111-74c46e00-6c29-11e9-8229-fccad3db5de3.png)

**If the test didn't work, you need to review your information and try again.  If it does work but you can't log in with your AD account, then the Base Bind DN isn't in the format needed for this entry.  Use the Test LDAP Login below instead of trying to log into Snipe It every time.  Once the one below works, you are good.**

**Test LDAP Login**
LDAP username   LDAP password   Test LDAP

Enter a valid LDAP username and password from the base DN you specified above to test whether your LDAP login is configured correctly. YOU MUST SAVE YOUR UPDATED LDAP SETTINGS FIRST.

![image](https://user-images.githubusercontent.com/25690788/57042554-9e31c980-6c2a-11e9-823d-b08d5575a6b7.png)

**We aren't using the Custom Password Reset URL**
Custom Password Reset URL 
https://my.ldapserver-forgotpass.com
This replaces the built-in forgotten password URL on the login screen, useful to direct people to internal or hosted LDAP password reset functionality. It will effectively disable local user forgotten password functionality.

**I hope this helps!**

**Comment by tankerkiller125** [comment]
Caps do matter for the samAccountName= and other settings, make sure you have the caps correct, I made this mistake and only discovered it after copying the exact names from the documentation.
