### ISSUE TITLE
Barcode problem (C128)

### ISSUE THREAD

**Issue by GlowManCZ** [snipe/snipe-it#7014]
Version: v4.6.16 build 4018 (gce16eae50)
Runtime: Docker

Printer: Brother QL-800
Label: 29mm x 90mm
Barcode Reader: MS9540 

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

When printing Barcode I encountered a subsequent problem with reading a barcode with a scanner. When I print a label from a snipe-it application it looks like a top label and is not readable for a scanner. I generated the other one via (https://barcode.tec-it.com) with the same content and it is normally readable for the reader.

![image1](https://user-images.githubusercontent.com/23487345/57434441-481ce180-723b-11e9-924e-44ef541c4a2b.jpeg)

![image](https://user-images.githubusercontent.com/23487345/57434467-5b2fb180-723b-11e9-9a3f-031c0bc9683b.png)

![image](https://user-images.githubusercontent.com/23487345/57434495-6aaefa80-723b-11e9-9dc0-7cab3d4f068b.png)

**Comment by gilesytheking** [comment]
Hi I had the same issue. The main problem is with the CSS code used to format the label. Some small CSS tweaks should get the label printing correctly. You may need to adjust the below CSS to suit your label size. If the img.barcode width is too small the barcode may become unreadable. You may have to compromise some label fields in order to fit the barcode onto the label.

![label](https://user-images.githubusercontent.com/15634270/57447282-a8694e80-724e-11e9-8f13-f93bcd4fbbfc.png)

My label Settings are as follows:

Display 3D Codes = Disabled
1D barcode type = C128

![label-settings](https://user-images.githubusercontent.com/15634270/57448603-afde2700-7251-11e9-955f-4696973d64de.png)

Add the below CSS code to Brand Settings -> Custom CSS

`div.barcode_container {
    height: auto;
}
img.barcode {
width: 75%;
padding-top: 0.05in;
height: auto;
}
.qr_text {
height: auto;
padding-top: 0.02in;
}
.pull-left {
text-align: center;
font-weight: 600;
}`

I also found that the GD image library generated the barcode images in a low quality and were not readable by a scanner. Changing the image library to imagick worked for me. 

You can change the image library setting in the .env file

# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=imagick

If you change the image library you will need to delete any existing barcode images. they will be regenerated with the new image library settings when you generate the labels.

You will find the barcode images in /your-snipe-IT-install/public/uploads/barcodes/

**Comment by GlowManCZ** [comment]
@gilesytheking Thank you very much, I set up the instructions. It looks a lot better, but the scanner still doesn't take the code :-(

**Comment by gilesytheking** [comment]
did you update the image library settings in the .env file?

You may need to clear the config cache for the new .env settings to take effect - https://snipe-it.readme.io/docs/clearing-the-config-cache

once you have cleared the cache delete the barcode images and regenerate the labels to create new barcode images.

Also make sure that your label printer is setup correctly. Most label printers have the following settings, however they may vary slightly for your printer.

- graphic, printer quality = 600 x 300 dpi
- printer feature, print quality = barcodes & graphics (best)
