### ISSUE TITLE
Snipe with Apache Mod_Proxy

### ISSUE THREAD

**Issue by MrPetkus** [snipe/snipe-it#703]
Great app!
I've set the service up on an internal network and everything works flawlessly.  However, I need to expose the application to a broader audience on a more public network.
With other apps of this sort, I use Apache with Mod_proxy on a separate system to proxy external connections.
This doesn't work with snipe-it - proxied connections cause a loop that I suspect has to do with the rewrite rules in .htaccess.

Here is the error message on the internal system:
Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

Any help or ideas would be appreciated.

Internal Apache conf:
 Alias /snipe-it "/var/www/snipe-it/public"
        <Directory /var/www/snipe-it/public>
                Options FollowSymlinks Indexes
                AllowOverride All
                Require all granted
                ...
       </Directory>

External Apache conf (proxy):
ProxyPass /snipe-it https://internal-system.local/snipe-it/
ProxyPassReverse /snipe-it https://internal-system.local/snipe-it/

Thanks in advance!

**Comment by uberbrady** [comment]
Is this still an issue?

If so, let me ask some follow-up questions - 

- Can you *definitely* access https://internal-system.local/snipe-it/ without any issue? You can log in, you can navigate around the app, everything is normal?
- Can you tell which URL's you're being repeatedly redirected to/from? I'm wondering if it's a cookie problem on login - establishing the session - possibly referencing the 'wrong' domain name - see ```ProxyPassReverseCookieDomain``` and ```ProxyPassReverseCookiePath```
- If you change the TLS (SSL) requirement - switch to http:// instead of https:// in your proxy config, does that make any difference?

As a work-around, many users simply host a normal version of Snipe-IT and expose it to the internet. You may want to at least consider that temporarily until we can figure out what's going on here.
