### ISSUE TITLE
Issue Upgrading from v4.6.16 to v4.74

### ISSUE THREAD

**Issue by Gareth2019** [snipe/snipe-it#7134]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Upgraded from v4.6.16 to v4.74 via the sudo -u apache php upgrade.php script ends with the following error under most Steps:

In Kernel.php line 59
  Call to undefined method App\Console\Kernel::load()

Snipe give a: System Unavailable error when accessing the url.

Kernel.php appears to be updated and line 59 is:
$this->load(__DIR__.'/Commands');

**To Reproduce**
1. cd /var/www/snipe-it
2. sudo -u apache php upgrade.php

running php artisan serve gives the same error

**Screenshots**
![Capture](https://user-images.githubusercontent.com/51477296/59095644-f5554900-8910-11e9-9677-24c83b842fdd.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.16 
 - CentOS 7
 - Apache
 - PHP Version 7.2.18

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [chrome, safari and IE]

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on Centos 7, apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- Indicate whether or not you've manually edited any data directly in the database. No manual editing

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Gareth2019** [comment]
The issue turned out to be related to the Laravel version which was 5.4.35 and the upgrade was failing as the Kernal.php was referring to new code added in 5.5.  Pulled the composer installer via:

curl -sS https://getcomposer.org/installer | php

Then ran the upgrade again and it all worked and the correct version of Laravel was running (5.5.45)

**Comment by snipe** [comment]
> The issue turned out to be related to the Laravel version which was 5.4.35 and the upgrade was failing as the Kernal.php was referring to new code added in 5.5

When you use `upgrade.php`, it will pull from master (which in this case is Snipe-IT 4.7.4, which uses Laravel 5.5). Usually when you see this it's because composer has cached some critical files.

Also you should never use sudo to upgrade. If you have to, your permissions are donked somewhere else in your system. 

Glad to hear you're all sorted tho. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
