### ISSUE TITLE
Companies list not displaying

### ISSUE THREAD

**Issue by bdmchamp** [snipe/snipe-it#7142]
Hello,

When I go to select a "company" that an asset belongs to, a list is not populated. However, the companies are present in the settings menu. Any help will be greatly appreciated. Thank you.

![Image](https://user-images.githubusercontent.com/30905530/59226073-37e08500-8ba0-11e9-8f7b-c1b51a8d579d.PNG)
![Capture2](https://user-images.githubusercontent.com/30905530/59226079-3a42df00-8ba0-11e9-8876-81d66f8ed6d9.PNG)

**Comment by bdmchamp** [comment]
Hello,

Does anyone have any thoughts on this? Is this something that was seen before?

**Comment by vedder26** [comment]
Hi, I have the exact same problem with all the lists...category, manufacturer, etc. It's a fresh install, 4.7 version of Snipe-it, with IIS on windows 10, and MariaDB 10.0.36

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

#### Confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Add any other context about the problem here.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by snipe** [comment]
Additionally, does the logged in user have the ability to see all companies (are they super admin)?

**Comment by sreu94** [comment]
Five years later and still the same issue?
I just installed the software for the 3 time (git, install script and docker), in none of the installs I am able to load the manufacturers.

**Comment by snipe** [comment]
@sreu94 because clearly this was already resolved a long time ago, as clearly evidenced on [the demo](https://demo.snipeitapp.com) - and we really don't need the attitude. Open a new issue, since yours is clearly unrelated. Be sure to include the debugging info we request in the issue template.

**Comment by dbhalla2280** [comment]
> Hello,
> 
> When I go to select a "company" that an asset belongs to, a list is not populated. However, the companies are present in the settings menu. Any help will be greatly appreciated. Thank you.
> 
> ![Image](https://user-images.githubusercontent.com/30905530/59226073-37e08500-8ba0-11e9-8f7b-c1b51a8d579d.PNG) ![Capture2](https://user-images.githubusercontent.com/30905530/59226079-3a42df00-8ba0-11e9-8876-81d66f8ed6d9.PNG)

SOLUTION:

go to your .env file
Make sure there is no / at the end of your App_URL. it should end with IP address or port if you changed default.
run D:\Snipe-IT>php artisan migrate

any time you make any change in .env file, make sure to run this command
