### ISSUE TITLE
txt file upload being treated as mime type application/x-wine-extension-ini

### ISSUE THREAD

**Issue by seanmcilvenna** [snipe/snipe-it#7284]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
We have a license file that we are trying to upload that is in .txt format. When we upload the .txt file to Snipe-IT, it fails with a message saying "Error: Please check the form below for errors". After investigating, we find that we can ZIP the .txt file and upload the ZIP just fine. For some reason, it thinks the .txt file is a different mime-type than it is or allows. I've looked for a way to add custom mime-types to a "white-list" (of sorts) but can't find anything. Somewhere, some magic is happening that is checking the mime-types instead of the file extensions.

**Expected behavior**
It should always treat a .txt file as a plain text file, rather than a different mime-type.

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.16
 - OS: Ubuntu 18
 - Web Server: Apache 2
 - PHP Version 7.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  75.0.3770.142

**Comment by snipe** [comment]
> Somewhere, some magic is happening that is checking the mime-types instead of the file extensions.

That's expected behavior. We can't trust file extensions and allow them to be downloaded/potentially executed from the server, as that's easily faked just by changing the file extension. Mime types aren't THAT much safer, but they're better than just trusting the file extension. I'd guess wherever you got the text file from gave it an incorrect mime type. Try copying it into a new text file and saving it and then uploading it that way.
