### ISSUE TITLE
Asset tags without leading zeros

### ISSUE THREAD

**Issue by enosvazquez** [snipe/snipe-it#7299]
We have asset tags with leading 0s i.e. 012345 but the prior team added them as 12345 in snipeIT; now when we search, for 012345, snipeIT shows no asset found; however, if you type 12345, it will show up.

Could we make snipeIT so that it does return the result regardless if you have or don't have a leading zero in the search field?

Thanks

**Comment by enosvazquez** [comment]
This is the first response I have gotten about my post. This issue continues to happen.

**Comment by eduder** [comment]
I'm having the same issue as @enosV 

Our assets are stored in Snipe-IT without the leading zero's, but our pre-printed asset labels all have leading zeros. So if I scan one into the asset search box, it isn't found.

I wasn't able to find anything in the documentation that shows a way to have search ignore leading zeros.

**Comment by uberbrady** [comment]
I would probably go through and update the asset tags to have the leading zeroes in the DB. There’s a SQL query that will do that for you here: https://snipe-it.readme.io/docs/regenerate-asset-tags

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/regenerate-asset-tags">Regenerate Asset Tags</a></strong></div><div>Though this is likely not something that would be necessary in most cases, Snipe-IT provides a command-line tool that allows you to regenerate all of your asset tags. From the Snipe-IT project root, via command line, run: After the asset tags are regenerated, you'll want to update your Admin &gt; As...</div></blockquote>

**Comment by eduder** [comment]
@uberbrady Thank you for that workaround - it will work, I was able to do the SELECT query to preview the change. However, I forgot that for some items we have that don't have an asset tag label yet, I have the device serial number in the asset field. I was able to modify the SELECT query to only make the changes to numeric asset_tag fields (the ones with serial numbers also have letters), but I don't know how to translate that to an UPDATE/SET query. Would you happen to know how to do that?

Here is the query I am using (we use 5 digits):
``SELECT asset_tag,LPAD(`asset_tag`, 5, '0') from assets WHERE asset_tag > 0 and asset_tag != LPAD(`asset_tag`, 5, '0');``

**Comment by uberbrady** [comment]
@eduder There’s a `LENGTH(asset_tag)` clause you could put in there somewhere, I’m thinking something like (and PLEASE run backups first!!!)

```
UPDATE assets SET asset_tag=LPAD(asset_tag,5,’0’) WHERE LENGTH(asset_tag) < 5
```

(the above query assumes that all serial numbers are longer than 4 characters, which is probably pretty safe to assume)

But for your original question, it looks like it oughtta be something like:

```
UPDATE assets SET asset_tag=LPAD(asseet_tag,5,’0’) WHERE asset_tag > 0 and asset_tag != LPAD(‘asset_tag’,5,’0’)
```

But I’m not convinced the second one will definitively work…

One trick you can use is running the `UPDATE` within a transaction, then do some check SQL queries to make sure it looks okay, and hit `COMMIT` only when you’re sure you’ve got what you want (and `ROLLBACK` if otherwise). Note though that if you make a syntax error in your SQL check queries, that will fail the transaction and you’ll have to re-start it (and re-run your `UPDATE` query).
