### ISSUE TITLE
Bulk Checkout not working with barcode scanner

### ISSUE THREAD

**Issue by HoosierLand** [snipe/snipe-it#7306]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Bulk Checkout will not except Barcode Scanner input.  When selecting the Assets form box (in Bulk Checkout), a dropdown lists some assets, with the first asset highlighted.  When a barcode is scanned, the highlighted asset is returned in the form box - instead of adding the scanned barcode.

Keyboard entry does work - which also searches and finds the correct Asset.  

**Server (please complete the following information):**
 - 4.7.6
 - OS: Windows Server 2012 R2
 - Web Server: IIS
 - 7.3.7
- MySQL 8.0.17

**Desktop (please complete the following information):**
 - OS: Windows 10 build 1809
 - Browser Chrome v75

**Additional context**
- Fresh Install
- Manual installation
- During installation I had to disable the PHP extension php_mysql.dll to install Composer

**Comment by TJucutan** [comment]
I'm having a similar issue. Whenever I use a scanner in bulk checkout, it will always select the first Asset listed alphabetically in the field, then I have to scan again to get the correct asset and delete the first asset when I'm done scanning. 
![Screen Shot 2019-10-02 at 5 23 10 PM](https://user-images.githubusercontent.com/49167810/66090698-5e547280-e539-11e9-910e-cca1ec6e05a2.png)
So the first asset listed will always be entered first when using a scanner. I think it's because the scanner is detected as a keyboard by the computer, so the first scan is registered by Snipe IT as "Enter" even if I click away so the drop menu goes away, the first item will always be that top asset listed.

**Comment by phoenix-303** [comment]
Did anyone find a solution for this? I'm running into the same thing.

**Comment by athompsoncmc** [comment]
I am still having this issue. I have also tried using line feed and carriage return on the scanner. Upon first scan, the text enters but then disappears. Upon second scan, the text enters and remains, but bulk checkout does not receive the "enter" key submission that would be given by carriage return or line feed. So when the next item is scanned, it just deletes the entry. If anyone has any solutions to this, I would appreciate it. I've tried implementing bricelabelle's google script #6819, but it won't work because I'm using a localhost, and it goes through Google's DNS.
