### ISSUE TITLE
Restore backup

### ISSUE THREAD

**Issue by MarkWareham** [snipe/snipe-it#7469]
**Server (please complete the following information):**
 - Snipe-IT Version : v4.7.7
 - OS: Ubuntu 18.04
 - Web Server: Apache2
 - PHP Version 7.2

**Is your feature request related to a problem? Please describe.**
Attempting to restore a backup. I have found a few issues here, but each only give a fragment of help. For example I have setup snipeIT using the install script, so I am not aware of any DB credentials to restore using mysql

**Describe the solution you'd like**
A simple file upload to restore.
or documentation on how to restore using mysql and regarding the file structure that comes in the backup zip

**Describe alternatives you've considered**
Tried various snippets of help in issues.

**Additional context**
Swift recovery is useful. I have spent several hours trying to restore after an OS upgrade.

**Comment by NightyKnight** [comment]
Hey Mark,
I just had to go through the painful process of migrating from one older Snipe-IT version to a new server and installing from the script.
I made a gist about how to migrate the database and application data, maybe it will be of some help to you.
[Restore Snipe-IT From Backup](https://gist.github.com/NightyKnight/de5e832050f4b996e63ffaa305037bf9.js)
I also have the whole process documented as I'm behind a corporate proxy and had to make some modifications to a few scripts in order to get it to work. Let me know if you would like the rest of my documentation.

-Brad O
