### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by goetzk** [snipe/snipe-it#775]
I've just set up snipe and noted a few things down about the setup process which I feel the docs should be expanded to cover. I don't see the documentation in git so I'm assuming its handled separately.

* Downloading source
http://snipeitapp.com/documentation/ nor http://snipeitapp.com/documentation/installing-on-linuxosx/ cover downloading/acquiring the project.

* Requirements
There seem to be some requirements missing. I had to install php-pdo, php-mysql (for database access to work correctly) and php-mbstring (for composer).

* MySQL as database
I installed on Centos 7 which comes with Mariadb, one of the mysql clones and it seems to be working fine. It might be worth mentioning in the documentation that any of the mysql compatible databases will do but I'll understand if you think it needs more testing.

* Choice of image library
I installed php's imagagick extension php-pecl-imagick via yum but can't figure out how to use image magic instead of gd. I edited vendor/intervention/image/src/config/config.php but it doesn't seem to have been enough. Could the docs be expanded to cover that choice? Is there a command that needs to be run after?

* Composer
Installing composer locally is mentioned but not installing it system wide. if 2.2 could be updated to include the install command that would be really handy (I used `curl -sS https://getcomposer.org/installer |php -- --install-dir=/usr/local/bin').

My git checkout seems to have an out of date composer.lock so i had to use 'composer.phar update' instead of 'composer.phar install'. I'm not sure if install should be replaced with update in the guide but thought I'd mention it here.

* Permissions
When using selinux there can be permissions problems. These two chcons might be handy for others too.
 chcon -R --reference=/var/ww/html /srv/snipeit
 chcon -R --type httpd_sys_rw_content_t /srv/snipeit

* Webserver
The config example for a lamp stack is incomplete, it should include 'Allow From All' / 'Require all granted' in the Directory section as in OS X.

Thanks for your work on this project, hope the feedback above helps.

**Comment by snipe** [comment]
Hi @goetzk - thanks for your thoughts. I'll address them line by line.

- Downloading source - There's a pretty big link to download on the website (http://snipeitapp.com/download/) so I really didn't think that was necessary, but I can add something there.

- Requirements - That's fair. Most people use MySQL or MariaDB, and any app (not just ours) that uses MySQL or MariaDB will need that. I was keeping the requirements to things that are specifically uniquely required for this app, versus any other web based app.

- MySQL as database - There are some migrations that don't work with certain flavors of SQL databases, but I don't have enough data on them to know what they are, since most folks use MySQL or MariaDB. 

- Choice of image library - I'll need to look into how that library wants you to do it, but you should never ever edit anything in the `vendors` directory. Anything you change there can (and will) be blown out next time you update. it's why we don't check vendors into version control, and let Composer handle it. 

- Composer - Honestly, most of our users have a hard enough time installing it locally, and unless you're looking to install other composer-based apps, installing it globally doesn't really help you. That documentation is available on the Composer website, so I think it's out of scope for our docs.

- Permissions - Again, I feel like SELinux is a little our of scope for our documentation. I can add it, but the longer the docs are, the higher the chances that people won't read it, and then I have more tickets to answer. :(

- Webserver - Again, `Allow from All / Require Granted` shouldn't be something we have to explain, as it's pretty standard for any web-based application. We do require mod_rewrite, that's why we specify `AllowOverride All`, but `Allow from All` should be the default unless someone has set up specific denial rules.

**Comment by snipe** [comment]
I've updated the linux/OSX documentation. Take a look when you get a chance. http://snipeitapp.com/documentation/installing-on-linuxosx

**Comment by goetzk** [comment]
On 30/04/2015 12:36, snipe wrote:
> Hi @goetzk <https://github.com/goetzk> - thanks for your thoughts. I'll
> address them line by line.

Thanks for the updates! Sorry about my delay in getting back to you.

>     Downloading source - There's a pretty big link to download on the
>     website (http://snipeitapp.com/download/) so I really didn't think
>     that was necessary, but I can add something there.

Thats fair enough, if you think its redundant. I went the git clone
route so wasn't thinking about the download page.

>     Requirements - That's fair. Most people use MySQL or MariaDB, and
>     any app (not just ours) that uses MySQL or MariaDB will need that. I
>     was keeping the requirements to things that are specifically
>     uniquely required for this app, versus any other web based app.

Ah I see. I don't object to the instructions being like that but it
wasn't clear to me that was the case.

>     Choice of image library - I'll need to look into how that library
>     wants you to do it, but you should never ever edit anything in the

Thanks. I'm happy with the work around (use gd) should it turn out that
removing the imagick option is preferable.

>     Composer - Honestly, most of our users have a hard enough time
>     installing it locally, and unless you're looking to install other
>     composer-based apps, installing it globally doesn't really help you.
>     That documentation is available on the Composer website, so I think
>     it's out of scope for our docs.

I understand.

>     Permissions - Again, I feel like SELinux is a little our of scope
>     for our documentation. I can add it, but the longer the docs are,
>     the higher the chances that people won't read it, and then I have
>     more tickets to answer. :(

More tickets is bad :(
While I won't push you on this issue I think its worth mentioning given
the number of distributions enabling it by default (Although a sense our
conversation has provided free documentation - if someone has the issue
they can refer here).

>     Webserver - Again, |Allow from All / Require Granted| shouldn't be
>     something we have to explain, as it's pretty standard for any
>     web-based application. We do require mod_rewrite, that's why we
>     specify |AllowOverride All|, but |Allow from All| should be the
>     default unless someone has set up specific denial rules.

Thanks for adding it despite your preferences. I certainly feel its
clearer that way.


Thanks again for your work on this project.
kk

**Comment by snipe** [comment]
Hi @goetzk - thanks for your thoughts. I'm updating the docs now to add the SELinux bits. Would you want to use:

`chcon -R --reference=/var/ww/html /srv/snipeit`
`chcon -R --type httpd_sys_rw_content_t /srv/snipeit`

or would it be better to only change the security contexts on the directories that need to be writable?

**Comment by goetzk** [comment]
On Fri May   1 15:09:42 2015 snipe <notifications@github.com> wrote:
> Hi @goetzk - thanks for your thoughts. I'm updating the docs now to add
> the SELinux bits. Would you want to use:
> 
> `chcon -R --reference=/var/ww/html /srv/snipeit`
> `chcon -R --type httpd_sys_rw_content_t /srv/snipeit`
> 
> or would it be better to only change the security contexts on the
> directories that need to be writable? 

The writable directories need changing, i haven't tried with the rest of the project in its user context - if you like i will test on monday to see if its needed.

Thanks, 
kk
