### ISSUE TITLE
UI Request: Move Edit / Generate Labels dropdown to the top of the page

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#785]
A very minor thing, but, having the Edit dropdown at the bottom of the page means having to constantly scroll down to use the edit feature - especially as a lot of our asset lists are long enough that they require scrolling.

Typically when doing a bulk edit I will adjust all items by Model, and then select all of that model and perform the edit.

I suppose I could filter by the model as well - however, IMHO, moving the edit option to the top of the page (maybe beside the Show # of items dropdown) would be slightly more functional.

Cheers,

**Comment by snipe** [comment]
We have it down at the bottom because that upper left hand space on the table is already pretty crowded.  Adding another dropdown in that area will make for a very cluttered UI, leading to some mis-clicks and frustration. I'll try to think about a better way to solve this. 
![screen_shot_2015-05-04_at_11_16_34_am](https://cloud.githubusercontent.com/assets/197404/7459268/938f9934-f24f-11e4-8f91-58a3f92cb4f5.png)

**Comment by snipe** [comment]
This is fixed in the upcoming v3
