### ISSUE TITLE
MySQL User permissions

### ISSUE THREAD

**Issue by deltamualpha** [snipe/snipe-it#790]
Hi, having some fun setting up Snipeit and just had a documentation question:

For a MySQL user, what's the bare minimum permissions they need to the database? I set the user up with `GRANT ALTER, CREATE, INSERT, SELECT, DELETE, UPDATE, DROP, LOCK TABLES, INDEX` etc etc, and the migrations all ran... are any of those superfluous? Should this be added to the documentation?

**Comment by snipe** [comment]
It's funny, I actually always recommend granting the least possible privilege to DB users, and because of the way migrations are run, it's actually not possible the way I prefer to do it. For example, the privs for just running the app (after migrations have been run) would be  `INSERT`, `SELECT`, `DELETE`, `UPDATE`, but because running the database migrations requires the ability to alter tables (and potentially drop them), I can't recommend using just those, even though those perms are only necessary during DB migrations. 

The bare minimum I think you can get away with would be `ALTER, CREATE, INSERT, SELECT, DELETE, UPDATE, DROP, INDEX`.
