### ISSUE TITLE
Losing permissions when updating Snipe-IT

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#823]
I have noticed each time I update my snipe-it install I have to re-do all of my permissions on my snipe-it dir (probably because the upgrade process currently involves copying and pasting the new installation over the old one)?

Is there a simpler way to do this that I'm missing? I've tried copying without preserving permissions but because the files + directories are still being over-written it didn't really make any difference - to be clear, my Apache web dirs are secured so that by default public users can't write to the web app dirs, unless explicitly given permission to do so (they have read and execute but not write by default on the parent folders). That leaves me with having to set write permissions on the folders that require it each and every time.

Is there any way to upgrade Snipe-IT without having to keep resetting the write permission back to the folders that need to be written to?

**Comment by rp-tech** [comment]
Hi I'm just wondering if anybody else has seen this problem or has looked into it - the way Snipe is being updated now each time I end up with errors such as these and have to go back / set up permissions again for apache:

![2015-07-13 11_49_48-whoops there was an error](https://cloud.githubusercontent.com/assets/10659713/8657922/5e89f738-2955-11e5-80ca-a90a1b54dd49.png)

**Comment by snipe** [comment]
Hi @rp-tech - that usually happens when there is a mismatch in the group for the web/cli user. For example, if your files are all owned by apache, when you run things via command line, you're not usually running them as apache, so if the command line user and the apache user aren't in the same group, you can run into permissions conflicts. Basically, the file you're trying to overwrite is owned by apache, but as you're updating it with your linux system user, that linux system user isn't apache. You can try adding your linux system user to your apache linux group.

**Comment by rp-tech** [comment]
it's actually the opposite; each time I over-write the snipe dir with the upgraded one I have to chgrp the respective files in the /app/storage directory to the apache group.

I  was wondering if there is a way to avoid this - by default all files when i first copy them over belongs to the system user i used to copy the files.

Regards,

**Comment by snipe** [comment]
I don't think that's the opposite at all, I think that's exactly what I'm describing. When you run the cli stuff, you're running it as the system user, which is why it breaks on files owned by apache. If you add the system user to whatever primary group apache is running is and the file contents and directories and all in the apache group with group write permissions, you should be good.

**Comment by rp-tech** [comment]
Hmm, I never thought of it that way. Then again I am still fairly new to the way linux is assigning permissions so I will definitely give it a try.
