### ISSUE TITLE
Deleting User Doesn't Delete Email

### ISSUE THREAD

**Issue by AnthonyHautin** [snipe/snipe-it#824]
I have deleted a user then went to create a new user which has the same email address of the one I just deleted and it won't let me add it as it says it is in use.

**Comment by kobie-chasehansen** [comment]
Nothing is ever really deleted.

If you click on people, then show deleted users button in the top right you can restore that user/email and just edit the details.

**Comment by AnthonyHautin** [comment]
Ah how embarrising I didn't even notice that button!

Thank you.

**Comment by mahesh2471990** [comment]
can we restore bulk users at time. 
Or can we delete all the users in Deleted Users.
@kobie-chasehansen  Please me out i tried to delete the user i got some error..
![error](https://cloud.githubusercontent.com/assets/16305213/12015842/8d00c44c-ad68-11e5-9e10-ea6270ea7a32.JPG)

The user was imported from LDAP. i deleted all user re-sync. But the sure didnt display. So i wanted to delete all user in Deleted Users. Sync again.

**Comment by viewmithun** [comment]
Snipe - IT doesn't have the feature of deleting the users completely. But, it would be great, if we have this feature. We have so much of dump users and their email ids, which we could like to delete forever. 

@snipe It would be really great, if we have your eye in this case and any suggestion please?

**Comment by snipe** [comment]
@viewmithun if you permanently delete users, you lose the history associated with them for any assets that might still be in circulation. Historical knowledge for things that still exist is specifically why we only soft-delete things.

**Comment by viewmithun** [comment]
I think, Snipe IT already doesn't allow deleting a user, who owns an asset. 

Maybe, we could have some grace period to each user like a month and then a Super user should be able to permanently delete the users. 
Any thoughts toward this?

**Comment by snipe** [comment]
@viewmithun You can delete a user that owns an asset via bulk deleting, but you have to pick a status for the assets that were previously associated with them. 

Again, the grace period doesn't matter. If I have a laptop that has been checked out and checked in to 8 different people (because of employee turnover, etc), if I delete the previous 7, I won't have any idea how many people (or who) that asset used to be associated with. The historical information is one of the most beneficial parts of using a system like Snipe-IT versus Google Docs.
