### ISSUE TITLE
Checking out asset does not change status

### ISSUE THREAD

**Issue by athena-harting** [snipe/snipe-it#833]
When I check out a system to a user, the in/out status is set to deployed but the status id is still set to "ready to deploy". Is that by design? 

![checkin](https://cloud.githubusercontent.com/assets/11642137/7973578/06e6b74a-0a0c-11e5-8225-ff5872bc1a81.PNG)
![readytodeploy](https://cloud.githubusercontent.com/assets/11642137/7973579/092454b8-0a0c-11e5-823c-aaad529ee42e.PNG)

This messes up reporting because when you go to see the status of the asset in the reports, it displays as "ready to deploy" and not "deployed"

**Comment by snipe** [comment]
I think the real issue is that there isn't a "deployed" status label. Once an asset gets checked out, it becomes deployed regardless of whatever the assigned status label is, so I think what we should do in that situation is to remove the status dropdown when editing an asset that's already checked out to someone.

**Comment by fikrigusti** [comment]
I keep don't understand why must must remove the status dropdown. In my case, when generating report the status is important to get the detail whether the asset is 'ready to deploy', 'broken', 'archived' or else. It is the important thing from my point of view. Is it possible to make the status following the transactional module?
