### ISSUE TITLE
Custome Report

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#844]
Hi all,

 there is any option for custom report or individual person report option in snip-it.if have pl tell me about

**Comment by modernknight** [comment]
Hey umerafridi,

The best I can find is click on "reports," "Custom Asset Report," then check needed cells (in this case "Asset Tag/Display Asset Name" and "Assigned To"), then on the downloaded .csv do a search on the user you need to. Otherwise, I don't see a quick option for getting a single person report. Perhaps a feature for later? I know they have come a long way with reports in the past few months!

**Comment by snipe** [comment]
The user view pages (which include history, assets, accessories, etc) are printable. They *are* the report.
