### ISSUE TITLE
Configuration tab for Desktops and laptops

### ISSUE THREAD

**Issue by sreejoo** [snipe/snipe-it#864]
Hi,

This could be better if we get a option for insert the desktop /laptop configuration details

Like processor/Ram/hard disk. 

Thanks
Sreeju

**Comment by sreejoo** [comment]
Filtering option based on Processor is another suggestion

Thanks
Sreejith.G

**Comment by snipe** [comment]
This would be handled via custom fields, which @uberbrady is working on for v2.1 or 2.2

**Comment by tarundixitravi** [comment]
I have added custom fields( Processor RAM  HDD etc) not showing on asset create page. 
Showing on import page. But importer not working. skipping records without error.

**Comment by snipe** [comment]
@tarundixitravi - Hi there - this issue is closed and doesn't seem directly related to your issue. Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)

You have to [associate the fields with a fieldset, and then associate that fieldset to the asset model](https://snipe-it.readme.io/docs/custom-fields).
