### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by jkarol7** [snipe/snipe-it#942]
Does anybody know how the QR codes work with Snipe-it and a good system for exporting all the different QR codes so I could print them out. Thanks.

**Comment by joeykhan** [comment]
Not sure what you want to print them with, but we use a Brother label maker....... with the P Touch Editor software you can link to a database, so I'm guessing you could export assets and hook it up to the asset-tag column.. If you have a Mac I suppose I could get you the software, otherwise you need a Brother serial. You can print to any printer technically.

**Comment by snipe** [comment]
@jkarol7 You can just use label stationary. Click on the assets you want to generate tags for, scroll down in the assets view and click on "generate labels" from the dropdown. That will generate the printable labels.
