### ISSUE TITLE
Feature Request - Asset Audit

### ISSUE THREAD

**Issue by hoody1** [snipe/snipe-it#943]
It would be great to have an Asset Audit (stocktake) feature that could be run yearly that then when complete would spit out a report with the relevant information on whether the asset has been updated, correct, created or was not Audited.

My currant thought is to have another menu category titled Audit then under that a subcategory’s that would be a link to the Audit page & Audit Report

My thought on how it might work was to have a page that had a field that you would enter the asset tag in and then it would pull up the info of that asset and you would click correct, update or add new if the asset tag turned no results from there it would then take you to a page to either edit or add a new asset and on completion of editing or adding or clicking the correct button an entry would be tied to the asset with that it was audited and then it would shoot you back to the Audit page  so that you can scan the next asset. 

Maybe a section on the Asset Audit page that allows setting an audit start and finish date 

With the report maybe an export to PDF that would contain the number of devises audited how many correct, updated and new and also a number of assets that are in the system that weren’t audited and then maybe full details as another report. 

The attached image was something I drew up to help explain my thoughts.

I know this would be a large feature but it is something that would benefit the school I work in as we have to conduct audits yearly on all of our Assets and generate a report for the principal to sign off.

![asset thought1](https://cloud.githubusercontent.com/assets/7729807/8842516/42a2c40e-313a-11e5-81aa-3174f4b5a011.png)
##

**Comment by lcalway** [comment]
My company is looking to purchase the hosted product and would love to see this enhancement included. Do you have a release date?

**Comment by snipe** [comment]
@lcalway we haven't released 2.0 yet, so 2.1 wouldn't be for another month or so most likely

**Comment by snipe** [comment]
@hoody1 I think what I'm trying to parse here is how "correct" would be different from "update". We could have an audit section, but duplicating the edit functionality and calling it something else feels clunky to me

**Comment by lcalway** [comment]
Awesome! Thanks for letting me know!

**Comment by hoody1** [comment]
@snipe Yeah I understand that it feels clunky I was just thinking from a point of view of someone who would be reading the report so that it was in more simple terms in a manner of speaking.

The thought on the “Correct” tag would be an asset for which the details are correct i.e. they don’t need to be edited. The “Updated” could be called “Edited” instead and this would be for an asset for which the details weren’t correct and needed to be updated i.e. was now being used by someone else or had been moved to a different location.  The “New Asset” would be used if during the audit process you came across a device that wasn’t in the SnipeIT database.  In our case, I know we will have a lot in this category as our SnipeIT database contains over 1000 items and I know we have a lot of devices that we still need to add.

**Comment by c-jones** [comment]
Looks like this didn't make 2.1. Is 3.0 the current target or a new timeline for this feature?

**Comment by tmongero** [comment]
@snipe Also curious if there is any timeline on this.

**Comment by lcalway** [comment]
+1 for this feature as soon as possible.

Regards,

*Lyndon Calway*
ICT Client Services Coordinator



Phone: (03) 5625 4600 ext. 118
Support Number: (03) 5625 0118
www.chairo.vic.edu.au  <http://www.chairo.vic.edu.au>

On 30 January 2016 at 05:03, Thomas Mongero <notifications@github.com>
wrote:

> @snipe <https://github.com/snipe> Also curious if there is any timeline
> on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snipe/snipe-it/issues/943#issuecomment-176889197>.
>

-- 
Disclaimer: Whilst every attempt has been made to ensure that material 
contained in this email is free from computer viruses or other defects, the 
attached files are provided, and may only be used, on the basis that the 
user assumes all responsibility for use of the material transmitted. This 
email is intended only for the use of the individual or entity named above 
and may contain information that is confidential and privileged. If you are 
not the intended recipient, please note that any dissemination, 
distribution or copying of this email is strictly prohibited. If you have 
received this email in error, please notify us immediately by return email 
or telephone 03 5625 4600 and destroy the original message. The contents of 
this message are provided without responsibility in law for their accuracy 
or otherwise and without assumption of a duty of care by the Warragul 
District Parent Controlled Christian School Association Incorporated 
trading as Chairo Christian School.

**Comment by chozian** [comment]
+1 for this feature request

**Comment by kayec** [comment]
+1 for this feature request

**Comment by charlieafoxtrot** [comment]
+1 from me too!

**Comment by lbogdans** [comment]
+1 from me too!
