### ISSUE TITLE
Barcodes Can be More Useful

### ISSUE THREAD

**Issue by dscherertfm** [snipe/snipe-it#973]
Currently, barcodes are generated as a 2D QRCode, it would be cool to be able to choose 2D or 1D code (Code 3 of 9 for example), as well as have the generated labels suitable for more label formats.

Also, the barcode currently encodes an asset URL. I think it might be more useful to encode the asset tag, or have an option to encode one or the other (which helps support the feature(s) below).

Following that, having a check-in/check-out box on the user's profile page where I can quickly scan barcodes to check an asset out/in to/from a user would make the process really straight-forward and fast. The note could be set to "Scanned" or something or left blank to eliminate the need for a manager to do anything more than scan and go (by configuring the scanner to trigger an Enter keypress after scanning and setting/resettting the focus on the field on page load and subsequent scans).

Baring that, at least being able to search for an asset/accessory/software license from the user's profile page in an omni-box type thing would possibly do the same thing and would at the very least keep a manager from moving between the different sections of the site to find and checkout assets to a user. Being able to search would help for assets that are not barcoded, like accessories or software licenses.
##

**Comment by dscherertfm** [comment]
Similar to #827

**Comment by uberbrady** [comment]
The poster from #1185 wants a more programmatic way of generating the QRCode - choosing to display different numbers or codes or serials rather than whatever we have hardcoded.

Some other users want access to this too; I just don't know how far down a template-writing hole we want to necessarily go - would it be bad to let users write their own blade-style templates - with `{{variablename}}` type escapes or something? Or maybe something like BBCode or Markdown? I don't really know.
