### ISSUE TITLE
Custom Model Attributes

### ISSUE THREAD

**Issue by peelman** [snipe/snipe-it#98]
@snipe has mentioned this in another ticket, but I was hoping to get some discussion going on it and define the idea and storage model some.

**Comment by mattparkes** [comment]
+1.
We'd love to see Custom Fields, even if they aren't initially searchable or the searching is quite naive.

**Comment by pratikpul** [comment]
The requirement was added under consideration and atleast 6 months ago, we would love to get this feature. I am new to Snipe IT and is preety amazing but the first thing I noticed about missing Model attributes.
Can we have any updates on when we will get this?

Thanks!

**Comment by cobrien165** [comment]
I would certainly like to see this as well in a future release. Even a simple notes field under each asset model would work for my scenario. Along with most people I'd imagine, we purchase most models in bulk that will all have the same specs as far as CPU, RAM, Hard Drive, etc. Then we would detail any upgrades under the notes field of the specific asset. 

Some other fields to maybe think about would be FRU part numbers for spare laptop parts ordering such as replacement keyboards, bezels, screens; but again, could be added into a notes field for now.

**Comment by ari** [comment]
Is this feature still on the cards? It is the only reason we can't adopt your very nice system for our own use. I'd be very pleased with a very simple implementation:

custom_attribute

    id
    asset_category_id (FK)
    type (enum: string, number, password)
    allow_multiple
    name

custom_attribute_value

    id
    custom_attribute_id
    asset_id
    value (string)


No searching. No validation (other than the type).


For us at least, that would be great.

**Comment by snipe** [comment]
Still on the table. Again, the tricky part is searchability, and even if you don't need it, other folks definitely will. :-/ Hoping to get it handled for the next big release.

**Comment by ari** [comment]
Cool. I'm not clear why searching is hard. Without looking at your schema for the details, it is something like:

     select id from asset join asset.id = custom_attribute_value.asset_id where custom_attribute_value.value = "something" and custom_attribute_id = 47

where 47 is the attribute id determined from the UI. There would be a drop down menu for choosing which attribute to search on and a field next to that to type in a value. Obviously there is more work needed to construct multi-line searches and allow AND/OR combinations, but a single attribute is trivial.

**Comment by snipe** [comment]
I think you just answered your own question. It's the and/or combos that are problematic if we want to include an "all things" search (which we do). As I said, hoping to get it handled in the next big release. It's mostly only me developing this, and I run a startup in addition. It's not really about the technical challenge, just about the time.

**Comment by ari** [comment]
No worries. I know that open source isn't something you can always devote a lot of time to. I had a quick dig into your code, but PHP isn't my strength. I'm guessing you need [to edit the search in the controller](https://github.com/snipe/snipe-it/blob/3c00f38a0fd902407e49a79e315fb207ecee8706/app/controllers/admin/AssetsController.php#L1094) by adding 

    ->join(‘attributes’, ‘custom_attribute_value.asset_id’, ‘=’, ‘asset.id’)

Anyhow, perhaps I'm telling you how to suck eggs, so I'll leave you to it. Thanks again for a neat app.

**Comment by snipe** [comment]
With all due respect, I've stated several times that this is not a technological challenge but a time challenge. I don't actually need you to explain my code to me, especially when you've admitted that this language isn't your strength, and you haven't looked at the schema. 

While I understand that this feature is important to you, so are many other features to many other users, so unless you have a pull request ready, stop telling me how to manage my software. I've told you I'm hoping to have it in the next big release. No matter how many times or ways you speculate on how this problem could be solved (with no knowledge of the schema, no notion of the project's priorities, and no strength in the language), that's not going to change. 

You can either be patient, you can provide a pull request, or you can find another "neat" app that solves your problem.

**Comment by ESWBitto** [comment]
@snipe,
Thank you for making an awesome open source solution! 

Anywho, I wanted to add to this conversation on custom fields. I've read the entire discussion and I see now where your going with it. One thing that I've noticed with poking around testing out the UX is when creating an asset. If you don't have the model or the supplier already configured. You have to stop what your doing and then add them and then come back to creating the asset again. 

How much trouble would it be to branch into creating a new model or supplier (or custom field) while still trying to add your asset?

I think you mentioned something like a wizard? Would love to hear your $0.02 on it.

**Comment by snipe** [comment]
@ESWBitto - the ability to add a model while creating an asset is already on deck, though not in this ticket. :)

**Comment by uberbrady** [comment]
I'm going to start messing with this. I might end up painting myself into a corner or something, but I'd like to at least make a stab at it.

I am planning on doing it this way:

- "Models" determine which fields exist/dont-exist.
- Since many models will share the same 'fieldsets', I think I have to create a concept of a 'fieldset'
- I think my concept of 'fieldsets' (which I'd love a better term for, btw) can also handle required-ness, too. E.g. the field "Dell Service Tag" exists, and *must* be non-blank. Or the field "Apple Service ID(?)" must exist, and follow the regex: ```/[a-zA-Z][0-9]+/```. I think I will internally just have a regex, but for display I may offer the user "non-blank", "numeric only", "alphabetic only", "alphanumeric", or "custom regex" - and then substitute the appropriate regex in on save.
- so Models then can pick fieldsets
- Things like IP Address and MAC address can be encapsulated in this; should I yank them out and port them over? I can build a migration perhaps.

And finally, the scary bit: I think I want to do them as additional fields, with a particular name-scheme. E.g., if you create a new field within one of your fieldtypes named "case color", we actually do an ```sql
ALTER TABLE Assets ADD COLUMN (dynamic_case_color TEXT)``` or maybe something like "dynamic_17" for the 17th custom field (that way it's not name-specific). Maybe I'll do the former, and just not let you rename the field.

@snipe - any thoughts? Any of this you need to veto, or want changes for?

**Comment by snipe** [comment]
No, that's all about the way I was planning on handling it as well. We'll also need to dynamically add those fields to the listing JSON output and the "show fields" DataTables javascript.

**Comment by snipe** [comment]
(Or somehow handle that intelligently, models may have different custom fields, and so it will be challenging to normalize that into a table view when viewing all assets)

**Comment by uberbrady** [comment]
My thought for that one is simply "don't" - but maybe that's too simplistic.

Maybe, just to get a version of this out, I'll start with only showing them on an individual item's page. A later revision can perhaps include them in the columnar list-view.

**Comment by snipe** [comment]
@uberbrady - No, I get that, but we also want to build this in such a way where getting to that point won't be completely horrific.

I'm going to want some unit tests on this, I think, since a bug in the "delete custom fields" functions could be destructive to other data. 

I really hate handling this via alter table, but the only other alternative is a custom fields table which will put us into even more join hell.

**Comment by snipe** [comment]
Or maybe we just don't handle that on the listing page, but instead show that on the model's asset listing page: http://demo.snipeitapp.com/hardware/models/1/view

**Comment by cantmz** [comment]
Hi there,
I am planning to use snipe-it for smartpones/tablets and SIM cards too.
Custom fields for asset would be a huge step forward.
I'm thinking about the opportunity to add SIM card phone number, serial number, PIN, PUK, IMEI for devices and so on.
In a previous company I used Sugar CRM CE and built my own modules.
It worked like a charme but I was using a CRM for everything but its main purpouse.
I discovered snipe a couple of days ago and it is great.
It does exactly what most of us need.
Many thanks to all of you.

**Comment by Xu1** [comment]
I come here every once in a while and check the demo and read through the comments. Still no custom attributes. It's really sad that such a nice product lacks something as simple as being able to add an IMEI for a phone. I just don't understand the logic.

Almost 2 years since the OP made the request

Could someone please fork this and add the dam feature please.

**Comment by snipe** [comment]
@Xu1 The original OP in the discussion about this was *me* - the person who wrote the software to begin with, to communicate our intention and have a record of the feature I wanted to add. It never implied we'd be working on it first, or second, or anything. 

Custom fields are non-trivial, and potentially data-destructive - not to mention that they complicate search and just about everything else. We release new features *constantly*, so it's not a matter of not understanding the logic. It's not some vast conspiracy to withhold features. There are only 24 hours in the day, and this is free software. It's not as if we've been sitting around not adding other features for the past several years. We release features based on user feedback. 

If you've read the most recent comments, you'll see that it's actively in development right now, with a pull request submitted: https://github.com/snipe/snipe-it/issues/1277. The PR still needs some work, but it's getting there, and we're hoping to have it merged in the next few weeks.

**Comment by uberbrady** [comment]
If it's so simple, feel free to submit a pull request. If it works, it will be accepted, regardless of your horrible attitude. I have a feeling you'd find it isn't quite so simple.

So here's another way you could help - you could test out my branch. It's still very early stages, but even something as simple as "this seems like a good start, and it works so far for me" would have been helpful. But - you didn't do that either.

Fine, well, maybe *here's* a way you could help - I work on this project in my spare time, of which I don't have a lot of. Maybe you could just do something like say, "+1, would love this feature too, then I could use Snipe-IT! Excited to test it out once it's ready!" - not even requiring any work on your part. Nope, didn't do that either.

Instead, you post this miserable message. A message which discourages me, instead of encourages me. That is not a good way to get what you want. I'd almost be tempted **not** to finish the feature just to spite you, because I think you are behaving like an entitled, privileged jerk. I also fantasize about finding a way to finish the feature - but not make it available to you. Unfortunately, by the license terms, I cannot do this. (And, also, I wouldn't actually do it, either. But it's fun to fantasize).

But I'm not going to do any of those things; I will instead finish the feature. The 'guts' of it are already there, and there's more still to flesh out. But the hard parts are over. Now it's just figuring out the UI of what adding new fields looks like, and figuring out which field types and input types to support. As @snipe mentioned, it's probably a few weeks away still. But it's getting there.

**Comment by bioldame** [comment]
Its been a while since I write or report an issue here. I just wanted to say SnipeIT has been great for my team this year, we use it as our main tool for a laptop loaner library that is used a LOT by our users. We are very happy that LDAP integration was added and every time a new update comes out we update right away to take advantage of the new features. We will patiently wait for custom fields to come out and once it does Snipe IT will become our main and only asset tool for all of our assets! 

Thanks for creating and contributing for such a great tool!

**Comment by Xu1** [comment]
Wow that blew up! I'm impressed by that passionate response above.

I'll take a look at your branch... :+1:

**Comment by jgarm07** [comment]
Hello!

I wasn't a member of github but I am now. I'm hoping a little more positive feedback may help grease the gears a little.

I work at a public university in a department that manages computer labs on campus. 5 of us handle software, and one ops manager handles inventory. Our total inventory includes roughly 1800 desktop workstations (mixed mac and PC) along with 25 servers (mixed physical and virtual). For about 10 years that inventory has been managed in an access database. A few years ago a new department manager came along and decided to move the database into MySQL, leaving access as a front end, and abandoning the project; which has caused a headache for all of us. His next master plan is to move it into SharePoint and use views to navigate the data, which we also don't believe is the solution.

We're all systems administrators, not programmers, but the need for a usable tool to handle our inventory is great enough that I've spent the last couple months in my spare time trying to learn Ruby on Rails to develop a solution. Needless to say I was ecstatic to stumble across snipe IT. It is absolutely perfect for what we're trying to accomplish, particularly the archiving feature (because as a state entity we have to track stuff that permanently leaves our inventory too) which I have not seen in other open source solutions. All that's holding us back from implementing this solution is that the most important pieces of our database that we track are unit IP addresses, MAC addresses, kensignton key assigned to the unit, building, room, and room key. If I'm following this thread right, the addition of custom attributes will allow us to track those items and put this tool in place!

At least from where I'm sitting, your work will not go unappreciated. Thank you so much for everything you've put into this project. It is and will continue to ease some of the strain many IT departments put up with daily. We're eagerly looking forward to the next release!

**Comment by steveelwood** [comment]
Hey guys and gals,

Like jgarm07 above, I just joined Github so I could tell you all that my team and I really appreciate the effort you have put in and continue to put in to this software. I work at a small private college and we have been looking for something... ANYTHING, to replace an old Access database inventory solution that is difficult to work with or pull reports out of. There is an arcane, lengthy, twice-yearly process my boss and I go through to pull budget numbers, replacement schedules, and reserve analyses from that system. That being said, we've been staying up-to-date as new versions come out, and eagerly await the custom model attributes feature you are developing.

Thank you so much for a fantastic product backed by great developers!

**Comment by snipe** [comment]
Thanks so much for the kind words of encouragement, @jgarm07 and @steveelwood! I can promise you that custom fields are absolutely a priority, and the first version of them is coming along well. The basic functionality is there, and now we're just working in the UI elements. 

We're getting there!

![02xmfoi](https://cloud.githubusercontent.com/assets/197404/11260202/cd1d074e-8e1d-11e5-85e0-d7413b43e906.gif)

**Comment by rootAmeen** [comment]
Great to hear that it is coming along pretty well, @snipe. Can't wait to test it once it has been released.
Keep up the good work!

**Comment by snipe** [comment]
This is available on develop now.

**Comment by swegaj** [comment]
I want create  workstation in dropdown list in snipe-IT
Like Asset,User, License,
Please guide me on this
