### ISSUE TITLE
Import csv not working

### ISSUE THREAD

**Issue by aarnold-sd68** [snipe/snipe-it#9989]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When importing import the process button does not seem to do anything.  

**To Reproduce**
1. Go to 'Import'
2. Click on 'Select import file, select a file'
3. Click on 'Process'
4. No error, nothing happens

**Expected behavior**
You should get a screen that asks what type of import, and what to map the headers to.
 

**Server (please complete the following information):**
 - Snipe-IT Version : 5.1.8
 - OS: Windows
 - Web Server: IIS
 - PHP Version 7.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge and Chrome

**Error Messages**
- Production.ERROR: Too many arguments, expected arguments "command" "filename". in ...vendor\symfony\console\input\argvImput:172 <--This came from the browser There is about 7 more of these with a slightly different line number (I'm assuming that's what 172 is) but all the same argvImput.php file.
- Production.ERROR:  There are no commands defined in the "snipeit:c" namespace.
- production.ERROR: the "-f" option does not exist. {"exception":"[object] (Symfony\\Component\\console\\exception\\runtimeexception(code: 0) The \"-f\" option does not exist. at ...vendor\\symfony\\console\Input\\ArgvInput.php:187)
- 

**Additional context**
-Upgraded to 5.1.8 I think I was on 5.1.6.
- Windows Server 2019, IIS 10
- Git
- Followed the install procedure, and then upgraded to 5.1.8 using the update php file
- Everything should be as it was released, only thing I've changes is the .env file

**Comment by francogp** [comment]
I can confirm a similar problem. If I use Spanish, and for example export all users as .CSV, then I cannot import them because the columns identifier are duplicated (generating conflicts) or ignored due to bad translation.

**Comment by snipe** [comment]
This is expected behavior., You should be using the CSV templates in the docs, not the exported headers

**Comment by aarnold-sd68** [comment]
I am using a CSV template just like the docs.  
this is one example of the file, if I take this same file and use the command line it works as expected.
item name,serial,Expiration Date,Licensed to Email,Licensed to Name,Manufacturer,seats,Avail,category,supplier
Nameof,Code,21-Mar-24,,,HPe / Aruba,135,135,Aruba Central License,X10 Networks

**Comment by inietov** [comment]
I am using the importer extensively to import assets this week and it appears to be working correctly.
@aarnold-sd68 can you be so kind to please provide a CSV import file that fails to you, so I can see if I can reproduce the error?

**Comment by francogp** [comment]
> This is expected behavior., You should be using the CSV templates in the docs, not the exported headers

I tried, and it fail. I tried to import all users to a new installation. Errors everywhere.

**Comment by aarnold-sd68** [comment]
[ArubaLicenses-Clean.csv](https://github.com/snipe/snipe-it/files/7050434/ArubaLicenses-Clean.csv)
Here is the file I used.  I have removed the serial numbers from it.  I've also had the same issue importing assets.

**Comment by inietov** [comment]
Thank you! Let me see what I can find.

**Comment by snipe** [comment]
> I tried, and it fail. I tried to import all users to a new installation. Errors everywhere.

@francogp it will never be possible for us to diagnose an issue with a statement like “errors everywhere”. Please be specific to be terrific. Actual error log output, browser console logs, screen output, etc. 

The importer works - we have thousands of customers that use it. If it’s not working in your case, we need more info to work with with.

**Comment by francogp** [comment]
> > I tried, and it fail. I tried to import all users to a new installation. Errors everywhere.
> 
> @francogp it will never be possible for us to diagnose an issue with a statement like “errors everywhere”. Please be specific to be terrific. Actual error log output, browser console logs, screen output, etc.
> 
> The importer works - we have thousands of customers that use it. If it’s not working in your case, we need more info to work with with.

Nothing too fancy to reproduce: 
1) I just start a new clean snipe-it instance, 
2) set it to spanish, 
3) download your CSV example for users, and import it
4) results:

![Sin nombre](https://user-images.githubusercontent.com/2739706/130941366-32d88f3d-0f46-4f04-9fbe-410ded306219.png)

**Comment by aarnold-sd68** [comment]
@francogp your issue is much different then mine as far as I can tell.  The command line importer works perfectly for the file I posed it's the GUI importer that doesn't seem to work right.  I think it might be best for you to open a different ticket on your issue.

@inietov any luck on reproducing my error/issue?

**Comment by Ashficial1** [comment]
Why would you wanna reproduce a bug

Sent from Yahoo Mail on Android 
 
  On Wed, Aug 25, 2021 at 4:46 PM, Franco Gastón ***@***.***> wrote:   


I can confirm a similar problem. If I use Spanish, and for example export all users as .CSV, then I cannot import them because the columns identifier are duplicated (generating conflicts) or ignored due to bad translation.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by inietov** [comment]
@aarnold-sd68 Hello again!!
I run your file without any problem. I remember that a couple of weeks ago we saw this problem (the button process of the importer doesn't working) but it got fixed in this commit https://github.com/snipe/snipe-it/commit/131a285e2f360fc6705b27ca64a2a6c7a53ef9d2
Maybe you can try installing the last available version to test. Or upgrade your installed version to latest master.

**Comment by Ashficial1** [comment]
I know that's what u said

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 26, 2021 at 10:34 AM, Ashley ***@***.***> wrote:   Why would you wanna reproduce a bug

Sent from Yahoo Mail on Android 
 
  On Wed, Aug 25, 2021 at 4:46 PM, Franco Gastón ***@***.***> wrote:   


I can confirm a similar problem. If I use Spanish, and for example export all users as .CSV, then I cannot import them because the columns identifier are duplicated (generating conflicts) or ignored due to bad translation.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by snipe** [comment]
@Ashficial1 - I am going to be charitable and assume this is a language barrier issue, but your comments are coming off a little spammy right now. 

We reproduce bugs so that we can figure out what’s causing them. It’s a critical part of how we identify and fix issues. 

Please be considerate with your comments, and comment only when you have additional debugging information to add.

**Comment by aarnold-sd68** [comment]
> @aarnold-sd68 Hello again!!
> I run your file without any problem. I remember that a couple of weeks ago we saw this problem (the button process of the importer doesn't working) but it got fixed in this commit [131a285](https://github.com/snipe/snipe-it/commit/131a285e2f360fc6705b27ca64a2a6c7a53ef9d2)
> Maybe you can try installing the last available version to test. Or upgrade your installed version to latest master.

Would that be just by running the update script?

**Comment by snipe** [comment]
Assuming you installed via git, yes, that should do it

**Comment by aarnold-sd68** [comment]
That fixed my problem.  I didn't know how the update process worked fully.  I was going by the fact I had 5.1.8 so I had the latest I thought.  Thank you all who help with this.  The answer was so simple..

**Comment by snipe** [comment]
That’s not really your fault, so don’t feel badly. We tag releases when we’ve got enough changes to warrant them, but there isn’t really a good way (other than checking the commit logs) to see what’s changed *in between* tagged releases. We at least try to update commit hashes in the version.php file when something big-but-not-big-enough-to-tag has happened, but it’s still very much a manual process. 

I’m going to close this issue for now. I’m glad you’re all sorted.
